### ISSUE TITLE
[Site Creation] Show visual cue when exact match on domain suggestions is taken

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10089]
### Expected behavior
Show a visual cue when the exact match for the provided query is already taken. Should probably work even for the default list of suggestions which is derived from "Site title" entered on the previous screen.

### Actual behavior
The app displays only a list of _available_ domains. It might be quite confusing for the user and they might even think the search doesn't work as expected.

### Steps to reproduce the behavior
1. My Site
2. Switch Site
3. Plus sign icon in the top right corner
4. Select a site type
5. Skip 
6. Enter a title and click on next
7. Notice the app displays only available domains - eg. if you type "test" it doesn't show "test.wordpress.com" as it's already taken

cc @SylvesterWilmott 

Proposed solution is in [this comment](https://github.com/wordpress-mobile/WordPress-Android/issues/10089#issuecomment-546062587)

**Comment by jd-alexander** [comment]
Hi @SylvesterWilmott  I am going to be working on this, and I would be more than happy to have your help 😄 

So as discussed above the current UI just displays the domains that are available and there's no visual cue that shows the current availability of the query/domain name that was searched for. 

<img src="https://user-images.githubusercontent.com/1509205/67051272-43206000-f100-11e9-8e82-3b0406b9c93a.png" width="300"/>

So based on my understanding, what would be expected is something similar to what's taking place in Calypso where the domain's availability is being showcased above the suggestions. eg. this domain isn't available.
 
<img width="598" alt="Screen Shot 2019-10-17 at 5 12 34 PM" src="https://user-images.githubusercontent.com/1509205/67052021-8b408200-f102-11e9-8926-adb9261f732b.png">

Will this `domain availability check` be a `List Item` so the user is able to select it and they can scroll and it disappears?

## Some considerations

### Domain Purchases 
Since users can't purchase domains via the mobile app it only surfaces domains that are available free so do we want to prompt to them to purchase the domain via the web app but they can select a temporary one for now? This thought process is reiterating what @malinajirka mentioned: 

>The app displays only a list of available domains. It might be quite confusing for the user and they might even think the search doesn't work as expected.

### Error UI 
 The current app is surfacing errors in two ways. 
1. When there's a connectivity error that's caused by lack of internet access that control is shown as a `List Item` with a button to perform the retry action. 

<img src="https://user-images.githubusercontent.com/1509205/67052444-d60ec980-f103-11e9-92d1-3c4eb4663a17.png" width="300"/>

2. When there are no domain suggestions available a `Text View` representing the empty state is made visible on the screen since the `List View` is empty. 

<img src="https://user-images.githubusercontent.com/1509205/67052645-69e09580-f104-11e9-93a3-37fbb28c27bd.png" width="300"/>

I made mention of this because the representation is going to be changed since another piece of functionality is being added to the screen. How can we go about combining the errors of the `Fetch Domain Suggestions` & `Domain Availability` API calls? If for eg. the suggestions are returned successfully but the availability check fails how will we represent that? Do we show a general error and prompt the user to retry.

Let me know your thoughts. Thanks 😄

**Comment by malinajirka** [comment]
Thanks for the great comment @jd-alexander !

I just want to share a couple of my thoughts
1. If the user types eg "books-reviews" do we want to show that "book-reviews.com" isn't available or "book-reviews.wordpress.com" or "book-reviews.home.blog" or ...? (cc @SylvesterWilmott)

2. We might want to consider modifying the current api endpoint instead of invoking another endpoint. I'm not sure if it's feasible or if it even make sense. I just think it might be worth exploring before we start solving issues we might not actually end up having.

3. `If for eg. the suggestions are returned successfully but the availability check fails how will we represent that?` In case we decide to use two endpoints, I'd vote fore ignoring this error as imo it's not critical for the user.

Both 2 and 3 get around the partial fail scenarios - I'd like to avoid them as coming up with a good UX for partial fail scenarios is always difficult.

**Comment by jd-alexander** [comment]
Based on the discussions that were had about this issue, the solution will comprise of. 

- [ ] Checking if the results from `FetchDomainsUseCase` contain the requested domain and update the `uiState` with a property that will reflect if the domain is taken or not. 
- [ ] Modify the `SiteCreationDomainViewHolder` to translate that state to the design below.

**Comment by yaelirub** [comment]
@jd-alexander , does this still in "needs design" status? If not, please remove the label

**Comment by jd-alexander** [comment]
@yaelirub No it doesn't. Removed 😄
