### ISSUE TITLE
[Analytics] Double check editor_post_published event

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#10098]
It seems that the editor event `post_published`  went up after 21/4/2019 and never went back to normal values. 

A few details of my investigation:
- They go up in 12.2
- This seems to be the cause of the bump: https://github.com/wordpress-mobile/WordPress-Android/pull/9544

**Comment by daniloercoli** [comment]
@etoledom Would you mind to check on iOS if `post_published` event is bumped when you publish a page? On android it's bumped, and there is no prop to distinguish between post and page.

I've found out the following:
- Draft posts:
-- The first time a draft post is _saved_ on the server the `post_published` event is bumped (Not sure if it's correct or not).
-- Every time you tap on the `Save` menu item, and the post gets updated, the `post_published` event is bumped again. 
-- When you publish a draft post `post_published` is bumped. So, for draft posts this Stat is bumped at least twice. The first time is saved, and the later when you decide to publish.
Wondering if this could also be a problem with the autosave feature, where it can get triggered while typing the content/insert images, and then resulting in double counting the same event.

- Pages are counted in post_published event

**Comment by etoledom** [comment]
This is what happens on iOS:
- There is the same problem than on Android bumping `post_published` when publishing a page.
- This is even worst when saving a page (or post) async as draft.
- The `save/update` button (without leaving the editor) seem correct. 

I'll send a PR to fix the double events, but still it will be great to know what to do with the ⚠️ and ❓

Here I'm sharing the details of what's tracked on each interaction:

## Create new page:
⚠️ Post created when creating a new page. Not sure if it's correct. Maybe this should have a `"post_type" = page;` property
```
editor_post_created, properties: { 
    "blog_id" = 138685806;
    "tap_source" = "posts_view";
}
```

✅ Looks good with `"post_type" = page;`
```
editor_session_start, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    "post_type" = page;
    "session_id" = "042EB818-9071-47AC-8E96-39E7F89B2E4C";
}
```
❓Weird but harmless I guess.
```
post_list_status_filter_changed, properties: {
    "blog_id" = 138685806;
    filter = Drafts;
    type = page;
}
```

## Publish a page:

⚠️ Same than in Android, `editor_post_published` gets bumped up without page specific prop.
```
editor_post_published, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
    .... (some metadata counters props)
}
```
✅ Looks good with `"post_type" = page;`. Closing the previous `editor_session_start` event.
```
editor_session_end, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    outcome = publish;
    "post_type" = page;
    "session_id" = "7E8C8D98-F134-48AC-B483-C516DAB4EBA6";
}
```
❓Closing the editor. There is no previous `editor_open` event, and no `page` specific.
```
editor_closed, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
}
```
❓Again this weird one.
```
post_list_status_filter_changed, properties: {
    "blog_id" = 138685806;
    filter = Published;
    type = page;
}
```

## Creating a new post (from the bottom TabBar button):
✅ Looks good even though it's not specific for posts. Maybe that's fine.
```
editor_post_created, properties: {
    "blog_id" = 138685806;
    "tap_source" = "tab_bar";
}
```
✅ Looks correct.
```
editor_session_start, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    "post_type" = post;
    "session_id" = "1EA287E2-798A-44F3-A1CA-3708B1AEB442";
}
```

## Save draft post (save as draft menu option):
✅ Looks fine I guess. This is exactly the same one triggered by saving a draft from pages, but the event seems to not be specific for post or pages
```
editor_quick_draft_saved, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
}
```

## Save draft post (async save draft option from X button)
✅ Ending editor session with `post_type = post`
```
editor_session_end, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    outcome = save;
    "post_type" = post;
    "session_id" = "11AE559A-A300-4250-AF90-2493D7285515";
}
```
❌This one seems wrong. No post has been published.
```
editor_post_published, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
    "with_categories" = 0;
    "with_photos" = 0;
    "with_tags" = 0;
    "with_videos" = 0;
    "word_count" = 8;
}
```
❌ Ending the editor session again. Can't be good.
```
editor_session_end, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    outcome = save;
    "post_type" = post;
    "session_id" = "11AE559A-A300-4250-AF90-2493D7285515";
}
```
❓Closing editor. Looks fine but again, there is no corresponding `editor_opened`.
```
editor_closed, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
}
```
❓Again the weird one. I did notice that the tab is changed programmatically, but should we track it if it wasn't an interaction from the user?
```
post_list_status_filter_changed, properties: {
    "blog_id" = 138685806;
    filter = Drafts;
    type = post;
}
```

## Update post via Update button.
✅ Looks legit.
```
editor_post_update, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
    "post_id" = 731;
    "word_count" = 8;
    "word_diff_count" = 7;
}
```

## Close editor by Updating post:

✅ Looks good. It says `outcome = save` instead of update but we could say that we are actually `saving` the changes.
```
editor_session_end, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    outcome = save;
    "post_type" = post;
    "session_id" = "154EAF28-E321-42A4-A7D6-E4CE66DAB6BF";
}
```
✅ Looks good.
```
editor_post_update, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
    "post_id" = 728;
    "word_count" = 8;
    "word_diff_count" = 8;
}
```
❌ Bumping session ended again! Can't be good.
```
editor_session_end, properties: {
    "blog_type" = wpcom;
    "content_type" = new;
    editor = gutenberg;
    "has_unsupported_blocks" = 0;
    outcome = save;
    "post_type" = post;
    "session_id" = "154EAF28-E321-42A4-A7D6-E4CE66DAB6BF";
}
```
❓The classic closing editor event without previous editor open event.
```
editor_closed, properties: {
    "blog_id" = 138685806;
    "editor_source" = gutenberg;
    "has_gutenberg_blocks" = 1;
    "post_id" = 728;
}
```
❓D:
```
post_list_status_filter_changed, properties: {
    "blog_id" = 138685806;
    filter = Drafts;
    type = post;
}
```

cc @koke

**Comment by etoledom** [comment]
It would be great to have a list like this with the desired behavior. Is there any?

**Comment by daniloercoli** [comment]
>  Post created when creating a new page. Not sure if it's correct. Maybe this should have a "post_type" = page; property

I agree, we should add it.

**Comment by daniloercoli** [comment]
> It would be great to have a list like this with the desired behavior. Is there any?

Don't think there is anything for that. The only document i'm aware of  is the one about events list.

**Comment by koke** [comment]
> Weird but harmless I guess

There's code switching the post list filter in the background to ensure the post is visible on the list when the editor is closed. That said, I think it would make sense to only track an event like this if it was initiated by the user.
