### ISSUE TITLE
Menu items and actions available in Posts Remote Preview

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#10107]
**Draft issue to start tracking things, it will be updated as things/investigation progress further**

This is related to the work in PR #10085.

We are replacing the local preview with a more consistent remote preview. Talking about the remote preview, it uses a WebView internal to the app in `WPWebViewActivity` (so no external browser is opened for that).

Currently the `WPWebViewActivity` has the following menu and actions also when used for remote preview.
<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60137603-af6d0180-97a7-11e9-942c-e671c02bcbf7.png">
</p>

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60137643-d297b100-97a7-11e9-8a56-136b1366c87e.png">
</p>

So we have:
- Open link in external browser action
- Share post link action
- Overflow with Refresh menu item

Not have a complete defined idea on what/if to present a menu here, but I would at least remove the possibility to open the post in the browser since now the preview is already actually a remote preview, so I would prefer to stay in the app for a smoother UX.

Also not sure if a link to all the kind of posts (trashed for example) can be shared (more investigation needed).

Advice/comments more than welcome.

cc @maxme

**Comment by maxme** [comment]
> Not have a complete defined idea on what/if to present a menu here, but I would at least remove the possibility to open the post in the browser since now the preview is already actually a remote preview, so I would prefer to stay in the app for a smoother UX.

My opinion about these actions:
- Refresh: I'd keep it (can be useful if some resources were not loaded on this page).
- Share: this is useful when you work on a multi-users site, when you want someone to review your draft or changes. It's also a bit dangerous as this is only a private preview and some users might be tempted to share it on social media. I'd remove it.
- Open in the external browser: Someone could use it to test their post in other browsers (but I don't see the point since you're not updating the theme). It's probably better to remove it since this would also cut other features provided by the browser (like share). I'd remove it.

@osullivanchris, what do you think about this?

**Comment by osullivanchris** [comment]
I agree with @maxme 

Keep refresh, remove the other two (as they create lots of conundrums for unpublished posts) 

One other thing to call out: its a little weird to have an overflow icon with only one menu action in it. But we should probably leave it as is for now because its consistent with the other versions of this component. The only upside is if we add more actions later it will be easier to scale. Still feel a little funny about it though!

**Comment by develric** [comment]
Hi @osullivanchris , thanks for the above 😊.
Since this item seems quite well defined, with @maxme we were thinking to include it in the running #10085 PR.

AFAIU you suggest to leave the overlay as is for now, but since I'm going to work on it during the we I would like if possible to have a final thought from your side about it. Following the three simple alternatives I can think of. Thanks in advance 🙇‍♂️.

### Leave as is
<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60307426-d90f5f80-9944-11e9-92fb-b92178833585.png">
</p>

<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60307537-56d36b00-9945-11e9-8a99-88fccde0d761.png">
</p>

### Icon button action
<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60307567-79fe1a80-9945-11e9-87d3-44af20d644fe.png">
</p>

### Text button action
<p align="center">
  <img width="300" src="https://user-images.githubusercontent.com/47797566/60307609-9f8b2400-9945-11e9-96d2-f24b4a9182fd.png">
</p>

**Comment by osullivanchris** [comment]
Lets go with option 2: icon button action. 

- it solves the issue of having an overflow menu with only one item
- current version has icons not text so its keeping that
- Its a pretty universal icon so should be safe

**Comment by develric** [comment]
Thanks @osullivanchris , will go that way 😊.

**Comment by develric** [comment]
Just leaving a quick comment here to say that on the 27 July week I will be in Grounds Keeping and will take care to check if this can be fully closed.

**Comment by develric** [comment]
Looked into this one and I think we can close it. Reasons:

- The menus and icons in the remote preview have been revised starting from [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/10190) that adds a Preview Nav Bar at the bottom and desktop previews. Below a current version taken from 16.3-rc-1 release.

<p align=center><image src="https://user-images.githubusercontent.com/47797566/101060914-370b9200-3590-11eb-933c-cfd60df2ef1d.png" width=300/></p>

- Re this part: 

>Also not sure if a link to all the kind of posts (trashed for example) can be shared (more investigation needed).

we do not allow to preview not meaningful posts (like trash posts) anymore, but correctly offer to restore them eventually before they can be previewed again

<p align=center><image src="https://user-images.githubusercontent.com/47797566/101061194-8356d200-3590-11eb-94d9-4ba5919ddee3.png" width=300/></p>
