### ISSUE TITLE
Editor (Aztec): edit link dialog and UPDATE action are not translated

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#10132]
### Expected behavior
When having the device switched to a language other than English, the app should show all the text translated to such language.

### Actual behavior
It seems the Link Edit Dialog only shows text in English.

![Screenshot_20190701-191030](https://user-images.githubusercontent.com/6597771/60476552-6c50d980-9c52-11e9-87ee-2624d937fbd7.png)

Also note the action bar's main action ( "UPDATE" up there) is in English too.

### Steps to reproduce the behavior
1. change the device language to german
2. open the editor (Aztec)
3. with text selected, tap on the link icon on the toolbar
4. observe the Link Edit Dialog appears, but it's in English.

**Comment by rachelmcr** [comment]
Looks like "Update" is intentional — it's the [translation provided here](https://translate.wordpress.org/projects/apps/android/dev/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=135132&filters%5Btranslation_id%5D=7835409).

But I'm not sure what's happening with the other strings. For example, there's [a German translation for Open link in a new window/tab](https://translate.wordpress.org/projects/apps/android/dev/de/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5454869&filters%5Btranslation_id%5D=53805506) but it isn't being used. And I don't see the string `Insert link` in GlotPress although I do see it in [this string file](https://github.com/wordpress-mobile/WordPress-Android/blob/master/libs/editor/WordPressEditor/src/main/res/values/strings.xml), along with other strings that _are_ in GlotPress.
