### ISSUE TITLE
Question: Can I use this code for own Wordpress site ?

### ISSUE THREAD

**Issue by varoon** [wordpress-mobile/WordPress-Android#10371]
I have hosted a Wordpress website on godaddy.

Need a custom Android app to provide for my authors to manage the post/edit articles.

can i use this code ?

Sorry for posting on issues page. But i could not find anything related.

**Comment by designsimply** [comment]
Your authors should be able to manage posts and edit articles  already if they download and install any of the [mobile apps made for WordPress](https://apps.wordpress.com/mobile/) and you shouldn't need to modify the code for that.

If you are asking whether or not you can copy the code here in order to make your own app—I wouldn't recommend it because it would be a lot of things to maintain on your own and could become out-of-date very quickly. However, you may use the code as long as you follow everything in the GPLv2 license which you can find at https://github.com/wordpress-mobile/WordPress-Android/blob/develop/LICENSE.md — it is a legal agreement and if you have any questions about the details of that then I would recommend consulting an attorney, especially if you are unsure about how your situation applies to following the software license agreement.

If you would be interested in contributing updates to the apps as part of the open source project here, check out the documentation about contributing at https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md ! 😊

Thanks for using WordPress and for reaching out!
