### ISSUE TITLE
Switch to disable all notifications for a specific notification type

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#10484]
Currently after navigating to the Notification settings from the notifications tab, when disabling notifications for a specific site you'll have to manually uncheck each of the specific notifications for a type of notification

![WhatsApp Image 2019-09-04 at 11 43 05 PM](https://user-images.githubusercontent.com/6520461/64312487-cb421000-cf6d-11e9-91dc-df9cdf67eb33.jpeg)

I'm proposing an on/off switch at the top right of the dialog maybe, to switch off all the items.

**Comment by planarvoid** [comment]
What do you think about this proposal @osullivanchris ?

**Comment by osullivanchris** [comment]
I think its a good idea to allow the user to turn on/off all notifications.

However, if it is done as a switch it doesn't really work. Because the switch will need an indeterminate state when some of the below items are on/off. 

I explored a few ways to do it

1. Add a button above the list to 'turn off all notifications'. Once the user hits it, it changes all the other switches. Once the user is in this state, the action would change to 'turn on all notifications'. I am not sure if this is possible, because I think this system component only allows actions at the bottom of the modal?
2. Following the thought process of the first option. Do we really need 'OK' and 'CANCEL' actions here? We could just make the change happen as soon as the user taps the switch, without needing confirmation. That frees up this action space to add the all action.
3. Checkboxes are better at dealing with indeterminate states, so we could follow the material guidelines here. But I don't know if we use checkboxes in settings today (See 'when to use checkboxes instead of toggles) https://material.io/components/selection-controls/#usage
<img width="1187" alt="Screenshot 2019-10-02 at 17 21 03" src="https://user-images.githubusercontent.com/50576199/66063032-78428500-e53a-11e9-91c4-79c414bdcbf4.png">


However I wasn't happy with any of these options. I found something that we already have that we can re-use. In the main "Notification Settings" page there is a switch in a blue bar. When this switch is on, you can choose subsets. When it is off, everything is disabled. This gets me out of the complexity of indeterminate states in all the previous options. So this is what I propose we go with. Here's how it would look
![Notification Settings](https://user-images.githubusercontent.com/50576199/66063109-9e682500-e53a-11e9-97ff-396b59f628a1.png)



If we are doing this we should also implement it for app notifications and email. Let me know what you think. Its slightly non-trivial. A copy review might be needed to for the super-switch.

**Comment by martkop12** [comment]
Hi, can i work on this issue ?

**Comment by planarvoid** [comment]
hey @martkop12, this is actually already being worked on

**Comment by planarvoid** [comment]
This is done
