### ISSUE TITLE
PNG images displayed as a grey box in reader posts on bad connectivity

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#10506]
### Expected behavior
Post media will show up or show an indication that they were not loaded.

### Actual behavior
PNG images show up as grey boxes.

### Steps to reproduce the behavior
1. Enable link conditioning with "Very bad network"
2. Go to Reader and open a post with PNG images.
3. Scroll through the post and see a spinner instead of PNG images.
4. Some of them will be updated to a grey box.

This issue was created on iOS. Please see reference to the issue here:
https://github.com/wordpress-mobile/WordPress-iOS/issues/12517

And the proposed design solution here:
https://github.com/wordpress-mobile/WordPress-iOS/issues/12517#issuecomment-532935835

**Comment by malinajirka** [comment]
Thanks for the report @yaelirub ;)

It'd be nice to tackle this as a small project and add support for "reload" to all images within the app. Imho it shouldn't be overly complicated since we load all images through the `ImageManager`. I think/hope we might be able to come up with a single solution for all the images.
If we add this support we could also add support for preloading images only on wifi and require a tap to load an image on data plan in order to save users' data.

SideNote: This doesn't seem related to offline **posting**. :P

**Comment by yaelirub** [comment]
Thanks for the input @malinajirka .
I agree. I'm thinking this could be a trial project.
I just put this on the board here to keep it going (I won't be using this method often :) )

**Comment by planarvoid** [comment]
Changing image loading in a WebView (our reader) is very complicated (and maybe not possible). There is one thing we can do and that's adding a reload on click. The first step is to add reloading to the Reader post list. It would be great to have a solution that would work all over the place and be implemented in the ImageManager.

**Comment by planarvoid** [comment]
To fix this issue we'd need to replace the image loading in the WebViews and I don't think that's possible. A theoretical fix would be to replace the WebView with TextView (or a list of TextViews) where we can replace the image loading. This was investigated in a trial and we skipped it because we couldn't find a solution. The image loading is done the same way as in all the other WebViews which should be ok for now.
