### ISSUE TITLE
Gravatar vs Icon in the Me Section menu.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#10511]
As part of the **Information Architecture project** we are moving the access of the Me section from Bottom Navigation bar to a menu in My Site section (see  #10495).

A dedicated PR has been created for this (see #10498). Note that in this PR we used the "ic_user_circle_white_24dp" icon for the My site section menu.

This issue has been created as a reminder to track eventual further discussion about the convenience or not to use the user Gravatar instead of the "ic_user_circle_white_24dp" icon in the menu.

cc @planarvoid and @osullivanchris .

**Comment by designsimply** [comment]
I found this change very disorienting while beta testing and thought it was a bug. 🙂 

I'm not opposed but may I ask for the reasoning behind this to be noted here in GitHub so that the decision is publicly accessible?

**Comment by planarvoid** [comment]
I'll try to explain what's happening. We're trying to change the architecture of the app to increase the usability. One of the steps is to reduce the number of actions in the bottom navigation. The first step of this is to move the `Me` tab to a separate screen which can be accessed from the toolbar of the `My sites` tab. 
This change is now merged to develop but it's behind a feature flag for release because by itself it has issues (for example the bottom navigation toolbar now looks lopsided). Once we finish the other parts of the project, we'll release all the changes to the public at once.

**Comment by develric** [comment]
Hi @planarvoid, thanks for answering above 🙇‍♂️. 

Hi @designsimply, hope the Issues/PR linked by planarvoid can also help with the context 😊.

**Comment by osullivanchris** [comment]
Thanks for explaining @planarvoid @develric 

Once we get the other top level nav changes lined up. It will be visually balanced. And the aim is to create a clearer hierarchy of tasks for the users, rather than making them choose from too many things at the top level.
