### ISSUE TITLE
Auto-upload of a local draft can result in "Unhandled auto save" state

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#10526]
Running the following steps sometimes makes the local draft end up in "Unhandled auto save" state:

1. Turn on airplane mode
2. Go to post list - drafts
3. Add a new draft with some title and/or content
4. Tap back which should say "Local draft"
5. Turn off airplane mode and wait for the post to be uploaded

Here is my test: https://cloudup.com/c-v9cAlcCOU

Edit: This test was run with a WordPress.com account.

**Comment by malinajirka** [comment]
The issue is that we call `remote-auto-save` on a post which isn't locally changed. 

This happens when the UploadStarter is invoked twice within a few millis -> once from `UploadWorker` and once from `UploadStarter.connection listener`. 

The first invocation enqueues the post and calls `startService`. The second invocation calls `UploadService.isPostQueuedOrUploading` which returns false (should return true) because the OS didn't have enough time to actually start the service -> therefore the second invocation also calls `startService` -> the post is enqueued twice.

The first item in the queue is uploaded as draft -> `pushPost` action.
The second item in the queue is remote-auto-saved as it's not a local draft anymore -> this is the issue as the post doesn't contain any local changes.

Quick win fix: Delay the start of the `UploadWorker` so it's not always called right after `UploadStarter.connection listener`.

However, I'm still trying to come up with a better. Any ideas are welcome:).

**Comment by oguzkocer** [comment]
Fixed in #10531.
