### ISSUE TITLE
Stats: tapping the site title on the blog details screen generates one view in stats when it should not

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10675]
Steps to reproduce:

1. Delete and reinstall the app (use a fresh install).
1. Go to My Site and select a site if prompted.<br><sup>Note that it's helpful to test with a site that gets little or no traffic.</sup>
1. Tap the site title at the top to open a webview.
1. Go to Site Pages and tap View for some of the pages.
1. Go to Blog Posts and tap View for some of the posts.
1. Wait a few minutes (up to 30).
1. Check stats to see if any views were recorded.

**Result:** opening a web view by tapping on the site title on the Blog Details screen generates a single view in stats for the home page when it should not. Views for blog posts or pages from the Posts List and Pages List via the app did not generate any stats. Also, the home page view is only counted once, even if the site title is tapped to open a webview several times.

**Note:** I am not sure whether it matters for webviews but I made sure I was logged out of WordPress.com in the web browser on my device before testing. I also noticed that logging out and back in or closing and reopening the app didn't affect that one single view was recorded, but if I deleted and reinstalled the app then I could generate one more view each time I repeated the testing steps.

<img src="https://user-images.githubusercontent.com/1119271/67443523-79f3eb80-f5c2-11e9-8836-3921f4b690ac.png" width="270" alt="Screenshot_20191023-174449"> <img src="https://user-images.githubusercontent.com/1119271/67443522-79f3eb80-f5c2-11e9-81c6-aa1ea4700e71.png" width="270" alt="Screenshot_20191023-182322"> 
<sup>Tested with WPAndroid 13.4 on Pixel 3 Android 10.</sup>

<sub>/hat tip @charliescheer for the report (internal reference: p4a5px-2qf-p2)</sub>

**Comment by shiki** [comment]
@malinajirka: @hafizrahman is looking into this. I wonder if you have some insights or ideas for why this happens?

**Comment by malinajirka** [comment]
Hmm, not much comes to my mind. When the user clicks on the title, we open an internal webview and we log the user in. So I'd assume the server won't record any stats events since the server knows we are logged in. 🤷‍♂ 
Only thing I remember is that when you click on "View" on posts/pages list, "preview=true" query parameter is attached to the url. Maybe that's what makes the difference?

**Comment by hafizrahman** [comment]
I tested it this way:

1. Have a test site and make sure it's public (since visits to private sites are recorded),
2. Add a menu to my test site that goes to wp-admin
3. Start a fresh install on an Android emulator
4. Log in to account, select the test site
5. Tap site title/address
6. Webview is loaded, opening the site
7. Select the wp-admin menu item that was added to the site

In my test, I was able to go to the wp-admin area without being asked to log in.

The logic flow for the tap site title action looks like this, it's a bit huge:

<img width="953" alt="wp android - understanding issue 10675" src="https://user-images.githubusercontent.com/266376/67860171-c48bdf80-fb4f-11e9-97a5-4a795e47655b.png">

What matters here is that as far as I can check, the action does call the correct function to load the webview using proper authentication, so that the user is already logged in when the site is loaded. The test above also confirms that the auth/login works properly.

So what I'm not sure now is why it's still recorded as a visit, even though it is correctly an admin visit to the site's home page 🤔

**Comment by reginabally** [comment]
~Another report in 3415661-zen, using Google Pixel (not specifying the actual model), Android 11 and WPAndroid version 15.8.1.~ (EDITED: The report in the ticket isn't related to this issue but I was able to replicate the steps in the original thread)

Able to replicate this on OPPO Reno 4, Android 10, WPAndroid version 15.9-rc-2.

**Comment by thehenrybyrd** [comment]
This is still an issue in 20.6-rc-2, reproduced on Samsung Galaxy S21.

**Comment by reginabally** [comment]
Another report in 7104118-zen.

Reproduced on Nexus 5X (Android emulator), Android 13, App version 23.3.1.

**Comment by ariel-maidana** [comment]
7789929-zen User would like to be notified when a fix is released.

**Comment by ravishanker** [comment]
This opens up in a WebView, not something to fix in the app.  See also #10653, and https://github.com/wordpress-mobile/gutenberg-mobile/issues/1387
