### ISSUE TITLE
Incorrect notation for billion views

### ISSUE THREAD

**Issue by melindahelt** [wordpress-mobile/WordPress-Android#10709]
#2452316-zen

### User Reported

> Take a look - 1G for 1 billion views is pretty funny. Gigaviews? I guess not many sites operate at this scale in your test env.

![](https://cld.wthms.co/cWRLdh+)Image Link: https://cld.wthms.co/cWRLdh

##### Tested on [device], Android [version], WPAndroid [version]
Android app version 13.5-rc-1

**Comment by archon810** [comment]
I'm the one who reported this bug. Feel free to ask any questions.

**Comment by hafizrahman** [comment]
Working on a fix.

**Comment by hafizrahman** [comment]
The thing here is that the suffixes in use currently follow the SI / International System of Units symbols for large numbers, which is "k", "M", "G", "T", "P", and "E" as also listed on the table in this Wikipedia entry: https://en.wikipedia.org/wiki/Names_of_large_numbers#Extensions_of_the_standard_dictionary_numbers

The suffixes are set in the code here: https://github.com/wordpress-mobile/WordPress-Android/blob/603763fa8b9561410bd9bcdadeef0c7fa1a757d5/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/utils/StatsUtils.kt#L7

Technically it's simple to replace the "G" there to "B", but I think this would be a good opportunity to refactor the suffixes to support translations, since "B" for "billion" might still not make sense on other languages (it doesn't make sense in my language, Indonesian, for example).

**Comment by archon810** [comment]
I would further argue that having no decimals for something as big as a billion is not as useful as specifying the millions part too. 1,234 million or 1.234 billion is far more useful than 1B.
