### ISSUE TITLE
Post List: cannot see author picker for pages

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#10726]
### Expected behavior

I expected to be able to filter pages by me or everyone.

### Actual behavior

There's a space for an author filter toggle at the left side of the pages filter lost, but the option to toggle between my own pages and everyone's pages is missing.

### Steps to reproduce the behavior

1. Switch to a site with published pages from more than one author.
1. Go to My Site > Site Pages.
1. Look for the author picker at top left.

##### Tested on Pixel 3, Android 10, WPAndroid 13.5-rc-2

<img src="https://user-images.githubusercontent.com/1119271/68053955-d5a13180-fcb2-11e9-8790-15a8fcb5b8b4.png" width="270" alt="Screenshot_20191101-135948"> <img src="https://user-images.githubusercontent.com/1119271/68053957-d639c800-fcb2-11e9-9f7f-c9ef467052ab.png" width="270" alt="Screenshot_20191101-135840">
<sup>Site Pages author toggle cannot be seen while logged in as design5279 admin role (left) and then testuser0313 author role (right).</sup>

<img src="https://user-images.githubusercontent.com/1119271/68053932-ca4e0600-fcb2-11e9-8f99-6bafe79b7f13.png" width="270" alt="Screenshot_20191101-140006"> <img src="https://user-images.githubusercontent.com/1119271/68053954-d5a13180-fcb2-11e9-9887-a52cb27bd113.png" width="270" alt="Screenshot_20191101-140002">
<sup>Compare to Blog Posts where the author toggle can be seen while logged in as design5279.</sup>

**Comment by jd-alexander** [comment]
Since this exists in the `PostList` the UI and functionality for the `Spinner` could be migrated to the `PagesFragment` so that the author selection could trigger a reload from the PageStore`.

To accomplish this for the `PageList` from a data standpoint,  we would need to modify the `FetchPosts` functionality that powers the `PageStore`'s ability to fetch pages. This modification involves adding a parameter to the `FetchPostsPayload` to specific an author so that when the params are being created to fetch the post the specific author's id can be added.

**Comment by malinajirka** [comment]
I believe this feature was never supported on the Page List. We might want to consider proposing it as a mini-project and removing it from Groundskeeping. Wdyt @designsimply ?

**Comment by jd-alexander** [comment]
Indeed @malinajirka based on my investigation, it's not supported there so I agree it's a mini project 🙏
