### ISSUE TITLE
Site Settings: changes to "Lazy load images" setting aren't saved

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#11021]
Steps to reproduce:

1. Go to My Site > Settings, scroll until you find "Lazy load images" setting.
1. Toggle the "Lazy load images" setting on.
1. Tap the back arrow (top left).
1. Re-open settings and check to see if the "Lazy load images" setting is still on.

**Result:** the "Lazy load images" setting cannot be saved to on. ([20s](https://cloudup.com/cn9ezYe_ux8) WP.com, [23s](https://cloudup.com/c6N3SroC0TY) WP5.2.3 JP8.0)

<img src="https://user-images.githubusercontent.com/1119271/71378101-da33e900-2583-11ea-9901-f8ba122e2509.png" width="270" alt="Screenshot_20191223-125657">
<sup>Tested with WPAndroid 13.9-rc-1 on Pixel 3 Android 10.</sup>

**Comment by malinajirka** [comment]
I've quickly looked into this issue and I found the following:

Any of "lazy load images", "Site accelerator - faster images, faster static files" doesn't work on WPCom sites (including AT sites). However, it works on a self-hosted site with installed and activated JetPack.

It seems the issue is on [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/cd67006be891656c84cb85becc03759d81318fef/WordPress/src/main/java/org/wordpress/android/ui/prefs/WPComSiteSettings.java#L131) => `mSite.isJetpackConnected()` returns true only for a self-hosted site with JetPack (the user needs to be logged into the app with the same wpcom account they used for JetPack), therefore it's the only scenario when we push the changes to the server. 

I don't have enough context to suggest an appropriate fix. We might want to hide the settings unless the user is logged in with the wpcom account connected to jetpack + we somehow want to make sure we push the changes even on wpcom sites 🤷‍♂. @khaykov Do you by any chance have more context about this feature?


SideNote: 
>Result: the "Lazy load images" setting cannot be saved to on. (20s WP.com, 23s WP5.2.3 JP8.0)

The WP.com video corresponds to my findings. The WP5.2.3 JP8.0 doesn't correspond to my findings, however I believe the Jetpack wasn't activated (connected to your wpcom account) or you weren't logged into the app with the wpcom account. (I don't see "Plugins" in the My Site section which would confirm this theory) @designsimply Can you please confirm this? Thank you!

**Comment by designsimply** [comment]
> The WP5.2.3 JP8.0 doesn't correspond to my findings, however I believe the Jetpack wasn't activated (connected to your wpcom account) or you weren't logged into the app with the wpcom account. (I don't see "Plugins" in the My Site section which would confirm this theory) @designsimply Can you please confirm this?

I re-tested, and you are correct! I used a WordPress 5.3.2 site with Jetpack connected in a new test while logged in to the app as the connected user at the time of the test and the lazy load images setting stays saved as expected in that case: [17s](https://cloudup.com/cKL4nbbFhC0).

**Comment by khaykov** [comment]
@malinajirka , sorry, no idea how that feature was implemented 🤷‍♂

**Comment by malinajirka** [comment]
@designsimply I think the best next step would be putting this into the prioritized Groundskeeping column. 

For reference: This is the PR where the feature was introduced - https://github.com/wordpress-mobile/WordPress-Android/pull/10468

**Comment by designsimply** [comment]
Will do. 👍
