### ISSUE TITLE
Empty lines get deleted from codeblocks

### ISSUE THREAD

**Issue by anfelor** [wordpress-mobile/WordPress-Android#11031]
### Actual behaviour

When I open a post containing code blocks (I can't and don't edit on mobile), edit *another* block and update the post, the code loses empty newlines. Sometimes this only happens after swapping the code block with a content block above and back (using the up/down buttons).

##### Tested on [device], Android [version], WPAndroid [version]

OnePlus 7T, Android 10, newest, WordPress self-hosted but newest too.

**Comment by designsimply** [comment]
Thanks for the report! I tested and confirmed this using WPAndroid 13.9-rc-1 on Pixel 3 Android 10 and I have moved the issue to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1727 since that is where we are tracking block editor issues.

Aside: "WordPress self-hosted but newest too" ← noting that the current latest stable version of WP is 5.3.2 at the time of this writing and that I tested with a WordPress.com simple site and found the same problem there as well.
