### ISSUE TITLE
[GlobalStep] Long text in quizes clips outside the borders

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-Android#11189]
### Description
Long text in quiz shortcodes causes horizontal pagination and the text to clip past the borders.

### Reproduction Rate
4/4 100%

### Expected behavior
The text should continue to a new line when it’s too much to be contained within the page’s borders.

### Actual behavior
The text clips past the borders and horizontal pagination occurs.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add a quiz. The following example may be used:
```
[quiz]

[question]Insert question here
[/question]
 

[answer]Insert correct answer here
[/answer]
 

[wrong]Insert wrong answer here
[/wrong]
 

[wrong]Insert wrong answer here
[explanation]Add additional information or an explanation for why it’s wrong here[/explanation]
[/wrong]
 

[/quiz]
```

##### Tested on the following
LG G7 (8.0)

#### Please see the attached screenshot for more information

<img width="270" src="https://user-images.githubusercontent.com/60415523/73352898-0b41c080-428a-11ea-8f2f-eced979fd87b.jpg">

### Submitted by:
Luis Pimenta

**Comment by chipsnyder** [comment]
Because preview is loaded in a web view, I believe this is an issue with their theme.

Here's the web version of their page and a test page I used:

| madefortesting9845 | my test site | 
| --- | --- |
| <img width="400" alt="madefortesting" src="https://user-images.githubusercontent.com/3384451/73379893-151af200-4291-11ea-913d-02bab3e3de33.png"> |<img width="400" alt="mytestsite" src="https://user-images.githubusercontent.com/3384451/73379916-2237e100-4291-11ea-9f76-7abc15696bc9.png"> |

**Comment by hypest** [comment]
Closing since by @designsimply 's findings this is a theme related issue. While at it I'll remove the "gutenberg-mobile" label as well since it's not an editor issue. Please, feel free to reopen if needed.
