### ISSUE TITLE
Offline Support Pages - Update Page Status causes null post when fetching upload status

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11260]
### Expected behavior
A post should be available in the `PageItemUploadProgressHelper`s `getProgressStateForPage` at all times so that the `UploadStatus` can be used to determine the `ProgressState`.

### Actual behavior
when the page status is being changed and  `PageItemUploadProgressHelper`s `getProgressStateForPage` is called it returns null at times. 
This will require investigation. 

1. The current null check might be hiding a potential issue. 
2. `The database just returned us a list of pages and a few ms later it seems the page is not in the database anymore. Do we remove the page from the database before we move it to draft/publish it?` an important question posed by @malinajirka which should help the investigation. 

### Steps to reproduce the behavior
1. Go the `Page List` and change the page status of either a `Published` or `Draft` page multiple times until there is a crash. 

Tested on Google Pixel 4 XL, Android 10, WPAndroid https://github.com/wordpress-mobile/WordPress-Android/pull/11191

**Comment by malinajirka** [comment]
AFAIK this issue will be fixed in https://github.com/wordpress-mobile/WordPress-Android/issues/11271. We won't load the model from database and we'll interact with the model which we already have and can't be null, right?  If I'm not missing something, please feel free to close this issue @jd-alexander . Thanks!
