### ISSUE TITLE
Offline Support - Pages : Refactor PageListDialogHelper 

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11272]
### Expected behavior
There should be independent classes for each type of dialog.

### Actual behavior
`PageListDialogHelper` currently houses multiple dialogs. It can become unmaintainable in the future if more dialogs are added. 
For more details see this comment https://github.com/wordpress-mobile/WordPress-Android/pull/11228#discussion_r376992517

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.5` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.4` branch which will be available later today and update the milestone for the issue accordingly.

**Comment by malinajirka** [comment]
We've decided not to do these changes.
