### ISSUE TITLE
PostListDialogHelper :  add post type to dialog events 

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11282]
### Expected behavior
 When the dialog events are tracked as being done in PageListDialogHelper https://github.com/wordpress-mobile/WordPress-Android/commit/ac2129bb159cd5334f2e1ec9093f9fea3547a8b4
https://github.com/wordpress-mobile/WordPress-Android/blob/f54c0bc2bd58c5048415ee7317de8175f20b13d7/WordPress/src/main/java/org/wordpress/android/ui/posts/PostListDialogHelper.kt#L113

It should contain the type of post. This is necessary because the same events are being used in this PR https://github.com/wordpress-mobile/WordPress-Android/pull/11228 that adds support for similar dialogs and being able to differentiate the events are a value-added measure. 

### Actual behavior
Currently, the events don't pass the type since they were only being done for posts only.

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()
#11228

**Comment by oguzkocer** [comment]
This issue is targeting the current frozen milestone which is about to be released. I am bumping it to `14.5` which is when a PR that lands to `develop` in the next 2 weeks will be released. If it's more urgent than that, please make sure to target `release/14.4` branch which will be available later today and update the milestone for the issue accordingly.
