### ISSUE TITLE
[Stats] Incorrect image is shown on "New" card

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-Android#11723]
### Expected behavior
The UI should be reflected in the "New" card

<img width="357" alt="Screenshot 2020-04-22 at 16 30 55" src="https://user-images.githubusercontent.com/36532468/80001754-a677ba00-84b6-11ea-8438-8203454b6aa0.png">

Note: the gradient fade will have to be added programmatically since `.svg` format doesn't support gradients or masks.

### Actual behavior
The image being shown is of the old UI and contains non-translated text

<img width="358" alt="Screenshot 2020-04-22 at 16 17 37" src="https://user-images.githubusercontent.com/36532468/80000234-cc9c5a80-84b4-11ea-8723-c16cdad8718e.png">

### Steps to reproduce the behavior
1. Create a new site
2. Visit stats to see the "New" Card
3. Notice that the image shows a UI that doesn't reflect the actual UI 

Image asset:
[manage_your_stats.svg.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4517089/manage_your_stats.svg.zip)

**Comment by planarvoid** [comment]
hey @SylvesterWilmott , do you think you can add the dark version of this asset?

**Comment by SylvesterWilmott** [comment]
@planarvoid does it look bad to use the same image in dark mode as well? iOS is using the same image for both but I understand the platforms have different surface colours.

**Comment by planarvoid** [comment]
I think it looks OK @SylvesterWilmott . Check it out. I've used the `surface` color as the gradient so it is darkened in the dark mode. Otherwise the image is  emphasized instead of fading away. WDYT? :-) 
![Screenshot_1592833148](https://user-images.githubusercontent.com/1079756/85294243-b011a400-b49e-11ea-9918-a1a6bb2dc470.png)
![Screenshot_1592833163](https://user-images.githubusercontent.com/1079756/85294238-adaf4a00-b49e-11ea-854e-f0ab679045e4.png)
