### ISSUE TITLE
Snackbar notice when switching to HTML editor prevents editing last line of text

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-Android#11819]
### Expected behavior
When I switch to the HTML editor it is easy for me to edit all areas of my post as I need to

### Actual behavior
When I switch to the HTML editor there is a pop up at the bottom of the screen preventing me from editing the last line of text in my post. This pop up lingers for a long time, preventing me from editing as I need to.

### Steps to reproduce the behavior
1. Create a new post with content in the block editor
2. Tap the 3 dots in the upper right corner to then tap switch to HTML
3. Try to edit the last line. You wont be able to until the pop up disappears, which can take awhile

##### Reported on Galaxy Note 8 WPAndroid 14.6.1
Ticket #2929016-zen

Example of hidden text:
![](https://d.pr/i/tFtiRB+)
(Image link: https://d.pr/i/tFtiRB )

![](https://d.pr/i/nPWWFP+)
(Image link: https://d.pr/i/nPWWFP )

**Comment by rezzap** [comment]
The user has confirmed they are using Android 9. Additional user device details provided in the ticket if needed.

**Comment by designsimply** [comment]
This affects me too! It makes me wish for an easy way to dismiss those kinds of notices, maybe with a swipe? @yaelirub for a gut check on the idea (and because I remember you've worked on notices in the past). Good idea? Would something like that be complex to implement or a good first issue? Would a different solution I'm not thinking of yet be better?

**Comment by yaelirub** [comment]
@designsimply , on iOS we don't show any notice when switching to HTML so I think we should do the same on Android.

**Comment by ovitrif** [comment]
@iamthomasbishop As @yaelirub mentioned earlier, we don't show any notice on iOS when switching to HTML or visual editor.

Edit: Just checked the web version, we also don't show a notification there.

<details>
<summary>iOS App Preview</summary>

| Switch to HTML Mode | Switch To Visual Mode |
| ----- | ----- |
| ![ios_switch_to_html](https://user-images.githubusercontent.com/4588074/141681848-60ac3d49-0f42-4063-8a2e-8c8e2da209c1.png) | ![ios_switch_to_visual](https://user-images.githubusercontent.com/4588074/141681866-731fa6a0-e1d9-4149-ae8d-760b10928872.png) |
</details>

<details>
<summary>Android App Preview</summary>

| Switch to HTML Mode | Switch To Visual Mode |
| ----- | ----- |
| ![android_switch_to_html](https://user-images.githubusercontent.com/4588074/141684301-a6df03c3-ad4a-47db-a495-8cad238250b3.png) | ![android_switch_to_visual](https://user-images.githubusercontent.com/4588074/141684310-1e2c8ada-34ba-445e-a3d9-f6a2462124af.png) |
</details>


## Proposal
After discussing together with @antonis we propose to remove the notice altogether on the Android app.

### Checklist
- [ ] Remove snackbar notice when switching to HTML Mode
- [ ] Remove snackbar notice when switching to Visual Mode

Please review our proposal and let us know what you think! Thanks in advance 🙇🏻‍♂️

**Comment by iamthomasbishop** [comment]
@ovitrif Thanks for the ping! Rather than remove the editor-switch messaging altogether (on Android -- I'm not sure if that was never implemented or was removed at some point on iOS), I would rather "translate" the message to use our compact version of the [Notice](https://github.com/WordPress/gutenberg/tree/trunk/packages/components/src/notice) component if possible (I'm not 100% sure if this is the exact one we're using). This is a bit more subtle but should have the same effect as the Snackbar without taking up as much space and should disappear more quickly. (Note: This would be implemented on both platforms)

@antonis How does this sound? Any conflicts this would cause or would it leave us with the same result?

**Comment by antonis** [comment]
Thank you for the detailed feedback @iamthomasbishop 🙇 

> I would rather "translate" the message to use our compact version of the Notice component if possible

It think that would work and be less distracting for the user. This is the same notice we use when we we create a new page. Correct?

<details>
<summary>Page created notice</summary>

https://user-images.githubusercontent.com/304044/141979086-f82fda7e-d0eb-4693-9ec8-8ab2d2fef3b7.mp4
</details>

If that is the case I think @ovitrif can explore this route using the [same notice type we use for page creation](https://github.com/wordpress-mobile/WordPress-Android/blob/d04e68d49554fd31f5c6cd73b9ee80caf9eab8ef/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L720).

**Comment by ovitrif** [comment]
Thank you too for the feedback @iamthomasbishop, I'll look into using the less intrusive notice! 🙇🏻

Many thanks @antonis for pointing where to start and for your follow-up 🙇🏻

**Comment by iamthomasbishop** [comment]
@antonis Yes, that's the one! Thanks for confirming!
