### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11821]
**Sentry Url**: https://sentry.io/share/issue/117d819f32fa4523af739daae450d190/
**User Count**: 434
**Count**: 1617
**First Release**: org.wordpress.android-12.7
**First Seen**: 2019-07-04T22:19:11Z
**Last Seen**: 2020-05-05T13:57:08Z
**24 Hours**: 20
**30 Days**: 359

```
NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
     at org.wordpress.mobile.ReactNativeAztec.ReactAztecText$4.run(ReactAztecText.java:197)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:145)
     at android.app.ActivityThread.main(ActivityThread.java:6934)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by bummytime** [comment]
>  org.wordpress.mobile.ReactNativeAztec.ReactAztecText$4.run(ReactAztecText.java:197)

@maxme or @hypest any thoughts on this one? 😄

**Comment by hypest** [comment]
Looks like we can just guard for `getLayout()` being null and bail. The code in the offending line only tries to bring the caret into view, but apparently the View is no longer alive. Should be safe to skip trying to scroll the View.

@marecar3 , would you mind opening and driving a PR with null-checking getLayout and exit the function? Thanks!

**Comment by marecar3** [comment]
Hey @hypest 👋 
Yup, I can drive this one, thanks.

**Comment by designsimply** [comment]
230 events have been tracked for crash [WORDPRESS-ANDROID-2NG](https://sentry.io/share/issue/117d819f32fa4523af739daae450d190/) in 14.7 and 14.7.1 since they were released 15d and 4d ago on May 15 and May 4 respectively.

**Events:** 1,900
**Users affected:** 616
**Limited to:** ~98% Android 5.x
**Also see:** [this graph](https://sentry.io/organizations/a8c/discover/results/?cursor=0%3A0%3A1&display=daily&field=timestamp&field=version&field=os&field=device.brand&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1098755416&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Note:** it does look like there was an uptick for this crash beginning Apr 24 but it's numbers still aren't as high as some other crashes we're seeing.
<sub>https://sentry.io/share/issue/117d819f32fa4523af739daae450d190/</sub>

First seen in WPAdroid 12.7…

Also see https://github.com/wordpress-mobile/WordPress-Android/issues/11122 which contains the same `NullPointerException` error and was closed.

@marecar3 please still look into this, but also please prioritize the top crashes noted at https://github.com/orgs/wordpress-mobile/projects/7 over this one during Groundskeeping rotation because we want to go for the high impact issues in that rotation whenever possible. 🙏

**Comment by marecar3** [comment]
PR is created: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2276

**Comment by designsimply** [comment]
Closing as fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2276 and noting users should see the update in WPAndroid v15.0. Props @marecar3. 🎉
