### ISSUE TITLE
"Switch Site" text cut off in the header on My site if the device font size is set to Large or Largest

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#11839]
The "Switch Site" text is slightly cut off at the bottom on my device, using alpha-220. Here's a screenshot of what it looks like for me:

![wp-1588844274360](https://user-images.githubusercontent.com/2998162/81280903-10fd2e00-9051-11ea-93ab-667c5d5643f5.png)

### Steps to reproduce the behavior

* Log into any account with multiple sites.
* Navigate to the My Sites tab and view the "Switch Site" text.

@rezzap, @donalirl, and @kriskorn, didn't see the issue on their Android devices, but they're running on 14.7 while I'm on the alpha. Here's what the text looked for Kris (running on OxygenOS 9.0.11):

![Screenshot_20200507-124947](https://user-images.githubusercontent.com/2998162/81280678-bd8ae000-9050-11ea-80c0-8256cf5c1954.jpg)

##### Tested on Pixel 3, Android 10, WPAndroid alpha-220

**Comment by rezzap** [comment]
Just clarifying that I DID see the same issue on my Samsung Tab A in version 14.7-rc-3

<img src="https://user-images.githubusercontent.com/10325627/81340795-5c8ef680-90a8-11ea-925b-68683c732f21.jpg" width="400" alt="Screenshot_20200507-211433_WordPress">

**Comment by designsimply** [comment]
Strange! I can't see the same problem on my Pixel 3 Android 10 device. I tested several versions of they app by way of apk files from the [releases](https://github.com/wordpress-mobile/WordPress-Android/releases) page.

WPAndroid 14.8-rc-3|WPAndroid alpha-220|WPAndroid alpha-221
---|---|---

**Comment by designsimply** [comment]
Got it! It happens when font size is set to large or largest. h/t @theck13 

Steps to reproduce:

1. On the device, go to Settings > Display > Advanced > Font size and change it to "Largest."
1. In the app, go to My site and check to see if the "SWITCH SITE" text is cut off in the header.

**Result:** "SWITCH SITE" text is clipped in the header on the My site page if the device font size is set to Large or Largest.

Default font size|Largest font size
---|---
<img src="https://user-images.githubusercontent.com/1119271/81970347-9eee9100-95dc-11ea-9228-1328a7a5353a.png" width="200" alt="Screenshot_20200514-080931">|<img src="https://user-images.githubusercontent.com/1119271/81970528-e70db380-95dc-11ea-8664-a31f5f612e69.png" width="200" alt="Screenshot_20200514-080938">

<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
> You can see that the SWITCH SITE is not exactly centered vertically even with the default text size.  That suggests it’s some layout issue or related to padding, margin, etc.

<img src="https://user-images.githubusercontent.com/1119271/81971359-2e487400-95de-11ea-8718-b2fd5b8f84d9.png" width="200" alt="1589479486">

<p style="clear:both;"><sup>h/t @theck13 for the tip and screenshot.</sup></p>

**Comment by khaykov** [comment]
@develric `@+id/switch_site ` is using hardcoded height (I think I just copied it from before when doing IA v1). Switching it to wrap_content should do the trick.

**Comment by develric** [comment]
Hi @khaykov , thanks for sharing 🙇‍♂️! Going to create a quick PR for this later and if you can I'll ask for your review. 

Re the following:

> You can see that the SWITCH SITE is not exactly centered vertically...

I think that was intentional since there are explicit margin set.

**Comment by theck13** [comment]
For the button:
- top/bottom **_padding_** match
- start/end **_padding_** match
- top/bottom **_margin_** can differ
- start/end **_margin_** match.

**Comment by develric** [comment]
Hi @theck13 👋! Thanks for the above 🙇‍♂️! Yep that seems to be what we have here with:

```
android:layout_marginTop="@dimen/margin_medium"
android:layout_marginBottom="@dimen/margin_extra_extra_medium_large"
```

and the other parameters that match.

So I think it sounds good to keep; let me know in case you have different advise 🙇‍♂️.
