### ISSUE TITLE
Post Password Dialog : Input validation required

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11835]
### Expected behavior
That the password dialog should have input validation and empty spaces and such forth shouldn't allow it to be submitted. 

### Actual behavior
It has no input validation so you are able to set empty spaces as a password. 

<kbd><img src="https://user-images.githubusercontent.com/1509205/81223061-fa040080-8faa-11ea-8e54-9d8c3e857a28.png" width="320"></kbd>

### Steps to reproduce the behavior
1. Create a new post.
2. Go to Post Settings.
3. Click on the field and add an empty password.
4. Once you press okay you will see the empty password below the Password title.

Link to video https://drive.google.com/open?id=1A3lTcgO9MQAFmVa7heDq2XztIlO9hmMa

Tested on Google Pixel 4 XL, Android 10, WPAndroid `develop` ()

**Comment by adityabhaskar** [comment]
Hi @jd-alexander , if no one's working on this issue, I'll pick it up.

Cheers!

Adi

**Comment by jd-alexander** [comment]
@adityabhaskar yes, please go ahead 😄 If you have any questions, I am more than happy to help 🙏

**Comment by adityabhaskar** [comment]
Hi @jd-alexander 

Thanks for assigning this issue. Here's how I intend to resolve this:

If the password is empty, 
   1. Show a toast to user
   2. Ignore blank password / remove previous password

The password check will go in here:
https://github.com/wordpress-mobile/WordPress-Android/blob/a5623c4262a7fd062053161246ec1ea52caf0da6/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java#L745-L758

Does this sound ok? 

In case of an existing post password being replaced with a blank password, what do you think is the correct action:

1. Ignore change
2. Remove existing password

\#2 appears reasonable since this is how the user removes a password on a protected post. However, I'm not sure if this may cause some users to inadvertently remove passwords.

Cheers!

Adi

**Comment by jd-alexander** [comment]
Thanks for tackling this @adityabhaskar I did a review of your PR. Let me know your thoughts 😄
