### ISSUE TITLE
(ReaderDatabase) RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.main.WPMain...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11845]
It looks like this might be related to #11590 authored by @khaykov.

**Sentry Url**: https://sentry.io/share/issue/236a9338065a437d8d0eebcebc7af66e/
**User Count**: 3
**Count**: 20
**First Release**: org.wordpress.android-14.7
**First Seen**: 2020-05-06T04:17:04Z
**Last Seen**: 2020-05-07T09:43:07Z
**24 Hours**: 14
**30 Days**: 20

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: android.database.sqlite.SQLiteException: duplicate column name: is_private_atomic (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE tbl_posts ADD is_private_atomic BOOLEAN;
     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java:null)
     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1819)
     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1747)
     at org.wordpress.android.datasets.ReaderDatabase.onUpgrade(ReaderDatabase.java:187)
     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:398)
...
(28 additional frame(s) were not displayed)
```

**Comment by khaykov** [comment]
Hm. This happens when you update from quite an old version of the app (before 10.2). This happens because migration script [drops and recreates reader tables for a specific range of old DB versions](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L178), and then we go through individual version-by version upgrade scripts, which causes the issue (we try to add a row to the table that we already recreated with that row).

This issue is relatively rare and not blocking - you can open the app without any issues after the crash. 

If we want to fix it, there are a couple of ways to do it, but they are all not too elegant, so I wonder if misunderstood the logic or process behind reader DB migration scripts. 

@malinajirka I know you added support for [migration scripts](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/datasets/ReaderDatabase.java#L172) really long time ago, but maybe you remember if there was a plan on how to use them? Maybe I'm doing it the wrong way :)

**Comment by malinajirka** [comment]
I think it's a bug in 

```
 if (currentVersion <= DB_LAST_VERSION_WITHOUT_MIGRATION_SCRIPT) {
            // versions 0 - 136 didn't support migration scripts, so we can safely drop and recreate all tables
            reset(db);
            currentVersion = DB_LAST_VERSION_WITHOUT_MIGRATION_SCRIPT;
        }
```

I think it should set the `currentVersion` to the most up to date version. Since the tables were recreated with the most up-to-date script. In other words we shouldn't go through the remaining migration steps after we recreated the db from scratch. Does it make sense? (cc @khaykov )

**Comment by khaykov** [comment]
@malinajirka Thanks! This totally makes sense :)

**Comment by oguzkocer** [comment]
@khaykov Is this issue leaving users in a state they can't recover from? I don't know the details of the issue, but if that's the case I believe we need to write a post about it.

**Comment by khaykov** [comment]
@oguzkocer Yes, it might. The proposed fix rectifies that situation. 

I'll write up a short post with details after the fix will get merged.

**Comment by oguzkocer** [comment]
@khaykov In that case, I think we want to target `release/14.8` for this and might even consider a hotfix. What do you think @bummytime?

**Comment by khaykov** [comment]
@oguzkocer Sure thing. We can merge it into `develop` and cherry-pick commit into the hotfix or release branch PR.

**Comment by bummytime** [comment]
@oguzkocer @khaykov a hotfix release seems reasonable given the fact our users _might_ be in a wack state without it. 👍

**Comment by malinajirka** [comment]
I agree, this issue might be worth creating a hotfix - it's technically a hotfix for 42 users, but they would need to clear the app data or wait for the regular release otherwise.
