### ISSUE TITLE
[GlobalStep] [Android] Application displays "nothing found" when user taps on "Home" button when on "my site->pages under draft"

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-Android#11860]
Environment:
 Samsung Galaxy s9(v10).
 
 Steps To Reproduce:
 
 1. Install and open the application.
 2. log in with valid credentials.
 3. Tap on "My site"
 4. Tap on "Page".
 6. Sroll by side to "drafts"
 5. Assume there is a blog in draft.
 6. Tap on 3 dots.
 7. Webpage opens->Tap on "Menu"
 8. Tap on "Home" button.
 9. Observe that upon tapping on "Home" button application displays "nothing found".

 Actual Result:
Application displays "nothing found" when user taps on "Home" button when on "my site->pages under draft"

 Expected Result:
At my site->pages under draft, upon tapping on "Home" button application should display related blogs.

[#11860.zip](https://github.com/wordpress-mobile/WordPress-Android/files/4594777/11860.zip)

**Comment by designsimply** [comment]
Thank you for the report! This is not a bug but we should consider in a future iteration how to make this more clear.

It appears that you created a new site and it either did not have any published posts or the published posts were deleted or reverted to drafts. A blog will display the latest posts on the home page by default, and if the site does not have any published posts then it is expected that "Nothing Found" would be displayed. This setting can be changed for the site by going to My Site > Themes > Customize > Homepage Settings. Note: the Customize section is currently only available on the web and not in the app, so you may be prompted to log in again in order to see this screen.

<img src="https://user-images.githubusercontent.com/1119271/81877759-30112980-9543-11ea-888d-3d26ae202f79.png" width="200" alt="Screenshot_20200513-135525">
<p style="clear:both;"><sup>Tested with WPAndroid 14.8-rc-3 on Pixel 3 Android 10.</sup></p>
