### ISSUE TITLE
Prepublishing Nudges : Schedule's secondary action of Publish triggers scheduling

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11954]
### Expected behavior
When the user schedules a post they should see the `PrimaryAction` of `Schedule`. If they click the more button in the toolbar to display the `SecondaryAction` and they press `Publish Now` they should see `Publish Now` in the bottom sheet. 

### Actual behavior
Currently, when the `Publish Now` button is pressed and the bottom sheet is shown, `Schedule Now` is seen. 

### Steps to reproduce the behavior
1. Create a new post. 
2. Click Post Settings. 
3. Change the publish date to one in the future. 
4. Ensure that `Schedule` is being shown as the `PrimaryAction`. 
5. Click the more icon. 
6. Click `Publish Now`. 
7. Observe that `Schedule Now` is shown. 

<kbd><img src="https://user-images.githubusercontent.com/1509205/82278870-dcdb1480-9950-11ea-9083-b98ac0aec916.gif" width="320"></kbd>

Tested on Google Pixel 4 XL, Android 10, WPAndroid `https://github.com/wordpress-mobile/WordPress-Android/pull/11945` ()

**Comment by jd-alexander** [comment]
@malinajirka so I was thinking about the best way to implement this and I have some important questions before I begin. 

### Findings 

 The previous version utilized a dialog that didn't contain any state. It didn't need to make any changes to the post before starting the publish operation. 

The difference, I have noticed is we are using the bottom sheet that utilizes the `EditPostRepository` as the source of truth so how will we reflect the `Publish Now` state? 

Meaning, the `PostStatus` of the current post is `SCHEDULED` so the button will say `Schedule Now` and the `Publish Date` will say the future date. I am assuming that the user expects to see `Publish Now` and `Publish Date` as `Immediately`. 

### Solution 

1) Some ideas that came to my mind were to pass either the enum or a boolean flag that overrides the `UiStates` that represent `Publish Date` and the `Submit Button`. So, if the user trigger the `Publish Now` secondary action and this flag is passed, we ignore the `EditPostRepository` values and show the publish immediately state. If the user were to modify the date then that flag would be cleared and we would default to using the `EditPostRepository` to determine the date and button `UiState`. 

2) The simpler solution is to clear the `Scheduled` status and set the date to `Now` so the `Publish Date` says `Immediately` and the button says `Publish Now`. 
The only drawback of this approach is the user loses the date they had set but is that such a big loss? They intentionally pressed the `Publish Now` secondary action so they should be fine with the bottom sheet reflecting that state?

**Comment by malinajirka** [comment]
This logic is currently located [here](https://github.com/wordpress-mobile/WordPress-Android/blob/d8f3802c7c1d9af49fda5201530aaccb85beb0ae/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1903). I agree that in the current implementation the post is changed after the user confirms the action on the confirmation dialog. 

However, the confirmation dialog is there so the user doesn't unintentionally publish the post - it's not there to prevent the user from unintentionally clearing the scheduled date or state. Therefore, I thing #2 is definitely the right path. 

The user still won't be able to publish the post unless they click on "publish now" and confirm the action in the bottom sheet => which is the main goal. The fact that we clear the scheduled date and status is imo fine, since as you mentioned the user clicked on "Publish Now".
