### ISSUE TITLE
[ReaderPostListViewModel] IllegalArgumentException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12210]
We have a single crash for this issue and I am not sure if it's even a real one or just happened during development. @zwarm @malinajirka  I thought I'd give you two a heads up since it looks like this might be related to https://github.com/wordpress-mobile/WordPress-Android/pull/11902. Please feel free to close it if it's not relevant.

**Sentry Url**: https://sentry.io/share/issue/5c1517ddc34c493d9973b30b0af26ed8/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.0+880
**First Seen**: 2020-06-16T14:43:10.058000Z
**Last Seen**: 2020-06-16T14:43:10Z
**24 Hours**: 1
**30 Days**: 1

```
IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter tag
     at org.wordpress.android.ui.reader.viewmodels.ReaderPostListViewModel.onEmptyStateButtonTapped(null:2)
     at org.wordpress.android.ui.reader.ReaderPostListFragment.setCurrentTagFromEmptyViewButton(ReaderPostListFragment.java:1840)
     at org.wordpress.android.ui.reader.ReaderPostListFragment.access$2400(ReaderPostListFragment.java:153)
     at org.wordpress.android.ui.reader.ReaderPostListFragment$12.onClick(ReaderPostListFragment.java:1803)
     at android.view.View.performClick(View.java:6935)
     at android.widget.TextView.performClick(TextView.java:12752)
     at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
     at android.view.View$PerformClick.run(View.java:26214)
     at android.os.Handler.handleCallback(Handler.java:790)
     at android.os.Handler.dispatchMessage(Handler.java:99)
...
(5 additional frame(s) were not displayed)
```

**Comment by malinajirka** [comment]
Thanks for the ping;)

I think this happens when the user clicks on the Reader emptyViewButton while we are re-fetching tags -> the discover tags is not found in the database and null is returned. This is something we haven't anticipated and tbh I'm quite surprised it a happened. But I don't have any other explanation. Wdyt @zwarm ?

**Comment by designsimply** [comment]
**Events:** 71
**Users affected:** 55
<sub>WORDPRESS-ANDROID-D06: https://sentry.io/share/issue/5c1517ddc34c493d9973b30b0af26ed8/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1729177122&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85978914-d94d9b00-b99c-11ea-95a9-9c4c7190b5f8.png)</a>

**Note:** this is worth spending an hour or so on to see if we can fix it quickly because it's a new crash but the numbers aren't high enough yet to move it past medium priority compared to other high priority crashes we're tracking.

**Comment by malinajirka** [comment]
I've found another instance of this issue with 96 events and 76 users affected - https://sentry.io/share/issue/6af1c42d5d16439eae663e987fe95387/.

I decided to create a fix - it isn't ideal as we are technically hiding the bug. But I couldn't figure out a reason why the data are not in the db. https://github.com/wordpress-mobile/WordPress-Android/pull/12310
