### ISSUE TITLE
Feature announcements endpoint is returning an error

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12235]
While trying to fix the failing connected tests in #12234, I tried to retrieve the json response we get from `/mobile/feature-announcements` endpoint and found out that it was returning a `Missing parameter` error.

<img width="1312" alt="Screenshot_1" src="https://user-images.githubusercontent.com/662023/85094154-11462880-b1bc-11ea-847b-1766df8baff3.png">

**Comment by khaykov** [comment]
cc @develric

**Comment by develric** [comment]
Hi @oguzkocer , thanks for taking care of the connected tests issue and documenting this one here. I think this should be fixed with a running differential (D45139) that hopefully will be merged in next few days, and that among other things, widen the `app_version` parameter format to allow for example the coverage of our alpha versions format (like the `alpha-229` in the check image you reported).

I will monitor the endpoint update and follow up here once it's merged 🙇‍♂️.

**Comment by develric** [comment]
Hi @oguzkocer , in my understanding this should now be fixed with the updated endpoint merged (D45139). Could you have a bit of time to check if it works for you also so we decide if we can close? Thanks 😊

**Comment by oguzkocer** [comment]
The call seems to be successful now, so we can close it 👍
