### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.SiteModel.ge...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12341]
A single user is having this issue, so maybe it'd be a good win during Groundskeeping considering it should be easy to fix 🤞 

**Sentry Url**: https://sentry.io/share/issue/57de38ddfcb346f6b4b9fde615966757/
**User Count**: 1
**Count**: 11
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-07-01T08:54:54.819000Z
**Last Seen**: 2020-07-01T09:13:22Z
**24 Hours**: 0
**30 Days**: 11

```
NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.SiteModel.getUrl()' on a null object reference
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:612)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
     at org.wordpress.android.ui.uploads.UploadService.updateOnePostModelWithCompletedAndFailedUploads(UploadService.java:707)
     at org.wordpress.android.ui.uploads.UploadService.doFinalProcessingOfPosts(UploadService.java:993)
     at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:670)
     at org.wordpress.android.ui.uploads.UploadService.onPostUploaded(UploadService.java:1082)
...
(6 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Agree with @oguzkocer here — adding to Groundskeeping.

**Comment by designsimply** [comment]
**Events in the last 90d:** 121
**Users affected in the last 90d:** 18
<sub>WORDPRESS-ANDROID-F7H: https://sentry.io/share/issue/57de38ddfcb346f6b4b9fde615966757/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1756432648&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96306464-f5f9f700-0fbc-11eb-801a-41e1857adf97.png)</a>

**Comment by designsimply** [comment]
Number of occurrences are still very low but I'm leaving this open because of the note about it being a potentially easy fix.

**Comment by designsimply** [comment]
**Events in the last 90d:** 310
**Users affected in the last 90d:** 15
<sub>WORDPRESS-ANDROID-F7H: https://sentry.io/share/issue/57de38ddfcb346f6b4b9fde615966757/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1756432648&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105412037-68e4c080-5bf1-11eb-8791-b227e74f4705.png)</a>

I think this one's worth keeping open a little longer to see if we can get it fixed because it's related to media uploads which is an important part of the app.

**Comment by designsimply** [comment]
Numbers still fairly low but the comment about media still stands.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1756432648&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/110086205-5365c900-7d4f-11eb-8b5e-9b36bc317443.png)</a>

**Comment by mzorz** [comment]
This is interesting! This crash was happening [here:](https://github.com/wordpress-mobile/WordPress-Android/blob/4a6df393d07cf6363da6070f2bb513830dd33bec/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L625-L627
)

```
            // actually replace the media ID with the media uri
            processor.replaceMediaFileWithUrlInPost(post, String.valueOf(media.getId()),
                    FluxCUtils.mediaFileFromMediaModel(media), site.getUrl());
```

This one was still like this in [16.8.1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/16.8.1)

But it was changed recently as part of this PR here https://github.com/wordpress-mobile/WordPress-Android/pull/14191

With those changes, the offending call to `site.getUrl()` has now been removed and the `SiteModel` instance is passed down to the processor with the `@Nullable` annotation, and it is then [checked for nullity safely here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/uploads/MediaUploadReadyProcessor.java#L36):

```
String siteUrl = site != null ? site.getUrl() : "";
```

Checked Sentry and found there's no reports for version 16.9, where the changes in #14191 were shipped.

With that, I think this issue should be now fixed by these changes, so we can close this one 👍
