### ISSUE TITLE
REST all the things

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Android#1235]
Every API call should use REST if possible, otherwise fall back to XML-RPC
Let's use this issue to keep track of more specific migrations

**Comment by aforcier** [comment]
With FluxC, all WP.com/Jetpack sites are using the WP.com REST API exclusively.

**Comment by snarfed** [comment]
hi! this is (was) great news. the current app published in google play still seems to require XML-RPC, though...? i tried blocking `/xmlrpc.php` on my self-hosted site jetpack, and the app no longer works or connects.

out of curiosity, any plans to take this the rest of the way so that the app doesn't need XML-RPC at all? i'd love to be able to continue blocking XML-RPC on my site, as security hardening.

thanks in advance!

**Comment by aforcier** [comment]
@snarfed Jetpack itself requires XML-RPC to connect to your site, so unfortunately blocking `xmlrpc.php` disables your site's connection to WordPress.com entirely (and therefore, the app can't reach your site via WordPress.com either).

**Comment by snarfed** [comment]
@aforcier ugh, ok, understood. thanks for the explanation.

i guess my ask then is for jetpack itself to wean off xml-rpc, but i expect that's a bigger project, and for different people. whee!
