### ISSUE TITLE
Unified Login & Sign-Up: Default Gravatar icon changes on the Epilogue screen

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#12380]
### Expected behavior
The default Gravatar icon should stay the same during all the login flow.

### Actual behavior
The default Gravatar icon changes from an outlined icon to a filled icon on Epilogue screen, when using an Email to login.

### Steps to reproduce the behavior
1. Clear app data.
2. On the Prologue screen, if the Smart Lock dialog appears, dismiss it.
3. Tap **Continue with WordPress.com**.
4. On the Get Started screen, enter an email address associated with an account with no Gravatar profile picture.
5. Tap **Continue**.
6. On Login Magic Link screen, notice the default Gravatar icon is outlined.
7. Complete the login flow normally.
8. On the Epilogue screen, notice the default Gravatar icon is filled.

| Outlined Icon | Filled Icon |
|---|---|
|![outlined](https://user-images.githubusercontent.com/830056/86872352-88cbf100-c0b2-11ea-977a-7f3c6a98575f.jpg)|![filled](https://user-images.githubusercontent.com/830056/86872355-8b2e4b00-c0b2-11ea-8ce0-9e19e6c21554.jpg)|

Note: this issue was originally raised by @megsfulton in pbMoDN-ET-p2#comment-1225

**Comment by planarvoid** [comment]
I've investigated this issue and it seems that the problem is that the account without an avatar does actually have an avatar with [this URL](https://0.gravatar.com/avatar/90b46aa37debc685442f7dfa57ccc588?s=176&d=mm) (in my case). This points to the filled user image. This unfortunately seems to be the issue all over the place. Have you ever seen the avatar not set to the filled default icon @renanferrari ?
