### ISSUE TITLE
[ImageBlockProcessor] UnsupportedOperationException: JsonNull

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12397]
This seems to be the same issue as #12105 which was addressed by @mkevins in https://github.com/wordpress-mobile/WordPress-Android/pull/12114. The issue still happens in the latest beta. I don't know if the fix is shipped yet, but since it has a lot of events, I didn't want to risk not reporting it.

I took some time to go through all the similar issues in Sentry and found 64 different issues which all seem to point to the same root cause. I merged them aggresively to the linked Sentry issue. This is due to crashes during `EventBus` callbacks being reported as part of the event, so if a piece of code is called from different `EventBus` callbacks, they will generate different issues in Sentry. This is something I've addressed recently in #12102, but of course it only affects the issues going forward. Due to all these issues being merged, some details we add through our script was inaccurate, so I removed them manually. (such as first release, first seen etc)

@mkevins Could you please check if the fix is shipped yet? If it is, could you look into the issue again to see if we missed anything? Please feel free to ping me if you need any assistance with Sentry. (or anything else)

cc @bummytime 

**Sentry Url**: https://sentry.io/share/issue/e9b85687aca34e74af221f0ca14832aa/
**User Count**: 172
**Count**: 1072
**24 Hours**: 30
**30 Days**: 706

```
UnsupportedOperationException: JsonNull
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.ImageBlockProcessor.processBlockJsonAttributes(ImageBlockProcessor.java:36)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.BlockProcessor.processBlock(BlockProcessor.java:91)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processBlock(MediaUploadCompletionProcessor.java:78)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:59)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:60)
     at org.wordpress.android.ui.posts.PostUtils.replaceMediaFileWithUrlInGutenbergPost(PostUtils.java:433)
     at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.replaceMediaFileWithUrlInPost(MediaUploadReadyProcessor.java:25)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:611)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
     at org.wordpress.android.ui.uploads.UploadService.updateOnePostModelWithCompletedAndFailedUploads(UploadService.java:707)
...
(15 additional frame(s) were not displayed)
```

**Comment by mkevins** [comment]
Thanks @oguzkocer :+1: 

The previous fix did ship (it should be included as far back as [15.1-rc-1](https://github.com/wordpress-mobile/WordPress-Android/blob/15.1-rc-1/WordPress/src/main/java/org/wordpress/android/ui/posts/mediauploadcompletionprocessors/ImageBlockProcessor.java#L36)), so I'm glad you reported this. Also, thanks for wrangling all of these issues in Sentry that were previously masked.

> If it is, could you look into the issue again to see if we missed anything?

It seems that we are, though I have not been able to reproduce the problem. I examined the trace and what seems to be occurring is that the `id` parsed from the block header json is in some cases not `null`, but rather `JsonNull` (the singleton instance that represents JSON null instead of Java null). Here is an example of the difference:

`id == null` | `id == JsonNull`
-|-
`<!-- wp:image {"align":"full"} -->` | `<!-- wp:image {"id":null,"align":"full"} -->`
:point_up_2: Note the absence of `id` in the JSON | :point_up_2: here `id` is explicitly _defined_ as `null`
The previous fix guards for this scenario | The exception reported here arises from this scenario

I've created some tests (https://github.com/wordpress-mobile/WordPress-Android/pull/12412/commits/5a92e97531aa85bca3518b2da0820484141bbf67, https://github.com/wordpress-mobile/WordPress-Android/pull/12412/commits/281d52a1af24c28463bb59dd9cbcbe7ab6b8bce0) and confirmed that they produce the same exception: `UnsupportedOperationException: JsonNull`, and added guards to protect against this scenario in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/12412), however, I think it would be good to reproduce this from a user flow to make sure we aren't missing any other errors that could lead to problems in other places before adding such guards. I'm not sure how / why the block header json would have id(s) explicitly set to null. :thinking: 

@oguzkocer do you know off-hand if there is a particular pattern in user activity that is common in the breadcrumbs prior to this exception?

**Comment by oguzkocer** [comment]
> @oguzkocer do you know off-hand if there is a particular pattern in user activity that is common in the breadcrumbs prior to this exception?

@mkevins Unfortunately I didn't look into the breadcrumbs, so off-hand I have no idea. However, I am happy to help with it if you think it'll be valuable to you. It'll just need to be Tuesday the earliest since Monday is a release/code-freeze day.

**Comment by mkevins** [comment]
> I am happy to help with it if you think it'll be valuable to you

Thanks for the offer Oguz :smiley: . I was interested if you happened to see a pattern while you gathered the issues (which I imagine required some manual effort on your part, so thanks for that!), but no worries if you didn't.

**Comment by mkevins** [comment]
I have tried manually editing a post to insert `{"id": null}` into the block json attributes, but this fails to reproduce the problem. I've debugged the processors during an upload completion event in the resulting post by leaving the editor and allowing the media upload (in a separate block) to complete while the editor was closed. Debugging confirmed that the `id` attribute appears to be stripped during serialization of the post content prior to the processors' invocation, so it still is not clear how an explicit `JsonNull` is being parsed.

The count is currently at 1.3k, with users affected at ~ 200, and it appears to still occur in the latest release. Since the PR to guard against the `JsonNull` is fairly straightforward, and the tests reproduce the exception, I'm leaning towards proceeding with that fix. Though it isn't ideal to lack steps to reproduce, the processors are designed with the intent to modify as little as possible, and the addition of this extra guard should not alter that.

@oguzkocer I've added you as a reviewer on the fix adding the guards, if you have the time, otherwise, let me know, and I can add another reviewer. Thanks again for your help in tracking these down!

**Comment by mkevins** [comment]
Hi @bummytime :wave: :slightly_smiling_face: , I don't have great context on the urgency of this one, but just wanted to ping you in Oguz's absence. The PR should be fairly straightforward to test / review, if you're up for it, but it may not be urgent. Wdyt?

**Comment by bummytime** [comment]
@mkevins Thanks for the ping — checking it out now.

**Comment by oguzkocer** [comment]
@mkevins I was afk last week, but I am glad to see that this got resolved. I'll keep an eye on Sentry and let you know if it pops up again.
