### ISSUE TITLE
IllegalStateException:  wasn't resolved by any case in this when clause.

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12398]
**Sentry Url**: https://sentry.io/share/issue/42f39a84466148199bdfbf78004940aa/
**User Count**: 18
**Count**: 38
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-07-03T03:39:05.924000Z
**Last Seen**: 2020-07-08T16:58:58Z
**24 Hours**: 10
**30 Days**: 38

```
IllegalStateException:  wasn't resolved by any case in this when clause.
     at org.wordpress.android.ui.posts.prepublishing.visibility.usecases.GetPostVisibilityUseCase.getVisibility(GetPostVisibilityUseCase.kt:24)
     at org.wordpress.android.ui.posts.PrepublishingHomeViewModel.setupHomeUiState(PrepublishingHomeViewModel.kt:57)
     at org.wordpress.android.ui.posts.PrepublishingHomeViewModel.start(PrepublishingHomeViewModel.kt:47)
     at org.wordpress.android.ui.posts.PrepublishingHomeFragment.initViewModel(PrepublishingHomeFragment.kt:78)
     at org.wordpress.android.ui.posts.PrepublishingHomeFragment.onViewCreated(PrepublishingHomeFragment.kt:55)
...
(13 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@jd-alexander What are your thoughts on this one?

**Comment by jd-alexander** [comment]
Thanks for the ping @bummytime checking this out.

**Comment by jd-alexander** [comment]
This crash is related to the `Status & Visibility` functionality we are removing. Basically the `PostStatus` that got to the Status & Visibility option isn't supported and the app shouldn't be in that state. 

So the supported `PostStatus` that are supposed to trigger the bottom sheet ( from the Editor & Post List) are:

` PUBLISHED,
    DRAFT,
    PRIVATE,
    PENDING,
    SCHEDULED` 

and the ones that shouldn't get to it since the functionality doesn't get triggered from anywhere in the app with such a `PostStatus` are : 
    `TRASHED,
   UNKNOWN`

But currently, the exception isn't even printing a `PostStatus` so the message above `    wasn't resolved by any case in this when clause.` should be something like `TRASHED  wasn't resolved by any case in this when clause.`

In this case, since the feature is going to be removed, I could try to reproduce this state and see how the app behaves and just log this exception.

**Comment by jd-alexander** [comment]
This PR https://github.com/wordpress-mobile/WordPress-Android/pull/12427 removes the component in question that's causing this crash. It was shipped in 15.3 so once 15.3 is released then this crash will not take place any more.

**Comment by oguzkocer** [comment]
@jd-alexander When the issue is fixed, please remember to close it. If you can also resolve the Sentry issue, that'd help. Thanks!

**Comment by jd-alexander** [comment]
Thanks @oguzkocer will do!
