### ISSUE TITLE
[LoginBaseDiscoveryFragment] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12463]
This issue was reported as #11491 before and fixed in #11492. However, it looks like it's happening in the recent production release although doesn't have high numbers.

**Sentry Url**: https://sentry.io/share/issue/2e6c079378b84f72a20ac45ed5ec42d1/
**User Count**: 76
**Count**: 466
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-10T01:25:08Z
**Last Seen**: 2020-07-16T00:40:44Z
**24 Hours**: 4
**30 Days**: 43

```
EventBusException: Invoking subscriber failed
     at org.wordpress.android.login.LoginBaseDiscoveryFragment.onDiscoverySucceeded(LoginBaseDiscoveryFragment.java:43)
...
(3 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
Looks to be dwindling again. Could keep an eye on it.

**Events in the last 90d:** 659
**Users affected in the last 90d:** 72
<sub>WORDPRESS-ANDROID-68: https://sentry.io/share/issue/2e6c079378b84f72a20ac45ed5ec42d1/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1020093720&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96308259-4b83d300-0fc0-11eb-9f64-9f837935dd52.png)</a>

**Comment by designsimply** [comment]
Closing because there were no cases recorded by Sentry in the last 30d and because there have been no cases recorded by Sentry for any app version after 15.7-rc-3 in the last 90d.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1020093720&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/100553438-27681280-324b-11eb-9bb3-12dd92540f21.png)</a>
