### ISSUE TITLE
DeadObjectException in InstallationReferrerServiceLogic.onInstallReferrerSetupFinished

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12465]
It looks like maybe `mReferrerClient` is cleared up by GC before the callback, so it might be good to check that out.

**Sentry Url**: https://sentry.io/share/issue/bc434295f8b144768849e9bc34a9df8f/
**User Count**: 223
**Count**: 596
**First Release**: org.wordpress.android-13.7
**First Seen**: 2019-12-04T14:49:13Z
**Last Seen**: 2020-07-16T13:42:40Z
**24 Hours**: 1
**30 Days**: 47

```
DeadObjectException: 
     at org.wordpress.android.util.analytics.service.InstallationReferrerServiceLogic$1.onInstallReferrerSetupFinished(InstallationReferrerServiceLogic.java:69)
...
(5 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Adding to groundskeeping.

**Comment by designsimply** [comment]
I can see that Sentry reported this issue as having started 9 months ago in org.wordpress.android-13.7 so I agree with moving to Groundskeeping.

**Events in the last 90d:** 584
**Users affected in the last 90d:** 84
<sub>https://sentry.io/share/issue/bc434295f8b144768849e9bc34a9df8f/</sub>

It's also worth noting the frequency has been very low over the last 90d and has gone down from ~2 to 4 issue per day before Jun 30 to only 4 instances after Jun 30.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1371119107&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/91350955-ac531400-e7a4-11ea-8f76-c871307d6d19.png)</a>

@oguzkocer I also noticed this issue is tagged as an error, not a fatal, in Sentry and that there have been no new cases above v15.0 in the last 90 days. Do you think it's still worth investigating considering those details? Asking because you  made a specific note about checking out when `mReferrerClient` is called and if you think it's worth it then I can see leaving it open due to that.

**Comment by oguzkocer** [comment]
The reason this error no longer shows up is because we removed all the crash logs (`error` type Sentry issues) a while back, so this got removed as part of it [here](https://github.com/wordpress-mobile/WordPress-Android/commit/3984a4f8d9aa7090d93dd79aa050c8358475a811#diff-6f21283e30f3228c960c81242d354739L89-R89). That doesn't mean the issue is gone, it just means we are just not tracking it.

@designsimply I think it's worth doing a quick check by maybe time-boxing it to about two hours and see if anything looks out of order. If the investigation doesn't reveal anything, I guess we can just close the issue.

It doesn't seem so from a very quick look, but just to cover our basis, #10532 might be related.

**Comment by antonis** [comment]
This seems to be linked with https://github.com/wordpress-mobile/WordPress-Android/issues/9985 (that caused crashes [recently](https://sentry.io/organizations/a8c/issues/1016999115/?project=1438088&query=onInstallReferrerSetupFinished&statsPeriod=14d)) and both are related with the [Play Install Referrer Library](https://developer.android.com/google/play/installreferrer/library). We currently use version `1.0` and the latest version is `2.1`. Since updating the library might prevent those crashed I'm adding the `Tech debt` label to be revisited.

**Comment by designsimply** [comment]
Let's update the library! Are there any worries about doing that or is it an easy update?
