### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.optInt(java.lang.String, int)' on a nul...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12552]
Another issue with very low number of users but very high number of events, so might be worth prioritizing. The first release seems wrong to me, not sure why. `15.0` seems like the first meaningful release for this.

**Sentry Url**: https://sentry.io/share/issue/cdafd860323d4df49e911de5ce5af741/
**User Count**: 5
**Count**: 590
**First Release**: org.wordpress.android-12.8
**First Seen**: 2019-07-25T20:17:52Z
**Last Seen**: 2020-07-20T14:26:07Z
**24 Hours**: 0
**30 Days**: 515

```
NullPointerException: Attempt to invoke virtual method 'int org.json.JSONObject.optInt(java.lang.String, int)' on a null object reference
     at org.wordpress.android.ui.prefs.WPComSiteSettings.deserializeWpComRestResponse(WPComSiteSettings.java:662)
     at org.wordpress.android.ui.prefs.WPComSiteSettings.access$000(WPComSiteSettings.java:31)
     at org.wordpress.android.ui.prefs.WPComSiteSettings$1.onResponse(WPComSiteSettings.java:178)
     at org.wordpress.android.ui.prefs.WPComSiteSettings$1.onResponse(WPComSiteSettings.java:171)
...
(4 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Interesting issue. In the past 2 months, I'm seeing a single person encounter this crash. @designsimply, it probably is worth having somebody investigate this NPE on the next Groundskeeping rotation just as a sanity check.

**Comment by designsimply** [comment]
@bummytime according to the data I'm seeing right now, only 3 users were affected that got recorded in this Sentry issue in the last 90 days but the frequency come in at 995 which I found confusing at first. Upon a closer look, it appears that it has a relatively high number of cases in 15.7 and then it started up again more heavily in 15.9-rc-1 and 15.9-rc-2. Because the cases are happening mostly in a beta release and a release one back from the current latest stable, I think a case like this should normally be triaged by a developer as a new crash to see if we can stop it sooner than later. Also, sending an issue to Groundskeeping, especially with low numbers, could take months before it gets reviewed because we typically look at the most severe crashes in Groundskeeping and don't always close very many since they are typically the ones that take the most time and energy to solve. Capacity is also a factor because we only do Groundskeeping once per month per platform and sometimes Hack Weeks take their place and we try to address issues other than crashes such as top user-reported issues and other internal requests. That said, our next Android rotation happens to be next week (we didn't have one in September because of Hack Week) and I will add this to the requests list. 🙂

**Events in the last 90d:** 995
**Users affected in the last 90d:** 3
<sub>WORDPRESS-ANDROID-3JQ: https://sentry.io/share/issue/cdafd860323d4df49e911de5ce5af741/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1126295697&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/96308925-7c183c80-0fc1-11eb-8545-21a81dca6341.png)</a>

**Comment by bummytime** [comment]
Thank you @designsimply! 🤠
