### ISSUE TITLE
Sign up: Quick Start prompt does not happen if you sign up and create a new site using the new UL&S flow

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#12578]
Steps to reproduce:

1. Install WPAndroid 15.4 or higher.
1. Log out.
1. Tap the Continue with WordPress button.
1. Enter an email address not already associated with a WordPress.com account.
1. Follow the prompts to sign up.
1. Create a new site.
1. Expect to see a prompt asking, "Want a little help getting started?" after signing up and creating a new site.

**Result:** I do not get a Quick Start prompt when signing up for a new site through the Unified Login & Signup flow (Jul 2020 project launching in 15.4) but I do get the Quick Start prompt if I create a new site _after_ I have logged in. ([2m30s](https://cloudup.com/c-sWridqfwl), [3m7s](https://cloudup.com/cOZkNSiaRcL))

Starting here, no Quick Start prompt is given|A Quick Start prompt happens if you start here though|Quick Start prompt
---|---|---
![screenshot_20200730-153732](https://user-images.githubusercontent.com/1119271/89086948-b7ef1e80-d34f-11ea-8e99-1190c0adf13c.png)|![screenshot_20200730-153718](https://user-images.githubusercontent.com/1119271/89086946-b7ef1e80-d34f-11ea-9332-ae834fd495c0.png)|![screenshot_20200730-153225](https://user-images.githubusercontent.com/1119271/89086945-b6bdf180-d34f-11ea-9a41-29f4fa924725.png)

<p style="clear:both;"><sup>Tested with WPAndroid 15.4-rc-1 on Pixel 3 Android 10.</sup></p>

<sup>(internal reference: p5T066-1rB#comment-5496-p2)</sup>

**Comment by bummytime** [comment]
@renanferrari any updates on this one?

**Comment by renanferrari** [comment]
>1\. Install WPAndroid 15.4 or higher.
> ...
>6\. Create a new site.

@designsimply As I mentioned during our internal discussion, I believe this bug was introduced before that version and that it only happens when creating a site from the Post Signup Interstitial. Can you confirm this or is there something I'm missing?

--- 

@bummytime Already shared this with you internally, but sharing it here again to give it more visibility and also to add some more details:

As far as I can tell, this is actually related to the Post Signup Interstitial screen and not the new flow. Basically, we are not passing the results from the Site Creation screen back to the Main screen, so it doesn’t know it needs to display the Quick Start dialog.

A bit more explanation: when the Site Creation screen is finished it sends a result back to its caller informing whether or not a site was successfully created. So when we start the Site Creation flow from the Site Picker screen, the chain looks something like this:

`WPMainActivity → SitePickerActivity → SiteCreationActivity`

When finished, `SiteCreationActivity` passes its result back to `SitePickerActivity`, which then performs some action based on it (like refreshing the site list) and then passes the result further back to the `WPMainActivity`, which in turn uses it to decide if the Quick Start dialog needs to be displayed or not.

The same isn’t happening when we start the Site Creation flow from the Post Signup Interstitial screen, because it starts the `SiteCreationActivity` without expecting a result, and the screen chain is a bit more complex:

`LoginActivity → WPMainActivity → SignupEpilogueActivity → WPMainActivity → PostSignupInterstitialActivity → SiteCreationActivity`

In this particular case, `WPMainActivity` is actually started twice, but always in the background (the user actually doesn't see it). To achieve the behavior we want, we would have to signal to the `SiteCreationActivity` that we are expecting a result, but also (and here's the tricky part) to make sure `WPMainActivity` receive it, even though we're finishing both `SignupEpilogueActivity` and `PostSignupInterstitialActivity` in between.

I have a couple of ideas on how we could approach this, but none are really that simple. I'm still considering other options and should share an update here (or in a PR) soon.
