### ISSUE TITLE
Adding to the Reader P2 Follow/Unfollow comments capability

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#12602]
### Background

We already massively use P2 blogs internally in a8c to enforce teams project collaboration and we are going to launch the P2 Product [p7DVsv-8N3-p2] pretty soon. 

In a P2 web page we allow a user to Follow/Unfollow a stream of comments to a post by the `Follow` button available at the bottom of a post itself.

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89401055-05370b80-d715-11ea-8bcf-5bf2b49d831a.png>
</p>

The effect of Following a post comments stream is that the user gets notified by emails of new comments to that post.

### Task

With the above in mind we would like to add the capability in the app to Follow/Unfollow a P2 post comments stream from the Reader (will add some mocks related to this soon)

### Relevant endpoints

- [Subscribe to a post comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/new/)  
- [Unsubscribe from a post comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/mine/delete/)
- [Get subscription state](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post/subscribers/mine/)

This will require some work on the [FluxC library](https://github.com/wordpress-mobile/WordPress-FluxC-Android) as well

NOTE: the new P2 Product blogs are marked as `"is_wpforteams_site": true,` in the site options response

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89405144-606bfc80-d71b-11ea-804d-d6b915d7100b.png>
</p>

as of current understanding this does not apply to older a8c internal P2s. In case we cannot find a flag that marks an old P2 site as being a P2 we could eventually evaluate to assume that the blogs that are in the reader Automattic Tab are P2s (note those P2s are only available to Automatticians).

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89405504-f7d14f80-d71b-11ea-8acc-41e8390b6a10.png>
</p>

**Comment by designsimply** [comment]
This came up in an app review:

> It does not allow you to access notifications, not even comments or sites followed. 
> 
> <sup>1-star app review Sep 7, 2020 at 1:16 PM - A7 Pro WPAndroid 15.5.1 Android 10</sup>

<sup>google-play-reviewid=gp:AOqpTOFyu1QJghB73esWuPgdYICF131y5uTmbZfIB1CxXcSHxTi0kXFDPr2paMQmCmVfo7lg5Md3eSrtgv7AGA</sup>

Accessing notifications and getting notifications about posts followed site should be possible (I think we just need to explain the settings to them) so I sent a reply about that, however, they are correct that following comments is not yet available.

@yaelirub are comment follows a planned update for the Android app? I saw that they will be updated in the iOS app in version 15.7 (https://github.com/wordpress-mobile/WordPress-iOS/pull/14721) and also noticed this issue is in a backlogged milestone. Does that just mean we'll need to wait a few releases more to see this update on the Android side?

**Comment by yaelirub** [comment]
Hey @designsimply  👋 
This project is a candidate for a project but I know @frosty has some ideas about this task.

**Comment by designsimply** [comment]
Ace. Thanks @yaelirub!

**Comment by mindgraffiti** [comment]
Removing from Trial Projects board as it is will be included in the future P2 + Comments projects.
