### ISSUE TITLE
Add an in-app review prompt

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Android#12605]
Google recently released a [new In-App Review API for Google Play reviews](https://android-developers.googleblog.com/2020/08/in-app-review-api.html). From their [developer docs](https://developer.android.com/guide/playcore/in-app-review):

> The Google Play In-App Review API lets you prompt users to submit Play Store ratings and reviews without the inconvenience of leaving your app or game.
>
> Generally, the in-app review flow can be triggered at any time throughout the user journey of your app. During the flow, the user has the ability to rate your app using the 1 to 5 star system and to add an optional comment. Once submitted, the review is sent to the Play Store and eventually displayed.

Naturally, there are some restrictions to consider:

> To protect user privacy and avoid API misuse, there are strict guidelines that your app should follow about when to request in-app reviews and the design of the review prompt.

Let's figure out how to integrate this into WPAndroid!

/cc @mattmiklic @frosty @yaelirub

**Comment by hafizrahman** [comment]
This is cool! I'd suggest making the prompt appear after user successfully publishes a new post or page.

**Comment by frosty** [comment]
We already implement the existing app rating system – @khaykov, would you be able to take a quick look and see how different this is from what we use already?

**Comment by khaykov** [comment]
@frosty It is pretty different. Currently, we just show a dialog that takes user to the Play Store where he has to write a review. The new review prompt and API are superior, and we will probably get more reviews from them since you can do it without leaving an app. 

I checked the guidelines and we are in a clear with our current and new flow.

**Comment by mattmiklic** [comment]
In terms of design, could we re-use the existing prompt to review, but have it lead to this new in-app UI instead of linking out to the Play Store?

**Comment by khaykov** [comment]
@mattmiklic No, If I understand the guidelines correctly:

> Your app should not ask the user any questions before or while presenting the rating button or card, including questions about their opinion (such as “Do you like the app?”) or predictive questions (such as “Would you rate this app 5 stars”).

**Comment by mattmiklic** [comment]
Ahh ok, thanks for clarifying that. I had a chance to look through the documentation and it sounds like we'd be required to figure out situations in which it would feel natural and unobstructive to make this modal dialog appear. 

I think this requires greater sensitivity than our current prompt in Notifications (are there more?) because there will be no ability to present the option to review the app in-line with what they're already doing. The only way to trigger this is in a modal sheet, which if timed incorrectly, could be annoying to the user and potentially lead to a bad review.

So I think we should take a little time to think about when we'd want to show the user this kind of sheet. After publishing is just one idea, but I'm sure there may be more.
