### ISSUE TITLE
Contact Support: Set character minimum

### ISSUE THREAD

**Issue by msilbers** [wordpress-mobile/WordPress-Android#12736]
We'd like to see if we can set a character minimum for when folks contact us. We get a fair amount of tickets that include things like the following:

- Hi
- Hii
- Hey
- hello
- text

If we could set a character minimum in the form to at least 6, it would help most of this (I hope!), but I can see up to 10 characters being good too. Folks should be sending us questions and their site link, and I don't think it's possible to do that in 10 characters.

mentioned in comment on p8wKgj-1ox-p2

**Comment by mzorz** [comment]
I've been checking their [documentation](https://developer.zendesk.com/embeddables/docs/android-support-sdk) and couldn't find a way to do this as a SDK consumer.

I also wonder, this behavior is requested for the _first_ message only, and then we'd have to lift the character limit after the first message has been sent (so in order to allow conversations with shorter words like "yes", "no" to happen seamlessly). I doubt they'd have this functionality with this specific behavior but we can ~try asking them for a feature request.~ _EDIT: I asked, waiting for them to reply._

Also to note, we're [on version 2.0.0 of it](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/build.gradle#L322-L324), not sure why we're stuck there since they're already on 5.0.0 as per their SDK's [release notes](https://developer.zendesk.com/embeddables/docs/android-support-sdk/release_notes). Summoning @oguzkocer here since maybe you have some insights? 🙏 (forgive me if it's been some time already, but wondering whether there are plans to update)

**Comment by designsimply** [comment]
If we cannot enforce a character limit using the SDK in our current implementation, would it be possible to identify the tickets with a very short amount of text and tag them so that an auto-responder could then be triggered on the Zendesk side?

<sup>(internal reference: p8wKgj-1ox-p2#comment-8682)</sup>

**Comment by mzorz** [comment]
> would it be possible to identify the tickets with a very short amount of text and tag them so that an auto-responder could then be triggered on the Zendesk side?

That's a great idea! however if we tried to do this from the Android app itself, the SDK is closed in this aspect, we present the chat screen and it doesn't expose this information to us (so we can't really tell what length the messages are).

**Comment by mzorz** [comment]
> we present the chat screen and it doesn't expose this information to us (so we can't really tell what length the messages are).

I wonder if this is possible from Zendesk side on the web though? 🤔

**Comment by oguzkocer** [comment]
> Also to note, we're on version 2.0.0 of it, not sure why we're stuck there since they're already on 5.0.0 as per their SDK's release notes. Summoning @oguzkocer here since maybe you have some insights? 🙏 (forgive me if it's been some time already, but wondering whether there are plans to update)

@mzorz As with almost every library/SDK that's outdated, as far as I know, it's because nobody has updated it yet. We don't have a process in place to regularly update our dependencies, which we probably should, so it happens fairly randomly. I think Hack week would be a great time to do these upgrades since we already go through so many changes and the app pretty much needs to be tested as a whole.

**Comment by mzorz** [comment]
> @mzorz As with almost every library/SDK that's outdated, as far as I know, it's because nobody has updated it yet.

Thank you for your answer @oguzkocer, I imagined you wouldn't have this information but since you were among the last people to work on the Zendesk files in the repo it still made sense to ask.

**Comment by bummytime** [comment]
**Nov 2nd, 2020 Update:** @mzorz emailed Zendesk about this and they replied that having a minimum character limit is **not** possible with any version of the Zendesk SDK.  

Ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/14695#issuecomment-720625770

cc @msilbers @ScoutHarris

**Comment by bummytime** [comment]
After a quick chat with @elibud, we decided to close this issue since nothing can happen on the app side. Please re-open if this situation changes.
