### ISSUE TITLE
App Slowness reported when editing posts.

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#12907]
### Expected behavior

We would expect the app to respond quickly and blocks to respond correctly to content size and selection when adding new text despite the length of the post they are trying to edit. 

### Actual behavior

A user has reported in response to an app review, that the behaviour of the app is very slow and they see significant delays when trying to edit long posts. 

### Steps to reproduce the behavior

They've shared a video with the exact steps that is available in the ticket. 

A couple of issues we noted from the video:

* Opening a post to edit is very slow.
* Block size sometimes not resized immediately when typing over the current size.
* Clicking on another block, the typing happens, but the block is not displayed as active (doesn't have the blue rounded rectangle indicating a block is active).
* Cutting/copying a text from a block, then move it to another block, is not happening immediately. It's very slow.
* Once the cursor active in another block, pasting doesn't happen immediately. It took sometimes and when a typing happens, suddenly the text is pasted, removing part of, if not all, the current typing.

They mention this is happening on a post that is longer than 2000 characters. I was able to replicate some delays in opening a long post to edit and also the delay in the block resizing from my Samsung Tab A, Android 10, WP app 15.6-rc-2

@sarahfg wasn't able to replicate any of this on her Pixel 3, Android Version 10, running WP App Alpha-241. 

##### User reported on Moto E5 Cruise, Android 8.0, WPAndroid TBC

Reported in 3285801-zen

This may require separate issues, but I'm not sure if it's more device-related so opted for one report to start with.

**Comment by designsimply** [comment]
Thanks so much for reporting this @rezzap! It's way cool that this person took the time to send in a video!

We are tracking two performance-related issues that I think cover the most prevalent cases they've brought up in https://github.com/wordpress-mobile/gutenberg-mobile/issues/2594 and https://github.com/wordpress-mobile/gutenberg-mobile/issues/1888. Let's close this issue in favor of following those for now and we can re-visit after any updates go through if we keep seeing similar user feedback after that. BTW, thank you for filing a case here because now we'll have a search path in case someone searches for the same thing again here in the future.

<sup>(also see internal reference: p9ugOq-1gR-p2#comment-2565)</sup>
