### ISSUE TITLE
Support: "Browse our FAQ" link does not respond if an automattic.com email address is saved in the contact email field

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13015]
### Expected behavior
I would expect to be able to access the FAQ page to check out the app's documentation.

### Actual behavior
Tapping Browse our FAQ does nothing.

### Steps to reproduce the behavior

1) Go to Me > Help & Support
2) Tap on Browse our FAQ
3) The screen stays and does nothing

### Application log

```
94 - [Sep-25 10:19 STATS] 🔵 Tracked: support_help_center_viewed
95 - [Sep-25 10:19 UTILS] trackLastActivity, activityId: Help Screen
96 - [Sep-25 10:19 STATS] 🔵 Tracked: support_help_center_viewed
97 - [Sep-25 10:19 UTILS] trackLastActivity, activityId: Help Screen
```

##### Tested on OPPO Reno 4, Android 10, WPAndroid 15.8-rc-1

**Note:** The Browse our FAQ feature is working fine on Huawei Nova 2i, Android 8, WPAndroid 15.7.

**Comment by designsimply** [comment]
Thanks for the report @reginabally. I have a few questions if you don't mind?

1. Does pull-to-refresh help at all?
1. If you go back to the My Site screen and then browse back to the Help & Support screen, is the FAQ link still unresponsive?
1. Does this problem happen if you log in using a test user account?

Aside: this came up in beta testing for 15.7 from another happiness engineer (and I wanted to recognize that) but I wasn't able to replicate it reliably at the time and I double checked just now using 15.8-rc-1 on my Pixel 3 Android 10 and it's still working properly for me. FTR, I see the exact same lines in the app logs even when the link works and loads properly.
<sup>(internal reference: p5T066-1vr-p2#comment-5840)</sup>

<img src="https://user-images.githubusercontent.com/1119271/94296905-d8d38a80-ff20-11ea-9c87-d3f5570fa482.gif" width="185" alt="20200925_111633">
<p style="clear:both;"><sup>Tested with WPAndroid 15.8-rc-1 on Pixel 3 Android 11 logged in as design5279.</sup></p>

**Comment by msilbers** [comment]
I was able to replicate this just now on the beta (15.8-rc-1). I had just opened and scrolled through the FAQ. However, after checking My Site and navigating back, the "Browse Our FAQ" button no longer did anything. I checked my app logs and it shows no errors.

Closing and reopening the app didn't resolve it, the Browse our FAQ button no longer works for me.
Edit: It works again after uninstall/reinstall.

**Comment by designsimply** [comment]
Thanks for testing @msilbers! 

To summarize, we've seen 3 reports of this, starting in 15.7 beta testing, all from a8c accounts and no reports from users yet (based on what has been reported in this issue). It only appears to happen after something goes wrong with the link and deleting/reinstalling the app fixes the problem but we would like to avoid giving delete+reinstall as advice if at all possible. In other words, we should only recommend delete+reinstall as a last resort or in extreme cases such as cannot startup the app.

If the broken "Browse our FAQ" happens to anyone else, or if you see it again, can you let me know if clearing app cache resolves the problem. If clearing app cache doesn't work, does clearing app storage resolve the problem? Also, please note whether you're seeing this problem while logged in as a non-a8c user or if you've only seen the problem when logged in as an a8c user. Thanks tons!

**Comment by msilbers** [comment]
Just want to note that I tested with a non-a8c account and it worked just fine!

**Comment by reginabally** [comment]
It's also worth mentioning that once I switched to a test account, I was able to access the FAQ with the Browse our FAQ button. After I switched it back to my HE account, I'm able to access the FAQ page too!

Not directly related to the issue but I used to try sending a test message through Contact Support under Help and Support but I wasn't able to send using my a8c email account. So I guess there's a validation/checking somewhere to verify if it's an a8c account for these two options?

**Comment by simison** [comment]
On a8c account, using alpha-253 release I see empty page:

<img src="https://user-images.githubusercontent.com/87168/97988681-06e0a000-1de6-11eb-9dfe-d4720f7178e9.jpg" width="270" alt="2020-11-03 15 04 41">

**Comment by designsimply** [comment]
Thank you for the screenshot @simison! 

I tested again and confirmed that this is only happening if an @automattic.com email address is saved in the contact email field in the Help & Support section, and I was able to reproduce the issue using the following steps:

1. Go to My Site > Account > Help & Support > Contact email.
1. Enter any email address ending in @automattic.com and tap OK.
1. Go to Browse our FAQ.
1. Observe the error "Failed to get categories" appears and the support FAQ cannot be loaded.

<img src="https://user-images.githubusercontent.com/1119271/105250293-bbad7200-5b36-11eb-8c18-1bcbe833fbc1.png" width="270" alt="Screenshot_20210120-154554"> <img src="https://user-images.githubusercontent.com/1119271/105250291-bb14db80-5b36-11eb-9184-3df4921552a5.png" width="270" alt="Screenshot_20210120-154614">
<sup>Tested with WPAndroid alpha-268 on Pixel 3 Android 11 while logged in with `mobile-support@automattic.com` saved in the contact email field.</sup>

In comparison, if the contact email is not set or if I enter a non-automattic.com email address in the support section settings then the help pages work normally for me:

<img src="https://user-images.githubusercontent.com/1119271/105251806-69ba1b80-5b39-11eb-8660-195a6dc93432.png" width="270" alt="Screenshot_20210120-152510"> <img src="https://user-images.githubusercontent.com/1119271/105251803-67f05800-5b39-11eb-8f93-641d639fc0a1.png" width="270" alt="Screenshot_20210120-152535">
<sup>Tested with WPAndroid alpha-268 on Pixel 3 Android 11 while logged in with `mobile-support@automattic.com` saved in the contact email field.</sup>

Aside: the "failed to get categories" error has come up before in the past ([10919](https://github.com/wordpress-mobile/WordPress-Android/issues/10919)) when the Help Center was mistakenly deactivated in the automattic.zendesk.com settings, however, I tried checking this by logging in to that site and clicking the gear icon at the bottom of the left menu and it does appear to be active because there's an ominous looking "Deactivate" button at the bottom of the "Guide settings" section so I assume that means it is active. ([screenshot](https://user-images.githubusercontent.com/1119271/105251574-0a5c0b80-5b39-11eb-96ba-c4121f0afea8.png))

> I wasn't able to send using my a8c email account. So I guess there's a validation/checking somewhere to verify if it's an a8c account for these two options?

@reginabally correct, it's not possible to send a help request through the app using an a8c email address. It would be a good enhancement if we could get a warning about this in the app as it does come up from time to time but it has not been given priority as a task in the past as it does not affect most users.

**Comment by thehenrybyrd** [comment]
The "Browse our FAQ" link now opens the Mobile App Support docs directly in a web browser, even with an automattic email address entered in contact details. Closing this issue.
