### ISSUE TITLE
WordPress Lint Checks not running on the codebase

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#13100]
### Expected behavior
That the WordPress Lint dependency should run checks against the files in our codebase.

### Actual behavior
The checks aren't being run. 

### Steps to reproduce the behavior
 Basically you would need to push a change that's supposed to break the lint rules that exist within the WordPress Lint dependency and the build will pass which means the checks aren't being run. Check this PR for more details. https://github.com/wordpress-mobile/WordPress-Android/pull/12847

**Comment by thehenrybyrd** [comment]
@jd-alexander I'm just doing some routine triage here - can you help me determine if this is still an issue?

**Comment by jd-alexander** [comment]
> @jd-alexander I'm just doing some routine triage here - can you help me determine if this is still an issue?

Hi @thehenrybyrd I don't currently have the WordPress-Android app setup on my computer to check because I am working at Tumblr now. You could ask one of the WP Android folks in the android channel to see if this is still the case. I think that it may still be the case but it would be better to get it verified. 

If you aren't able to get anyone to test I could setup the app on my computer and do it but I just thought of suggesting that you chat with someone who is in this codebase on a daily basis as they will have a better idea of the changes that have been made there since I haven't really contributed to it much in almost two years.

**Comment by thehenrybyrd** [comment]
Yep, will do, thanks @jd-alexander!

**Comment by thehenrybyrd** [comment]
@AliSoftware would you be able to take a quick look at this?

**Comment by thehenrybyrd** [comment]
@AliSoftware would you be able to take a quick look at this?

**Comment by AliSoftware** [comment]
I'm not sure if this is about:
 - The "WordPress Lint" step not running on our CI on PRs
 - The "WordPress Lint" step running, but not including the right files, and failing to include the expected files in our codebase
 - The `lintWordPress` gradle task not working, even locally

This issue is 2 years old, and we have updated our CI configuration a lot since then. In particular, we migrated from CircleCI to Buildkite, we rewrote our steps to lint both WordPress and Jetpack and re-enabled them on CI, and we fixed some lint failures/warnings along the way.
So before digging deeper into this to check if there's still an issue (while it's likely obsolete now given all the changes that happened), I'd love to understand what was the actual problem to begin with back then 🙂

**Comment by thehenrybyrd** [comment]
I got confirmation from @AliSoftware that the WordPress Lint step does get triggered and run in CI currently, so I'll close this since it seems to be no longer an issue.
