### ISSUE TITLE
Duplicate post created if the internet connection is lost while trying to save a draft post

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13137]
Steps to reproduce:

1. Go to My Site > Blog Posts > Drafts > +.
1. Add a title and some content.
1. Tap More (three dots at top right) > Save.
1. Quickly turn off the network connection or turn on airplane mode.
1. Observe that the new draft now has a notice on it in the Posts List that says,<br>"We couldn't complete this action but we'll try again later."
1. Turn on the network connection again.
1. Go back to the Drafts list and observe that the draft automatically uploads.

<strong>Result:</strong> a duplicate draft post is saved if the internet connection is turned off while trying to save. ([1m20s](https://cloudup.com/ct8H8N6wFNA))

Go offline while draft is uploading|Post uploads after back online|Duplicate post created
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/96052197-4268f980-0e3a-11eb-9055-282bc0a87e71.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 14 PM">|<img src="https://user-images.githubusercontent.com/1119271/96052195-4268f980-0e3a-11eb-8eeb-2b5f2d0e0750.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 23 PM">|<img src="https://user-images.githubusercontent.com/1119271/96052193-41d06300-0e3a-11eb-8422-c03688aa3a6f.png" width="270" alt="Screen Shot 2020-10-14 at Oct 14 4 21 31 PM">

<sup>Tested with WPAndroid 15.9-rc-2 on Pixel 3 Android 11 on a WordPress.com Free site (fuzzywuzzy.home.blog) while logged in as user design5279.</sup>

**Comment by designsimply** [comment]
Possibly a regression of https://github.com/wordpress-mobile/WordPress-Android/issues/9347.

Also, note that the user reports on https://github.com/wordpress-mobile/WordPress-Android/issues/8594 are more likely this bug (or another similar one) because those users reported duplicates being persistent (like in the test above) and unlike in the 8594 issue where the duplicate post only appears briefly.

> Everything works fine until it gets long and lots of media added. Now it shows two identical blogs in my list.

> On my blog the latest post (still a draft which I'm still editing) has for some reason duplicated itself. There is no way I did that.

<sup>(internal references: p4a5px-2om-p2/#comment-9755 and 1953510-zen, reported on Apr 17, 2019 10:09 WPAndroid 12.1.2)</sup>

> I have had an ongoing issue with the app for YEARS where, when I post, the app often posts the same thing multiple times, and again if I edit the post. The last time I posted, the app posted at least 8 duplicates...

> Yes, I have published from many, many locations (Wifi vs data, etc...), and the same issue occurs.

> This has also spanned multiple Android devices, starting with the Nexus 6P, then to the Pixel 2, then finally the Pixel 3, running Android 10 (current).

<sup>(internal reference: 2463838-zen, reported on Nov 01, 2019 15:51 WPAndroid 13.4)</sup>

> Very often i have a duplicates of posts. Fix, please

<sup>(internal reference: 2721292-zen, reported on Feb 17, 2020 01:35 WPAndroid 14.1)</sup>

**Comment by malinajirka** [comment]
This is a known issue and unfortunately one we can't fix without making changes to the API.

Let me try to explain the issue on an example:
1. Create a draft in the app -> `remoteId` is 0 since the draft exists only on the mobile device
2. Click on `save` button -> a http request with the draft is send to the server -> the server assigns a new `id` (called `remoteId` in the mobile apps) -> the server send a response back to the app
3. Go offline before the response is received -> the app doesn't know the `remoteId` since it got lost along with the response
4. Go online -> the app sends a new http request with the draft to the server -> the server doesn't know it's the same draft so it assign a **new** `id` (called `remoteId` in the apps) -> the server sends a response back to the app
5. The app receives the response and updates `remoteId` of the draft from 0 to the actual remoteId.
6. The app re-fetches changes from the server -> there is "a new draft" so it displays it (it's the duplicate created in step `2`)

I can't think of any meaningful client side solution. I think we have two options
1. IMHO the proper solution: Assign a UUID to each post created in the apps. The server in step `4` would recognize it's still the same draft and it wouldn't create a duplicate. This requires changes on both sides client + backend. If we use the UUID just for this one endpoint, I believe the changes shouldn't be too complicated.
2. Hotfix on the backend: Compare if the same post has been recently uploaded and return "duplicate_error" or success 🤷 . I'm not sure about the complexity of this solution.

@bummytime This is one of the issues which keeps circling back to us. I'm not sure how many users are actually affected by it, but we might want to consider syncing with the API folks and implementing a proper fix. Wdyt?

**Comment by bummytime** [comment]
Thank for the deets here @malinajirka. 

@designsimply do we have a sense of how many people are impacted?

**Comment by designsimply** [comment]
@bummytime I don't have a good sense of how many are affected overall what I can tell you is that reports from users do come in consistently over time. If I had to guess I'd say the number affected is low but the frustration level for the ones that are affected is high—so I'd say reports are low impact, high severity, recurring on a regular basis. Does that help?

**Comment by SiobhyB** [comment]
Noting this recent comment about the possibility of this issue now being fixed: https://github.com/wordpress-mobile/WordPress-Android/issues/9845#issuecomment-811349543

It could be worth closing this if now new reports come in after some time.

**Comment by AmandaRiu** [comment]
I was unable to replicate this issue using an emulator or on a physical device. Closing.
