### ISSUE TITLE
Improving Error Messaging for non-English characters in Site Creation Flow 

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Android#13220]
### Expected behavior

I would expect to be told non-English characters are not supported if I'm using unsupported characters in trying to create a site. 

### Actual behavior

When trying to create a site using a language like Arabic or Chinese, we see the error `No available addresses matching your search` instead. It would be helpful if we could show a message that non-English characters are not supported in site addresses on WordPress.com. 

### Steps to reproduce the behavior

1. Navigate to the site creation flow and add a new WordPress.com site.
2. Use Chinese, Arabic, Hebrew, etc. characters to create a new site address.
3. See the error. 

![image000000](https://user-images.githubusercontent.com/154014/97027566-8639be00-1520-11eb-8c0c-065bac4305af.png)

##### Tested on Pixel 3, Android 11, WPAndroid 16.0-rc1

Internal report: p4a5px-2Ez-p2#comment-11419
WPiOS companion issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/15155

**Comment by bummytime** [comment]
On WP.com, this is the error displayed when the `اختبارات` is used as a site name:

<img width="953" alt="Screen Shot 2020-10-23 at 11 18 46 AM" src="https://user-images.githubusercontent.com/154014/97028480-d1080580-1521-11eb-94c1-64b598c731aa.png">

**Comment by ovitrif** [comment]
According to the internal report a solution could be to use the error message from the API, since it was translated after the improvement to the error messages referenced at p4a5px-2Ez-p2#comment-11509 was merged.

I'll explore what we get by using the error message from the API and ask for additional feedback once I have a working solution; thank you @bummytime for providing the link to the discussion on this. 👍

**Comment by ovitrif** [comment]
@antonis Following up on my initial idea to check if we can use the error message from the backend I proceeded to inspect the network calls behind the domain input.

Error when I input `الجماعة` (the app is in English):  

```json
{
  "error": "invalid_query",
  "message": "Domain searches only support the following characters (many accents are also allowed): A-Z, a-z, 0-9, -, ., space. You searched for the following unsupported characters: \u0627\u0644\u062c\u0645\u0627\u0639\u0629"
}
```

Then I checked if the API error message is translated by changing the app language to Dutch, and it is:
```json
{
  "error": "invalid_query",
  "message": "Het zoeken naar domeinen ondersteunt alleen de volgende tekens (veel accenten zijn ook toegestaan): A-Z, a-z, 0-9, -, ., ruimte,. Je hebt gezocht naar de volgende niet-ondersteunde tekens: \u0627\u0644\u062c\u0645\u0627\u0639\u0629"
}
```

For me the error message is a bit technical, but on the plus side it seems aligned with the language used on this screen, I.e. both the error message and the title include the word "domain".

I did a quick test by hardcoding the error message to see how the backend error looks in the app:

| Before | After |
| ---- | ---- |
| ![before](https://user-images.githubusercontent.com/4588074/154090658-7d62c19b-2bf0-47a8-ad7d-1b2abc610aeb.png) | ![after](https://user-images.githubusercontent.com/4588074/154090720-f573f942-412b-4d05-b2e4-93d4f4458629.png) |





Let me know what you think of this. There are 2 main different approaches we can take to solve this faster:

1. Use a different, less technical error message which is managed in the app(s) (this appears to be a quicker fix)
2. Use the error message returned by the API

~I think both approaches might need changes in WordPress-FluxC-Android~ &rarr; That's not actually true, FluxC parses the error, but in the WordPress-Android code the result gets mapped to `ListState.Success` regardless of the actual backend response. 

Probably the main work for fixing the issue will revolve around making the app recognise the error because currently the state is always labelled as "success" (also for HTTP Status Code: 400). Below is the `toString()` representation of the `state` variable captured while debugging:

```
org.wordpress.android.models.networkresource.ListState$Success@47fdc08
```

EDIT: Further digging into the code led me to this comment, which reveals that mapping `INVALID_QUERY` to `Success` is intended:
```kotlin
// We want to treat `INVALID_QUERY` as if it's an empty result, so we'll ignore it
```

**Comment by antonis** [comment]
Great investigation @ovitrif 👍 
Let's move forward with option 1 for now since this is a low priority issue and this screen might be deprecated in the near future (ref: `pc8HXX-6Z-p2`). We can document your findings to revisit this if needed. Wdyt?

**Comment by ovitrif** [comment]
Thank you @antonis for checking this and suggesting the option for fixing the issue!

> We can document your findings to revisit this if needed. Wdyt?

Sounds like a good plan to me! 👍
