### ISSUE TITLE
Cannot exit from previewing changes to a post or page and still continue using the app

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13320]
Steps to reproduce:

1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap the ellipsis menu (top right) > Preview.
1. Tap the arrow at top left to go back.

And:

1. Go to My Site > Blog Posts and open any pre-existing post or page.
1. Make any change to the post.
1. Tap the ellipsis menu (top right) > Preview.
1. Tap the arrow at top left to go back.

**Result:** the app becomes stuck showing a "Saving…" dialog if you try to preview changes to a post before saving and you cannot use the app again until you force close and re-open it. ([2m38s](https://cloudup.com/cob2tEd0EGU))

<img src="https://user-images.githubusercontent.com/1119271/98419912-49eb7f00-2043-11eb-8e19-8ee7a5ca9737.png" height="350" alt="Screenshot_20201106-115928">

<sup>Tested with WPAndroid 16.1-rc-1 on Pixel 3 Android 11 tested on a WordPress.com Simple site madefortesting110620.wordpress.com logged in as user110620.</sup>

**Comment by reginabally** [comment]
I'm able to replicate this on OPPO Reno 4, Android 10 and WPAndroid 16.1-rc-1. Video recording: https://d.pr/v/SUmqqQ/udAqnWP7Rn

**Comment by malinajirka** [comment]
This might be related to https://github.com/wordpress-mobile/WordPress-Android/pull/12144 and https://github.com/wordpress-mobile/WordPress-Android/pull/13124 (cc @mchowning)

**Comment by cameronvoell** [comment]
I reproduced this immediately when testing using WPAndroid 16.1-rc-1 (downloading APK from release page and building locally both showed the issue). 

However this issue is not occuring on latest WPAndroid `develop`, I narrowed down that the issue seemed to be fixed by PR https://github.com/wordpress-mobile/WordPress-Android/pull/13217 which was merged just after `16.1-rc-1` was merged to develop. 

If we would like to fix this for the 16.1 WPAndroid release the following PR shows the changes I believe we need: https://github.com/wordpress-mobile/WordPress-Android/pull/13331

**Comment by designsimply** [comment]
I re-tested using WPAndroid 16.2-rc-2 by exiting several different previews and confirmed it's no longer getting stuck. Props @cameronvoell @planarvoid @mchowning. 🎉
