### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13463]
**Sentry Url**: https://sentry.io/share/issue/1caa56f08ba140ff8ff1b53d31810f5c/
**User Count**: 165
**Count**: 335
**First Release**: org.wordpress.android@15.7+924
**First Seen**: 2020-09-25T11:43:36.074000Z
**Last Seen**: 2020-11-24T07:42:18Z
**24 Hours**: 11
**30 Days**: 206

```
ExceptionInInitializerError: 
     at org.wordpress.android.ui.posts.editor.ImageEditorFileUtils.deleteFilesOlderThanDurationFromDirectory(ImageEditorFileUtils.kt:10)
     at org.wordpress.android.ui.posts.editor.ImageEditorInitializer$Companion$init$1.invokeSuspend(ImageEditorInitializer.kt:43)
...
(4 additional frame(s) were not displayed)
```

**Comment by leandroalonso** [comment]
@ashiagr `deleteFilesOlderThanDurationFromDirectory` was recently added. Do you have any idea what might be causing this crash?

**Comment by ashiagr** [comment]
Sorry about the late reply, I missed this GH Mention due to some filters I think.

Noticed this issue in the reports:
`exception: NoSuchFieldException: _decision`

It occurs on:
Brand: `Samsung`
OS: 99% `Android 5.0.x`

Related discussions from `kotlinx.coroutines`:
https://git.io/JLNP0
https://git.io/JLNPL

I'll take a deeper look and update here.

**Comment by designsimply** [comment]
**Events in the last 90d:** 703
**Users affected in the last 90d:** 261
**Majority of cases are:** Android 5.0.x
<sub>WORDPRESS-ANDROID-RW3: https://sentry.io/share/issue/1caa56f08ba140ff8ff1b53d31810f5c/}</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1913181912&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105527873-79ed0a80-5ca1-11eb-9af0-6f7a40c930f8.png)</a>

43.28% | Android 5.0 
-- | -- 
43.11% | Android 5.0.2 
13.09% | Android 5.0.1 
0.35% | Android 8.0 
0.17% | Android 5.1.1

I agree it's worth a look in the short term if possible @ashiagr since it's a new crash. But if you cannot solve it in a short amount of time, please send it to Groundskeeping and it will get triaged again the next time we review issues. 👍

**Comment by designsimply** [comment]
Looping back with a quick update. Still happening in the latest release, still limited to Samsung devices using Android 5.0.x.

**Events in the last 90d:** 892
**Users affected in the last 90d:** 190
**Limited to:** Android 5.0.x on Samsung devices
<sub>WORDPRESS-ANDROID-RW3: https://sentry.io/share/issue/1caa56f08ba140ff8ff1b53d31810f5c/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1913181912&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/111197274-e5f23d80-8583-11eb-8ef0-a0a726a15915.png)</a>

**Comment by jkmassel** [comment]
This only happens with very very old versions of the app, so this can be closed.
