### ISSUE TITLE
Domain credits are not being offered to Atomic sites

### ISSUE THREAD

**Issue by renanferrari** [wordpress-mobile/WordPress-Android#13580]
While working on #13568, I noticed that domain credits were available for some of my Atomic test sites on Calypso, but not on the app. These test sites are all on the Business plan, but this only seems to happen with sites that have already been converted to Atomic:

Calypso (before converting to Atomic) | Calypso (after converting to Atomic)
------------ | -------------
<img width="270" src="https://user-images.githubusercontent.com/830056/101836575-6b48fa80-3b1c-11eb-9ef9-2d1cc9896311.png"> | <img width="270" src="https://user-images.githubusercontent.com/830056/101836577-6c7a2780-3b1c-11eb-9870-5574cc350fcc.png">

WPAndroid (before converting to Atomic) | WPAndroid (after converting to Atomic)
------------ | -------------
<img width="270" src="https://user-images.githubusercontent.com/830056/101836699-a64b2e00-3b1c-11eb-9b2d-56aaac346df1.jpeg"> | <img width="270" src="https://user-images.githubusercontent.com/830056/101836695-a4816a80-3b1c-11eb-9f76-4b1d04e3bbf8.jpeg">

I'm not sure if this behavior is currently known or what's causing it exactly, but since [it seems to be happening on iOS as well](https://user-images.githubusercontent.com/830056/101837166-689ad500-3b1d-11eb-95cc-06372e42a329.jpeg), I guess there's either some API limitation for the apps or we are simply overlooking this particular scenario, in which case we should probably take a look at how Calypso is doing it and try to replicate it on the apps.

### Steps to reproduce the behavior
1. Create a new site.
1. Upgrade it to the Business plan.
1. Open the app and go to the My Site tab.
1. Notice that the domain credit is being offered.
1. On the web, convert the site to Atomic (try to install a plugin or go to `Jetpack > Backup` and activate it).
1. Restart the app and go back to the My Site tab.
1. Notice that the domain credit is not being offered anymore.

**Comment by renanferrari** [comment]
I've received confirmation this is not a known behavior, so I'm updating its priority accordingly.

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid 16.3-rc-2 on Pixel 3 Android 11 that if I have setup a WordPress.com Business site on the web, I cannot see the "Register Domain" prompt in the app after I have done the step that changes the temporary domain from *.wordpress.com to *.wpcomstaging.com. ([1m19s](https://cloudup.com/cVTx2fJBbeG))

We should update to make the domain credit available in the app if it is available on the web.

Site address ends in wpcomstaging.com|Domain credit is available in Calypso|Domain credit is not available in the app
|:---:|:---:|:---:|
<img src="https://user-images.githubusercontent.com/1119271/101940889-6f205f80-3ba4-11eb-83f1-93e9f63a3367.png" width="270" alt="wpcomstaging-address">|<img src="https://user-images.githubusercontent.com/1119271/101941118-c7576180-3ba4-11eb-9da0-ced824ea7217.png" width="270" alt="domain-prompt-on-web-for-wpstaging-site">|<img src="https://user-images.githubusercontent.com/1119271/101940893-70518c80-3ba4-11eb-80de-050ff61a7f09.png" width="270" alt="missing-domain-registration-prompt-atomic-site-16 3-rc-3">

Note: I verified this is limited to WordPress.com Business sites with at least one plugin installed and that has not yet selected a custom domain. Other types of sites such as WordPress.com Premium do not show the same problem because they do not use a *.wpcomstaging.com domain.

<sup>Also see internal reference C011BKNU1V5/p1607707264245400-slack-wpmobile asking for this to be done in Groundskeeping within the next few months.</sup>
