### ISSUE TITLE
Unable to select a .blog subdomain

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13653]
### Expected behavior

I would expect to be able to select a .blog subdomain regardless of whether I'm choosing a homepage design when creating a new site.

### Actual behavior

If I skip the homepage design picker or select a certain homepage design (the first or the second in the list), I can only select a WordPress.com subdomain. I can select a .blog subdomain when I choose the third or the fourth homepage design.

### Steps to reproduce the behavior

1. Go to My Site > Switch Site > "+" > Create WordPress.com site
2. Tap "SKIP" to skip choosing a homepage design
3. Type a keyword to search for a site address, e.g. testsite20201222
4. See that the available options are WordPress.com subdomains
5. Go back to the homepage design selection screen, select the first or second design in the list
6. See that the available options are WordPress.com subdomains
7. Go back to the homepage design selection screen again, select the third or the fourth design in the list
8. See that the available options are .blog subdomains.

Screen recording: https://d.pr/v/7JGKtT/QZpjqsCWZB

**Comment by designsimply** [comment]
This tripped me up in the past as well, but in my case it was for the previous type of site selection in the create site flow (see screenshot from v16.1 below). I had assumed I should be able to see .blog subdomains for some of the different options but they were actually only intended to show if the "Blog" option was selected. Discussed at https://github.com/wordpress-mobile/WordPress-Android/issues/13417#issuecomment-731445425.

<img src="https://user-images.githubusercontent.com/1119271/103721649-6e080580-4f8b-11eb-9558-ccd10431aa2e.png" width="270" alt="image">
<sup>Tested with WPAndroid 16.1-rc-1 on Pixel 3 Android 11.</sup>

Now that we've updated to the homepage layout picker, I am not sure what the expected behavior is so I'll defer to @chipsnyder 🙂  (I just wanted to chime in with some background and screenshots). 

<img src="https://user-images.githubusercontent.com/1119271/103721902-0d2cfd00-4f8c-11eb-8da1-e18693a0966b.png" width="270" alt="image">
<sup>Tested with WPAndroid 16.4-rc-3 on Pixel 3 Android 11.</sup>

**Comment by chipsnyder** [comment]
There is a bit more info on why we went this route in an internal reference here `pbAok1-1MG#comment-3581`

Ultimately we did use the theme's segment that mapped to the segment's in the previous flow. Although this does make it less clear to a user on how to get a .blog domain. I went ahead and added this ticket and the [iOS one](https://github.com/wordpress-mobile/WordPress-iOS/issues/15553) to our board.

**Comment by chipsnyder** [comment]
Dropping a note here b/c it came up in a side conversation. We can achieve this by settings the same parameters the backend uses for blog segments. iOS has these tied to an enum here: https://github.com/wordpress-mobile/WordPressKit-iOS/blob/767b0ba87dbc7b0d026b2a01760f80042159be0b/WordPressKit/DomainsServiceRemote.swift#L59-L63
