### ISSUE TITLE
NullPointerException: updatedSite must not be null

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13664]
**Sentry Url**: https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/
**User Count**: 9
**Count**: 10
**First Release**: org.wordpress.android@16.2+961
**First Seen**: 2020-12-09T21:11:26.370000Z
**Last Seen**: 2020-12-22T23:22:59Z
**24 Hours**: 2
**30 Days**: 10

```
NullPointerException: updatedSite must not be null
     at org.wordpress.android.viewmodel.pages.PageListEventListener.onSiteChanged(PageListEventListener.kt:180)
...
(1 additional frame(s) were not displayed)
```

**Comment by loremattei** [comment]
This has not many occurrences, but since it has been introduced recently we may want to fix it.

**Comment by ashiagr** [comment]
Assigning low priority and adding to Groundskeeping.

Severity - Low: edge case (doesn’t affect core/default functionality)
Impact - Low: estimated 0-5% of users affected.

**Comment by designsimply** [comment]
I noticed this crash is new in 16.2 so I [looked at PRs](https://github.com/wordpress-mobile/WordPress-Android/pulls?q=is%3Apr+is%3Aclosed+milestone%3A%2216.2%22+page+) filed in the 16.2" milestone containing the word "page" and saw that, besides a few library updates, the majority of page-related updates were for the Home Page Picker project but I am not sure those would be related tbh. @antonis would you mind having a quick look at this crash to see if anything jumps out at you as the cause for it and do a quick fix _if_ it's quick or add a note with ideas for testing if not? At this point, it's not worth spending a ton of time on it because the occurrences are low but it is worth a quick check to see if anything stands out.

**Comment by antonis** [comment]
Thank you for pinging me @designsimply 👍 
I did a preliminary investigation on this. The crash occurs when the `getSiteByLocalId` [function](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/06b3ae0579529757f5a9321286cf9fbe38d79f49/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java#L1203) returns null.
There are [cases that this follows a site creation](https://sentry.io/organizations/a8c/issues/2081853904/events/df6c2d80b08d4aa2996195966fb8fa1b/?project=1438088) and others that are not (e.g. [1](https://sentry.io/organizations/a8c/issues/2081853904/events/d2f973c490ed4983a5f7fd78c40d06fe/?project=1438088), [2](https://sentry.io/organizations/a8c/issues/2081853904/events/5bdfd41a87e94aaaa12d8799fcc9e035/?project=1438088)). Thus I don't think this is directly related with the additions for the Home Page Picker.
A quick workaround would be to [perform a null check before using the `updatedSite` constant](https://github.com/wordpress-mobile/WordPress-Android/blob/f351591289d166f0ca2d4f2b00fb72188e281b58/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt#L177) but this will actually just hide the problem since `getSiteByLocalId` is used in many places. Since this does not affect many users my suggestion would be to investigate this deeper during a Groundskeeping rotation.

**Comment by designsimply** [comment]
Awesome. We should definitely avoid fixes that hide a problem, thank you for pointing that out.

**Events in the last 90d:** 57
**Users affected in the last 90d:** 51
<sub>WORDPRESS-ANDROID-10NE: https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A2081853904&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105533329-38f8f400-5ca9-11eb-8853-4b8abb4e5e02.png)</a>

Low instances so we'll probably look at other higher impact crashes next and circle back to this one later.

**Comment by designsimply** [comment]
**Events in the last 90d:** 115
**Users affected in the last 90d:** 99
<sub>WORDPRESS-ANDROID-10NE: https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A2081853904&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/111197811-88122580-8584-11eb-89ba-b66951a365f5.png)</a>

**Comment by ashiagr** [comment]
I wasn't able to reproduce this issue. The only thing I'd share is that, in several instances, users deleted a blog around the same time when the crash occurred. 

E.g. See User's ReportCard (Blog Audit Trail) for crash instances: [1](https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/), [2](https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/), [3](https://sentry.io/share/issue/762bf8571c744bd69bdc10deb8ac4f66/)

**Comment by zwarm** [comment]
I spent a couple of hours during my groundskeeping rotation trying to reproduce this issue and was not successful. I tested site creation, changing the homepage, and deleting a site. I also tried deleting a site on the web and then trying to add pages and changing homepage via the app. No crashes and the appropriate errors messages show. The numbers are still low. And as Antonio pointed out above, we _could_ just wrap the check with a null, but that won't help us solve the underlying issue.
