### ISSUE TITLE
Slow Loading Insights Stats Screen

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#13685]
### Expected behavior

When visiting the Stats Insights page, I would expect a short loading time.

### Actual behavior

It actually takes quite a while for the page to load on first and second reload (after pulling down to refresh). 

### Steps to reproduce the behavior

1. Go to My Sites > Select any site with stats.
2. On the Insight tab, notice how long the delay is before the content loads. 
3. Pull down to refresh, same time is needed to refresh the tabs too.
4. Navigate to the other tabs (Days, Weeks, Months, etc..) content shows right away.

Reported in an app review: 

> But the stats page takes a loooooooooooong time to reload. It's it just me or is it the app?

* Device: Huawei 荣耀9青春版
* Device language: English
* App version name: 16.3
* Android 9 (SDK 28)

<sup>(internal reference: play-store-reviewId=gp%3AAOqpTOEVgHXUuZaqwNqswUEhAjthVdfSCYp5XjzzWdXwTHfkmUl4YT1wX7a8dBj3jv4mmPP-lbBuxq3IENUpFA&corpus=PUBLIC_REVIEWS)</sup>

**Comment by ParaskP7** [comment]
👋 @rezzap !

Would you mind attaching a recording of this behavior as it seems that on my device and network the loading time for the stat tabs and cards to appear seems reasonably fast.

The only thing I am noticing, that I wouldn't have expected otherwise, is the fact that the pull-to-refresh loading icon on top persists for some (additional) time even though the stat tabs and cards have already loaded. This makes me think that there might be some kind of extra loading happening in the background, which tries to update the information that is already shown. But, this would require further investigation.

**Comment by designsimply** [comment]
I tested with WPAndroid 16.4-rc-3 on Pixel 3 Android 11 and Stats loaded reasonably quickly for me as well. ([46s](https://cloudup.com/cRtey88klpI)) I also tried with a site that has a lot more traffic (not pictured in the video but if you have access, you can try checking en.blog) and I did notice the loading icon remained for quite a long time even though the stats cards did already appear to load, as you already noted @ParaskP7. 

@rezzap if possible to get the info, it may help to note how many views per day are showing on the sites being tested (i.e. ~5,000 views per day) as it might be relevant if the delay is only happening for sites with a large amount of traffic.

**Comment by rezzap** [comment]
@designsimply  @ParaskP7 Sorry for the delay on this one!

What I'm seeing is the same as what Sheri shows in the video. I think the difference here is that the other tabs instantly have content showing while the Insights tab shows loading for some time. It's not a significant delay, but if that's expected I think it's fine to close this issue for now. We haven't received many other reports about this I believe.

**Comment by ParaskP7** [comment]
👋 @rezzap !

Thanks for the response. 🙏 

> What I'm seeing is the same as what Sheri shows in the video. I think the difference here is that the other tabs instantly have content showing while the Insights tab shows loading for some time.

Great, we are all consistent on that then. 👍 

> It's not a significant delay, but if that's expected I think it's fine to close this issue for now.

It is not significant indeed. Whether that is expected or not it probably depends. Out of the top of my head I think this loading indicates that although the screen was done loading there are some kind of other data that is pending loading, maybe on other tabs, thus the delay. But, this needs to be further investigated so that we can get to the bottom of this.

@designsimply , your thoughts?

> We haven't received many other reports about this I believe.

This is good to know, thanks for sharing! 🌟

**Comment by designsimply** [comment]
Ok, so what I'm hearing is that we got one user complaint that Stats Insight is loading slowly but after testing ourselves we think it only _feels_ slow in comparison with other stats screens—which seem to display instantly when we switch between different Stats tabs. While I do think it would be lovely to improve the user experience by making the Insights screen as delightfully fast as the other screens 🙂  I think it is out of scope for now. 

@ParaskP7 do you feel it's important enough to leave the issue open to re-visit later or would you prefer to close the issue with an ask to re-open it if we receive similar feedback from more users in the future?

**Comment by ParaskP7** [comment]
👋 @designsimply !

> Ok, so what I'm hearing is that we got one user complaint that Stats Insight is loading slowly but after testing ourselves we think it only feels slow in comparison with other stats screens—which seem to display instantly when we switch between different Stats tabs. While I do think it would be lovely to improve the user experience by making the Insights screen as delightfully fast as the other screens 🙂 I think it is out of scope for now.

I agree.

> @ParaskP7 do you feel it's important enough to leave the issue open to re-visit later or would you prefer to close the issue with an ask to re-open it if we receive similar feedback from more users in the future?

I am tending towards the `close the issue with an ask to re-open`. However, I am not sure what an `ask to re-open` closed issue will look like or how we deal with those afterwards.

**Comment by designsimply** [comment]
It just means we close and mention in a comment to please re-open and create a new issue if it comes up again. 👍
