### ISSUE TITLE
[Home Page Picker] Wrong design applied

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#13749]
**Describe the bug**
The wrong design is applied in Home Page Picker when creating a site with the Overton layout design.

**To Reproduce**
1. Start the site creation flow (e.g. Choose site > Add button)
2. Select the Create WordPress.com site option
3. Select the **Overton** design
4. Press **Choose**
5. Search and select a domain
6. Select create site
7. Notice that the created site has the **Leven** design applied

**Expected behavior**
The created site should have the **Overton** design applied

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android
 - Version 16.4

**Comment by antonis** [comment]
Hello @chipsnyder, @enejb 👋 
I opened this issue after a report from @mkevins in his empathy challenge. It's the first time I noticed this behaviour which is reproducible on Android only.
Investigating this further I noticed that [on iOS the `segment_id` is `null` during the site creation](https://user-images.githubusercontent.com/304044/104319125-1e748d00-54e9-11eb-861c-d8ce7f071f51.png) while on [Android the `segment_id` value of the design is used](https://user-images.githubusercontent.com/304044/104319134-203e5080-54e9-11eb-8cc2-2b02d17d61c5.png).
I remember [adding the `segment_id` field](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1754) specifically I probably I misunderstood its usage.
I [opened a PR fixing this on Android](https://github.com/wordpress-mobile/WordPress-Android/pull/13751) but I'm not sure if it a client issue or the service should handle the `segment_id` value differently or ignore it. Wdyt?

**Comment by enejb** [comment]
I think what is going on is that there is no such thing as an "Overtone" theme. (https://wordpress.com/theme/overton) the site layout is called overtone but it is based on the "Leven" theme. So when you go to the customizer even though you picked "Overtone" in the layout picker you end up with the "Leven" theme. 

Hopefully that makes sense. 

I am not sure what the solution to this should be? With site layouts we are introductory a completely new concept to WordPress. Maybe the simplest solution would be to not show the Layout labels to the user. Since they are not really that meaningful.

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13751
