### ISSUE TITLE
App Review: Changes made on desktop not getting updated in the app

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#13793]
Reported in the app review:

> I think there were some problems after the last update. If the note was created in the app, but then edited in the desktop, it doesn't see the changes, it doesn't see the published version, only the app versions.

Date of review: Dec 14, 2020, 00:05
App version name: 16.2
Android version (SDK): Android 10 (SDK 29)

I've tested this on self-hosted as well as Jetpack sites but I wasn't able to replicate it. We've requested the user to reach out to us so that we can take a look.

There's a similar issue on WPiOS that's being tracked [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/9449).

**Comment by AmandaRiu** [comment]
Tested the following scenarios on a Pixel 4 running Android 11:
- Edit a post using the Desktop app then open on mobile. **Only updates after a PTR on the posts list. Expected**
- Edit a post on mobile but don't save it (local changes). Edit the same post on Desktop and publish. **Refreshing the lists of posts mobile shows a version conflict as expected.**
- Edit a post on the web then refresh the list of posts on mobile. Open post. **Updated post as expected**

The only way I was able to reproduce this issue was to **not** manually refresh the list of posts on mobile before opening the edited post. Once the list of posts have been refreshed, the changes are always available. 

Closing this ticket as it appears to no longer be an issue.
