### ISSUE TITLE
Review the convenience of changing the overlay message 

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-Android#13815]
This issue was spawn from #7103 to keep track of this two comments ([#1](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-755770958) and [#2](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-759810809)). 

Overall the #7103 was addressed in #13752 so we are closing it but this is a note to eventually come back to reconsider, as a further improvement, the possibility to change the Media upload fail overlay message that currently is a generic one like below

<p align=center><image src="https://user-images.githubusercontent.com/47797566/105047423-98b58c00-5a6a-11eb-9802-f80bcf586b61.png" width=300/></p>

Ideally we could report the error message related to the upload issue instead.

Some analysis on what should be changed in GB side was [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-689695617)

**Comment by hypest** [comment]
Thanks for the ticket @develric !
Feels to me this ticket might not be easily addressable though or we might not just be able to cover all cases to close it so, may I ask, is this ticket about introducing some way to pass detailed error messages, or is it about covering the various cases by specializing their messages?

If it's the latter, I think it'd be better if we have specific cases/flows mentioned so to make the ticket more actionable? WDYT?

**Comment by develric** [comment]
Hi @hypest , 
the first reason to create this ticket was to decouple the main solution implemented for the #7103 in the PR #13752 (that is adding a snackbar to the Editor currently to report messages related to media upload issues) so it was not lost by closing the aforementioned thicket. 

It would deserve more digging, but my first understanding was: if we implement the changes highlighted [here](https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-689695617) we should be able at least to pass a `causeOfFailure` string to GB side so that we could replace the static generic message `Failed to insert media` with a more descriptive one that is currently reported in the added snackbar. I can see an advantage in having the message in the overlay (like you don't risk to miss it when the snackbar is dismissed automatically). 

It requires some work on both GB and WP app side though, so wanted to open this mainly to keep track of this possibility and discuss if it's worth or not. 

Don't think it's an urgent thing to act on since we have the snackbar solution in place but happy to hear your thoughts (and of course also from design in case) so we can further dig it or decide to close.

**Comment by hypest** [comment]
Ah, I see, thanks for expanding @develric !

OK so, looks to me like we're interested in a "causeOfFailure" passing and displaying mechanism so, may I suggest rephrasing the ticket title and description to point to just that? Feel free to include all the context you already mentioned, that will help connect the dots. In the end, I feel the ticket will be perfectly actionable when we decide to work on it.
Does that still portray the goal of this ticket?

**Comment by SiobhyB** [comment]
I confirmed I was able to get the error message to display in the overlay for both iOS and Android following the suggested changes described at https://github.com/wordpress-mobile/WordPress-Android/issues/7103#issuecomment-755770958:

| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/154537150-a0de4d9e-a2a7-403c-880d-150a3c464066.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/154537693-105cdc3b-fc46-4212-9004-9011b8ab568c.png" width="100%"> |

However, following design feedback at https://github.com/wordpress-mobile/gutenberg-mobile/issues/2448#issuecomment-1043270046, we're going to refine the current generic message to `Tap for more info.` instead of displaying the full error message in the overlay. 

I'll go ahead to close this issue as we've decided against changing the overlay further for now, but it can be reopened if anyone feels strongly against that decision.
