### ISSUE TITLE
In Dark Mode Text Color Does Not Change Automatically (to a light one - presumably white)

### ISSUE THREAD

**Issue by Sandkorner** [wordpress-mobile/WordPress-Android#13841]
### Expected behavior
In dark mode the "Reader" should change the dark text color to "white" or some light color (perhaps light grey etc.) automatically.

### Actual behavior
On Android in dark mode the text color of posts stays the same as they are/were in light mode. Yellow is yellow, green is green, black is black etc. 

### Steps to reproduce the behavior
1. Publish a post with different color text in it. 
2. Use Android phone in dark mode to access that post in "Reader"
3. Success!? ... Shows the same color text as in light mode. 

##### Tested on [device], Android [version], WPAndroid [version]
Phone: OnePlus5 
OS: Oxygen OS 10.0.1 (based on Android 10)
WP App version: 14.7

Images on Android: 

<img src="https://user-images.githubusercontent.com/71094068/105397645-022fc900-5c2a-11eb-9412-022b249de99b.jpg" width="270" alt="Screenshot_20210121-204005"> <img src="https://user-images.githubusercontent.com/71094068/105397660-04922300-5c2a-11eb-8af2-50336489284f.jpg" width="270" alt="Screenshot_20210121-204011">

Same Images on iOS: 

<img src="https://user-images.githubusercontent.com/71094068/105397738-1d023d80-5c2a-11eb-9732-cffdb04f003a.PNG" width="270" alt="IMG_1021"> <img src="https://user-images.githubusercontent.com/71094068/105397748-1f649780-5c2a-11eb-925e-f592e9994e42.PNG" width="270" alt="IMG_1020">

**Comment by designsimply** [comment]
Nice catch @Sandkorner!

Tested and confirmed using WPAndroid 16.5-rc-3 on Pixel 3 Android 11:

Text with colors in Reader|Same content in Chrome
---|---
<img src="https://user-images.githubusercontent.com/1119271/105416301-27efaa80-5bf7-11eb-934e-eab1a1904f13.png" width="270" alt="Screenshot_20210121-144138">|<img src="https://user-images.githubusercontent.com/1119271/105416295-2625e700-5bf7-11eb-99c5-f42b3131ad62.png" width="270" alt="Screenshot_20210121-144317">

**Comment by zwarm** [comment]
Reviewed during groundskeeping rotation. This was fixed in #13958 and retested in WPAndroid 17.2-rc-2.  

Reader Light|Reader Dark|Browser
---|---|---
<img src="https://user-images.githubusercontent.com/506707/116242947-6c2da200-a734-11eb-8a2d-040db15fe4e8.png" width="270" alt="Screenshot_20210121-144138">|<img src="https://user-images.githubusercontent.com/506707/116242956-6df76580-a734-11eb-8591-12305d3b4fd5.png" width="270" alt="Screenshot_20210121-144317">|<img src="https://user-images.githubusercontent.com/506707/116243088-92534200-a734-11eb-895b-61c10e7a2c69.png" width="270" alt="Screenshot_20210121-144317">
