### ISSUE TITLE
Show topics picker screen to allow users to add topics to their initial selection

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-Android#13972]
relevant WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/issues/15806

Based on user feedback - Show the topic picker again to allow adding topics. 
One suggestion was to replace "Add a topic" on the setting screen to "add topics" and show the topic picker from there but this needs design 

### Current
<img src="https://user-images.githubusercontent.com/1335657/106979337-fc021800-6712-11eb-884e-0c047fd21a22.jpeg" width="270" alt="IMG_18FB79BD05B9-1">

### Design (iOS)
![a](https://user-images.githubusercontent.com/793774/108564197-bcb9f680-72d0-11eb-9c16-6085d62d5828.png)

**Comment by ParaskP7** [comment]
👋 @mbshakti !

Quick questions in terms of design.

1) What happens when you are on the `Follow topics` screen (`3rd screen`) and you click the `Done` button after selecting a couple of new topics from the chip group list? Do you go back to the `Manage` screen (`2nd screen`) and get those new topics appear there or do you completely go back to the `Reader` screen (`1st screen`)?
1) Is the `Done` button always enabled, even if you don't select any of the topics? If so, when you click on it, will it navigate back to previous screen?
    * From the `3rd screen` to the `2nd screen` and from the `2nd screen` to the `1st screen`, or
    * To the `1st screen` no matter which screen you are in at any given point in time (`3rd` or `2nd screen`)?
1) Is it possible to get `Android` specific designs for the `2nd` and `3rd screen` (ie, Android specific toolbar and navigation controls, back button and flows, etc)?

🙏

**Comment by mbshakti** [comment]
Hi @ParaskP7! Thanks for the questions. I've documented the behavior here, let me know if I'm missing anything.
![behavior(2)](https://user-images.githubusercontent.com/6350997/108759152-fcbfea00-7519-11eb-8d7e-3c79f8ffe051.png)

For the android designs, I'm working on it, and will share by the end of today.

**Comment by ParaskP7** [comment]
👋 @mbshakti !

Thank you so much for sharing the behavior. 🙏 

I am copy-pasting the current design below, for future reference (from Figma):

![image](https://user-images.githubusercontent.com/9729923/108813085-faf93380-75b8-11eb-9fd0-de4bf12fee8c.png)

The only thing I am missing from the design are the `Done` button on the `topic picker` screen. Let me know how you would want that to work. Currently the `Done` button works like the below:

Without Topics Selected | With Topics Selected
-------|------
<img width="250" height="500" alt="before" src="https://user-images.githubusercontent.com/9729923/108813236-47dd0a00-75b9-11eb-8037-e1d0c8260d6e.png"> | <img width="250" height="500" alt="after" src="https://user-images.githubusercontent.com/9729923/108813289-693df600-75b9-11eb-8a09-a1be3c0c6cc8.png">
