### ISSUE TITLE
Stories: Add ability to add featured image to the stories post [Enhancement]

### ISSUE THREAD

**Issue by aleone89** [wordpress-mobile/WordPress-Android#14278]
### Expected behaviour

When creating a story, the story will appear as an ordinary post in the blog post feed.

The expectation would be that there would be an image/snapshot taken as a featured image. 

In a way I thought it would be a "Stories" post type.

### Actual behaviour

If a Blog Post Block is in use, an empty tile will show where the story appears: https://d.pr/i/9qa79b 

<img width="1409" alt="Screenshot on 2021-03-17 at 18-49-39" src="https://user-images.githubusercontent.com/1119271/112070734-ec5c5880-8b33-11eb-9a46-1888aac5cd15.png">

### Steps to reproduce the behaviour

1. Create a story as per https://wordpress.com/support/wordpress-editor/blocks/story-block/#creating-a-story-in-the-word-press-app
2. View site with a Blog Post block.

**Comment by aforcier** [comment]
Just a note that we would probably implement this along with some planned updates to the prepublishing bottom sheet in general; otherwise we would want to look at porting the post settings feature into the story builder.

(see https://github.com/Automattic/stories-android/issues/580)

As an aside though for future consideration, I wonder if it would make sense for the blog posts block to be more permissive with the media it shows; similar to how the Reader works and how Jetpack adds media tags for social media sharing by parsing the posts' media content.

**Comment by SiobhyB** [comment]
Stories have been deprecated as of 24.1 (released to users yesterday), so I'll go ahead to close this issue.
