### ISSUE TITLE
Jetpack App (Basics): Configure Zendesk

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14314]
Parent: #14293

Change the subject from "WordPress for Android Support" to "Jetpack for Android Support" (the latter without internationalization).

### To test

1. Contact the support from the Jetpack app and enter your message
2. Check that the ticket was sent with the "Jetpack for Android Support" subject'
3. Contact the support from WP app
4. Check that the ticket was sent with "WordPress for Android Support" subject

**Comment by leandroalonso** [comment]
Updating this ticket: we'll keep the current WP credentials.

The only thing we'll change is the subject of the ticket that is sent to Zendesk. Instead of `WordPress for Android Support` we'll use `Jetpack for Android Support`. The latter doesn't need to have i18n — given i18n for Jetpack strings will need to go through a different flow.

@ParaskP7 I updated the ticket with this info, feel free to change it if needed. :)

(ccing @ashiagr — this shouldn't affect any of the recent changes made into Zendesk but I want to make sure)

**Comment by ParaskP7** [comment]
👋 @leandroalonso !

Many thanks for updating this ticket with this extra info! 👀 

🙏
