### ISSUE TITLE
Horizontal scroll position after orientation change in layout picker and site creation design picker

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#14364]
### Expected behavior
Horizontal scroll position of thumbnails is preserved after screen rotation.

### Actual behavior
Horizontal scroll position of thumbnails is not preserved on configuration change, even if you select a theme. It is expected to see the theme even after screen rotation.
Vertical Scroll position is not preserved in the most accurate way after configuration change either.

### Steps to reproduce the behavior
1. Open the page layout picker or the site design picker
2. Scroll horizontally on a category
3. Rotate the device
4. Notice that after rotation the visible themes change

**Comment by ParaskP7** [comment]
👋 @designsimply and @antonis !

I have been investigating this today and after trying a couple of things, I managed to find one solution that fits our needs. However, it seems that the fix is not as simple as one would have liked, at least in terms of lines of code that need to change. As such, I am not too confident yet and would like to first discuss it with you before proceeding with the implementation.

So, here is what I found so far:
- Stack Overflow: [How to save RecyclerView's scroll position using RecyclerView.State?](https://stackoverflow.com/questions/27816217/how-to-save-recyclerviews-scroll-position-using-recyclerview-state)
- Medium: [Restore RecyclerView scroll position](https://medium.com/androiddevelopers/restore-recyclerview-scroll-position-a8fbdc9a9334)
- Rúben Sousa: [Saving scroll state of nested RecyclerViews](https://rubensousa.com/2019/08/27/saving_scroll_state_of_nested_recyclerviews/)

Initially, following the above mentioned medium article, I was hoping that the new `StateRestorationPolicy` will somehow auto-magically solve that for us. However, after updating our out-of-date `RecyclerView` library from `1.0.0` to [1.2.0](https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.2.0), and trying that out, didn't help much. At this point I am not sure if I am missing anything here or if that just not solving our specific case. Wdyt?

Then, and after reading through some other custom made solutions from various developers in the wild, I stumbled across the above mentioned blog post from `Rúben Sousa`, which actually made the most sense. I then tried this quickly and it worked for the first scenario, the one which you would scroll up-and-down and the scrolling position of the horizontal nested list would not be preserved. This was easy!

However, it got more complicated while trying to preserve the horizontal nested list scrolling position on configuration change and as such I tried to completely incorporate his [ScrollStateHolder](https://github.com/rubensousa/RecyclerViewNestedExample/blob/master/app/src/main/java/com/rubensousa/recyclerview/nested/ScrollStateHolder.kt) solution into our problem. I must admit, it did take a bit of tuning, but in the end I managed to solve it, reusing this approach, and the result ended up being more pleasant that I initially thought. The only thing that doesn't make the solution as straightforward as I would have liked to, is the fact that we would need to included, as if actually copy-pasting the `ScrollStateHolder` exactly as is, making it a kind of a helper holder class of ours, which will allow us to achieve this effect and if need be, help us reuse this pattern in the future anywhere else we might need it.

Let me know your thoughts so far.

🙏

**Comment by antonis** [comment]
Hey @ParaskP7 👋 
Thank you for looking into this 🙇 
I spent some time on this during groundskeeping following a similar path but did come up with a good approach without too much custom code.

> I was hoping that the new StateRestorationPolicy will somehow auto-magically solve that for us

Sorry for not sharing my experiment on this. It would have saved you time 😐 

> The only thing that doesn't make the solution as straightforward as I would have liked to, is the fact that we would need to included, as if actually copy-pasting the ScrollStateHolder exactly as is, making it a kind of a helper holder class of ours

The `ScrollStateHolder` approach looks good to me. It seems much cleaner than the custom code I have tried and can be reused in the future 👍

**Comment by ParaskP7** [comment]
👋 @antonis !

> I spent some time on this during groundskeeping following a similar path but did come up with a good approach without too much custom code.

Yes, after having investigated it a bit as well, I ended up concluding the same.

> Sorry for not sharing my experiment on this. It would have saved you time 😐

No worries, I could have asked you as well but didn't, haven't realised that you started an investigation as well. 😅 

> The ScrollStateHolder approach looks good to me. It seems much cleaner than the custom code I have tried and can be reused in the future 👍

Yes, it seems a good approach to me too, and apart from adding the `ScrollStateHolder` class, the rest of the enhancements which need to happen in order to have this working as needed are very limited and easily understandable.

-----

PS: Whoever picks that task next shouldn't have any problems implementing the `ScrollStateHolder` solution. I actually tried it myself and it worked like a charm, for both cases, preserving the horizontal scrolling position while scrolling up-and-down the list and during configuration changes. 🤞

**Comment by SiobhyB** [comment]
I began to look into this in preparation for my groundskeeping rotation, which starts next week, and found I'm not able to replicate the original issue. 🤔 

The scroll position is preserved when I try rotating from both the page layout and site design pickers. I tested on a physical Pixel 5 on version 17.8 of the app. I also took the following video from an emulator to show the position's preserved when scrolling from the page layout picker:

https://user-images.githubusercontent.com/2998162/125818547-3b5cb6f8-9353-4ed9-916d-497d0592d6b7.mov

@ParaskP7, @antonis, are either of you still able to replicate the original problem or has it indeed been fixed somewhere along the line?

**Comment by ParaskP7** [comment]
👋 @SiobhyB !

Thanks for looking into it! 🙏 

The issue is a bit tricky because we have two scrolling positions in this case, the `vertical`, which is the one you tested and the `horizontal`, which is the one that we are actually having problems with.

So, in order for your to test and verify that this problem still exists, one thing you could do is to scroll `vertically` to the bottom of this screen, then scroll `horizontally` to the end of the `Home pages` list, then select the last layout, like the `Raise Your Helping Hand` and either scroll up to the top and back down to the bottom to see that the `horizontal` scroll position was reset to the left, or rotate your device to experience something similar.

Does that help?

PS: You would need to go to the `Choose a layout` screen from the `FAB` -> `Site page` since you will help more layouts there to scrolling through.

**Comment by SiobhyB** [comment]
Aha, I somehow skimmed over the important piece about this being specific to the `horizontal` positioning. 🤦‍♀️  Thank you so much, @ParaskP7! I'll aim to get a PR in place for this next week on my groundskeeping rotation. :D

**Comment by ParaskP7** [comment]
Hey, it's Friday, who can blame you, right! 😆 😛 

Anytime @SiobhyB , and please feel free to reach out if you need any help with that, I am looking forward to have this fixed, happy groundskeeping!

🍾

**Comment by SiobhyB** [comment]
Following our internal discussion, it's been confirmed we can't use the suggested code snippet at the moment as it's licensed under Apache 2.0, which isn't compatible with the app's current version of GPL.

As this seems to be a deceptively tricky issue that the snippet would be perfect for, I've sought some feedback around other approaches we could take, other than going straight back to the drawing board: paqN3M-ma-p2

**Comment by SiobhyB** [comment]
For the next Groundskeeper, @renanferrari outlined a possible solution for this here: paqN3M-ma-p2#comment-642
