### ISSUE TITLE
Unable to switch published post to a draft

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14543]
It was originally reported in 3944043-zd-woothemes that it wasn't able to switch a published post to a draft in the app.

### Expected behavior

To be able to switch a published post to a draft.

### Actual behavior

There's only a PUBLISH button even after changing the post visibility to "Draft".

### Steps to reproduce the behavior

1. Go to My Site > Blog Posts, select a published post.
2. In the editor, tap the three vertical dots and go to Post settings.
3. Change the "Status & Visibility" option to "Draft".
4. See that the only option is to "PUBLISH" the post.
5. Tapping on the "PUBLISH" button will show a publishing confirmation box.

**Video recording**

https://user-images.githubusercontent.com/40906847/116329860-cf840680-a7fe-11eb-8ef2-808e9be74482.mp4

##### Tested on OPPO Reno 4, Android 11, WPAndroid 17.2-rc-2

**Comment by yaelirub** [comment]
@planarvoid , can you please take a look at this?

**Comment by planarvoid** [comment]
hey @reginabally  @yaelirub , I've looked into it and I think this is intentional. The reasoning is that once you change the `Post Status` to draft, the primary action for a draft is `Publish`. I think the expectation is that drafts get published. What you can do is to go to the overflow menu and click on "Save". 

<img width="246" alt="Screenshot 2021-04-28 at 14 00 36" src="https://user-images.githubusercontent.com/1079756/116400240-205d2480-a82a-11eb-8344-f2ef214d2fc4.png">

I think the primary action always triggers the "Publish" action if the user has the rights. The exception is when the post is already published (and in this case we just update the post). One option I could see here is to trigger some kind of dialog when this change happens, something like "Move post to draft" and close the editor. Another option would be to somehow base the primary button not only on the current post state but also on the transition state. This might be tricky because this is untested code with a lot of business logic and hacks. 

Another option would be to add the "Move to draft" action to the post list overflow menu. There is already the "Trash" option there. Let me know what you think!

**Comment by yaelirub** [comment]
Thanks so much, @planarvoid ! I think we should add the move to draft option to the overflow menu (we have that on iOS)

**Comment by planarvoid** [comment]
I've added the option to the overflow menu in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14554)
