### ISSUE TITLE
Jetpack App (Basics): Match Border Color for the Notification Badge for Dark Theme

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#14629]
Parent: #14293

This is based from this [comment](https://github.com/wordpress-mobile/WordPress-Android/pull/14514#pullrequestreview-642222310) from @osullivanchris within this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14514).

**Comment by RenanLukas** [comment]
I'm investigating this issue and I was wondering if we really want to have a stroke with the same color as the background around the badge. Maybe this is not a problem, but when the item is tapped you can clearly see the stroke since the background color changes (and the stroke color remains the same).
Taking the light theme as an example, it looks like this when the `Notifications` item is tapped:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/14964993/180096678-fcdfff7e-c56e-4280-9c10-382594526ac0.png">

Besides that, I've tried for some time to have the stroke matching the background color of bottom navigation with dark theme enabled, and although [in theory we're setting the background color here](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/res/layout/main_activity.xml#L56) in practice it is not the color being shown. In this example, I'm setting the same `?attr/colorSurface` to the badge's stroke, and in the result we can see that the bottom navigation background color and the stroke color are clearly different:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/14964993/180098478-64a6f44e-fb9b-4f39-86bc-02f84fb02f3e.png">

I went ahead and used the `Layout inspector` to double-check the background color, and found that actually `BottomNavigationView` has a `MaterialShapeDrawable` as background:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/14964993/180098910-068a9922-5229-4054-8ad9-5787bce10d24.png">

As a last attempt, I've put a breakpoint after `WPMainActivity` is inflated to see what I could do with the `MaterialShapeDrawable`. 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/14964993/180099280-bf29869d-cf14-459c-b9f8-e8e140303614.png">

I've tried looking for the name of the resource ID returned in the `getFillColor()` but it throws `Resources$NotFoundException`:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/14964993/180099501-da236ed1-e03c-4218-a3dc-8c60702a5f16.png">

The exception above shows that it tried to get the color `#0xff121212`, which would be the correct hex for `?attr/colorSurface` in dark theme. So it seems like internally something's happening where our resource color stops being used directly (but it's value is still correct) and something else (which I'm not sure what) is also being drawn and changing the final background color of the `BottomNavigationView` 🤔 

Has anyone seen this before?

**Comment by AjeshRPai** [comment]
Hey @RenanLukas, I Investigated the colour being used as background for the bottom bar and found out that `wpColorSurfaceSecondary` is the correct colour being displayed on dark mode. I was investigating the colour as part of another [Issue](https://github.com/wordpress-mobile/WordPress-Android/issues/15927). Since these issues can be solved in one go, I have raised this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17034) a fix for  it. 

>I'm investigating this issue and I was wondering if we really want to have a stroke with the same color as the background around the badge. Maybe this is not a problem, but when the item is tapped you can clearly see the stroke since the background color changes (and the stroke color remains the same).

Although I agree with this opinion, since it's only during the tapping duration I think we can neglect it for now. WDYT?.

**Comment by RenanLukas** [comment]
Hey @AjeshRPai 
>  since it's only during the tapping duration I think we can neglect it for now. WDYT?.
  
I agree. Thanks for taking care of it 🙇‍♂️
