### ISSUE TITLE
Bug: Use Block Editor visible on self-hosted sites.

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#14728]
### Expected behavior
To not show the toggle for the block editor on self-hosted sites

### Actual behavior
Currently, when you are viewing the site setting you are NOT able to toggle to  the `Use Block Editor` setting for self-hosted sites. 

See
<img width="200" src="https://user-images.githubusercontent.com/115071/119774741-7cda5080-be77-11eb-8072-f93df08f12d4.png" />

### Steps to reproduce the behaviour
Connect a .org site to the app. 
Go to Settings
See the Toggle for Block Editor

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 2, Android 11, WPAndroid 17.4-rc-1

**Comment by thehenrybyrd** [comment]
@guarani I know we removed this toggle from WordPress.com simple sites a few months ago, should it still be present for self-hosted sites?

If so, as @enejb mentions, the toggle isn't functional currently - it's nearly impossible to toggle:

https://user-images.githubusercontent.com/15107387/119827962-63cab180-bf02-11eb-971c-6cfafa098dee.mp4

**Comment by guarani** [comment]
> @guarani I know we removed this toggle from WordPress.com simple sites a few months ago, should it still be present for self-hosted sites?

👋 @thehenrybyrd, yes it should still be present on self-hosted sites.

> If so, as @enejb mentions, the toggle isn't functional currently - it's nearly impossible to toggle:

There's an issue I recall seeing in Gutenberg Mobile for this, https://github.com/wordpress-mobile/gutenberg-mobile/issues/1632. Since the classic editor (along with the editor preference switch) is deprecated, I'm not sure if this will be fixed (see https://github.com/wordpress-mobile/gutenberg-mobile/issues/1632#issuecomment-793037024).

**Comment by guarani** [comment]
Since the original issue here reported that the block editor switch being present on self-hosted sites was a bug, and [that's actually expected](https://github.com/wordpress-mobile/WordPress-Android/issues/14728#issuecomment-849612236) behavior, I think this issue can be closed.

I've created [a separate issue](https://github.com/wordpress-mobile/WordPress-Android/issues/14782) for the difficulty toggling the editor preference switch.

Closing this issue now but please feel free to re-open if you feel otherwise.
