### ISSUE TITLE
Feature Request: Add Story option to the menu on My Site

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14749]
It was requested in 4031150-zd-woothemes to add the Story option to the menu on the My Site screen.

> Separate part of the wordpress storys
Beside the other 4 menus

(translated from Portuguese)

**Comment by thehenrybyrd** [comment]
Great to hear folks are interested in this!
Currently, I do see "Story post" when tapping the "+" icon to add a post/page from My Sites. 

<img src="https://user-images.githubusercontent.com/15107387/120466873-3b323400-c3a8-11eb-9cc1-31852ce4cb82.jpg" width="40%">

However:
a. I don't remember seeing that last time I checked
b. The user seems to be referring to the four items under "Publish"

@mzorz did we put Story post into "Add new" recently, or are doing some A/B testing around this currently?

Having "Story Posts" under "Publish" would imply a list of such posts, as we have in Pages or Posts, would imply full management of that type of post. That is, you could have a draft Story post, see all your previously published Story posts, etc. That's not in line with the way Stories currently work, as I understand, but may be something users want eventually.

**Comment by aforcier** [comment]
Mario's on sabbatical 🙂 

> did we put Story post into "Add new" recently, or are doing some A/B testing around this currently?

The story option has been part of the create menu (from My Site and from the posts view) since the Stories feature was launched - however it's somewhat recently been moved to be at the top of the list, perhaps that's why it looks unfamiliar. (pbArwn-26B-p2#comment-2975)

> Having "Story Posts" under "Publish" would imply a list of such posts, as we have in Pages or Posts, would imply full management of that type of post. That is, you could have a draft Story post, see all your previously published Story posts, etc. That's not in line with the way Stories currently work, as I understand, but may be something users want eventually.

Correct, it's not in line with how Stories currently work or how they're positioned (as a block/one of your regular posts). Technically somewhat difficult to achieve as well, since there is no way at present to filter Story posts other than parsing the content of each post one at a time to look for the block.

**Comment by thehenrybyrd** [comment]
> Mario's on sabbatical 🙂

Ah, that's right! 🎉 

> Correct, it's not in line with how Stories currently work or how they're positioned (as a block/one of your regular posts)

Thanks for confirming my understanding there.
I'll close this for now, but we can always re-open if more users bring it up. It seems like they may imagine Stories as being significantly different than a regular post.
