### ISSUE TITLE
RuntimeException: Unable to destroy activity {org.wordpress.android/org.wordpress.android.ui.media.MediaBrowserActi...

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#14759]
**Sentry Url**: https://sentry.io/share/issue/8f64c7ac34af4ea680df639665a1136a/
**User Count**: 2867
**Count**: 22289
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-11T13:16:59Z
**Last Seen**: 2021-06-01T20:10:35Z
**24 Hours**: 128
**30 Days**: 4423

```
RuntimeException: Unable to destroy activity {org.wordpress.android/org.wordpress.android.ui.media.MediaBrowserActivity}: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
     at org.wordpress.android.modules.GlideApp.with(GlideApp.java:86)
     at org.wordpress.android.util.image.ImageManager.cancelRequestAndClearImageView(ImageManager.kt:455)
     at org.wordpress.android.ui.media.MediaGridAdapter.onViewRecycled(MediaGridAdapter.java:456)
     at org.wordpress.android.ui.media.MediaGridAdapter.onViewRecycled(MediaGridAdapter.java:63)
     at org.wordpress.android.ui.media.MediaBrowserActivity.onDestroy(MediaBrowserActivity.java:431)
...
(45 additional frame(s) were not displayed)
```

**Comment by JavonDavis** [comment]
@khaykov wdyt about this one?

**Comment by fluiddot** [comment]
As far as I checked, this issue is related to sharing an image targeting the WordPress app while the media screen is opened, you can check the following steps to reproduce it:

1. Open the WordPress app
2. Navigate to the Media screen and put the app in the background
3. Open the web browser within the Android device
4. Navigate to a webpage that contains images
5. Long tap on the image to display the contextual menu
6. Share the image
7. Select WordPress as the target app for sharing
8. Pick a site and select "Add to media library"
9. Observe that when the app is opened it produces a crash

**Notes:**
- Looks like it only happens when the WordPress app is already opened and the current screen is the Media library
- It can be reproduced by sharing an image from any app, not just the web browser.

**Comment by fluiddot** [comment]
The Sentry issue has been marked resolved in the next release.
