### ISSUE TITLE
Jetpack App (Basics): [What's new] Disable for Jetpack

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-Android#14755]
Disable the [What's new] section when in Jetpack:
- [x] Disable from having it visible in `App Settings`. #14757
- [x] Disable from having it popping-up on `App Launch`. #14771

**Comment by ParaskP7** [comment]
👋 @zwarm !

I am reopening this issue since there is another case where this `What's New` feature announcement gets to pop-up, and this is when the user updates from one version to this new one that is bind with an announcement. As such, when the app starts you get the `What's New` feature announcement automatically being shown.

PS: See new checklist description: `Disable from having it popping-up on App Launch.`
PSS: I have created the `190` mobile app announcement for you to enable and test your solution. I have duplicated what iOS was already having so that going forward we would just use that and enable/disable it during testing. Also, bare in mind that in order to test your solution you would need to change the `versionName` to `79.0` and increment the `versionCode`. This is the trigger. Then, just update the app and the `What's New` feature announcement will automagically pop-up.
