### ISSUE TITLE
cannot build alpha-289

### ISSUE THREAD

**Issue by Geoffrey1014** [wordpress-mobile/WordPress-Android#14754]
### Expected behavior
build successfully

### Actual behavior

url  
https://dl.bintray.com/wordpress-mobile/react-native-mirror/
http://dl.bintray.com/terl/lazysodium-maven
is forbidened to access
so, i change them to 
mavenCentral()
https://a8c-libs.s3.amazonaws.com/android/react-native-mirror (i find it is forbidened to access too lately)
but i still get the error in the following.
if i did not changer those url, i all get similar problem like  "Could not get resource   'https://dl.bintray.com/wordpress-mobile/maven/com/goterl/code/lazysodium-android/code-lazysodium-android.pom' " etc

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':WordPress:compileJalapenoDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':WordPress:jalapenoDebugCompileClasspath'.
   > Could not resolve com.goterl:code:lazysodium-android.
     Required by:
         project :WordPress
      > Could not resolve com.goterl:code:lazysodium-android.
         > Could not get resource 'https://dl.bintray.com/wordpress-mobile/maven/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'.
            > Could not GET 'https://dl.bintray.com/wordpress-mobile/maven/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.goterl:code:lazysodium-android.
         > Could not get resource 'https://dl.bintray.com/wordpress-mobile/react-native-mirror/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'.
            > Could not GET 'https://dl.bintray.com/wordpress-mobile/react-native-mirror/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.goterl:code:lazysodium-android.
         > Could not get resource 'https://a8c-libs.s3.amazonaws.com/android/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'.
            > Could not GET 'https://a8c-libs.s3.amazonaws.com/android/com/goterl/code/lazysodium-android/code-lazysodium-android.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.goterl.lazycode:lazysodium-android:4.1.0.
     Required by:
         project :WordPress > com.github.wordpress-mobile.WordPress-FluxC-Android:fluxc:1.15.0
      > Could not resolve com.goterl.lazycode:lazysodium-android:4.1.0.
         > Could not get resource 'https://dl.bintray.com/wordpress-mobile/maven/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'.
            > Could not GET 'https://dl.bintray.com/wordpress-mobile/maven/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.goterl.lazycode:lazysodium-android:4.1.0.
         > Could not get resource 'https://dl.bintray.com/wordpress-mobile/react-native-mirror/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'.
            > Could not GET 'https://dl.bintray.com/wordpress-mobile/react-native-mirror/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.goterl.lazycode:lazysodium-android:4.1.0.
         > Could not get resource 'https://a8c-libs.s3.amazonaws.com/android/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'.
            > Could not GET 'https://a8c-libs.s3.amazonaws.com/android/com/goterl/lazycode/lazysodium-android/4.1.0/lazysodium-android-4.1.0.pom'. Received status code 403 from server: Forbidden

**Comment by AliSoftware** [comment]
Hello there,

This alpha-289 is a pretty old one 😅 

JFrog have been sunsetting their Bintray service recently (~ May 1st) – see [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) for more information. This is why this old alpha build can't find its dependency artefacts (which were handled by bintray back when this old alpha went out on Apr 16) and can't be built anymore. Unfortunately we don't have any control over Bintray being shut down by JFrog, so this is out of our control.

We fixed that since in newer alpha versions, and have migrated our dependencies artefacts to S3 since then, which is where all the new versions of our dependencies are now hosted since May; but versions of dependencies we released before Bintray was shut down by JFrog, and used by old alphas like this one from Apr 16, won't be available anymore given Bintray went down.

If you want to build an alpha version of WordPress-Android, we encourage you to try building a **more recent** alpha (especially one that went out _after_ Bintray sunsetting and after we migrated our dependency artefacts to S3), where this issue was already fixed. The latest alpha-297 from 2 days ago for example should build just fine.

**Comment by Geoffrey1014** [comment]
I want to know is there any chance to build old versions of WordPress? And HOW?
Becuase i have tasks to reproduce old bugs and build corresponding version source code.
Since you have migrated dependencies artefacts to S3, i guess i can also build old versions by doing this migrating.
I have tried to change maven { url "https://dl.bintray.com/wordpress-mobile/react-native-mirror/" }
     to  maven { url "https://a8c-libs.s3.amazonaws.com/android/react-native-mirror" }
But it does not work right.
What is more, url "https://a8c-libs.s3.amazonaws.com/android/react-native-mirror" seems has problem. 
I try to open it , the result is as follows:
![image](https://user-images.githubusercontent.com/35189652/120601753-e9a7a900-c47c-11eb-8f05-4b90420477ac.png)

**Comment by Geoffrey1014** [comment]
> Hello there,
> 
> This alpha-289 is a pretty old one 😅
> 
> JFrog have been sunsetting their Bintray service recently (~ May 1st) – see [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) for more information. This is why this old alpha build can't find its dependency artefacts (which were handled by bintray back when this old alpha went out on Apr 16) and can't be built anymore. Unfortunately we don't have any control over Bintray being shut down by JFrog, so this is out of our control.
> 
> We fixed that since in newer alpha versions, and have migrated our dependencies artefacts to S3 since then, which is where all the new versions of our dependencies are now hosted since May; but versions of dependencies we released before Bintray was shut down by JFrog, and used by old alphas like this one from Apr 16, won't be available anymore given Bintray went down.
> 
> If you want to build an alpha version of WordPress-Android, we encourage you to try building a **more recent** alpha (especially one that went out _after_ Bintray sunsetting and after we migrated our dependency artefacts to S3), where this issue was already fixed. The latest alpha-297 from 2 days ago for example should build just fine.

I want to know is there any chance to build old versions of WordPress? And HOW?
Becuase i have tasks to reproduce old bugs and build corresponding version source code.
Since you have migrated dependencies artefacts to S3, i guess i can also build old versions by doing this migrating.
I have tried to change maven { url "https://dl.bintray.com/wordpress-mobile/react-native-mirror/" }
to maven { url "https://a8c-libs.s3.amazonaws.com/android/react-native-mirror" }
But it does not work right.
What is more, url "https://a8c-libs.s3.amazonaws.com/android/react-native-mirror" seems has problem.
I try to open it , the result is as follows:
![image](https://user-images.githubusercontent.com/35189652/120601918-1491fd00-c47d-11eb-8948-21c4925c2e97.png)

**Comment by AliSoftware** [comment]
As I explained above, the artefacts for old builds of our dependencies have not been migrated in our new S3 repository.
But since all our deps are open source, @loremattei suggested that you should be able to rebuild all of them locally on your machine if your really need it; and set up a local maven repo and point the WPAndroid gradle to it.

(maybe @oguzkocer has some ideas/suggestions about here too, as he's more knowledgeable on this topic than me)

**Comment by oguzkocer** [comment]
@Geoffrey1014 The issue you've attached in the issue description is not related to any of our libraries, but instead about the `lazysodium-android` library which has moved from Bintray to `mavenCentral`. Here is where we have reflected this change in our FluxC library: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1987.

In order to build the `alpha-289`, you'd have to update FluxC library, and add `mavenCentral` to the repositories section in this project. However, that'd only be the first step, because there's a lot of movement due to Bintray shutdown and at the end of it all, you'd be close to where the client is at today, so I don't think it's a feasible route.

Having said that, we do publish artifacts for each pre-release & release in our Github releases, so you can install them without having to build the code: https://github.com/wordpress-mobile/WordPress-Android/releases

Specifically for `alpha-289` [here is the release](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/alpha-289). You can download the signed-apk and install it directly to your emulator or Android device. You can also download the source code for this release from its assets or you can checkout the tag for it.

Hope that helps!
