### ISSUE TITLE
Audio Block missing for Free and Personal plan sites.

### ISSUE THREAD

**Issue by devNigel** [wordpress-mobile/WordPress-Android#14799]
**Describe the bug**

Audio block is missing for sites in the free and Personal plan. When we upgraded to Premium plan, the Audio block appeared in the block list.

**To Reproduce**
1. Go to a Simple site with Free or Personal plan.
2. Create a new page or a post.
3. Try to add Audio block using / or from the + icon.
4. You will observe that Audio block is missing.

**Expected behavior**
Audio block is available on the web for sites with Free and Personal plan.

**Screen recording**
https://drive.google.com/file/d/12eMQTZi8nco8V9GE8m5ckMuQE-zEUf35/view?usp=sharing

**Screenshots**
https://drive.google.com/file/d/12xnUbH0lIRm5Q5pBTddshxtJGUutGoUr/view?usp=sharing

**Smartphone (please complete the following information):**
 - Device: Samsun Galaxy S10
 - OS: Android 11
 - Version: 17.5-rc-1

**Comment by thehenrybyrd** [comment]
Thanks for reporting, @devNigel! This issue will be fixed next release, in https://github.com/WordPress/gutenberg/pull/31966.

The Audio block has historically been hidden on free sites because it allows uploading audio, which requires a plan.
However, the Insert from URL functionality that is available on free plans was added in https://github.com/WordPress/gutenberg/pull/27817.
Next release, https://github.com/WordPress/gutenberg/pull/31966 will stop the Audio block from being hidden. That way folks on the free plan will be able to add the Audio block and use the Insert from URL functionality.
