### ISSUE TITLE
Improve swiping through notifications behaviour 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#14919]
When swiping between the screens for e.g. swiping through notifications on the Notification tab, the foreground and the background screens are not distinguishable (See https://github.com/wordpress-mobile/WordPress-Android/pull/14906#pullrequestreview-690723314).

<img width="813" alt="Screenshot 2021-06-24 at 9 25 03 AM" src="https://user-images.githubusercontent.com/1405144/123207332-db2c3a80-d4da-11eb-8e05-6bd3260a0d97.png">

Giving such screens an elevation doesn't look great either (See https://github.com/wordpress-mobile/WordPress-Android/pull/14906#issuecomment-867333493). 

![device-2021-06-24-102355](https://user-images.githubusercontent.com/1405144/123207337-de272b00-d4da-11eb-8591-4d41c66e7802.png)

The goal of this task to explore our options to further improve this swiping behavior.

**Comment by ssinha2103** [comment]
I would like to work on it.

**Comment by ashiagr** [comment]
Thanks for your interest in this issue! 

I've assigned it to you. Let me know if you have any questions on this issue, [Project Setup](https://github.com/wordpress-mobile/WordPress-Android#wordpress-for-android), or the [Contributing Guide](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md).

**Comment by ssinha2103** [comment]
Hii @ashiagr , can you please elaborate what is the issue, coz I am now using the app on emulator, and I cannot find any transition issues with the app.  I mean, the swipe feels perfect. What is the exact change that you want ?
![Screenshot 2021-08-29 at 1 32 40 PM](https://user-images.githubusercontent.com/54184277/131243293-f9d797cc-cec1-4184-8f4e-8f17f505b6f4.png)

**Comment by ashiagr** [comment]
👋 @ssinha2103 

Thank you for trying it out 👍. 

> the swipe feels perfect

The only issue is that the limit between the foreground and the background screens are not distinguishable on areas without content (see https://github.com/wordpress-mobile/WordPress-Android/pull/14906#pullrequestreview-690723314). I've highlighted it in the screenshot you shared.

<img width=320 src="https://user-images.githubusercontent.com/1405144/131247187-ac38339f-5841-43b2-a152-1a3ab91a4f0f.png">

One way is to add an elevation to the screens (see https://github.com/wordpress-mobile/WordPress-Android/pull/14906#issuecomment-867333493) but the common app bar doesn't look great with it. Can you try anything that can improve this transition?

**Comment by ssinha2103** [comment]
![Screenshot 2021-08-29 at 9 32 28 PM](https://user-images.githubusercontent.com/54184277/131257134-c4625c89-cf95-4f5d-9c37-e85fd7c3f4b0.png)
Hii @ashiagr , is it fine ?

**Comment by ssinha2103** [comment]
Hii @ashiagr , is it fine now ?

![Screenshot 2021-08-29 at 9 41 19 PM](https://user-images.githubusercontent.com/54184277/131257371-1e256f37-c0f0-4d7e-a473-38e23d2983bb.png)
Hii @ashiagr , is it fine now ?

![Screenshot 2021-08-29 at 9 42 34 PM](https://user-images.githubusercontent.com/54184277/131257421-9dbb710f-b1eb-454f-91c5-7059fc22996d.png)
![Screenshot 2021-08-29 at 9 42 49 PM](https://user-images.githubusercontent.com/54184277/131257423-5b8cdc73-85b7-4950-a068-f96c584e2025.png)

**Comment by ashiagr** [comment]
Looks better 👍. Can you create a PR? We can test and discuss it there.

**Comment by ssinha2103** [comment]
Hii @ashiagr  I didn't delete these lines still its showing in red, it is some issue ?
![Screenshot 2021-08-29 at 10 06 40 PM](https://user-images.githubusercontent.com/54184277/131258161-e895b90e-ad8a-410d-8aeb-17cfa942e495.png)

**Comment by ssinha2103** [comment]
I created One , can you please check.

**Comment by ashiagr** [comment]
Thank you! I'll check it tomorrow.

**Comment by ssinha2103** [comment]
Hii @ashiagr  Can you please check it and merge the PR.

**Comment by ssinha2103** [comment]
Hii @ashiagr , can you mention , which files have the configurations for dark mode ?

**Comment by ashiagr** [comment]
We try not to add custom colors and instead reuse colors like `colorSurface` or `colorOnSurface` which are present in `values/styles.xml `and `values-night/styles.xml`.  Let me know if you cannot utilize any of the existing colors.

**Comment by ssinha2103** [comment]
android:background="@color/quick_start_task_card_illustration_edit_site_icon_mountain_fill"
        Will it be fine @ashiagr  ?

**Comment by ashiagr** [comment]
Can you try `@color/placeholder`? Add a screenshot for both light and dark mode. I'll get some design feedback.

**Comment by ssinha2103** [comment]
![Screenshot 2021-08-30 at 12 58 58 PM](https://user-images.githubusercontent.com/54184277/131302396-06be27d7-17ca-4837-b3a3-bd1bc1e21908.png)
![Screenshot 2021-08-30 at 12 57 18 PM](https://user-images.githubusercontent.com/54184277/131302408-51b0358b-284f-4c9d-88d2-6519afe73079.png)

Is it fine ?

**Comment by ashiagr** [comment]
Thanks, @ssinha2103! 

👋 @osullivanchris, pinging you for a little help.
Can you advise us of the right color that we're trying to use here? Currently we've used view pager background as `@color/placeholder` (Light: `#1A000000,` Dark: `#1AFFFFFF`) in the screenshots above.

**Comment by ssinha2103** [comment]
Hii @ashiagr and @osullivanchris. currently I have modified notification_detail_activity.xml  with android:background="@color/quick_start_task_card_illustration_edit_site_icon_mountain_stroke"
Please guide further ? Working as shown in the screenshots above.

**Comment by ashiagr** [comment]
@ssinha2103, can you add screenshots for `@color/placeholder` as well, please? `quick_start_task_card_illustration_edit_site_icon_mountain_stroke` looks dark in the light mode.

**Comment by ssinha2103** [comment]
Sure, here are the screenshots for @color/placeholder as well  @ashiagr and @osullivanchris

![Screenshot 2021-08-30 at 1 20 06 PM](https://user-images.githubusercontent.com/54184277/131305089-492791a9-0bf0-4598-a34b-b94c117522a1.png)
![Screenshot 2021-08-30 at 1 20 36 PM](https://user-images.githubusercontent.com/54184277/131305106-ddb1bbd8-6599-42a2-aec7-433b2a700cf8.png)

**Comment by osullivanchris** [comment]
Hi @ashiagr and @ssinha2103 ! Thanks for the ping and for the work on this!

I have a slightly different approach I'd like to suggest. Sorry to throw a curve ball in. Let me know what you think. If you don't agree, I can have a further look at the overlay colours/shadow behaviour.

**Currently**
- when you swiped to move between notifications, the current notification (A) is shown a level above the next notification (B) on the Z-axis. 
- The next notification (B) is slightly reduced in size and opacity, but then animates to full size and opacity from behind the other one (A)
- The initial notification (A) moves horizontally out of the device frame.

Here's a sketch and a very rough video to try to clarify what I'm describing. 

<img width="1307" alt="Screenshot 2021-08-30 at 17 39 55" src="https://user-images.githubusercontent.com/50576199/131373846-2a6b96cb-e41c-4627-8e4f-991fd69e2df3.png">

https://user-images.githubusercontent.com/50576199/131374146-93a0a1c2-36a3-4574-a500-f074bd584b3f.mp4


**Issues**
- in the current solution, because notification B is 'behind' and smaller than notification A, I think it implies that there is a hierarchical or child/parent relationship between these two.
- In fact, when I tried this interaction, I thought I was going up/back to the notification screen.

**Proposal**
- I think these notifications are actually at an equal level of hierarchy. They are in a list. But they don't have a parent/child relationship. They are siblings of equal level.
- Therefore I think it might work better if they all just moved horizontally, with no shrinking or transparency. 
- Again here is a sketch and video to try to illustrate what I am suggesting
- If you agree, we could avoid the overlay issue entirely. The notifications would just swiped left/right on an infinite horizontal plane. It would be like they are all on one long sheet, and the device screen is a window framing one of them at at a time.

<img width="1242" alt="Screenshot 2021-08-30 at 17 45 32" src="https://user-images.githubusercontent.com/50576199/131374597-4d6ea1bf-ef0b-4b2a-8f0e-68e4d28bc784.png">

https://user-images.githubusercontent.com/50576199/131374650-2794b1b3-fccd-415a-b9e6-ae6c09fbe64f.mp4

Apologies if this is much more design input than you were looking for! But it struck me as a general possible improvement. Noting that we use the same system in My Site -> Comments. And there might be native/component conventions that conflict with what I'm saying, I'm open to feedback.

**Comment by ssinha2103** [comment]
@osullivanchris The issue you have mentioned is already resolved. I request you to build and try the app from my PR.
Currently the notification seems to be at same level.

**Comment by ashiagr** [comment]
👋 @osullivanchris 

Thank you so much for a detailed explanation of your thoughts on animation! 🙇‍♀️ 
I totally get your point. I see a slide animation similar to yours in the `Gmail` app when we horizontally swipe through emails and I agree it gives a better effect of screens being at the same level.

We'll try it out, and get back to you. 

------------

@ssinha2103

>  The issue you have mentioned is already resolved.

Not sure if you got the idea. Right now, the left screen goes deeper on the z-axis and it looks like it the right screen is sliding over it. They do not appear to be at the same level. Chris has included videos that demonstrate it very well, I'd suggest you carefully observe it. 

It seems we can get the suggested sliding effect using a different `PageTransformer` (E.g. see [screen slide](https://developer.android.com/training/animation/anim_screenslide.mp4) in this [Guide](https://developer.android.com/training/animation/screen-slide)).

Can you give it a try? Let me know if it is still not clear.

**Comment by ssinha2103** [comment]
Hii @ashiagr , can u merge the pr, coz something is better than nothing, and I am working on the suggestion by @osullivanchris . Kindly merge the PR and enrich the UI experience until I finish .

**Comment by ashiagr** [comment]
👋 @ssinha2103!

Alright, I'll merge it and we can create a separate PR for the suggested animation. 
Thanks for working on it!

**Comment by thehenrybyrd** [comment]
@ashiagr looks like this issue was addressed in [#15253 ](https://github.com/wordpress-mobile/WordPress-Android/pull/15253), and we'd wanted to work on an animation as well. Can we go ahead and close this issue? And, is there a new issue for the animation?
Thanks!

**Comment by ashiagr** [comment]
Thanks for the ping @thehenrybyrd!

https://github.com/wordpress-mobile/WordPress-Android/pull/15253 addresses the original issue: 

> the foreground and the background screens are not distinguishable

So I'll go ahead and close this issue. I've created a new issue for the animation: https://github.com/wordpress-mobile/WordPress-Android/issues/16600.
