### ISSUE TITLE
SQLiteException: too many SQL variables (code 1): , while compiling: SELECT * FROM PostModel WHERE (_id IN (?,?,?,...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15078]
**Sentry Url**: https://sentry.io/share/issue/d3317b74347b4735905db4acd05509f1/
**User Count**: 2
**Count**: 4686
**First Release**: org.wordpress.android@15.3+896
**First Seen**: 2020-07-29T15:42:56.913000Z
**Last Seen**: 2021-07-27T03:19:31Z
**24 Hours**: 34
**30 Days**: 576

```
SQLiteException: too many SQL variables (code 1): , while compiling: SELECT * FROM PostModel WHERE (_id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,...
     at org.wordpress.android.fluxc.persistence.UploadSqlUtils.getPostModelsForPostUploadModels(UploadSqlUtils.java:178)
     at org.wordpress.android.fluxc.store.UploadStore.getAllRegisteredPosts(UploadStore.java:197)
     at org.wordpress.android.ui.uploads.UploadService.doFinalProcessingOfPosts(UploadService.java:996)
     at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:685)
     at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:670)
     at org.wordpress.android.ui.uploads.UploadService.onMediaUploaded(UploadService.java:966)
...
(21 additional frame(s) were not displayed)
```

**Comment by AliSoftware** [comment]
Not a new one and apparently only 2 users… but still 4k events, which seems a lot 😓  so figured we'd want to track it anyway.

**Comment by AmandaRiu** [comment]
Issue Triage: Spent a bit of time digging into this one and here are the results:

## How
This issue appears to be happening in the [`doFinalProcessingOfPosts(...)`](https://github.com/wordpress-mobile/WordPress-Android/blob/085c53a0a616c7db32a03e390c14099eac03cce3/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L993) method of `UploadService.kt` which calls [`mUploadStore.getAllRegisteredPosts()`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/30ddd953de81208daacd793c08ea9ff93de0448d/fluxc/src/main/java/org/wordpress/android/fluxc/store/UploadStore.java#L195) which in turn first fetches all the `PostUploadModel`'s stored in the device database, and then matches those records with their corresponding `PostModel`'s by calling [`UploadSqlUtils.getPostModelsForPostUploadModels`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/30ddd953de81208daacd793c08ea9ff93de0448d/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/UploadSqlUtils.java#L170). This is where the app crashes. This is due to too many `PostUploadModel`'s being passed into the SQL query to find a matching `PostModel`. 

## Why
**This exception has been happening for over a year and it only ever happens to the same 3 users**. I believe that somehow these 3 users ended up with stale or error `PostUploadModel` records not being removed from the device database and the amount of records just continues to grow because the part of the process that cleans up these records fails due to this SQL Exception. Every time a new post is uploaded from a device, a new record is added to the database and the list of `PostUploadModel`'s grows and the number of records are so large that the number of `_id`'s passed in as variables to the SQL query are beyond the upper limit allowed in SQLite and this results in the `SQLiteException: too many SQL variables` being thrown. **This cycle will continue until either the user uninstalls the app and reinstalls it or, we add some sort of logic to correct this scenario for these edge cases.** 

## Possible Fix
My first thought was that we could catch this exception and if it happens we could go back and purge any stale `PostUploadModel` records, but unfortunately I don't see an obvious way to do that without possibly losing new or updated posts that haven't been successfully posted to the web. With that in mind I'd recommend implementing some sort of batching mechanism to [`UploadSqlUtils.getPostModelsForPostUploadModels`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/30ddd953de81208daacd793c08ea9ff93de0448d/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/UploadSqlUtils.java#L170) where we only fetch the matching `PostModels` in batches of 50 to prevent this SQLException.

**Comment by ravishanker** [comment]
The maximum value of a host parameter number is [SQLITE_MAX_VARIABLE_NUMBER](https://www.sqlite.org/limits.html), which defaults to 999 for SQLite versions prior to 3.32.0 (2020-05-22) or 32766 for SQLite versions after 3.32.0.

So, this is probably happening on [Android API 26 and below](https://developer.android.com/reference/android/database/sqlite/package-summary) 

Clearly, [this query is exceeding that limitation](https://sentry.io/share/issue/d3317b74347b4735905db4acd05509f1/) with over a thousand of ? params!   However, we need to find a better implementation for this.
