### ISSUE TITLE
NullPointerException: response.error.message must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15071]
**Sentry Url**: https://sentry.io/share/issue/938313c0968448688927884b12ee84d0/
**User Count**: 180
**Count**: 3813
**First Release**: 17.7-rc-2
**First Seen**: 2021-07-02T23:03:56.402000Z
**Last Seen**: 2021-07-26T11:30:14Z
**24 Hours**: 297
**30 Days**: 3784

```
NullPointerException: response.error.message must not be null
     at org.wordpress.android.fluxc.network.xmlrpc.site.SiteXMLRPCClient.fetchPostFormats(SiteXMLRPCClient.kt:146)
     at org.wordpress.android.fluxc.network.xmlrpc.site.SiteXMLRPCClient$fetchPostFormats$1.invokeSuspend(null:12)
```

**Comment by AmandaRiu** [comment]
Possibly related to changes from this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14812

**Comment by AmandaRiu** [comment]
Slack conversation: p1627333331068900-slack-C012H19SZQ8

**Comment by AmandaRiu** [comment]
Hi @planarvoid 👋 This crash looks like it may be related to the [FluxC changes](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2023) related [to this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14812).  Making `response.error.message` `nullable` would definitely prevent the crash, but I’m a little worried that there may be a bigger issue with the changes made in the referenced PR since the variable that is causing a crash now was not `nullable` before the changes and it wasn’t crashing before so why is it crashing now, after the changes. Are you able to take this ticket to look into it further?

**Comment by planarvoid** [comment]
hey @AmandaRiu , I wouldn't be worried about making the field nullable. Previously the code was Java so we didn't know whether the message was there or not. I think since this is XMLRPC, it's probably not reliable. Me and @develric  were trying to be super defensive but we didn't expect this. Since it's only about the error message, I think we can safely keep it nullable.

**Comment by AmandaRiu** [comment]
> hey @AmandaRiu , I wouldn't be worried about making the field nullable. Previously the code was Java so we didn't know whether the message was there or not. I think since this is XMLRPC, it's probably not reliable. Me and @develric were trying to be super defensive but we didn't expect this. Since it's only about the error message, I think we can safely keep it nullable.

Thanks @planarvoid, I didn't catch that in my initial review since the conversion of `SiteStore.java` to `SiteStore.kt` didn't happen in the PR I was looking at. It happened in a different PR from the same time period. I'll take care of making this change.
