### ISSUE TITLE
[Android] Blogging Reminders v2: Update event tracking

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-Android#15177]
add a `selected_time` property to the existing `blogging_reminders_scheduled` event

**Comment by AliSoftware** [comment]
@ravishanker I'm about to code-freeze 18.1 and I'm never sure if y'all wait for the release to be out and you check that issue was indeed fixed/addressed in the release build before closing the GH issue… or if it should be closed as soon as it's considered fixed…?
But I see this one was moved to Done in the kanban project and that associated PRs are merged, so should we close this one?

(Note: if it needs to be kept open for some reason, please move the milestone to 18.2)

**Comment by AliSoftware** [comment]
@ravishanker Should we close this?

**Comment by renanferrari** [comment]
Closed by #15178.
