### ISSUE TITLE
Crash: tgkill

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15343]
**Sentry Url**: https://sentry.io/share/issue/cffd91cb859146a1a2887f5e74040e65/
**User Count**: 724
**Count**: 1344
**First Release**: 17.7
**First Seen**: 2021-07-14T01:25:19.038000Z
**Last Seen**: 2021-09-17T03:50:07Z
**24 Hours**: 18
**30 Days**: 670

```
null: Abort

```

Stacktrace is not very helpful and it might be hard to debug and reproduce, but since numbers are high, still worth looking into imho.

**Comment by renanferrari** [comment]
This is a native crash, so it's very hard to debug due to the lack of symbolication in the logs. One thing we might want to try is to review [Sentry's documentation](https://docs.sentry.io/platforms/android/using-ndk/#symbolicate-stack-traces) and make sure we have everything set up to support that. Maybe this is something we can address as part of Groundskeeping? (cc @thehenrybyrd)

**Comment by RenanLukas** [comment]
This crash might be related to [`reanimated`](https://github.com/software-mansion/react-native-reanimated/issues/1912#issuecomment-1774665791) library. If this is the case, we won't be seeing this issue again after updating Gutenberg's version to Reanimated 3. This work is already [in progress](https://github.com/WordPress/gutenberg/pull/58475/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119R65) (thanks @dcalhoun).

**Comment by irfano** [comment]
Since React Native was [upgraded to 0.73](https://github.com/WordPress/gutenberg/pull/58475/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119R65), the issue should be addressed with v25.0.
