### ISSUE TITLE
NullPointerException: site.unmappedUrl must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15500]
**Sentry Url**: https://sentry.io/share/issue/50bfd0b4130f4fd8a3fa13a75c6bfd90/
**User Count**: 10
**Count**: 42
**First Release**: 18.5-rc-1
**First Seen**: 2021-10-19T08:54:19.386000Z
**Last Seen**: 2021-10-27T02:00:34Z
**24 Hours**: 5
**30 Days**: 42

```
NullPointerException: site.unmappedUrl must not be null
     at org.wordpress.android.ui.domains.DomainsDashboardViewModel.getSiteDomainsList(DomainsDashboardViewModel.kt:83)
     at org.wordpress.android.ui.domains.DomainsDashboardViewModel.start(DomainsDashboardViewModel.kt:72)
     at org.wordpress.android.ui.domains.DomainsDashboardFragment.setupViewModel(DomainsDashboardFragment.kt:45)
     at org.wordpress.android.ui.domains.DomainsDashboardFragment.onViewCreated(DomainsDashboardFragment.kt:32)
...
(19 additional frame(s) were not displayed)
```

Relatively low user and event count, so I hesitated creating the GH issue so soon… but also because on the current beta (which isn't out yet) I figured better flag it sooner than later. \cc @jhnstn I'll let you decide on priority.

**Comment by jd-alexander** [comment]
Hi @ravishanker there's a crash occurring at  https://github.com/wordpress-mobile/WordPress-Android/blob/0c735a551f5a6a924008facfecedcc2967c5326a/WordPress/src/main/java/org/wordpress/android/ui/domains/DomainsDashboardViewModel.kt#L87

Could you please take a look? It's is currently impacting 17 users in the beta. Thanks! 

I think this should be a betafix @AliSoftware because the fix should be straight forward and if we are able to prevent crashes for users then I think that should always be prioritized.

**Comment by ravishanker** [comment]
Closing this one as this fix is not necessary anymore due to the changes introduced by #15521
