### ISSUE TITLE
Editor: When switching between HTML-Visual mode quickly the notices do not track the mode change

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15643]
### Expected behavior
When switching between HTML-Visual mode quickly the notices are in sync with the mode change

### Actual behavior

When switching between HTML-Visual mode a bit faster than usual, e.g. Visual -> HTML -> Visual, the app shows more Notices than expected. Here’s a video:

https://user-images.githubusercontent.com/304044/144580739-31c6b7c8-8092-40e8-93f2-1cdd6b9c075f.mp4

### Steps to reproduce the behavior

1. Open the editor
2. Switch between Visual - HTML mode a few times
3. Notice that the compact notice keeps switching

##### Tested on Pixel 5, Android12, WPAndroid 18.8

Related PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15583
Internal ref: `p5T066-2Ra-p2#comment-10752`

**Comment by mchowning** [comment]
👋  @antonis ! Did you mean to attach a video to the description?

**Comment by antonis** [comment]
> 👋 @antonis ! Did you mean to attach a video to the description?

Yep 😬  Thank you for noticing @mchowning 🙇

**Comment by ParaskP7** [comment]
👋 @antonis !

First of all, thank you for opening this issue and nice find btw! 🙇 

After looking at this issue briefly and trying to think about possible solutions I came-up with the following that I would like to discuss with you:
1. `A Step Forward`: This seems like an issue that is only possible to be fixed through `Gutenberg`.
    - I am seeing this [WPAndroidGlueCode.showNotice(...)](https://github.com/WordPress/gutenberg/blob/942cd4225926298b18bafdfb3c7da110b74f7e3e/packages/react-native-bridge/android/react-native-bridge/src/main/java/org/wordpress/mobile/WPAndroidGlue/WPAndroidGlueCode.java#L800-L806) method being responsible to showing the notices.
    - However, for a potential client side fix, I am not seeing any APIs available for the clients to be able to hit in order for example to `(a)` figure out whether the notice is already shown or even `(b)` to dismiss the notice in case it is shown in order to discard this notice and instead show the most recent notice.
2. `A Step Back`: Although the same applies to [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS), as per this [identical issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/18036) that @tiagomar opened, when looking on the web I am not seeing any notices to be showing to our users, that is when they are switching from the `Visual Editor` to the `Code Editor`, and vice-versa. This makes me wonder whether we might want to reconsider showing that notice altogether. Wdyt?
    - `Pros`: From the [track trends - last 12 months](https://mc.a8c.com/tracks/trends/?eventname=wpandroid_editor_session_switch_editor%2Cwpios_editor_session_switch_editor&interval=day&startdate=20210401&stat=uniques), I am seeing that our users are indeed using this feature enough, almost 1K hits a day.
    -  🤔 No matter if our users are using this feature as a whole or not, that doesn't mean that they need the notice as well, does it? The web seems to have dropped it for some reason, or maybe they never even used it in to begin with? 
    - `Cons`: In addition to this bug, of multiple notices showing when a user switches between the `HTML Mode` and the `Visual Mode` faster than expected, when a user switch to the `HTML Mode`, I am also seeing another bug where the notice shown overrides the editor's first line, most probably the title, if that exists. PS: This doesn't happen when the user switches to the `Visual Mode` as it seems that the space for showing the notice is enough with that mode selected. Wdyt about that?

All in all, I wanted to share all this information with you because:
1. I am not sure if I or any native developer is able to solve this. Most probably this requires React native and Gutenberg experience. Should we maybe add a `Gutenberg` label or some kind of other such label to indicate that?
2. I am not sure if instead of solving it we might want to consider another path, removing this notice altogether. When the user clicks on the switch, and since they already see a visual update of the editor's state, maybe showing an extra notice is not that intuitive, makes the UI more complicated than necessary, and we could very easily do without showing such notice.

**Comment by antonis** [comment]
Hey @ParaskP7 👋 
Thank you for looping into this 🙇‍♂️ 
> This seems like an issue that is only possible to be fixed through Gutenberg

I agree. A Gutenberg solution would work better on this 👍 

> removing this notice altogether. 

Indeed [that was our original approach ](https://github.com/wordpress-mobile/WordPress-Android/issues/11819#issuecomment-631579036) but [the design feedback suggested to use the compact editor notice](https://github.com/wordpress-mobile/WordPress-Android/issues/11819#issuecomment-969670515) which made sense at that point.

**Comment by ParaskP7** [comment]
👋 @antonis !

Thank you for the input! 🥇 

> I agree. A Gutenberg solution would work better on this 👍

👍 

> Indeed https://github.com/wordpress-mobile/WordPress-Android/issues/11819#issuecomment-631579036but https://github.com/wordpress-mobile/WordPress-Android/issues/11819#issuecomment-969670515 which made sense at that point.

Ah, nice, thanks for connecting the dots for me and providing additional context as to why we switched from the bottom pop-up to the top notice. As it was noted, maybe we don't show a notice when switching to HTML, maybe we don't show the notice at all, or maybe we only show a notice for a specific switch only (`HTML` or `Visual` mode).

For example, we could say that we would always show the notice for when the user switches to `Visual` mode, since it can also host this extra needed space on top. We don't show the notice when the user switches to `HTML` mode, since it is actually very evident that what is happening. Thus, this way we can kind of get rid the problems of multiple notices showing because the same notice will be show anyway. Although it can be shown multiple time, if the user do the `HTML` -> `Visual` -> `HTML` -> `Visual` change very quickly, how much quick can the user be, or how many time we will get a user doing exactly that. 🤔
