### ISSUE TITLE
My Site Dashboard - Phase 2 - Fix Indefinite Pull-to-Refresh on Application Closed

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-Android#15767]
Parent: #15198

### Expected behavior

When closing the application using the back press/swipe and then re-opening, the pull-to-refresh appears for a second or two, while refresh is happening, and then it should disappear.

### Actual behavior

When closing the application using the back press/swipe and then re-opening, the pull-to-refresh appears, while refreshing is happening, but then it never disappears.

### Steps to reproduce the behavior
- Open app.
- Verify that the pull-to-refresh appears for a second or two, and then disappears.
- Back press/swipe to close app.
- Re-open app.
- Verify that the pull-to-refresh appears but never disappears.

##### Tested on [device], Android [version], WPAndroid [version]
Tested on [Pixel 4], Android [12], WPAndroid [18.9]

**Comment by zwarm** [comment]
Quick notes:
When the app is returned from the background the value of `selectedSiteRepository.hasSelectedSite()`, the refresh mutableLiveData, is true. Since we are not requesting a new fetch of site data, we are left in a state of refreshing because there is no event to trigger the false. For a quick test just update `SelectedSiteSource.init` as follows:

```
init {
        if (selectedSiteRepository.hasSelectedSite()) {
            super.onRefreshedMainThread()
        }
        dispatcher.register(this)
    }
```
This little snippet will turn off the refresh flag on return from background when there already is a selected site. @ashiagr - perhaps we can pair up to talk about possible solutions. I only gave it a cursory look late today.Thanks.

**Comment by ashiagr** [comment]
Thanks for taking a look, @zwarm! Let's pair up today to see what's going on. 🙏
