### ISSUE TITLE
Weekly roundup notification despite notifications off

### ISSUE THREAD

**Issue by adityabhaskar** [wordpress-mobile/WordPress-Android#15816]
### Expected behavior
When all notifications are off, the weekly roundup notifications are still delivered.

### Actual behavior
The weekly roundup notifications shouldn't be delivered. 

Ideally, there should be a toggle to specifically disable just them. I'd rather have one or two notifications enabled, but toggling 7-8 toggles per site is unnecessarily hard, so I've disabled all notifications at the top of the notifications settings screen. Weekly roundup still came through!

Now I've removed the notification permissions for the app from system settings, but thought I'd let you know just in case this is a bug and not a growth hack.

### Steps to reproduce the behaviour

1. Switch off all notifications using the top toggle on the notification settings screen
2. Wait for weekly roundup notifications

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 5, Android 12, WP 18.8

**Comment by thehenrybyrd** [comment]
Hi @adityabhaskar, thanks for bringing this up!
To clarify: 
> I've disabled all notifications at the top of the notifications settings screen. Weekly roundup still came through!

Do you mean that you went to Notifications (bottom menu) > Settings (gear icon) and toggled the toggle there from "On" to "Off"?

<img src="https://user-images.githubusercontent.com/15107387/151131820-8d51b332-e5ab-42a9-8612-e9c45c3db520.jpg" width="75%">

If so, I would expect the same thing you do. Since all Notification Types (Notifications tab, Email, and App notifications) are listed for individual sites in this Notification Settings section, I would expect toggling the whole thing to "off" to turn off all of those notifications.

cc: @Gio2018 this issue would effect the Weekly Roundup, but might also be a discussion around what we expect from that Notifications Settings on/off toggle.

**Comment by thehenrybyrd** [comment]
related: https://github.com/wordpress-mobile/WordPress-Android/issues/15318

**Comment by irfano** [comment]
This bug is still active on version 19.4-rc-1. 
This on/off switch is working only for push notifications (notifications sending from the remote server) but weekly roundup notifications are local notifications.

**Comment by scottshambaugh** [comment]
Can confirm same bug on iPhone 11 Pro, iOS 16.1, wordpress app 21.0.0.2. 

Really annoying bug for someone on a low-notification diet.

**Comment by irfano** [comment]
With the [fix](https://github.com/wordpress-mobile/WordPress-Android/pull/17496), weekly roundup notifications, create site notifications, and blogging reminder notifications won't be delivered when the Notification Settings switch is off.
