### ISSUE TITLE
IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15869]
**Sentry Url**: https://sentry.io/share/issue/bbe51c029f0b4c039edcdcfac38075d9/ + https://sentry.io/share/issue/ab9270a1f2bf475da4f64d5946ab167a/
**User Count**: 314 (incl 253 common users in 2nd issue now merged with the first)
**Count**: 319 + 253 = 572
**First Release**: 18.9-rc-1
**First Seen**: 2021-12-14T12:41:25.505000Z
**Last Seen**: 2022-01-28T11:33:31Z
**24 Hours**: 32
**30 Days**: 314

```
IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
     at org.wordpress.android.widgets.WPSnackbar$Companion.make(WPSnackbar.kt:15)
     at org.wordpress.android.widgets.WPSnackbarWrapper.make(WPSnackbarWrapper.kt:16)
     at org.wordpress.android.util.SnackbarSequencer.prepareSnackBar(SnackbarSequencer.kt:93)
     at org.wordpress.android.util.SnackbarSequencer.start(SnackbarSequencer.kt:60)
     at org.wordpress.android.util.SnackbarSequencer.access$start(SnackbarSequencer.kt:25)
     at org.wordpress.android.util.SnackbarSequencer$start$1.invokeSuspend(null:11)
...
(14 additional frame(s) were not displayed)
```

**Comment by develric** [comment]
The issue is related to 18.9 previous release and is also present in 19.0. Considering only numbers for 18.9 (currently, 97.24% of events are on that version since 19.0 is just starting rolling out)

- 18.9 number of users: 296k
- Number of affected users: 572
- Impact: 572/296k = 0.19% -> Low
- Severity: AFAIU the issue is happening while completing the quickstart for the "Grow your audience" -> "Follow other sites" step (the `Tracked: quick_start_task_completed, Properties: {"task_name":"follow_site"}` seems to appear before the issue). Since this is a crash on the quickstart flow, assigning high severity

Also, number of events seems pretty steady and luckely not growing up

![image](https://user-images.githubusercontent.com/47797566/151571799-0232394c-f2ba-4bc7-8b48-6987272c7401.png)


Given all the above, assigning a Medium priority. @ashiagr 👋 , do you think you could have a look into it? If I'm not wrong you may have worked on Quickstart not much time ago. Sorry for the wrong ping if not :), let me know 🙇 

cc @AliSoftware

**Comment by ashiagr** [comment]
Thank you for the ping, @develric! 🙏 I've addressed the issue in the linked PR. I've added you as a reviewer as it is a simple fix, but feel free to ignore and @zwarm can help in the review, her having more context about the feature.
