### ISSUE TITLE
Signup: The Check email button does not work

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#15883]
### Expected behavior
Pressing the `Check email` button during sign up redirects the user to the default email app. If this is not set we should directly prompt the user to open the email app manually and not with a button.

### Actual behavior
Pressing the `Check email` button show the `Can't detect your email client app` error message.

### Steps to reproduce the behavior

1. Press the Signup button on the landing screen of the app (on a fresh install or logged out state)
2. Provide an email
3. On the next screen press the `Check email` button
4. *Notice* the `Can't detect your email client app` error message

<details>
<summary>Screenshot</summary>

![device-2022-02-01-152101](https://user-images.githubusercontent.com/304044/151981935-536819d0-7b7c-4ccc-b237-e166a5646f07.png)
</details>

_Context: Gmail is the only email client on the device_

**Comment by ovitrif** [comment]
@antonis I wanted to discuss this issue too, but when I checked it on my physical device it won't reproduce.
It always reproduces in the emulator, which led me to believe it's related to the configuration of my emulator 🤷‍♂️

I will trigger a factory reset on my physical android device (since I've been planning to do it anyway for a long time already) and retest it.

> If this is not set we should directly prompt the user to open the email app manually and not with a button.
Can you please elaborate what you have in mind for this? Maybe I misunderstand this since it appears to me you suggest to use something else than the button at the bottom of the screen :)

**Comment by guarani** [comment]
I too have this issue. I'm using a Samsung Galaxy S10 with Android 11 and because I don't have a default email app configured, I see the "Can't detect your email client app" message. I agree that the app should instead prompt the user to manually check their email app.
