### ISSUE TITLE
an Incompatiable API Usage in APP of "<android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>"

### ISSUE THREAD

**Issue by PSDroid2022** [wordpress-mobile/WordPress-Android#16019]
[Type] Enhancement
[feature] Incompatibilie usages of some framwork APIs

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

1. <android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)> [28,30]
```java
One error invoking path:<org.wordpress.android.modules.AppComponent: void inject(java.lang.Object)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: void inject(org.wordpress.android.WordPress)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.WordPress injectWordPress(org.wordpress.android.WordPress)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.fluxc.tools.FluxCImageLoader fluxCImageLoader()>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.fluxc.network.UserAgent userAgent()>[[]]--><org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory: org.wordpress.android.fluxc.network.UserAgent provideUserAgent(org.wordpress.android.modules.AppConfigModule,android.content.Context)>[[]]--><org.wordpress.android.modules.AppConfigModule: org.wordpress.android.fluxc.network.UserAgent provideUserAgent(android.content.Context)>[[]]--><org.wordpress.android.fluxc.network.UserAgent: void <init>(android.content.Context,java.lang.String)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>
```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 28)" when invoking this API to prevent compatibility issues.

**Comment by Valentin-ys** [comment]
[Type] Enhancement
[feature] Incompatibilie usages of some framwork APIs
Dear developers,

We have recently developed a state-of-the-art static analysis tool for uncovering API compatibility issues in Android apps. Applying this tool to open source apps on F-droid, we have exposed a few instances of compatibility issues and submitting them to development teams for a fix.

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

1. <android.app.Dialog: android.view.View findViewById(int)> [1,25]
``` Java
One error invoking path: <org.wordpress.android.ui.posts.PrepublishingBottomSheetFragment$Companion: org.wordpress.android.ui.posts.PrepublishingBottomSheetFragment newInstance(org.wordpress.android.fluxc.model.SiteModel,boolean,boolean)>[[]]--><org.wordpress.android.ui.posts.PrepublishingBottomSheetFragment: void <init>()>[[]]--><org.wordpress.android.ui.WPBottomSheetDialogFragment: void <init>()>[]--><org.wordpress.android.ui.WPBottomSheetDialogFragment: void onResume()>[[]]--><org.wordpress.android.ui.WPBottomSheetDialogFragment: void restrictMaxWidthForDialog(android.app.Dialog)>[[]]--><android.app.Dialog: android.view.View findViewById(int)>
```
2. <android.view.View: void setAutofillHints(java.lang.String[])> [26,30]
```java
One error invoking path: <org.wordpress.android.widgets.HeaderGridView$HeaderViewGridAdapter: android.view.View getView(int,android.view.View,android.view.ViewGroup)>[[]]--><android.view.View: void <init>(android.content.Context)>[]--><android.view.View: void setAutofillHints(java.lang.String[])>
```
3. <android.view.View: boolean isImportantForAutofill()>  [26,30]
```java
One error invoking path: <org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference: void <init>(android.content.Context,android.util.AttributeSet,org.wordpress.android.models.NotificationsSettings$Channel,org.wordpress.android.models.NotificationsSettings$Type,long,org.wordpress.android.models.NotificationsSettings,org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference$OnNotificationsSettingsChangedListener)>[[]]--><org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference: void <init>(android.content.Context,android.util.AttributeSet,org.wordpress.android.models.NotificationsSettings.Channel,org.wordpress.android.models.NotificationsSettings.Type,long,org.wordpress.android.models.NotificationsSettings,org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.OnNotificationsSettingsChangedListener,org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.BloggingRemindersProvider)>[]--><org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference: android.view.View onCreateDialogView()>[[]]--><android.view.View: void <init>(android.content.Context)>[]--><android.view.View: boolean isImportantForAutofill()>
```
4. <android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)> [28,30]
```java
One error invoking path:<org.wordpress.android.modules.AppComponent: void inject(java.lang.Object)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: void inject(org.wordpress.android.WordPress)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.WordPress injectWordPress(org.wordpress.android.WordPress)>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.fluxc.tools.FluxCImageLoader fluxCImageLoader()>[[]]--><org.wordpress.android.modules.DaggerAppComponent: org.wordpress.android.fluxc.network.UserAgent userAgent()>[[]]--><org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory: org.wordpress.android.fluxc.network.UserAgent provideUserAgent(org.wordpress.android.modules.AppConfigModule,android.content.Context)>[[]]--><org.wordpress.android.modules.AppConfigModule: org.wordpress.android.fluxc.network.UserAgent provideUserAgent(android.content.Context)>[[]]--><org.wordpress.android.fluxc.network.UserAgent: void <init>(android.content.Context,java.lang.String)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>
```

5. <android.view.View: java.lang.String[] getAutofillHints()>
```java
One error invoking path:<org.wordpress.android.widgets.HeaderGridView$HeaderViewGridAdapter: android.view.View getView(int,android.view.View,android.view.ViewGroup)>[[]]--><android.view.View: void <init>(android.content.Context)>[]--><android.view.View: java.lang.String[] getAutofillHints()>
```


Note that, because of the nature of the static analysis, we cannot confirm whether the flagged APIs would actually be called at runtime (e.g., unreachable code). However, we still believe that those APIs, which may cause compatibility issues, should not be accessed or at least be accessed with proper protections.

In addition to the aforementioned APIs (i.e., backward-compatibility), which could cause app crashes if accessed, we have also identified that this project has also accessed some APIs that have been removed from the latest public SDK, making the app possibly suffer from forward-compatibility issues.

NONE

We would be very much appreciated if you can acknowledge to us that those reported APIs are indeed problematic for the projects long-term stability. please let us know if you need any more information relating to this issue report.

**Comment by hypest** [comment]
Thanks for opening this ticket!

I had a look and looks like the only place the `setDataDirectorySuffix()` method is used here is in `setWebViewDataDirectorySuffixOnAndroidP`, and it [is guarded with a check for Android P (API 28) already](https://github.com/wordpress-mobile/WordPress-Android/blob/a2218f0ea74ff4ee996b6266f09b290c43bc6aa1/WordPress/src/main/java/org/wordpress/android/WordPress.java#L768-L773). I will go ahead and close this ticket an "no further action needed" but, please feel free to add more info/context if you think further action is indeed needed, happy to reopen. Thanks!
