### ISSUE TITLE
Send "read signal" PNs to automatically dismiss notifications in the app

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1603]
Thanks @mjangda for this:

* I got 2 new email notifications from Gmail in succession; they ended up being stacked into one
* I went to Gmail on my computer (the notification was still active in my notification drawer on the device and I had it visible)
* I opened the newest email on my computer
* A few seconds later, the notification for that email got dismissed and the notification changed from the stacked view (“2 new emails”) to the single one (“New email from…”)
* I opened the next email on my computer as well
* The remaining notification was also dismissed
* It would be really amazing to be able to have this sort of behaviour for the WordPress app as well. If I view a notification from my computer, we should get rid of that notification for the user.

Also useful when you have a tablet and a phone and read notifications from one device.

**Comment by mzorz** [comment]
Been investigating this issue, making sense of it all now.

1) So when notifications tab is opened (or the app comes to the foreground and notifications tab is currently on top), the `last_seen` data is updated in the `meta` bucket, then synced up.
(iOS https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+Extensions.swift#L499 (thanks @jleandroperez )

(Android https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/notifications/utils/SimperiumUtils.java#L157)

2) when simperium gets this, we should trigger a notification to ~~all mobile clients~~ Android (not iOS because it’ll be available only since iOS 10 - thanks @jleandroperez  again) to dismiss any outstanding notification.
OR, find an alternative path that signals that the meta bucket has been updated, to trigger such notification.
 
3) on the mobile client (Android), enable receiving/intercepting this special notification and “remove” all pending notification cards.
