### ISSUE TITLE
Video Upload Errors Despite VideoPress Subscription

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-Android#16077]
### Expected behavior
Video uploads should be without errors when a self-hosted site has a VideoPress subscription

### Actual behavior
The user is getting the error `Uploading videos longer than 5 min requires a paid plan` that was added to the app in https://github.com/wordpress-mobile/WordPress-Android/pull/15719 

### Steps to reproduce the behavior
We haven't been able to reproduce this, but the user can reliably 

Ticket: 4787561-zen

**Comment by thehenrybyrd** [comment]
@azollafox thanks for reporting this!
An assumption I have here is that, in order to have a VideoPress subscription, the user must have the Jetpack plugin installed and connected to WordPress.com. Is that correct? (I'm 97% sure)

@ravishanker maybe you'd have some insight here about how Jetpack sites are currently handled for the purpose of limiting video uploads. Does that include allowing uploads for sites that have a VideoPress subscription? This might be a-la-carte, separate from one of the current Jetpack Plans.

**Comment by SiobhyB** [comment]
To round this off, this has been fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/16322 and will be included in 19.8.
