### ISSUE TITLE
Title is Scrollable on My Site Dashboard with no sites

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16226]
### Expected behavior
When no Sites are present, "My Site" title shown should not be scrollable. 

### Actual behavior
https://user-images.githubusercontent.com/17463767/161224504-f46a9578-98c0-42e1-9e81-4d945a89206e.mp4

### Steps to reproduce the behavior
- Launch app with an account having no sites
- Notice that "My Site" is shown on toolbar 
- Scroll down

##### Tested on [device], Android [version], WPAndroid [version]
Emulator, Android 12 version

**Comment by johnoricha** [comment]
I am working on this issue

**Comment by dmdbilal** [comment]
If this issue is still open, Can I work on this issue ?

**Comment by 07jasjeet** [comment]
### Issue irrelevant as of now since the title is not shown on the _My Sites_ destination in any of the flavors (Wordpress or Jetpack).

<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/98077881/593080fd-6173-41a5-880d-975fe8f2009b" width="300" height="600" />
<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/98077881/5945c8e7-b14b-4421-9137-132cedf45413" width="300" height="600" />

**Comment by AjeshRPai** [comment]
Closing this issues as pointed by @07jasjeet - Issue irrelevant as of now since the title is not shown on the My Sites destination in any of the flavors (Wordpress or Jetpack).

Thanks @07jasjeet
