### ISSUE TITLE
Cannot choose reader topics in some languages

### ISSUE THREAD

**Issue by jarvislin** [wordpress-mobile/WordPress-Android#16237]
### Expected behavior
It should have no problem after I submitted the topics that I chose.

https://user-images.githubusercontent.com/3839951/161374883-3229eb28-ae4d-4951-8a59-5e46486e8739.mp4

### Actual behavior

https://user-images.githubusercontent.com/3839951/161373527-c9532236-c1a1-432d-9411-35ad3b9cb8d0.mp4

I got a 400 error when I submitted the topics.

Logcat:
```
2022-04-02 15:30:12.313 24785-24882/org.wordpress.android E/Volley: [90] NetworkUtility.shouldRetryException: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.2/read/tags/mine/new?locale=zh_TW
2022-04-02 15:30:12.317 24785-24785/org.wordpress.android W/WordPress-READER: add tag failed
2022-04-02 15:30:12.320 24785-24785/org.wordpress.android E/WordPress-READER: null
    com.android.volley.ClientError
        at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

### Steps to reproduce the behavior
Locales that I tested: zh_TW, zh_CH, ja_JP

1. Choose one of the above locales as the device's language.
2. Log in to an account with no reader topics.
3. Click `Reader` on the bottom tab.
4. Click `Get Started` on the tab page of `DISCOVER`.
5. Choose topics.
6. Click `Done` and it will show the error message.

##### Tested on [device], Android [version], WPAndroid [version]
Tested on Pixel 3a, Android 12
WPAndroid 19.4
Also tested on the trunk branch, commit SHA-1: 1897f41f8eb47980df210568a58543cd6851b265

**Comment by thehenrybyrd** [comment]
@jarvislin thanks for reporting this!
I was able to reproduce easily, and it looks like the issue is with languages which do not use the latin alphabet. I'm guessing the non-latin strings being sent are causing some issues. It looks like these strings are being sent in UTF format, e.x. `%d0%b5%d0%b4%d0%b0`. 
cc: @zwarm as you've worked on Reader Topics, and @AliSoftware for your insight into localization.

**To reproduce:**
1. Head to Reader >  ⚙️ > Followed Topics and unfollow any topics you currently follow. (Alternatively, login to an account with no followed topics)
2. Head to My Site > Me > App Settings and change Interface Language to a non-latin language such as Chinese or Russian.
3. Back in Reader, choose the Discover tab (second tab from the left), and tap the "Get Started" button (the blue button in the middle of the tab when no topics are followed).
4. Select a few topics and tap the button at the bottom.
5. Note that a toast message appears with an error.

Error translates to:
> There was a problem executing the request
> Try again later

Original error in Russian:
> при выполнении запроса возникла. 
> проблема повторите попытку позже.

**Screenshots:**
![readererror](https://user-images.githubusercontent.com/15107387/161931909-1f37f842-638b-4a12-a2b3-04f7f41629fa.jpg)

**I tested in:**
Dutch - no issue
Chinese (Taiwan) - error
Swedish (making sure to select topics with extra-latin characters) - no issue
Russian - error
Korean - error

In languages without translation for Reader topics (these show the English), I had no issue.

Relevant logs:
```05 - [Apr-06 08:38 UTILS] trackLastActivity, activityId: Reader
06 - [Apr-06 08:38 STATS] 🔵 Tracked: reader_accessed
07 - [Apr-06 08:38 STATS] 🔵 Tracked: feature_flag_value, Properties: {"my_site_dashboard_phase_2":true,"my_site_dashboard_phase_2_state":"default_source_value"}
08 - [Apr-06 08:38 STATS] 🔵 Tracked: feature_flag_value, Properties: {"my_site_dashboard_phase_2":true,"my_site_dashboard_phase_2_state":"default_source_value"}
09 - [Apr-06 08:38 STATS] 🔵 Tracked: feature_flag_value, Properties: {"my_site_dashboard_phase_2":true,"my_site_dashboard_phase_2_state":"default_source_value"}
10 - [Apr-06 08:38 STATS] 🔵 Tracked: feature_flag_value, Properties: {"my_site_dashboard_phase_2":true,"my_site_dashboard_phase_2_state":"default_source_value"}
11 - [Apr-06 08:38 READER] reader discover service > job scheduled
12 - [Apr-06 08:38 MAIN] ReaderTracker: started MAIN_READER
13 - [Apr-06 08:38 READER] reader discover job service > stopped
14 - [Apr-06 08:38 READER] reader discover job service > started
15 - [Apr-06 08:38 NOTIFS] Register token action succeeded
16 - [Apr-06 08:38 NOTIFS] Server response OK. The device_id: 45681035
17 - [Apr-06 08:38 STATS] 🔵 Tracked: reader_discover_shown
18 - [Apr-06 08:38 READER] clearing ReaderDiscoverCardsTable
19 - [Apr-06 08:38 READER] Post from /cards json not found in ReaderDatabase
20 - [Apr-06 08:38 READER] clearing ReaderDiscoverCardsTable
21 - [Apr-06 08:38 READER] reader discover job service > all tasks completed
22 - [Apr-06 08:38 READER] reader discover job service > all tasks completed
23 - [Apr-06 08:38 READER] reader discover job service > destroyed
24 - [Apr-06 08:38 STATS] 🔵 Tracked: reader_reader_tag_followed, Properties: {"tag":"%d0%b5%d0%b4%d0%b0","source":"discover"}
25 - [Apr-06 08:38 STATS] 🔵 Tracked: reader_reader_tag_followed, Properties: {"tag":"%d0%bf%d1%83%d1%82%d0%b5%d1%88%d0%b5%d1%81%d1%82%d0%b2%d0%b8%d1%8f","source":"discover"}
26 - [Apr-06 08:38 STATS] 🔵 Tracked: reader_reader_tag_followed, Properties: {"tag":"%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5-%d0%b1%d0%bb%d0%be%d0%b3%d0%b0","source":"discover"}
27 - [Apr-06 08:38 STATS] 🔵 Tracked: select_interests_picked, Properties: {"quantity":3}
28 - [Apr-06 08:38 READER] add tag failed
29 - [Apr-06 08:38 READER] null
30 - [Apr-06 08:38 READER] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

31 - [Apr-06 08:38 READER] reader discover service > job scheduled
32 - [Apr-06 08:38 READER] reader discover job service > created
33 - [Apr-06 08:38 READER] reader discover job service > started
34 - [Apr-06 08:38 UTILS] trackLastActivity, activityId: My Site```

**Tested on Samsung Galaxy S21, Android 12, WP Android 19.5-rc-4**
**Problem remains in 19.6-rc-1.**

**Comment by thehenrybyrd** [comment]
I tested this again in 19.7-rc-4, and am still experiencing it. 
In this instance, I tested using the device-level language switcher, rather than in-app.
In addition, I found that topics are initially followed (despite the 404), but checking the settings unfollows them immediately.

**To reproduce:**

1. Head to Reader > ⚙️ > Followed Topics and unfollow any topics you currently follow. (Alternatively, login to an account with no followed topics)
2. Head to your device Settings and change device language to a non-latin language such as Chinese or Russian.
3. Back in Reader, choose the Discover tab (second tab from the left), and tap the "Get Started" button (the blue button in the middle of the tab when no topics are followed).
4. Select a few topics and tap the button at the bottom.
5. Note that a toast message appears with an error.
6. Tap the "back" button, and note that some posts from your followed topics appear.
7. Tap the ⚙️ for Reader Settings, and note you see your followed topics briefly, after which they disappear. Posts no longer load in the Discover section.

**Comment by ashiagr** [comment]
I was able to reproduce this issue for `zh_TW` locale. 

Endpoint for `GET` reader tags in `zh_TW` locale:
https://public-api.wordpress.com/wpcom/v2/read/interests?_locale=zh_TW

Title/ slug pair from the endpoint above:
`{"title":"美食","slug":"%e7%be%8e%e9%a3%9f"}`

We follow a tag using its slug. Notice that the slug returned from the server(`%e7%be%8e%e9%a3%9f`) has % characters but they get trimmed in the [sanitizeWithDashes](https://github.com/wordpress-mobile/WordPress-Android/blob/a2218f0ea74ff4ee996b6266f09b290c43bc6aa1/WordPress/src/main/java/org/wordpress/android/ui/reader/utils/ReaderUtils.java#L130) method. `%e7%be%8e%e9%a3%9f` is a valid url encoded string, it can be verified using [this online URL decoder tool](https://www.urldecoder.io/) and so doesn't need any sanitization. 

This is also confirmed from the exact error message that we get from the server: 
`{"error":"invalid_tag","message":"The tag requested does not seem to be valid: e7be8ee9a39f"}`

I'll create a PR with a possible fix (to skip tag sanitization if it is already URL encoded).
