### ISSUE TITLE
My Site Dashboard - UI Tweaks 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#16255]
Parent #15125

Apply tweaks to the My Site Dashboard UI based on what we subsequently did on iOS:

![android_updates](https://user-images.githubusercontent.com/1405144/161690068-1dab33a5-dd88-41b4-99fd-43442382520d.png)

PS: Struck-off items are implemented as part of other tasks.

**Comment by osullivanchris** [comment]
@ashiagr small update here. As part of other pieces of work it seems we've taken care of 'Serif Title' and 'Chips rather than circles'

So that only leaves the card changes:
- icon and bolder text in header
- arrow in top right of card rather than text link at bottom
- more roundy corners

<img width="672" alt="Screenshot 2022-04-08 at 11 16 31" src="https://user-images.githubusercontent.com/50576199/162416329-95c2d2b6-3f1c-4afa-804c-c1d2a5f61c9a.png">

**Comment by osullivanchris** [comment]
As discussed amongst the team, we won't change the blue text links to arrows right now.

(a) we have a conflicting ellipsis action in the top right location
(b) it could be useful to see if more people drill down on 'Go to' links on Android compared with chevrons on iOS

Here's how the desired state looks. The only outstanding changes are 
- more rounded corners
- icons in the heading and bolder text

<img width="738" alt="Screenshot 2022-04-12 at 12 09 29" src="https://user-images.githubusercontent.com/50576199/162947416-ca864cee-b728-4be9-ad50-8681c4f858c4.png">

**Comment by AjeshRPai** [comment]
Update the text colour used for the **Views/Visitors/Likes** text view to be of the same colour used in the **Description** text view of Posts Card 

![image](https://user-images.githubusercontent.com/17463767/168053602-bb979ee1-059c-4800-a653-06f8a8074397.png)
