### ISSUE TITLE
Feature request: Support HEIC files in media picker

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#16367]
Requested in 4954753-zd-woothemes.

Currently, the WPAndroid app doesn't allow selecting HEIC files in the media picker when uploading media files. Please consider adding the support for this file type.

**Comment by thehenrybyrd** [comment]
@reginabally do you know if HEICs are failing on a particular site type? I ask because a previous issue around this in iOS was Atomic-only: https://github.com/wordpress-mobile/WordPress-iOS/issues/14680

**Comment by ehg** [comment]
We now support HEIC files on WordPress.com, and I am getting the same behaviour reported here – the HEIC image is greyed out. The site is a WPCOM simple site.

I believe the problem is that `image/heic` and `image/heif` are not defined in [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/utils/MimeTypes.kt#L72) – but haven't looked into whether the FluxC takes the `allowed_file_types` site option into consideration when deciding what to allow (like Calypso does).

 <img src="https://user-images.githubusercontent.com/215074/165479962-1328e86e-87a1-4539-b298-45dd593cb62f.jpeg" height="600">

**Comment by reginabally** [comment]
@thehenrybyrd The reported case in the linked ticket happened on a WPCOM Simple site. I could also reproduce this on one of my WPCOM Simple test sites.

**Comment by thehenrybyrd** [comment]
@reginabally @ehg thanks for the extra details!
