### ISSUE TITLE
Media Quick start: Snackbar Flickering 

### ISSUE THREAD

**Issue by AjeshRPai** [wordpress-mobile/WordPress-Android#16572]
### Expected behavior
Snackbar should not flicker when shown during media quick start 

### Actual behavior
https://user-images.githubusercontent.com/17463767/168756562-3c9f9654-9817-4563-a13e-f84f2139e10c.mp4

### Steps to reproduce the behavior
- Go to a site with quick start in progress( Quick start for users v2)
- Start Media quick start 
- Notice that there is flickering when selecting plus icon to upload media

**Comment by Hoossayn** [comment]
hey @AjeshRPai, picking this issue up

**Comment by AjeshRPai** [comment]
Thanks @Hoossayn for volunteering to work on this issue. 🙌🏼 . Let me know if you need any help or additional info.

**Comment by Hoossayn** [comment]
👋  @AjeshRPai noticed the `Quick start` card on this issue is different from what we currently have. want to confirm if an update had been made over time or i worked on the wrong version. kindly see images for difference 
![gtkwh](https://user-images.githubusercontent.com/35276272/190999829-3e03c5be-c000-4f73-a25d-306fdc52294b.png)
![gtkh](https://user-images.githubusercontent.com/35276272/190999845-099677bf-cba3-474d-98a0-67c8e171004f.png)

**Comment by AjeshRPai** [comment]
@Hoossayn Thanks for the query. 

There are two versions of the `Quick start` card, that's displayed based on whether the user is creating a new site(Next steps card)/login into the app with an existing site(Quick start card with 5 tasks- Get to know the app). But this logic doesn't have any dependency/relation to the snack bar flickering issue as much as I know. Let me know if you need any other details. 

The media upload task is shown in the New quick start tour which is shown when a user logs in to the app with an existing site and clicks at show me around. 

![sc](https://user-images.githubusercontent.com/17463767/191021431-38672925-819c-41b0-93c3-e8e80c6fedcc.jpeg)

**Comment by Hoossayn** [comment]
@AjeshRPai, thanks for the clarification
