### ISSUE TITLE
Clicking on the Stats Widget after Closing the App Prompts User to Enable Site Stats Again

### ISSUE THREAD

**Issue by igotdes** [wordpress-mobile/WordPress-Android#16637]
### Expected behavior

If a user has already previously enabled stats, they shouldn't be prompted to enable it again.

### Actual behavior

The user is prompted to enable stats. However, clicking on "Enable site stats" only results in an "Unable to activate site stats" error.

### Steps to reproduce the behavior

1. Add a stats widget to your device's home screen
2. View the list of active apps and swipe on the WordPress app to close it
3. Click on the stats widget

##### Replicated on a Samsung Galaxy Note20 Ultra 5G, Android 12, WPAndroid 19.9-rc-2 (1220)

**Comment by thehenrybyrd** [comment]
Hi @igotdes, thanks for reporting this!
I wasn't able to reproduce this, so I may be setting things up differently than you are.

Can you let us know:
1. Which stats widget you are using? (At a glance, All-time, Today, or this Week?)
2. Whether your site is hosted on WordPress.com or elsewhere? (Stats relies on a Jetpack connection, so we'll want to try to replicate your setup for that)
3. Are you able to view stats successfully if you open the WordPress app directly and head to My Site > Stats?

Thanks!

**Comment by igotdes** [comment]
Hi, @thehenrybyrd. 👋  Thank you for looking into this!

Previously, I was testing on an AT site with the Today widget.

I just tested again. For nos. 1 and 2, I tested all four stats widgets—At a glance, All-time, Today, and Views this Week—on a self-hosted site that's on Pressable, a simple WordPress.com site, and an AT site.

For each site, the issue now occurs at random.

For no. 3, not sure if this is the scenario you're thinking of, but after I see the "Enable site stats" notice, if I head to my phone's home screen to open the WordPress app again:

1. I get the "Enable site stats" notice again
2. Clicking the back arrow takes me back to my phone's home screen

To view stats successfully again, I need to:

1. Close the app
2. Open the app from my phone's home screen so that it opens just on the My Site screen
3. Click on Stats from there

I hope that helps a bit more, but please let me know if I can test anything else!

**Comment by thehenrybyrd** [comment]
Thanks @igotdes!
One final thing I can think of is to check the Jetpack connection status of each site, to make sure they are not in a "site-only" ("userless") state. I've run into that state causing the "enable site stats" notice to appear before, so want to rule that out. (I'm honestly not sure if that's possible on a simple WordPress.com site though)

To check that, you can head into the site's Jetpack dashboard and scroll down to the "Connections" section. There, make sure there's both a Site Connection and an Account Connection listed.

> To view stats successfully again, I need to

Based on your steps here, it sounds like you can always get around this by restarting the app, then opening it directly from the app icon (rather than a widget). Am I understanding that correctly?

Thanks!

**Comment by igotdes** [comment]
> Based on your steps here, it sounds like you can always get around this by restarting the app, then opening it directly from the app icon (rather than a widget). Am I understanding that correctly?

Yes, that's correct!

**Comment by aleone89** [comment]
We've had a report of this bug on the forums here https://wordpress.com/forums/topic/unable-to-activate-site-stats/?view=all

**Comment by thehenrybyrd** [comment]
I was able to reproduce this issue in the Jetpack app, with three sites: a WordPress.com simple site (private), WordPress.com simple site (public) and an old Atomic site.
**Tested on a Samsung Galaxy S21, Android 12**

To reproduce:
1. Close the Jetpack app
2. Long-press on the Jetpack app and select widgets, then add the "Views this week" widget.
3. While the app is still closed, tap on a stat in the widget.
4. Note the widget opens into "Stats" but states "Looking for stats?" - "Enable site stats".

To "fix" the situation from here:
1. Open the Jetpack app, and navigate to Stats
2. Close the Jetpack app
3. Tap a stat on the widget

To see it break again:
1. Open the Jetpack app and navigate away from Stats. 
2. Close the Jetpack app
4. Tap a stat on the widget


Initial reproduction:

https://user-images.githubusercontent.com/15107387/190413952-7ea859d6-3460-4099-bd5b-5f686ff6196d.mov

Reproducing "Fixing" it:

https://user-images.githubusercontent.com/15107387/190414635-0fb1d1d9-9220-40d3-a9ad-d933925b35a7.mov

**Comment by wargcm** [comment]
While testing Android 20.8, I ran into this issue (p5T066-3Ak-p2#comment-13505).

**Testing details:**

- **Device**: Samsung Galaxy A53 5G / SM-A536U1
- **OS**: Android 12
- **App versions**: Jetpack 20.8-rc-1 / WordPress 20.8-rc-1
- **Site**: Hosted on WordPress.com (private)

**Repo steps**:

- Clean install either WordPress or Jetpack
- Login
- Close the app
- Long-press on the app and add the All-time stats widget
- Tap on one of the stats

The "fix" in https://github.com/wordpress-mobile/WordPress-Android/issues/16637#issuecomment-1248095157 did not work for me. The only time it'd work properly is if the app was already running.

https://user-images.githubusercontent.com/2454408/192331887-d4f5edf7-f6ac-4a0e-bde0-460fefd98527.mp4

Additionally, tapping on the widget header seems to work properly. When I tapped on "All-time", it would bring me to the stats screen correctly.

https://user-images.githubusercontent.com/2454408/192331997-7a21e4c2-5993-4201-b7da-4979575bd237.mp4

**Comment by ravishanker** [comment]
The issue seems to have cropped up [after this change](https://github.com/wordpress-mobile/WordPress-Android/pull/15034)

This is working alright when tapping on the widget header but not on the content.  Mystery needs to be resolved!

**Comment by mkevins** [comment]
> The "fix" in [#16637 (comment)](https://github.com/wordpress-mobile/WordPress-Android/issues/16637#issuecomment-1248095157) did not work for me. The only time it'd work properly is if the app was already running.

I also observed the same as @wargcm , so perhaps this behavior has changed since the issue was opened.

> This is working alright when tapping on the widget header but not on the content. Mystery needs to be resolved!

I also observed this. I believe the reason for this is that[ the title lives outside of the list](https://github.com/wordpress-mobile/WordPress-Android/blob/8668cf24c0f1daa95681863f106cdec6d24c0875/WordPress/src/main/res/layout/stats_widget_list_dark.xml#L9), and thus [has its own `PendingIntent`](https://github.com/wordpress-mobile/WordPress-Android/blob/8668cf24c0f1daa95681863f106cdec6d24c0875/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetUpdater.kt#L55), while the items inside the list use [a `fillIn`](https://github.com/wordpress-mobile/WordPress-Android/blob/8668cf24c0f1daa95681863f106cdec6d24c0875/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/weeks/WeekViewsWidgetListProvider.kt#L70) with a pendingIntentTemplate. The problem is that this template for the list items [is immutable](https://github.com/wordpress-mobile/WordPress-Android/blob/8668cf24c0f1daa95681863f106cdec6d24c0875/WordPress/src/main/java/org/wordpress/android/ui/stats/refresh/lists/widget/utils/WidgetUtils.kt#L198), so [ per the docs:](https://developer.android.com/reference/android/app/PendingIntent#FLAG_IMMUTABLE)
> This means that the additional intent argument passed to the send methods to fill in unpopulated properties of this intent will be ignored.

One solution to this is to set this template with `FLAG_MUTABLE`, and this seems to resolve the issue. Another possibility would be to provide `siteId` in the template intent directly, but this would leave all the subview intents undifferentiated (rendering the fillins useless).

I have opened a PR for this here: https://github.com/wordpress-mobile/WordPress-Android/pull/17439
