### ISSUE TITLE
Fix detekt suppressed errors in baseline.xml after bump to 1.19.0

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#16829]
In #16819 we had to bump `detekt` version to `1.19.0`, and because of that we had to suppress over 100 existing errors in `baseline.xml`.
They should be fixed and the PRs should be listed in this issue:

- ...

**Comment by ovitrif** [comment]
We're splitting #16819 into two separate work items, where the Detekt bump to `1.19.0` will be handled separately.

Key takeaways from the discussions in that PR:
- We plan switching to `buildUponDefaultConfig = true`, more on the implications of doing so [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16819#pullrequestreview-1019922150) and [here](https://github.com/wordpress-mobile/WordPress-Android/pull/16819#issuecomment-1167334531).
- There will probably be more checks that will need suppression as a result of switching to `buildUponDefaultConfig = true`.
  The scope of this issue is to keep the `baseline.xml` at least with the same number of suppressions as it was before updating to `1.19.0`. But of course, if we can manage to fix more then it's even better, as one of our long-term tasks is to cleanup the baseline file and use inline suppressions or addressing the reported lines of code with fixes when applicable.
