### ISSUE TITLE
Stories go to Draft and Content Deletes When Published

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/WordPress-Android#16888]
### Expected behavior

When a story is published, it shows the content live and appears in the list of published posts.

### Actual behavior

The story shows under Drafts after one taps Publish. When opened, the content is missing.

### Steps to reproduce the behavior

* Tap the + in the app then tap Story Post.
* Tap a video or image to add to the story.
* Tap the check on the upper right.
* Tap the + to add another image or video.
* Tap the check on the arrow on the upper right.
* Add a story title.
* Tap "Publish Now."
* Tap "Posts."
* Note that the story is listed under Drafts.
* Tap the story to open it in the editor.
* Note the content is missing.

**Comment by ParaskP7** [comment]
👋 @ChrissiePollock and thank you so much for opening this issue! 🥇 

I believe this issue is an exact replicate of this [other issue](https://github.com/wordpress-mobile/WordPress-Android/issues/16867) that @geriux opened 6 days ago. 🤔 

You will notice that this issue [got resolved already](https://github.com/wordpress-mobile/WordPress-Android/pull/16881) and will be part of the final `20.2` release, to be submitted today. Also, the last beta for WPAndroid was the `20.2-rc-4`, where this fix landed. Can you test with that newest beta version and verify that everything works as you would expect. 🙏 

Then, and if indeed, everything works as expected, feel free to close this issue. 💯

**Comment by thehenrybyrd** [comment]
Agreed, looks like this is a duplicate. I'll close for now, @ChrissiePollock feel free to reopen if you're still seeing an issue in `20.3-rc-1` :)
