### ISSUE TITLE
[Type] Reproduce: Sync failed in commit [fd10bf2] 

### ISSUE THREAD

**Issue by ERICXUCHI** [wordpress-mobile/WordPress-Android#17055]
I want to reproduce the issue [#12396](https://github.com/wordpress-mobile/WordPress-Android/issues/12396)

But the android studio generates a sync failed like this:

`Failed reaching Jitpack for com.github.wordpress-mobile:react-native-video:1b964b107863351ed744fc104d7952bbec3e2d4f: 404
`

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/57583292/185631523-ab8ac9ee-36b5-4010-a835-c81eefd4437b.png">

I wonder whether some libraries are unsupported. Look forward to your reply. Thanks.

**Comment by AliSoftware** [comment]
Hello,

First of all, thanks for trying to help fix this issue! 🙇 

Note that fd10bf2 is quite an old commit (from June 2020, so 2 years ago), and we have since retired the use of Jitpack for our dependencies — which we now host on S3 instead (see https://github.com/wordpress-mobile/WordPress-Android/pull/16420).
So I doubt you'll be able to resolve that old dependency from that old commit easily nowadays.

If you want to investigate this issue, I'd suggest you to work on it from the latest `trunk` instead. Not only because that should solve your issue with this old dependency and Jitpack resolution, but also because so much have changed in the codebase since June 2020 that it would avoid you trying to fix some old things… that likely already changed (or even got partially fixed) in `trunk` since those 2 years 🙂
