### ISSUE TITLE
Reader: "Now" timestamp not translated

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17171]
### Expected behavior
I expected the timestamp "now", on a brand new post in Reader, to be translated.

### Actual behavior
In languages I checked (German, Chinese, Arabic), this was not translated. 
Though I found two possible matching strings in GlotPress ([1](https://translate.wordpress.org/projects/apps/android/dev/ar/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3348152&filters%5Btranslation_id%5D=47203335), [2](https://translate.wordpress.org/projects/apps/android/dev/ar/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4833190&filters%5Btranslation_id%5D=50799036)), neither appear to be used for this currently.

### Steps to reproduce the behavior
1. Set your language to one that isn't English.
2. Publish a new post on a blog you author and follow.
3. Head to Reader and refresh your Followed blogs to see your new post.
4. Note that the timestamp "now" is not translated. 

<img src="https://user-images.githubusercontent.com/15107387/190979552-57dfdb86-4aee-4f65-914b-8b504d97581c.jpg" width="50%">

**Comment by ovitrif** [comment]
I've investigated the issue and it seems to be occurring because the `Context` we inject in the util wrappers  has the same locale from the system regardless of the language we select, in other words the language for the `now` text is not updated when we change the app language via `App Settings`.

I'll continue investigating to see what options we have for fixing it.
