### ISSUE TITLE
Sharing: Tumblr connection process doesn't load

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17401]
### Expected behavior
I expected to be able to connect my site to Tumblr in order to share posts automatically.

### Actual behavior
When I tap "Connect" for Tumblr, I encounter a blank screen and can't move forward.

### Steps to reproduce the behavior
Use a site that is not yet connected to Tumblr
1. Head to My Site > Sharing > Tumblr.
2. Tap Connect.
3. Note that you see a blank screen, with no actions to take and no way to move forward.

Occasionally at step 3 I have seen a "Tumblr Privacy & Cookies" heading at step 3. 
Both dark and light mode display a blank screen.

<img src="https://user-images.githubusercontent.com/15107387/199221156-d8f992be-c4d5-49ba-a9e5-ca8be5a34338.jpg" width="90%">

##### Tested on Samsung Galaxy S21, Android 12, WPAndroid 21.0-rc-3
Found during usability exploration: pdcxQM-1ff-p2

**Comment by hafizrahman** [comment]
I tried this and found that while the Tumblr page does load on step 3, the login popup immediately got pushed down and could not be reached again. Video below:

https://user-images.githubusercontent.com/266376/219545581-be767604-7606-4ae3-b98b-602189ff7b4e.mov

**Comment by thomashorta** [comment]
I was taking a look at our sharing connection flows and found the same issue as @hafizrahman reported [here](https://github.com/wordpress-mobile/WordPress-Android/issues/17401#issuecomment-1434061112). 

Since my team is about to take on a project related to _Sharing_/_Jetpack Social_, I am going ahead and fixing the issue right now to ensure this behavior is fixed.

Regarding the original problem of "Note that you see a blank screen, with no actions to take and no way to move forward.", I could not reproduce that and I only see the behavior above (login form "running away").
