### ISSUE TITLE
[Jetpack] 'Try the new Jetpack app' button is missing translation in several languages 

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#17427]
### Expected behavior
`Try the new Jetpack app` button should have translations for the most popular locations.

### Actual behavior
'Try the new Jetpack app' button is missing translation in several languages.

String name: `wp_jetpack_get_new_jetpack_app` 
Missing languages from Mag-16 list:
- Arabic
- Brazilian Portuguese
- Dutch
- French
- Hebrew
- Italian
- Japanese
- Korean

### Steps to reproduce the behavior
**Prerequisites**: The "jetpack_powered_bottom_sheet" feature flag should be enabled.

1. Set the language to French (or any other language from the list above)
2. Tap the `Powered by Jetpack` badge/banner
3. Notice the button text is not translated.

**Comment by AliSoftware** [comment]
The translations are present in GlotPress, so they will be present next time we do a new beta (and in the final release of 21.1 as well).

It's just that those new strings were sent to GlotPress for translation on Monday (day of the code freeze), and the last beta we did for `21.1` so far was `21.1-rc-2` on Wednesday, so only two days afterwards; so it's not surprising that by that time polyglots hadn't had enough time to translate the new strings in all Mag16 (that's pretty common for them to take more than 2 days to translate everything in all locales!). And we haven't done any new beta since they translated the string in all the Mag16 languages in GlotPress since, so it's not surprising that the latest beta / APK you have available for testing on your end (`21.1-rc-2` build Wednesday) don't have those new translations just yet.

The next beta (which we'll do next Wednesday 2 days before submission day, exactly for that reason of smoke-testing the app around translations) will include all the latest translations from GlotPress as usual, after the polyglots would have had 9 days to translate everything, at which stage we usually have a way better translation coverage %. 

In fact, at the time I'm writing this comment, the translations for the Mag16 are all already at 100% — except for `pt-BR` which is still missing 6 strings, including this `wp_jetpack_get_new_jetpack_app`. So by the time we'll do the next beta on Wednesday to do our usual L10n smoke testing, all those translations will be available and included in the APK.

**Comment by thehenrybyrd** [comment]
Sounds like that's sorted, so I'll close this issue. Thanks for making certain @tiagomar!
