### ISSUE TITLE
Jetpack Settings doesn't appear for Atomic sites

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#17430]
### Expected behavior
Expected Jetpack Settings to appear for WordPress.com Atomic (Business plan) sites, as on iOS.

### Actual behavior
On Android, Jetpack Settings doesn't appear for WordPress.com Atomic sites.

### Steps to reproduce the behavior
Prep: Find or create an Atomic site. The permanent address will end in .wpcomstaging.com.
1. Head into My Site > Menu.
2. Note you see Stats, Activity Log, and Backup. 
3. Note you do not see Jetpack Settings.

Compare to a self-hosted site with the Jetpack plugin installed and active, or an old Atomic site (permanent address will end in mystagingwebsite.com). In these cases, Jetpack Settings does appear.

iOS vs Android for Atomic site:
<img src="https://user-images.githubusercontent.com/15107387/200260951-26a0d863-fd3e-4049-85b1-1c01aed7d31a.jpg" width="70%">

**Comment by mkevins** [comment]
I have investigated this issue a bit, and it seems that this has been disabled intentionally, since the start of the feature: https://github.com/wordpress-mobile/WordPress-Android/pull/13402/files#diff-31fb4e702b179e3f6c3b168984995aaa2bb28051eb82d1188d9fddb05d2c8764R1030, and I'm not sure what the reason is.

Also, I was unable to see this Jetpack Settings row in the iOS app, so I'm not :100: I'm following the same flow mentioned in the description. :thinking: . In the iOS code, I did find a similar bit of logic as found on Android: https://github.com/wordpress-mobile/WordPress-iOS/blob/17ad86222e096d90c63dfb62089fa55a59a3217f/WordPress/Classes/Models/Blog.m#L738, so it is possible I may be missing something about this issue :man_shrugging:

**Comment by ravishanker** [comment]
This option is available in Site Settings -> **Jetpack Settings** [Scroll down to bottom if necessary] -> Security.  It was removed from Menu on MySite when it was recently re-organised as it was deemed redundant.  There's a plan to streamline various settings spread out across the app as part of UI Modernization.
