### ISSUE TITLE
InflateException: Binary XML file line #48 in org.wordpress.android:layout/login_prologue_first: Binary XML file li...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17464]
**Sentry Url**: https://sentry.io/share/issue/e2c3dec66f2f4fc5a74b4d1c47bbb6b7/
**User Count**: 1 _(false positive: login hasn't happened yet at that stage)_
**Count**: 1197
**First Release**: 20.3
**First Seen**: 2022-08-03T06:47:46.753000Z
**Last Seen**: 2022-11-15T07:59:48Z
**24 Hours**: 91
**30 Days**: 1037

```
InflateException: Binary XML file line #48 in org.wordpress.android:layout/login_prologue_first: Binary XML file line #48 in org.wordpress.android:layout/login_prologue_first: Error inflating class ImageView
     at org.wordpress.android.ui.accounts.login.LoginProloguePageFragment.onViewCreated$lambda-4(LoginProloguePageFragment.kt:60)
     at org.wordpress.android.ui.accounts.login.LoginProloguePageFragment.$r8$lambda$leSPBdiCCcOT4z5I_K8IxAFt-FQ(null:0)
     at org.wordpress.android.ui.accounts.login.LoginProloguePageFragment$$InternalSyntheticLambda$0$91c7614f249977a2de20c54f787cbae6351011c1b9ea36c65f7b59e348057d68$0.run(null:0)
...
(25 additional frame(s) were not displayed)
```

**Comment by ovitrif** [comment]
This issue is not really new, there are many other related issues listed in Sentry that are much older and they all point to the same line of code: `login_prologue_first.xml:48`:

https://github.com/wordpress-mobile/WordPress-Android/blob/84d4ab4f512bb71e1a8cbef13364f9247c6f547d/WordPress/src/main/res/layout/login_prologue_first.xml#L48-L52

The root cause of the crash is a missing resource, namely `login_prologue_first_asset_one`, but there's nothing specific to this asset, the failure occurs there because it's the first drawable resource in the xml layout.

There's been already a thorough investigation on it in this GitHub issue closed with the `wontfix` status:
- https://github.com/wordpress-mobile/WordPress-Android/issues/13644

According to that investigation the actual root cause is related to the [Android App Bundle](https://developer.android.com/platform/technology/app-bundle), and it's experienced by users installing the app from other sources than the Play Store, in which case, they only install the main `apk` and miss the right split `APKs` with the drawable resources for their device configuration.
The reason this issue can occur in high numbers seems to be related to the fact that the majority of OEM backup tools can only backup the master APK.

This explains why the issue doesn't reproduce with normal installing scenarios, and it can reproduce with these steps:
<details>
<summary><b>💥 Repro Steps</b></summary>

- Install bundletool, if you don't have it already (you can use brew: `brew install bundletool`).
- From AS Select Build -> Build Bundle(s) / APK(s) -> Build Bundle(s)
- When build is finished, press "locate" in the popup that will appear in the bottom right corner of AS.
- Use bundletool to convert resulting `aab` file into `apks`:  `bundletool build-apks --bundle=org.wordpress.android-vanilla-debug.aab --output=app.apks`
- Change extension of resulting `apks` file to `zip` and unzip it. You will find `splits` folder inside.
- On the device where you plan to install the app, Got to Settings > Developer Options > Then Turn off `Verify Apps over USB`
- Locate `base-master.apk` and install it onto device.
- You should get the exception from this issue.

---
</details>

The conclusion at that time was that it's [not worth implementing a fix since it would introduce a security vulnerability](https://github.com/wordpress-mobile/WordPress-Android/issues/13644#issuecomment-774336404), and we can help users to fix this issue on their side by instructing them to:
> Uninstall the app and install it again from the Play Store.

On another side, this issue was expected to resolve over time because devices which have Play Protect active or Android 10 should block installs with missing splits.

Investigating a fix for this specific issue might be less worth it also because we're planning to change the landing screen of the WordPress app in the near future, although the underlying issue of `Missing Resources` can still occur in more places.

@ParaskP7 @khaykov Can you please double check to confirm these issues are similar and if possible advise on how to move forward?

P.S. I triaged this as `Low` prio similar to the [related issue closed issue](https://github.com/wordpress-mobile/WordPress-Android/issues/13644) as this should be an edge case.

**Comment by ParaskP7** [comment]
👋 @ovitrif and thanks for yet another deep investigation, this is great! 🥇 

> Investigating a fix for this specific issue might be less be worth it also because we're planning to change the landing screen of the WordPress app in the near future, although the underlying issue of Missing Resources can still occur in more places.
> 
> @ParaskP7 @khaykov Can you please double check to confirm these issues are similar and if possible advise on how to move forward?

Yea, I am not sure if these issues are similar, it sure looks like that.

But, as you mentioned, trying to fix this specific issue, especially since we're planning to change the landing screen in the near future, might not be the best use of our resources for now, that is of course, since I am also seeing the event count not being too high to justify that, but I am not sure... 🤷 

@AliSoftware wdyt?

**Comment by irfano** [comment]
I'm closing this since this should be resolved with https://github.com/wordpress-mobile/WordPress-Android/pull/18865
