### ISSUE TITLE
Android - Investigate applying the language setting on the migration screens

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#17685]
## Description
In order to make the migration user experience more reassuring we should try to [enhance the implementation of transferring the user selected language](https://github.com/wordpress-mobile/WordPress-Android/pull/17648) by applying the setting on the migration screens. 

Internal ref: pcdRpT-1i3-p2#comment-2547

**Comment by ovitrif** [comment]
There's two other issues related to transferring the user selected language that I've noticed.

#### App Language from WordPress app on Jetpack app login screen after interrupting migration

1. Install WordPress app and login
2. Go to `Me` → `App settings` → `Interface language` and change the app language.
3. Run the Jetpack app of the same version and flavour
4. On the migration welcome screen press back
5. **Notice** the language of the Landing screen is different than in migration flow (it's equal to what was set at step 2).

#### App Language from WordPress app on migration help screen

1. Install WordPress app and login
2. Go to `Me` → `App settings` → `Interface language` and change the app language.
3. Run the Jetpack app of the same version and flavour
4. On the migration welcome screen press `Need Help`
5. **Notice** the language of the Help screen is different than in migration flow (it's equal to what was set at step 2).

Both these are likely to be addressed with the fix for the main issue.
