### ISSUE TITLE
App Settings: Changing system to dark theme makes the texts almost invisible

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-Android#17780]
### Expected behavior
The app responds correctly to system dark/light mode changes.

### Actual behavior
Changing the system theme to dark mode while on the App Settings screen results in the screen background becoming dark and the text remaining dark as well.

### Steps to reproduce the behavior
1. Build & install the WordPress app from `trunk`
2. Login, go to `Me` → `App Settings`
3. Drag down from the top of the screen to show the system notifications drawer
4. Enable `Dark theme`
5. Dismiss the system notifications drawer
6. 🔴 **Notice** The `App Settings` screen shows dark text on dark background

**Note:** If you navigate back to `Me` screen and tap `App Settings` again, the text colors are correct.

| <img width="200" src="https://user-images.githubusercontent.com/4588074/213108607-31cb5d1c-a764-4315-beba-0f3cf3c7cc18.png"> |
| - |

<details>
<summary>🎬 Video Preview</summary>

https://user-images.githubusercontent.com/4588074/213108819-efbb3e2d-3154-4104-95ac-3fc845626610.mp4
</details>

##### Tested on `Pixel 6 emulator`, Android `13`, WPAndroid `21.5-rc-1` from `trunk`.

💡 P.S. This might be just an emulator issue, I can't reproduce it in production version `21.5.rc-1` on my Samsung phone (Android 9).

**Comment by thehenrybyrd** [comment]
@ovitrif I was able to reproduce this on my physical device - Samsung Galaxy S21, Android 12, WP and JP Android 21.5.
In addition, it happens in reverse if you start with the device set to dark mode. 
Exiting App Settings and re-entering it solves the problem.
Here are recordings from my reproduction:


https://user-images.githubusercontent.com/15107387/214900635-6c7d8035-1e95-4a7b-85da-7f3048aa85cd.mp4


https://user-images.githubusercontent.com/15107387/214900671-6c1a3ad1-c8dd-4db2-983f-4bc2b8ef4409.mp4

**Comment by hafizrahman** [comment]
I can replicate this also in the emulator: `Pixel 5 Android 12.0` WP app version `21.7-rc-2` from trunk.

**Comment by zwarm** [comment]
This is true for the following views: Account Settings, Site Settings, and App Settings (and any other view that uses the android PreferenceScreen view). These screens have been identified as "in-need-of-upgrade" because of using obsolete libraries. See the wonderful write up by @ParaskP7 in this [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17962). It may be best to address these at the same time.

**Comment by thomashorta** [comment]
I agree that we should look into modernizing those settings screens, which would be better handled by working on #17962. 

But I did some investigation about the issue reported here (dark mode not being applied on those Preference screens) and found out the issue happens because these screens are using `PreferenceFragment` with `setRetainInstance(true)`. It seems other types of Fragments have better support even when they are retained, so this could indeed be an issue with the `android.preference` version of `PreferenceFragment`. At the same time, looking at the project history, it seems those fragments were retained simply to survive configuration changes and other system-initiated process deaths and re-creations because our custom preferences did not handle that instance state save/restore properly.

With that in mind, I made some changes to remove the `setRetainInstance` call in those fragments and implemented `onSaveInstanceState`/`onRestoreInstanceState` for the custom preferences we have to address this specific bug of changing the Dark mode system settings (and other configuration changes) while we don't tackle the bigger task of updating these screens to use `androidx.preference` or Compose. Wdyt?

**Comment by ParaskP7** [comment]
> With that in mind, I made some changes to remove the setRetainInstance call in those fragments and implemented onSaveInstanceState/onRestoreInstanceState for the custom preferences we have to address this specific bug of changing the Dark mode system settings (and other configuration changes) while we don't tackle the bigger task of updating these screens to use androidx.preference or Compose. Wdyt?

I agree @thomashorta and thanks for looking into it in more detail! 💯 

Maybe it is better to make this little adjustment first and only then move forward with the `androidx.preference` or `Compose` migration. The later might take some time and I don't think we need to block the user experience till then. 😊 

PS: The only think I would recommend while proceeding with this little adjustment is to properly test this and any other such settings screen, like `Site Settings`, since lots of events are being triggered even for something as simple as switching on-and-off the `Use Block Editor` option. 🕸️ 🤷 🕷️
