### ISSUE TITLE
Remove Zendesk library from WordPress

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#17931]
For the next milestone after the `wordpress_support_forum_remote_field` flag is enabled, we should remove Zendesk and all related classes from the WordPress variant.

**Comment by ravishanker** [comment]
@irfano 

It is easy enough to exclude Zendesk sdk from WP.  However, may not be possible to remove from WP given it is one codebase for both JP and WP. 

See https://github.com/wordpress-mobile/WordPress-Android/pull/17959

It is tightly coupled in many places...

AppInitializer
GCMMessageService
GCMRegistrationService
HelpActivity
LoginActivity
EditPostActivity
EditPostCustomerSupportHelper
ReleaseNotesActivity
SiteSettingsFragment

If you have an idea to achieve this without much work then try it out.  Otherwise, close this issue.  Not much of an issue with APK size since its only a few KBs.  This can probably get resolved when sooner or later JP repo is forked out.

**Comment by guarani** [comment]
I think @sla8c found something similar on iOS (see https://github.com/wordpress-mobile/WordPress-iOS/issues/20110#issuecomment-1431954078).

**Comment by guarani** [comment]
@irfano, do you agree with closing this? It seems low impact and high effort

**Comment by irfano** [comment]
After opening this issue, [we decided to show Zendesk on WP for paid users](https://github.com/wordpress-mobile/WordPress-Android/issues/17966). So, we can't remove the Zendesk library from WP. We can close this issue.

**Update:** The decision to use Zendesk has changed. It's [decided](https://github.com/wordpress-mobile/WordPress-Android/issues/18042) not to use Zendesk on WordPress.

---
I'll still comment in case we want to remove the library in the future.

> @irfano
> 
> It is easy enough to exclude Zendesk sdk from WP. However, may not be possible to remove from WP given it is one codebase for both JP and WP.
> 
> See #17959
> 
> It is tightly coupled in many places...
> 
> AppInitializer GCMMessageService GCMRegistrationService HelpActivity LoginActivity EditPostActivity EditPostCustomerSupportHelper ReleaseNotesActivity SiteSettingsFragment
> 
> If you have an idea to achieve this without much work then try it out. Otherwise, close this issue. Not much of an issue with APK size since its only a few KBs. This can probably get resolved when sooner or later JP repo is forked out.

Good point, @ravishanker. Removing all classes related to Zendesk doesn't seem possible. But the coupled class is only `ZendeskHelper`. So, we could create a dummy `ZendeskHelper` for JP and the real one for WP. 

Or we could at least skip [setupZenDesk()](https://github.com/wordpress-mobile/WordPress-Android/blob/2857f3f16ea362e91e95b0928bd1ffb3908036e8/WordPress/src/main/java/org/wordpress/android/AppInitializer.kt#L318) for JP for the performance concern.
