### ISSUE TITLE
WordPress app showing Zendesk based support in some places

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-Android#17963]
### Expected behavior

All of the WP app's support screens should now link to the .org forum instead of Zendesk-based support.
The JP app should remain unchanged.

### Actual behavior

The WP app lets users contact support via Zendesk.

### Steps to reproduce the behavior

1. Install the WP app
2. Tap "Enter your existing site address"
3. Tap "Find your site address"
4. Tap "Need more help?"
5. Notice you're asked for your email address to contact support (Zendesk-based support)
6. ⚠️ There might be other flows in the app so a code check is needed to catch all the places where we're doing this, such as:
    - site deletion
    - popups when the network is unavailable
    - popups when the server cert is not valid
    - the "start over" flow under site settings
    - the "review app" flow
    - login throttled by API
    - close account flow
    - Jetpack install flow
    - and others

### A possible solution
As @staskus suggested in p1675940848375639/1675758319.284069-slack-C441E3YTS, we can save a lot of trouble by making all support requests go through the support screen. At the moment, some support requests might first ask for the user's email before showing the support screen. This isn't practical because we should have a single place to customize the support options available to the user. I agree that all support requests (i.e. when a "help" button is tapped anywhere in the app) should open the app's support screen (never a popup asking for the user's email).

##### Tested on Samsung S10, Android 12, [WPAndroid build from this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17933#issuecomment-1423601713)

**Comment by irfano** [comment]
- @guarani, you probably skipped enabling the remote flag (`wordpress_support_forum_remote_field`). I tested it on `trunk` and "NEED MORE HELP?" button opened the Help screen. It's implemented in https://github.com/wordpress-mobile/WordPress-Android/pull/17938. 

> site deletion
> popups when the network is unavailable
> popups when the server cert is not valid
> the "start over" flow under site settings
> the "review app" flow
> login throttled by API
> close account flow
> Jetpack install flow

- I checked these screens. We don't have some of them on WPAndroid. The contact us feature works as expected.
- I also searched the code for possible issues on this. I found an unused screen using Zendesk and [removed it from the repository](https://github.com/wordpress-mobile/WordPress-Android/pull/17964).

I'm closing the issue since it works as expected.
