### ISSUE TITLE
Permalinks change when updating page title

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-Android#18123]
### Expected behavior
I'd expect the page URL to remain the same even if I update the page title after the page has already been published. 

### Actual behavior
When updating the page title from the Android app, the permalinks also update and the previous URL returns a 404 error. This is specific to changing from the app and does not happen when doing from a browser. 

### Steps to reproduce the behavior
1. Publish a new page on a self-hosted WordPress.org site (no Jetpack) with the title Test Page 1 for example. 
2. View the page in a browser and notice the URL. 
3. From the browser edit the page title to Test Page 1 and update the page. 
4. View the page again in a browser, notice the same URL as in 2. (/test-page-1).
5. Open the site from the WordPress app and select the same page to be edited. 
6. Change the title of the page to Testing Permanlinks and update the page.
7. View the page in a browser, notice /test-page-1 returns a 404 and the new page is found at /testing-permalinks

##### Tested on Samsung Galaxy S9+, Android 10, WPAndroid 21.8

User report: 6006915-zd-woothemes

**Comment by antonis** [comment]
I wasn't able to reproduce this on the latest version of the app (23.7). I tried changing the title of a page created on the web as described in the issue description and a page created on mobile and this did not affect the permalink of the page. The only way to modify the permalink was to change the `Slug` of the page. I consider this the expected behaviour.

https://github.com/wordpress-mobile/WordPress-Android/assets/304044/f01e3f61-0df9-4c41-8b4f-5d6c994483ec

I will close this issue for now. Please reopen if the issue persists.
