### ISSUE TITLE
Link to site doesn't show preview from invitation notification in Jetpack

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-Android#18135]
### Expected behavior
When an invited user taps on the site name in the Accept Invitation window, a preview of the site should open.

### Actual behavior
There's an error saying Jetpack is unable to open the link.

https://user-images.githubusercontent.com/103850310/225959494-7b1ea9c9-da77-43cb-a048-899bc8ad9318.mp4

### Steps to reproduce the behavior
1. With User 1, add User 2 as a user to the site (I did so as a shop manager)
2. Login to Jetpack with User 2
3. Go to Notifications and tap on the notification for the invitation
4. Tap Accept Notification
5. In resulting screen, tap on site title
6. Note error
7. Repeat on Jetpack on iOS or WordPress on Android -- note that site preview opens

**Comment by RenanLukas** [comment]
Hey @lmischner , thanks for reporting this issue.

I've tried following the steps to reproduce twice using JP Android but it worked as expected. I wonder if there's something else in the setup that I'm missing or if this was fixed by another PR since the issue was reported 🤔 

<p float="left">
<img width="300" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/2f124084-5444-4858-8476-64264d562b01">
<img width="300" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/c159a70f-84bb-418a-b551-07c595ff9229">
</p>

**Comment by lmischner** [comment]
I just tried it and also could not reproduce. I'll go ahead and close this issue.

Thank you for investigating it!

**Comment by RenanLukas** [comment]
I've also tried with a shop manager role, like mentioned in step 1, and couldn't reproduce the `"Unable to open the link"` error message.
<img width="413" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/14964993/db172834-c633-40e1-9833-b85c916cb31f">
