### ISSUE TITLE
Can't like a comment from Comments area of app

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1829]
Since it doesn't use notifications data, there'd need to be a way to get the like data from the REST API or XML-RPC.

**Comment by fadils** [comment]
I couldn't find how to get the likes from XML-RPC API. Can we do with REST instead? Which means this feature will not be available to self-hosted blogs?

**Comment by rachelmcr** [comment]
It looks like we could do this through the REST API:

https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/comments/%24comment_ID/likes/new/
https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/comments/%24comment_ID/likes/mine/delete/
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/comments/%24comment_ID/likes/mine/

**Comment by daniloercoli** [comment]
I started working on this ticket today, but a lot of changes are required to implement the feature. 
`CommentDetailFragment` is already in a bad state, and FluxC integration is close to be ready for prime time.
When FluxC will be release, we can quite easily implement the feature (since it uses REST API), and clean/remove a lot of the code in the Fragment.

**Comment by maxme** [comment]
@daniloercoli yes, please refrain from modifying `CommentDetailFragment`  in `develop` before the fluxc branch is merged. It's already complicated to fix the conflicts ;).

Note: I already cleaned up `CommentDetailFragment` in the fluxc integration branch, and I hope I can remove the `mNote` reference completely there.

**Comment by maxme** [comment]
I fixed this in the fluxc integration branch.

**Comment by daniloercoli** [comment]
I think we can then close this issue.
