### ISSUE TITLE
Like notifications sometimes displays View, Share and Menu buttons pointing to the wrong site.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#18693]
### Expected behavior
In `Like` notifications `View in browser`, `Share` and `Menu` buttons, if present, should point to the right site.

### Actual behavior
Some `Like` notifications display `View in browser`, `Share` and `Menu` buttons pointing to the wrong site.

|  |  |
| - | - |
| <video width="100" src="https://github.com/wordpress-mobile/WordPress-Android/assets/42008628/4c44d77c-cccc-423b-80d4-bb378fc6dc98"> | <img width="600" src="https://github.com/wordpress-mobile/WordPress-Android/assets/42008628/6c6407ad-41e0-48e1-a93c-215e20a496d8"> |

### Steps to reproduce the behavior
1. Go to Notifications tab
2. Tap a Like notification
3. Tap the View in browser icon on the top of the screen (not all the Like notifications will display it)
4. ❌ The post referenced in the notification is not open, a different site is open instead. In this case, a post from a followed site.

**Comment by ovitrif** [comment]
As promised last week, I'll focus on pinpointing the code that causes this, but my investigation will stop there 😄

**Comment by ovitrif** [comment]
During my testing I noticed that sometimes, the controls don't show up in the navbar, and in such cases even the screen title is different:

| ![Capture 2023 06 27 11 10](https://github.com/wordpress-mobile/WordPress-Android/assets/4588074/cf4589e3-35dc-4cc7-b93d-4cbbdcda9372) |
| - |

In the above screenshot I'm looking at the detail view of the same notification, both via the emulator and a physical device:
- On the physical device (Google Pixel 7 Pro), I went through `Notifications` → `Likes` → list item click
- On the emulator (Pixel 6 Pro Api 33), I went and clicked the item directly in the `Notifications` list

While investigating, I figured out the detail view is sometimes reusing `ReaderPostDetailFragment`, which makes it a no-brainer to me as to why we ended up with this bug, since the core principle of separation of concerns is heavily violated here.

I will not spend more time on fixing this bug, since my team's release rotation ended. To what I can confirm, it is not a new bug, it has been here for a long time.

@tiagomar I will let this to be handled by the team on maintenance rotation.

**Comment by ovitrif** [comment]
> **Note**
> Before seeing the unexpected menu, here's where the code goes:

![Capture 2023 06 27 11 40](https://github.com/wordpress-mobile/WordPress-Android/assets/4588074/a19a97be-628a-4476-9a67-727993171bce)
