### ISSUE TITLE
Navigation buttons point to the same side when viewing a post in the web for RTL languages.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-Android#18807]
### Expected behavior
When viewing a post in the web, navigate back button should point to the right and navigate forward should point to the left.

### Actual behavior
Both buttons point to the right.

<img width="300" alt="image" src="https://github.com/wordpress-mobile/WordPress-Android/assets/42008628/de8735ba-798c-44f7-96bd-99f00324caa3">

### Steps to reproduce the behavior
1. Configure the device language as an RTL language.
2. Go to Reader 
3. Select a post and view it in the web browser.

**Comment by antonis** [comment]
Verified that the issue is still present on the latest version of the app (24.0-rc-1)

**Comment by jarvislin** [comment]
**Root cause**
We include an → icon `ic_arrow_left_white_24dp` under the `ldrtl` directory which has an inverse direction of the normal arrow ←.
But we don't have the ← icon `ic_arrow_right_white_24dp` under the `ldrtl` directory. That's why we got two arrows with the same direction.

I think we just need to simply add a new arrow icon under the `ldrtl` directory.
