### ISSUE TITLE
[Jetpack Social] Edit social share message improvements in Post Settings

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#18834]
We've identified improvements in the edit social share message screen (Post Settings - > `"Social sharing"` section -> `"Message"`) See discussion https://github.com/wordpress-mobile/WordPress-Android/pull/18790.
- [ ] It doesn't seem to be possible to select all within the text field;
- [x] The cursor starts at the very start of the text field. If filled, I'd probably expect it to start at the end;
- [x] There's no 'x' to clear the text with one tap;
- [x] User sets a custom message then they change their mind and delete the custom message -> we force the last custom message where I would maybe expect we default back to the post title.
- [x] Remove extra padding from top bar

**Comment by thomashorta** [comment]
> It doesn't seem to be possible to select all within the text field;

@osullivanchris I wasn't able to reproduce this. Can you give more information about https://github.com/wordpress-mobile/WordPress-Android/pull/18790#pullrequestreview-1538859435 when testing this screen?

Just to double-check: if you mean the "Select all" text that appears when doing a long press in Text Field contents, it only appears if the text is not already all selected. 

E.g.: it doesn't appear if there's only 1 word and you long-press it, since it already selects the whole word (all content), but it appears if you have multiple words separated by `space` and long-press one word or if you long-press an empty space instead of a particular word inside the field.

**Comment by osullivanchris** [comment]
@thomashorta it seems to be working as I expect now. I'm not sure why I had problems before. It might have been that I was using double-tap, which I do on iOS. Long press seems to work fine.

**Comment by thomashorta** [comment]
> It might have been that I was using double-tap, which I do on iOS. Long press seems to work fine.

Ohhh, I see what you mean now. I was not even aware that double-tap to select was a thing on Android nowadays, but it seems to be the case at least for Android 7 and up 😱.

I found out that this double-tap not selecting is [an issue](https://issuetracker.google.com/issues/137321832) in this Jetpack Compose component, but it doesn't look like Google will fix that in the near future.

I will try to take a quick look into adding that feature in that field but will try not to spend too much time on it.

**Comment by thomashorta** [comment]
> I will try to take a quick look into adding that feature in that field but will try not to spend too much time on it.

I spent a couple of hours trying to implement it and it turns out it doesn't seem possible to do it from our side as we don't have access to internal code that handles selection in that component and shows the text context floating menu. 😞
