### ISSUE TITLE
Audio from video on another post is heard on Notifications tab and in Reader

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-Android#18870]
### Expected behavior
- The video doesn't play and no audio is heard.
- Content for other posts isn't loaded.

**Observation:**
- Videos loaded in the browser that autoplay appear to be muted, even when the "Muted" option isn't explicitly set.
  - Should the app have the same behavior? 
  - Does this match iOS?

### Actual behavior
Audio from the video on another post is heard.

<details><summary>🎬 Exhibit A: Tapping on a post in Reader will autoplay its video as well as another post's autoplayed video simultaneously</summary>

https://github.com/wordpress-mobile/WordPress-Android/assets/2092798/f9274061-732d-4147-9341-1c0af53cf3a4</details>

<details><summary>🎬 Exhibit B: Tapping on a comment in Notifications will autoplay another post's video in the background</summary>

https://github.com/wordpress-mobile/WordPress-Android/assets/2092798/5d6d2abd-e6ad-4403-9349-d77abf850624</details>

### Steps to reproduce the behavior

These may not be the most efficient steps, but they should be close:

**Prerequisites:**
- A WordPress.com account [Account A] logged into the Jetpack App.
- Account A follows a blog owned by another account, Account B, and receives notifications when new posts are published and when comments are replied to.

1. Using Account B, create a new post and add a video using the **Video Block** that contains audio. (can be done in the app or on web)
2. Toggle on the Autoplay setting for the video.
3. Publish the post.
4. **Expect:** The app (using Account A) gets a notification of a new post on the followed blog.
5. Repeat steps 1-3 with a new post containing a different video with audio.
6. Using Account A, leave some comments on both posts. Reply to those comments using Account B so that Account A's app will be notified.
7. In the app, tap the Notifications tab and ensure confirm the "ALL" filter is selected at the top.
8. Experiment with tapping on comments and leaving new ones on the two posts.
9. Go to Reader and tap on the two posts for the followed blog.

**Comment by twstokes** [comment]
In my testing, web browsers default to muting autoplaying videos (even when not explicitly set as muted). Perhaps we can match the browsers here and split this issue into two stages:
1. Mute autoplaying videos in the app (and require the user to tap the unmute button, like in the browser)
2. Don't render media in other posts while looking at comments / posts

**Comment by tiagomar** [comment]
> 1. Mute autoplaying videos in the app (and require the user to tap the unmute button, like in the browser)
> 2. Don't render media in other posts while looking at comments / posts

This sounds like good workarounds to mitigate the UX effects but, please let me know if I'm wrong, the biggest concern would be the lack of isolation between posts, right? I really don't expect Post A to point to anything from Post B, in this case, the audio. This reminds me of this other bug, #18693, probably unrelated but also breaking this isolation idea.

**Comment by twstokes** [comment]
> the biggest concern would be the lack of isolation between posts, right? I really don't expect Post A to point to anything from Post B, in this case, the audio. This reminds me of this other bug, #18693, probably unrelated but also breaking this isolation idea.

Certainly @tiagomar. Thanks for linking to that other issue! The first stage proposal was an idea for a quicker UX fix, with the second being the more important (but potentially complex) fix.

**Comment by RenanLukas** [comment]
Hey @tiagomar and @twstokes , I've been investigating this issue since yesterday.

### The current hypothesis
When we tap on a post to open post details from reader, it is opened in a `ViewPager`, so you can swipe left and/or right to move to the next post details (or the next "page"). The cause of this bug seems to be related to the default offscreen screen limit of a `ViewPager`: [the default value is `1`](https://developer.android.com/reference/kotlin/androidx/viewpager/widget/ViewPager#getOffscreenPageLimit()), which means that one page will be automatically created on each side of the currently selected page. What seems to be happening is that if we tap on a post and any post next to it in the `ViewPager` (either the previous or the next one) has a video and autoplay enabled, the video will be played since all the three pages (the selected + one on each side) are being created and loaded at the same time.

In the case of `Notifications` tab, if you swipe left or right after selecting a comment you'll see that it's also loaded in a `ViewPager`, so if the next page is a post with a video and autoplay enabled it will start playing it.

This is our current hypothesis (thanks @thomashorta for the offscreen page limit idea), but happy to hear your thoughts.

### What I've tried so far
I've tried many different things using `ReaderWebView` but no luck. Basically I was trying to intercept the video URL in many different ways to add a new query parameter (`muted=1`) to the videos that had autoplay enabled (the ones that had `autoplay=1` in their URLs). In theory I was able to overwrite the URL by using the `shouldInterceptRequest` callback but it didn't work. I even tried checking the implementation of this method in AOSP and changing it to use the non-deprecated version of it (`WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest request)`) but for now I'm not sure why it didn't work.

Then I've moved to another approach: instead of intercepting and changing the video URL, I'd directly change the rendered HTML content in `ReaderPostRenderer`. I did some tests and had some success by changing the HTML directly (e.g. in some cases we get a `<video` tag and looks like I was able to change the `"autoplay"` and `"muted"` attributes).

## The fix
Considering @twstokes thoughts [here](https://github.com/wordpress-mobile/WordPress-Android/issues/18870#issuecomment-1662419742):
> 1. Mute autoplaying videos in the app (and require the user to tap the unmute button, like in the browser)

IMHO if we want a quick "fix"/workaround we'd have to go all-or-nothing by applying the fix to all the posts until we figure out a proper solution. What I mean with "all-or-nothing" is that even the post being displayed will start muted if it has autoplay enabled (I'm not sure this is what you meant, @twstokes), since identifying the currently selected post doesn't seem easy right now.
Another thing I think it's possible is to disable autoplay for all of them instead of muting. The reason I'm talking about disabling autoplay instead of muting it is this: let's say we have posts A, B and C and user taps on post B. Post A has a video and autoplay enabled. Post A and C will be automatically created along with B, and the video in post A will start playing, but muted. If user stays in post B for some time and then moves to post A the video might be in the middle or even finished already, and then the user will have to tap the replay button. If we just disable autoplay instead, the video in post A won't start until the user taps on it.

> 2. Don't render media in other posts while looking at comments / posts

This part doesn't seem like a straightforward fix to me because of two reasons:
1 - The minimum offscreen page limit of `ViewPager` is `1`, so at least one page from each side of the current selection will **always** be loaded;
2 - The video is being loaded in a WebView, so we don't have direct control over it. I've never tried this sort of thing in a `WebView` before, but **maybe** we can try "pausing" the pages that are not currently displayed based on [ViewPager.OnPageChangeListener](https://developer.android.com/reference/kotlin/androidx/viewpager/widget/ViewPager.OnPageChangeListener). IMHO this sort of thing doesn't seem like a quick fix, but if we go with the disabling autoplay approach we'll know that the video will be loaded in background, but won't be played until users interacts with it.

**Comment by twstokes** [comment]
Thank you for the deep investigation @RenanLukas and @thomashorta! 🙇 

> What I mean with "all-or-nothing" is that even the post being displayed will start muted if it has autoplay enabled (I'm not sure this is what you meant, @twstokes), since identifying the currently selected post doesn't seem easy right now.

This is what I meant @RenanLukas, which in my (quick) testing on my Android device seemed to be the default behavior in Chrome. For all autoplaying videos I had to manually tap the "unmute" button to hear them.

**Comment by thomashorta** [comment]
Thanks for the investigation @RenanLukas.

> Another thing I think it's possible is to disable autoplay for all of them instead of muting. The reason I'm talking about disabling autoplay instead of muting it is this: let's say we have posts A, B and C and user taps on post B. Post A has a video and autoplay enabled. Post A and C will be automatically created along with B, and the video in post A will start playing, but muted. If user stays in post B for some time and then moves to post A the video might be in the middle or even finished already, and then the user will have to tap the replay button. If we just disable autoplay instead, the video in post A won't start until the user taps on it.

I totally agree with this, if we can't stop the offscreen videos from playing (i.e.: just go with the **mute all** approach) we still have this other problem of the videos not being at the beginning if the user just swipes to next/previous post, which is a very odd experience.

I did some extra investigation and noticed that the web reader actually [strips autoplay from media](https://github.com/Automattic/wp-calypso/blob/e342e9c89ddc51530e2175ba7788c3c71687276f/client/state/reader/posts/normalization-rules.js#L122-L123). It seems to affect both VideoPress videos and regular videos. The PR introducing this behavior (https://github.com/Automattic/wp-calypso/pull/2050) is quite old so I wonder if the autoplay on Jetpack App was actually introduced by mistake.

What I found so far is that autoplay for embedded content (`audio` and `video` tags) is generally enabled when we set a specific setting in the WebView:
```java
getSettings().setMediaPlaybackRequiresUserGesture(false);
```

And we are actually [doing it here](https://github.com/wordpress-mobile/WordPress-Android/blob/9d7fd1842c52e060656381473d5280cb81189d5a/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java#L106), but it seems this setting was added because of a different issue (PR adding the setting: https://github.com/wordpress-mobile/WordPress-Android/pull/9721) which I was not able to reproduce when removing that line anyway (maybe affects old Android versions or specific WebView versions?).

I personally think disabling autoplay (by removing `setMediaPlaybackRequiresUserGesture`) might be a good strategy since it's what we do on Web Reader and would prevent the bugs we are seeing, I am just not sure if removing that line also affects VideoPress videos, since they do not use a `video` tag. If that's the case we might want to understand how Web is stripping `autoplay` from everything and so something similar when rendering the `WebView` content.

**Comment by RenanLukas** [comment]
>What I found so far is that autoplay for embedded content (audio and video tags) is generally enabled when we set a specific setting in the WebView:
getSettings().setMediaPlaybackRequiresUserGesture(false);

IMHO if removing this works as expected, it might be the best fix we have right now. In case we have unexpected side-effects or decide to go with the muting everything approach instead of disabling autoplay everywhere, I've opened a draft PR based on updating the HTML. If needed, it can easily be updated to use `autoplay` instead of `muted` and hopefully still work🤞 

https://github.com/wordpress-mobile/WordPress-Android/pull/18936

**Comment by twstokes** [comment]
Sounds like great ideas. I just wanted to add my vote that disabling autoplay does seem like a better solution here. 👍

**Comment by RenanLukas** [comment]
>I personally think disabling autoplay (by removing setMediaPlaybackRequiresUserGesture) might be a good strategy since it's what we do on Web Reader and would prevent the bugs we are seeing, I am just not sure if removing that line also affects VideoPress videos, since they do not use a video tag

Hey @thomashorta , I'm testing your proposed solution.

The result I'm getting is that videos with `autoplay=true` are still being played after removing `setMediaPlaybackRequiresUserGesture(false)` , but they're muted (I also found [this](https://stackoverflow.com/questions/63683187/work-around-to-autoplay-video-while-the-app-has-set-setmediaplaybackrequiresuser#comment112619808_63683187) comment in SO, while the documentation states that `"requires a user gesture to play media."` and doesn't specify any behavior when autoplay is enabled). This SO comment reminded me of the link you shared regarding [Google Chrome autoplay policy](https://developer.chrome.com/blog/autoplay/#new-behaviors).
I still think this is good news: even though we agreed that disabling autoplay would be a better solution, I'm more comfortable in changing one line related to a [well-documented method](https://developer.android.com/reference/android/webkit/WebSettings#setMediaPlaybackRequiresUserGesture(boolean)) and muting all videos instead of [changing the received HTML ](https://github.com/wordpress-mobile/WordPress-Android/pull/18936/files#diff-14566f7497ad356b28a263ff669b27f8ea4bc9f9546dea4428ba9e6a7e799065R197)to add `autoplay=false`/`autoplay=0` directly in the client. 

If you all think it's worth, I can still try to change the HTML directly in https://github.com/wordpress-mobile/WordPress-Android/pull/18936 to disable autoplay in every video, but I think it might be risky for a quick fix. 

I believe it's still worth to implement a proper solution for this issue, but this workaround would mitigate the bad user experience we're having at the moment with users hearing the sound of a video from post they're not seeing.

WDYT? cc @twstokes @tiagomar

**Comment by RenanLukas** [comment]
Closed https://github.com/wordpress-mobile/WordPress-Android/pull/18936, opened https://github.com/wordpress-mobile/WordPress-Android/pull/18957
