### ISSUE TITLE
[Reader Improvements] Implement new design for site header

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19069]
Implement new header design for selected site on Reader.

Design specs: pcdRpT-3BI-p2

**Comment by thomashorta** [comment]
The design was slightly changed in the past week, so I am keeping this open and will use it to also push a PR to implement the new changes.

Specs: zQnohyMpLzBzQ5jzMMKni3-fi-867_8658

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/5ec5a5b2-5c27-44cd-9a57-e6154855d235)

Note: we will likely not implement the posts in this PR, since it requires data-related changes.
