### ISSUE TITLE
[Reader Improvements] Implement new design for tag header

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19077]
Implement new header design for selected site on Reader.

Design specs: pcdRpT-3BI-p2

**Comment by thomashorta** [comment]
The design was slightly changed in the past week, so I am keeping this open and will use it to also push a PR to implement the new changes.

Specs: zQnohyMpLzBzQ5jzMMKni3-fi-867_8658

![image](https://github.com/wordpress-mobile/WordPress-Android/assets/5091503/68e30d38-3c1b-4800-a1e4-bc2cf8f1a776)
Note: we will likely not implement the `posts` and `followers` info in this PR, since it requires data-related changes.
