### ISSUE TITLE
Can't build for Fdroid

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/WordPress-Android#1914]
Because the published source code omits certain 'secrets', functionality that uses, for example, OAuth, Fdroid maintainers can't build.

Can something be done ?

**Comment by stefan-niedermann** [comment]
any news? its very annoying to not be able to use wp via f-droid :sad:

**Comment by PanderMusubi** [comment]
Latest build on f-droid is version 2.7.1 from 12 April 2014. Perhaps one of the people involved in that build could please revive and update that?

**Comment by easyKL** [comment]
WordPress-Android team decide to include non-free libraries like Crashlytics, it's impossible for F-Droid to proceed with newer builds.
No, no option for download in apps.wordpress.com/mobile/ other than play$tore

**Comment by PanderMusubi** [comment]
Could someone contact the WordPress team? Perhaps they see the benefit of helping a Crashlytics-free build for the smaller F-Droid community. Perhaps that could be by offering a build parameter.

**Comment by fazlerabbi37** [comment]
Well it's 2020 and many (for reasonable cause) are not using Google Play and many are de-Googling their Android. I would hope that WordPress-Android team would consider providing a FLOSS version without the non-free libs and figure out a way to use WordPress Android via F-Droid.

**Comment by stefan-niedermann** [comment]
Maybe offering a own f-droid repository would be a easy first step?

**Comment by fazlerabbi37** [comment]
> Maybe offering a own f-droid repository would be a easy first step?

not sure what do you mean by that. mind clarifying a bit?

**Comment by stefan-niedermann** [comment]
Everyone can setup F-Droid repositorys.

Every F-Droid user can add those "unofficial" repositorys to their sources (go to "Options" in your F-Droid app).

This allows organisations and people to distribute for example proprietary apps via F-Droid - The apps won't show up for everyone by default but Wordpress could just post a hint / button / url on their download site so every F-Droid user can add this repository to their F-Droid app.

Have a look at https://forum.f-droid.org/t/known-repositories/721

For example i am currently using Firefox Fenix via https://rfc2822.gitlab.io/fdroid-firefox/fdroid/repo?fingerprint=8F992BBBA0340EFE6299C7A410B36D9C8889114CA6C58013C3587CDA411B4AED because it also has proprietary dependencies and can't be on F-Droid directly, too. another sample is "Tagesschau", a german public news broadcasting app similar to british BBC.

**Comment by fazlerabbi37** [comment]
That could be another very helpful option and I think would not need a lot of change in Android app itself but I would still request the devs to consider a separate build without the non-free libs. I am sure many and I for one would really welcome it.

**Comment by narcisgarcia** [comment]
Me and many F-Droid users we prefer self hosted sites than wordpress.com
This means a clean Wordpress app is needed although (or even better) is self hosted limited.
