### ISSUE TITLE
Post is blank after an error during the upload

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1929]
From a user:

> I just tried to upload a post to WordPress using the latest version of the
> Android app, but instead it has deleted the entire content on the post.
> 
> The progress bar showed it had uploaded all the images, then at the last
> second it gave an error saying missing peer certificate or something like
> that. When I opened it again in the WordPress App, it was blank! Only the
> post settings (keywords/categories etc) remain.
> 
> I was able to upload a different post 5 min before and I have uploaded one
> since as well (5 min after this happened).

I checked on the server and the post is there, but it's blank. Only categories are there.
Pictures are on the server, but not attached to any post.

Not sure how this could happen, may worth to take a closer look at the posting service.

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by thebriankeys** [comment]
Just had the same issue with the app on my Nexus 5. I spent a whole flight putting a post together, got off the flight, went to upload (when connected) got an error with the post failing to upload due to an error with the video in the post. When I tried to edit the local copy of the complete post has disappeared!

Android Version 6.0

Was this issue ever resolved?

Please tell me, is there a way to retrieve the local copy of my draft post?

**Comment by maxme** [comment]
Closing this, we fixed a content loss issue recently https://github.com/wordpress-mobile/WordPress-Android/pull/4927
