### ISSUE TITLE
Pages: When publishing pages you see the prepublish modal that tells you select catergoris

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-Android#19557]
### Expected behaviour
You should not see the prepublish modal and you should not be able to choose categories. 

### Actual behaviour
You see this. After you publish a page.
<img src="https://github.com/wordpress-mobile/WordPress-Android/assets/115071/edf1202d-73a2-4958-9b51-9da9dceaa748" width="300" />

### Steps to reproduce the behavior
Create a new page. Publish it.

**Comment by antonis** [comment]
I've opened a PR for this just removing the categories selection. I chose not to remove completely the pre-publishing nudge since this exists on the web with the scheduling option and a checkbox at the bottom to skip it.

https://github.com/wordpress-mobile/WordPress-Android/pull/19656

![Screenshot 2023-11-23 at 3 34 05 PM](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/58113883-d3e4-4bfd-811b-e94556ded41d)
