### ISSUE TITLE
🤖 [Dynamic Cards] Dismissing card from a dropdown menu

### ISSUE THREAD

**Issue by justtwago** [wordpress-mobile/WordPress-Android#19776]
After tapping on the ••• menu, a dropdown menu should appear with a "hiding the card" option. After tapping on the card it has to be removed from the screen permanently.

![Image](https://github.com/wordpress-mobile/WordPress-Android/assets/16563318/260eec1f-03fd-491d-a39c-8a7349527f0e)

**Comment by malirauf** [comment]
Hi,
I want to work on this issue.

**Comment by antonis** [comment]
> Hi,
> I want to work on this issue.

Thank you for offering to help on this @malirauf 🙇 
Since this issue is part of a feature that is still work in progress it might be hard to coordinate on the implementation. Would you like to have a look at [an issue from this list ](https://github.com/wordpress-mobile/WordPress-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22)?
