### ISSUE TITLE
[Reader IA] Add number of followed sites and tags to Reader analytics events

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-Android#19836]
We should add the number of followed sites and tags to Reader analytics events where it makes sense. This should be aligned with iOS so we use the same keys and values.

**Comment by thomashorta** [comment]
@RenanLukas, on my last 1:1 with @develric we discussed sending new events for followed sites and followed tags count by hooking directly into the EventBus observers in the Subscription feed ([here](https://github.com/wordpress-mobile/WordPress-Android/blob/f9c970a0462eeae6c9ca2d68cfaa5c8dcb3718f1/WordPress/src/main/java/org/wordpress/android/ui/reader/subfilter/SubFilterViewModel.kt#L367-L379)). 

We didn't discuss what the event details but I was thinking something like:

Event name: `reader_following_fetched`
Properties:
- `type` (String): either `blogs` or `tags`.
- `count` (int): number of following blogs or tags (depending on type).

This could be at least a first step into getting this number into our analytics without adding extra fetches on screens that don't use that information on the UI, avoiding data consumption and possible performance issues, while tracking the most up-to-date information. 

The caveat is that we would get those events only on the "Subscriptions" feed and we will likely track it multiple times, as we fetch that data on refresh and other situations (though there could be some logic to only track when the data is different from the last tracked event or something).

What do you think?

**Comment by RenanLukas** [comment]
Hey @thomashorta 👋 

As discussed in DM yes, this also makes sense to me as a first step. 

> though there could be some logic to only track when the data is different from the last tracked event or something

💯

**Comment by daniloercoli** [comment]
Related to https://github.com/wordpress-mobile/WordPress-Android/issues/19907

**Comment by daniloercoli** [comment]
Rather than incorporating new information into a single event, we could add it to the `user_property` and refresh `metadata`  either when the Reader is accessed or when the app is launched. By utilizing metadata, this information would be included in every event sent from the app.

See [refreshMetadata](https://github.com/wordpress-mobile/WordPress-Android/blob/eeec54055af88943943cebf98b94519a527e1c7a/libs/analytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java#L546) 

<img width="911" alt="Screenshot 2024-02-02 at 09 34 37" src="https://github.com/wordpress-mobile/WordPress-Android/assets/518232/fe9a5916-1f84-4068-86b3-8f23aed1115e">

**Comment by thomashorta** [comment]
> Rather than incorporating new information into a single event, we could add it to the user_property and refresh metadata either when the Reader is accessed or when the app is launched. By utilizing metadata, this information would be included in every event sent from the app.

That makes sense, though bear in mind this means that events sent before we fetch the information will be different from events after the fetch, even in the session since we only fetch that data in the Reader `Subscriptions` feed currently. So it could get difficult to interpret the data in situations like:
- Before user ever uses Reader->Subscriptions (all events will be sending the information of 0 subscriptions)
- Every time the user subscribes to blogs and tags from other platforms (we only update if they open Subscriptions feed)

The workaround would be fetching that outside the Reader, on App Start or something, but it's extra information that's not exactly needed for the user and could block the flow (if we want to be 100% sure the data is updated before any events).

But I agree that would be more desirable in the long run. The comment above (https://github.com/wordpress-mobile/WordPress-Android/issues/19836#issuecomment-1906152787) is a suggestion for a temporary solution that will provide reliable and up-to-date subscriber information for users that access the feeds that load such information, with the caveat that will not trigger at all for users that don't use the Subscription feed/Reader.

Maybe it would make sense to make it a different GH issue, for clarity?
