### ISSUE TITLE
Use "centerCrop" scaleType in image grid views (media library and media picker)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#1992]
How to deal with banner?
https://github.com/wordpress-mobile/WordPress-Android/pull/1987#commitcomment-8521343

**Comment by theck13** [comment]
What about using `StaggeredGridLayoutManager` to account for the different aspect ratios of images?  Or do we want to keep the uniform grid?

**Comment by maxme** [comment]
@theck13 that's a good idea, that could work pretty well.

**Comment by theck13** [comment]
Another option may be to use `RecyclerView` combined with `FlexboxLayout`.  Details and demo apps can be found [here](https://android-developers.googleblog.com/2017/02/build-flexible-layouts-with.html).

**Comment by nbradbury** [comment]
PMFJI, but I figured I would since I'm working on a device media chooser right now.

I think a `RecyclerView` with a `FlexboxLayoutManager` would look really nice, but I'm not sold on the idea of a non-uniform grid. That strikes me as something that would make it harder to find the photo you want (although perhaps the photo you want would be among the most recent anyway, in which case varying sizes wouldn't be so jarring?).

**Comment by mzorz** [comment]
Closing via #5339
