### ISSUE TITLE
[Reader] The selected dropdown is not always kept

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#20127]
Checked this on Android; we should double-check on iOS.

I haven't delved deeply into this, but it appears that when the app goes into the background and is restored, the drop-down menu often defaults to Discover, even if a different item (such as Subscriptions) was previously selected.

**Comment by thomashorta** [comment]
Upon some testing it looks like the app is working as expected when it's being sent to the background (even with the "Don't Keep Activities" on) or when we just change tabs within the app. Can you confirm that @daniloercoli?

If that's indeed the case I will use this issue to implement a persistent feed menu selection across sessions, which is when the app is removed from "recents" and opened again, which is likely a common usage and it's indeed always resetting to "Discover".

**Comment by daniloercoli** [comment]
Yes, it seems to work now. When I opened the ticket more than 3 weeks ago, I remember we had conducted some testing before creating it. The "persistent feed menu selection across sessions" seems like a nice feature to have.

**Comment by daniloercoli** [comment]
Hey @thomashorta - I found out steps to constantly reproduce the problem:
* Go to the Reader and select `Subscription`
* Tap on Blogs and select one of your subscribed blogs
* Wait until the single blog feed is loaded into the app, and tap the Back button (or the Back arrow)
* Notice the app is sent to background
* Tap on the JP icon, and the app is started on the Discover feed

**Comment by thomashorta** [comment]
> - Wait until the single blog feed is loaded into the app, and tap the Back button (or the Back arrow)
> - Notice the app is sent to background

Although a bit weird, note that this Back button press causes the app to be finished, so the next open is a cold start, so it's the same as killing the app from the Recent Apps list.

I have a branch with the selected feed persistence and it fixes this scenario as well.

Just a quick note that the current Filter selection will not be saved because it's way more complex (there's no good way of doing it right now) AND I honestly don't see the value of keeping a single Blog/Tag filter persist across app "sessions".
