### ISSUE TITLE
Offline Mode: Backups and Revisions

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-Android#20166]
## Tasks
- [ ] If the post is restored from a backup or a revision, accept the remote revision and discard the local changes

**Comment by pantstamp** [comment]
Weird bug related to the autosave and the conflict resolution discovered:

The scenario that I was trying is this:

- Edit post on app

- Back out to save local changes

- Go to web, edit same post (I do see the autosave message) and update it

- In the app, tap on the post to edit

- The post opens for edit with the local changes

The issue I’ve identified is as follows: There’s a noticeable difference in behavior when a user keeps the app active on their phone while simultaneously accepting the auto-save feature on the web, compared to when they close the app and then accept the auto-save on the web.

**1st case: User keeps the app open**
Check the recording [here](https://drive.google.com/file/d/1NdQrDWgVvvM2IUIaJvAE0tlB2xxAHNZe/view?usp=drivesdk)
You will notice that when the auto-save is accepted from the web, users open the post in the editor, tap on “Update,” and then the update fails with a “Version Conflict” message. If the user taps again on the post, the post conflict dialog appears, and they select “Discard local.” The process is completed without any problems.

**2nd case: User closes the app and after auto-save is accepted on web they relaunch it**
Check the recording [here](https://drive.google.com/file/d/1Ne3lYtzLyPyAfglD_GoZdi-4GLUG_Sac/view?usp=drivesdk)
You will notice that the user follows the same steps, but when they select “Discard local,” the message “You’ve made unsaved changes to this post” appears. Upon tapping on the post again, the dialog “Which version would you like to edit?” is displayed, which can be very confusing since the user has already resolved the conflict.

I was convinced that it is a bug that was added by the latest changes. Here are my findings:

1. User taps “Discard Local” and the PostConflictResolver.updateConflictedPostWithRemoteVersion() is called.
2. dispatcher.dispatch(PostActionBuilder.newFetchPostAction(RemotePostPayload(post, site))) is called.
3. PostStore.fetchPost() is called
4. A GET call is executed to fetch the post.
5. The post that is fetched is saved on the database with the PostSqlUtils.insertOrUpdatePost()

Between the 2 cases I noticed this difference. Here are some logs.

**1st case: User keeps the app open**
updateConflictedPostWithRemoteVersion() entered
updateConflictedPostWithRemoteVersion(): **post before edit** ->isLocallyChanged = true, autoSaveExcerpt = null, **autoSaveRevisionId = 585**
updateConflictedPostWithRemoteVersion() newFetchPostAction ready to be sent
onPostSuccessfullyUpdated(): **post after update** ->isLocallyChanged = false, autoSaveExcerpt = null, **autoSaveRevisionId = 0**
updateConflictedPostWithRemoteVersion(): conflictedPostUpdatedWithRemoteVersion ready to be called

**2nd case: User closes the app and after auto-save is accepted on web they relaunch it**
updateConflictedPostWithRemoteVersion() entered
updateConflictedPostWithRemoteVersion(): **post before edit** ->isLocallyChanged = true, autoSaveExcerpt = null, **autoSaveRevisionId = 589**
updateConflictedPostWithRemoteVersion() newFetchPostAction ready to be sent
onPostSuccessfullyUpdated(): **post after update** ->isLocallyChanged = false, autoSaveExcerpt = , **autoSaveRevisionId = 589**
updateConflictedPostWithRemoteVersion(): conflictedPostUpdatedWithRemoteVersion ready to be called

What we see here is that the updated post that we save in the database has different values for the autoSaveRevisionId between the two cases, and since it is > 0 on the 2nd case the

```
@Override
public boolean hasUnpublishedRevision() {
    return mAutoSaveRevisionId > 0;
}
```
returns true and so does the

```
public static boolean hasAutoSave(PostModel post) {
    // TODO: would be great to check if title, content and excerpt are different,
    // but we currently don't have them when we fetch the post list

    // Ignore auto-saves in case the post is locally changed.
    // This might be changed in the future to show a better conflict UX.
    return !post.isLocallyChanged()
           // has auto-save
           && post.hasUnpublishedRevision();
}
```

After investigating this further, I found something that I cannot explain.

When we try to fetch the post, we execute the exact same GET call on both cases, for example:
https://public-api.wordpress.com/rest/v1.1/sites/227972612/posts/628/?meta=autosave&context=edit&locale=en_US

The responses that we get from the backend are slightly different:

**1st case: User keeps the app open**

`{"ID":628,"site_ID":227972612,"author":{"ID":213211381,"login":"pantelisstampoulis","email":"pantelis.stampoulis@automattic.com","name":"pantelisstampoulis","first_name":"Pantelis","last_name":"Stampoulis","nice_name":"pantelisstampoulis","URL":"","avatar_URL":"https:\/\/secure.gravatar.com\/avatar\/7882326274326311bf439c5da7b99bed?s=96&d=identicon&r=g","profile_URL":"https:\/\/gravatar.com\/7882326274326311bf439c5da7b99bed"},"date":"2024-04-09T19:54:20+03:00","modified":"2024-04-09T19:55:30+03:00","title":"test","URL":"https:\/\/pantelisstampoulis.com\/2024\/04\/09\/test\/","short_URL":"https:\/\/wp.me\/sfqy5C-test","content":"<!-- wp:paragraph -->\n<p>1<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local <\/p>\n<!-- \/wp:paragraph -->","excerpt":"","slug":"test","guid":"https:\/\/pantelisstampoulis.com\/?p=628","status":"publish","sticky":false,"password":"","parent":false,"type":"post","discussion":{"comments_open":true,"comment_status":"open","pings_open":true,"ping_status":"open","comment_count":0},"likes_enabled":true,"sharing_enabled":true,"like_count":0,"i_like":false,"is_reblogged":false,"is_following":true,"global_ID":"21bbd2146299747ebc2851c17b6ed142","featured_image":"","format":"standard","geo":false,"menu_order":0,"page_template":"","publicize_URLs":[],"terms":{"category":{"Uncategorized":{"ID":1,"name":"Uncategorized","slug":"uncategorized","description":"","post_count":1,"parent":0,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612"}}}},"post_tag":{},"post_format":{}},"tags":{},"categories":{"Uncategorized":{"ID":1,"name":"Uncategorized","slug":"uncategorized","description":"","post_count":1,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612"}},"parent":0}},"attachments":{},"attachment_count":0,"metadata":[{"id":"1824","key":"_wpas_done_all","value":"1"}],"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612","replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/replies\/","likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/likes\/"}},"capabilities":{"publish_post":true,"delete_post":true,"edit_post":true},"revisions":[631,629],"other_URLs":{}}`

**2nd case: User closes the app and after auto-save is accepted on web they relaunch it**
`{"ID":628,"site_ID":227972612,"author":{"ID":213211381,"login":"pantelisstampoulis","email":"pantelis.stampoulis@automattic.com","name":"pantelisstampoulis","first_name":"Pantelis","last_name":"Stampoulis","nice_name":"pantelisstampoulis","URL":"","avatar_URL":"https:\/\/secure.gravatar.com\/avatar\/7882326274326311bf439c5da7b99bed?s=96&d=identicon&r=g","profile_URL":"https:\/\/gravatar.com\/7882326274326311bf439c5da7b99bed"},"date":"2024-04-09T19:54:20+03:00","modified":"2024-04-09T19:58:48+03:00","title":"test","URL":"https:\/\/pantelisstampoulis.com\/2024\/04\/09\/test\/","short_URL":"https:\/\/wp.me\/sfqy5C-test","content":"<!-- wp:paragraph -->\n<p>1<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local <\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local2<\/p>\n<!-- \/wp:paragraph -->","excerpt":"","slug":"test","guid":"https:\/\/pantelisstampoulis.com\/?p=628","status":"publish","sticky":false,"password":"","parent":false,"type":"post","discussion":{"comments_open":true,"comment_status":"open","pings_open":true,"ping_status":"open","comment_count":0},"likes_enabled":true,"sharing_enabled":true,"like_count":0,"i_like":false,"is_reblogged":false,"is_following":true,"global_ID":"21bbd2146299747ebc2851c17b6ed142","featured_image":"","format":"standard","geo":false,"menu_order":0,"page_template":"","publicize_URLs":[],"terms":{"category":{"Uncategorized":{"ID":1,"name":"Uncategorized","slug":"uncategorized","description":"","post_count":1,"parent":0,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612"}}}},"post_tag":{},"post_format":{}},"tags":{},"categories":{"Uncategorized":{"ID":1,"name":"Uncategorized","slug":"uncategorized","description":"","post_count":1,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/categories\/slug:uncategorized\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612"}},"parent":0}},"attachments":{},"attachment_count":0,"metadata":[{"id":"1824","key":"_wpas_done_all","value":"1"}],"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612","replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/replies\/","likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/likes\/","autosave":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/autosave"},"data":{"autosave":{"ID":634,"author_ID":"213211381","post_ID":628,"title":"test","content":"<!-- wp:paragraph -->\n<p>1<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local <\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local2<\/p>\n<!-- \/wp:paragraph -->","excerpt":"","preview_URL":"https:\/\/pantelisstampoulis.com\/2024\/04\/09\/test\/?preview=true&preview_id=628&preview_nonce=90ed0db4e7","modified":"2024-04-09T19:59:22+03:00"}}},"capabilities":{"publish_post":true,"delete_post":true,"edit_post":true},"revisions":[634,633,631,629],"other_URLs":{}}`

The difference is in the meta field.

**1st case: User keeps the app open**
```
"meta":{
   "links":{
      "self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628",
     "help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/help",
     "site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612",
     "replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/replies\/",
     "likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/likes\/"
   }
}
```

**2nd case: User closes the app and after auto-save is accepted on web they relaunch it**

```
"meta":{
   "links":{
      "self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628",
      "help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/help",
      "site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612",
      "replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/replies\/",
      "likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/likes\/",
      "autosave":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/227972612\/posts\/628\/autosave"
   },
   "data":{
       "autosave":{
           "ID":634,
           "author_ID":"213211381",
           "post_ID":628,
           "title":"test",
          "content":"<!-- wp:paragraph -->\n<p>1<\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local <\/p>\n<!-- \/wp:paragraph -->\n\n<!-- wp:paragraph -->\n<p>Local2<\/p>\n<!--    \/wp:paragraph -->",
         "excerpt":"",
         "preview_URL":"https:\/\/pantelisstampoulis.com\/2024\/04\/09\/test\/?preview=true&preview_id=628&preview_nonce=90ed0db4e7",
         "modified":"2024-04-09T19:59:22+03:00"
      }
   }
}

```

So, we call the exact same call with the same params but in the 1st case, we do not get the meta.data object.

**Comment by pantstamp** [comment]
Update: 

When Error occurs:
`18:50:50.642 D postLocalChangesAlreadyRemoteAutoSaved() called for post: Test100, getAutoSaveModified = 2024-04-10T18:50:49+03:00, getDateLocallyChanged = 2024-04-10T15:50:49+00:00, returned false`

Error does not occur:
`18:50:05.454 D postLocalChangesAlreadyRemoteAutoSaved() called for post: Test100, getAutoSaveModified = 2024-04-10T18:50:04+03:00, getDateLocallyChanged = 2024-04-10T15:50:03+00:00, returned true`

My theory is the following:

getAutoSaveModified and getDateLocallyChanged values are changing one after the other in a matter of milliseconds.

When we call this:
```
public static boolean postLocalChangesAlreadyRemoteAutoSaved(PostImmutableModel post) {
    return !TextUtils.isEmpty(post.getAutoSaveModified())
           && DateTimeUtils.dateFromIso8601(post.getDateLocallyChanged())
                           .before(DateTimeUtils.dateFromIso8601(post.getAutoSaveModified()));
}
```

We compare timestamps that contain only seconds not milliseconds. So we may end up with a case where getAutoSaveModified and getDateLocallyChanged have the same value (if you check above 18:50:49+03:00 15:50:49+00:00 is actually the same).

So even when the auto-save is actually successful,` postLocalChangesAlreadyRemoteAutoSaved(PostImmutableModel post)` might return false.

I will check if we could add milliseconds on those fields or we call the

```
public void setDateLocallyChanged(String dateLocallyChanged) {
    mDateLocallyChanged = dateLocallyChanged;
}
```
in places that we should not.

Otherwise we might need to think a better implementation of `postLocalChangesAlreadyRemoteAutoSaved(PostImmutableModel post)`
