### ISSUE TITLE
[Notifications] Can't see share icon in dark mode

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-Android#20285]
### Expected behavior
Share icon should be visible regardless of dark/light mode

### Actual behavior
Almost impossible to see share mode
![Screenshot_20240223-145627](https://github.com/wordpress-mobile/WordPress-Android/assets/103850310/97ae4e60-f3b4-4314-8d8a-353cf7738cb1)

### Steps to reproduce the behavior
Generate a notification for a post you own (have another account like it, e.g.)
In the Jetpack app, go to Notifications and look at that notification in dark and light mode
Note the dark mode version is black (on a black background) so you can't see it

##### Tested on Google Pixel 7, Android 13, JPAndroid / WPAndroid version from https://github.com/wordpress-mobile/WordPress-Android/pull/20072

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
Testing with the latest version of the app we were not able to reproduce the issue. Since the share icon on the issue screenshot is an older one we believe that this was an issue with an earlier version.

|Light mode|Dark mode|
|---|---|
|![Screenshot_20240226_111145](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/18cb515a-8950-41cc-8aaf-9eb0024e31d9)|![Screenshot_20240226_111232](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/e49f6831-ff4a-4e2a-8e14-c96df9693916)|
