### ISSUE TITLE
Optimize stats_accessed event

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-Android#20398]
```[tasklist]
### Tasks
- [x] `StatsLaunchedFrom.JETPACK_CONNECTION` value should be removed from `tap_source` property of `stats_accessed`. Instead, `tap_source` should be set to other `StatsLaunchedFrom` values based on where stats is launched from. _(Related comment: https://github.com/wordpress-mobile/WordPress-iOS/issues/22594#issuecomment-1959500292)_
- [x] All entry points to stats in [ActivityLauncher](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/ui/ActivityLauncher.java) should be reviewed to ensure that they track the `stats_accessed` event with the correct `tap_source` property.
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by aditi-bhatia** [comment]
Hi @irfano, sorry if this is an obvious question, what are the steps I should follow to trigger the `StatsLaunchedFrom.JETPACK_CONNECTION` event?

**Comment by irfano** [comment]
Thanks for working on this, @aditi-bhatia! You can check the testing instructions for `jetpack_connection` at https://github.com/wordpress-mobile/WordPress-Android/pull/20194.

**Comment by aditi-bhatia** [comment]
Hi @irfano thank you 👍 Just to double check, it should be fine to replace `StatsLaunchedFrom.JETPACK_CONNECTION` with `QUICK_ACTIONS`? 

- In the app, the Jetpack connection prompt only appears in `My Site -> Stats` (which is tap_source: `QUICK_ACTIONS`) or from `notifications`.  
- The only place `JETPACK_CONNECTION` is used is line 145 of JetpackConnectionResultActivity, where `mSource == JetpackConnectionSource.STATS`. 
- It seems like the only way Stats can be launched after a Jetpack connection is via `My Site -> Stats` (it's not launched after connecting Jetpack via `notifications`). 

Just wanted to do a confidence check since the ticket description mentioned `Instead, tap_source should be set to other StatsLaunchedFrom values based on where stats is launched from.` but there only seems to be one way that stats is launched from a Jetpack connection. Thanks again!

**Comment by irfano** [comment]
🤔 Good call @aditi-bhatia! Actually we can also launch stats from `shortcut` and `link` but that flow is broken. I'm sharing the video here and will open an issue for it. 

> it should be fine to replace StatsLaunchedFrom.JETPACK_CONNECTION with QUICK_ACTIONS

Yes, I agree. 

https://github.com/wordpress-mobile/WordPress-Android/assets/2471769/d575fd2b-fdaf-4faa-bbea-9e0aceb811c7

**Comment by aditi-bhatia** [comment]
Hi @irfano, I'm working on verifying the second portion of this task and had a few questions:
1. When I try to launch stats from `notifications` using the debug notification steps https://github.com/wordpress-mobile/WordPress-Android/pull/20194, I don't get a roundup notification. Is there something else I need to do in order to get one?
2. I couldn't find a way to access Stats from the `activity log`. I noticed Povilas had the same issue in the steps here: https://github.com/wordpress-mobile/WordPress-Android/pull/20194. Have we found a way to test this?

Besides the two entry points above, I've tested all other entry points and they have the correct `tap_source` property.

**Comment by irfano** [comment]
> Is there something else I need to do in order to get one?

I am using the Jetpack Wasabi variant with enabled notification permission, and I can receive a roundup notification. Are you using the same settings?

> Have we found a way to test this?

I still don't know. However, we can skip it for this issue because I've already handled it in #20194 and decided that the implementation is correct even though I couldn't test it.

**Comment by aditi-bhatia** [comment]
Hmm, I've been using `Jetpack Jalapeno Debug` with enabled notification permissions (both app and system), but I can try to see if Wasabi is any different

**Comment by aditi-bhatia** [comment]
Ah okay, I tried again a few more times and reinstalled the app as well. I'm finally seeing the notification and the event works as expected 👍 I'll go ahead and mark the second item as resolved + resolve this ticket as well
