### ISSUE TITLE
Notifications: Lollipop transition animation?

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2140]
Was thinking it'd be cool to do a shared element transition for notifications using the avatar (which is displayed in both the list and detail views)

**Comment by oguzkocer** [comment]
I've experimented with this today a bit to see how easy it'd be to just add it. But, due to the complicated nature of how notification activities & fragments setup, I couldn't make it work, at least not in a short time frame. I was going to suggest us to take another look in the `Notifications Refresh` project, but it looks like it's already added there. /cc @mzorz

**Comment by mzorz** [comment]
Thank you @oguzkocer ! Will probably start with the beautifying aspects within the `Notifications Refresh` after we're finished with the major stuff. Good to know it's not as easy as it seemed 😁

**Comment by oguzkocer** [comment]
@mzorz Maybe it's and I just missed. In any case, do let me know if I can help out with it. And I'd appreciate a /cc in the PR if you end up adding this feature. I am curious to see how the complicated fragment/activity setup we have affects it.
