### ISSUE TITLE
ANR on the Notification screen

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2158]
https://github.com/Simperium/simperium-android/issues/167

**Comment by rachelmcr** [comment]
I haven't been able to reproduce this yet on my Nexus 7, running Android 5.1.1. A few notes about the issue as described by a user:
- It happens when tapping on a notification and trying to scroll (in the detail view, not the main list)
- The initial scroll usually works but then the app gets stuck as you try to scroll further
- The ANR isn't consistently reproducible

**Comment by mzorz** [comment]
Closing this one as per the changes that have just landed on `develop` (removed simperium and pretty much the central part of notifications underlying flows arch has changed - #4661 )
