### ISSUE TITLE
Toggle arrows should be to the very left always

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2199]
Just to keep it consistent, toggle arrows should be to the very left always, unless there’s a prominent Android UI pattern that dictates them to be in another location.

https://cloudup.com/cdMVhmHgoWo

**Comment by daniloercoli** [comment]
Moving the toggle arrow to the very left of the row ends up in a screen like the one below:

![screen shot 2015-01-20 at 12 11 32](https://cloud.githubusercontent.com/assets/518232/5816160/a33ab6ce-a09d-11e4-96d4-df5d850f05c0.png)

On the web there is a "open external" icon where the toggle is not available:

![screen shot 2015-01-20 at 12 12 50](https://cloud.githubusercontent.com/assets/518232/5816191/1e64b7fa-a09e-11e4-8dbf-9ce47cc71b9e.png)

I'm not sure we should add that icon to Android, since it means open the URL in a external browser, instead we're loading the URL in the in-app web browser, without launching the default web browser of the device.

Any idea @jancavan

**Comment by jancavan** [comment]
@daniloercoli The arrows are for the ones that contain a sublist. Those that don't have a sublist don't have arrows. I would much rather have it open in app so users can easily go back to their Stats vs having to go back to the WordPress app from their mobile browser.

I agree on the new browser icon, but please move them to the left and change them to link icons instead. Please refer to this mockup below.

![links](https://cloud.githubusercontent.com/assets/4924246/5822475/4c7462ae-a089-11e4-8de0-2d2450a737b9.png)

**Comment by daniloercoli** [comment]
@jancavan That looks good, but we need the new "Link" icons at different resolutions. 
24x24 - 32x32 - 48x48 - 64x64

**Comment by daniloercoli** [comment]
@jancavan I've created and added 3 placeholder files that are needed to show the link icon. 
Here you can find a preview (don't take in consideration the icon link that is just a placeholder)
https://cloudup.com/ceDIQKIFwJL

Should we show the link icon, even on those modules that don't expand? See the 4th picture in the gallery, that shows Top posts and Pages module. I vote to not show link icons there, since we can save space, and use the whole space of the row for the title.


p.s: I'm working on this branch for major UI updates:
https://github.com/wordpress-mobile/WordPress-Android/compare/issue/2208-Stats-UI-tweeks

Placeholder icons are available here:
https://github.com/wordpress-mobile/WordPress-Android/blob/3d028681ddd7ac5bcb153201a68bb1350ff68c33/WordPress/src/main/res/drawable-hdpi/stats_link.png
https://github.com/wordpress-mobile/WordPress-Android/blob/3d028681ddd7ac5bcb153201a68bb1350ff68c33/WordPress/src/main/res/drawable-xhdpi/stats_link.png
https://github.com/wordpress-mobile/WordPress-Android/blob/3d028681ddd7ac5bcb153201a68bb1350ff68c33/WordPress/src/main/res/drawable-xxhdpi/stats_link.png

**Comment by jancavan** [comment]
@daniloercoli no, please only use the link icons for Referrers and Clicks since only those 2 modules have expandable sublists. Here are the icons. The Post & Pages module doesn't need them.

![hdpi-stats_link](https://cloud.githubusercontent.com/assets/4924246/5860717/36375830-a218-11e4-9c6d-ab4df07d2017.png)
![xhdpi-stats_link](https://cloud.githubusercontent.com/assets/4924246/5860716/3634be86-a218-11e4-89b6-b248f47ee4fc.png)
![xxhdpi-stats_link](https://cloud.githubusercontent.com/assets/4924246/5860718/3639c93a-a218-11e4-833a-1f50fee89fc8.png)

**Comment by daniloercoli** [comment]
Below a preview:

![screen shot 2015-01-22 at 18 43 57](https://cloud.githubusercontent.com/assets/518232/5861127/bd3975a4-a266-11e4-8c9c-ecab5ce8483e.png)

**Comment by jancavan** [comment]
@daniloercoli I have tried replacing the files in Finder, but for some reason, they seem like they're being auto-resized? I have replaced them in WordPress > src > main > res

**Comment by jancavan** [comment]
I've resized stats_link.png with the base size in 21x21 (hdpi), 28x28 (xhdpi) and 42x42 (xxhdpi). I used this formula you provided px = dp * (dpi / 160).

I did a test and because the stats_link icon has quite a thin stroke, it works better in 14dp while keeping the chevron icons at 12dp. This is how it will look like:

![chevron-12dpi-link-14dpi](https://cloud.githubusercontent.com/assets/4924246/5926064/045e2a1a-a61d-11e4-9633-30158d58ca91.png)

**Comment by jancavan** [comment]
@daniloercoli Here are the icons:

![stats_link](https://cloud.githubusercontent.com/assets/4924246/5926756/600e5e2a-a622-11e4-8dd3-282d30af699a.png)
![stats_link](https://cloud.githubusercontent.com/assets/4924246/5926760/63fd758e-a622-11e4-833a-4d6a702a7d8e.png)
![stats_link](https://cloud.githubusercontent.com/assets/4924246/5926761/66d969b6-a622-11e4-8f0a-78605dcd4651.png)
