### ISSUE TITLE
Malformed stats pseudo-tabs with certain translations

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2230]
I've just noticed that while browsing the french version:
![screenshot_2015-01-20-17-03-59](https://cloud.githubusercontent.com/assets/40213/5828473/9734d744-a0d2-11e4-9b42-364be310f5c8.png)

**Comment by daniloercoli** [comment]
There isn't an easy fix for this issue due to the way that labels are created. 
A quick solution is shown below:
![screen shot 2015-01-21 at 01 03 15](https://cloud.githubusercontent.com/assets/518232/5828812/4f315170-a109-11e4-86e6-a85e5528ade1.png)


Since we've a ticket for this area of the UI in 3.8, I think we can use the simple solution shown above, and fix the problem in 3.8 when we introduce icons there.
