### ISSUE TITLE
Minor UI updates for 3.8

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2297]
- Module tab behavior is reversed. Active tab should be solid while inactive tab should be hollow: 

![tabs](https://cloud.githubusercontent.com/assets/518232/6050689/04d78c1a-acc2-11e4-9d66-1ac8f33ac5e7.jpg)

- Add a bit more space after column title:

![space](https://cloud.githubusercontent.com/assets/518232/6050702/1807d43e-acc2-11e4-8344-cf57680ec656.jpg)

**Comment by daniloercoli** [comment]
@jancavan - I've corrected the color issue on tabs. See the picture below:
![screen shot 2015-02-05 at 08 24 21](https://cloud.githubusercontent.com/assets/518232/6056401/bf4cd0c0-ad10-11e4-9798-c7398414022c.png)

Noticed that the web version uses the reversed selection. Hollow for the active tab, solid blue light for the inactive tab:
![screen shot 2015-02-05 at 08 29 08](https://cloud.githubusercontent.com/assets/518232/6056423/1a42d8a8-ad11-11e4-82bc-d5fa8aceb868.png)

**Comment by jancavan** [comment]
@daniloercoli This is okay. On the web version, the selected button has some kind of inner shadow so it looks like it's being depressed while the normal state is a bit raised (so it looks like it's not being pressed down). But since on the Android UI both buttons are flat, there's no other way to tell other that the color - and it's more obvious that solid color means it's selected while hollow means deselected.

**Comment by daniloercoli** [comment]
@jancavan - Ok, let's implement these changes then.

FYI - Those buttons are something I came up with for the first iteration of Calypso Stats, and we were in a sort of rush. Feel free to redesign them bottom-up, and I will implement them in 3.9, or 3.8 if changes are small.
