### ISSUE TITLE
Reader empty blog message shows on failure

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2325]
In blog preview, if the request to get the posts for a blog fails the user sees a message saying "this blog is empty." It should instead say that the posts could not be loaded.

![screen_shot_2015-02-13_at_18 36 03](https://cloud.githubusercontent.com/assets/3903757/6192271/248cd85e-b37e-11e4-9e0e-6d4db3e386ee.png)

**Comment by daniloercoli** [comment]
We should probably intercept these kind of errors also in `loadBlogOrFeedInfo`, otherwise calling  `ReaderActivityLauncher.showReaderBlogPreview` from other places, like Stats, will not show the correct network errors.


Would you mind to squeeze the following simple change in this PR ?
https://gist.github.com/cf06dfcf04de24df23a2.git
