### ISSUE TITLE
Reader: Lag when loading detail view

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2461]
There appears to be a lag when loading the reader detail view for private posts that contain images, either in the post or in another post that is being loaded in the view pager.

It looks to be a block in the ReaderWebView here: https://github.com/wordpress-mobile/WordPress-Android/blob/17c21cd85975cd4872c9d7f53af1e7183cb428de/WordPress/src/main/java/org/wordpress/android/ui/reader/views/ReaderWebView.java#L221-L229

The docs say that `shouldInterceptRequest()` is run on a non-ui thread.

**Comment by nbradbury** [comment]
[Possibly related](https://code.google.com/p/android/issues/detail?id=67640)

**Comment by roundhill** [comment]
I think that is indeed the case. The multiple WebViews that are used in the ViewPager are competing for the Webkit thread.

Some ideas:
* See if there's some way to increase the amount of concurrent threads for the WebView.
* Don't pre-load off-screen pages in the ViewPager for private posts. Or maybe don't start loading it until the currently-viewing page has completed loading.
* Go back to the old method where we get the login cookie for the WebView :(

**Comment by nbradbury** [comment]
Using a [pooling connection manager](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html) with the DefaultHttpClient may resolve this. See section 2.8.4 on [this page](http://hc.apache.org/httpcomponents-client-4.2.x/tutorial/html/connmgmt.html) for details.

We could also benefit from re-using the http client rather than creating a new one for each request. That was something Apache [recommended for v3](http://hc.apache.org/httpclient-3.x/performance.html#Reuse_of_HttpClient_instance) and I assume it's still valid.

**Comment by nbradbury** [comment]
Closed via #2473
