### ISSUE TITLE
Remove wpid at the front of image URLs

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#2620]
An Android user would like to be able to remove the wpid at the front of image URLs. 

Reasons:
1) SEO
2) it looks ugly.

**Comment by rachelmcr** [comment]
From issue #2946:

The only thing that stops me from using the WordPress App instead of Desktop browser is that image files are always uploaded with names like `wpid-<date>_<time>.jpg`, e.g. wpid-20150624_152545.jpg to wordpress media.

So whatever SEO sensitive filename I pick for an image (I rename them earlier using another app), the WordPress Android app always overrides the name with this "meaningless" id. Afterwards there is no way of renaming the image filename in the app.

So during travelling I use the app to create blog posts, which I then afterwards I have to manually swap all the images just to have them with proper names.

I think there whould be an easy solution:
a) Either just use the original image filename and do not change it to `wpid-<date>_<time>.jpg`
b) Add a way one can edit the image filename during uploading it

**Comment by rachelmcr** [comment]
We received another complaint about the app changing image filenames in an app review. It would be great to have some way to retain the original filename if the file has been purposefully named.

**Comment by rachelmcr** [comment]
A user in 155691-h noted that she wants the original file name to be retained because she finds that searching the media library by name is easier than scrolling through the media library for a specific image.

**Comment by maxme** [comment]
Added the `fluxc-obsolete`  label - I just fixed it in the `fluxc-integration` branch. The app now tries to read the original filename from the source, and default to `wp-121213.xxx` only if it can't be read (data stream for instance).

**Comment by oguzkocer** [comment]
@maxme this is tagged with `fluxc-obsolete` and you mentioned you fixed it a while ago. Should we close this?

**Comment by aforcier** [comment]
Confirming this can be closed, I'm fixing a bug with that change right now 😉 (and the behavior is as @maxme describes).

**Comment by oguzkocer** [comment]
Thanks @aforcier 👍
