### ISSUE TITLE
Default Media Width

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-Android#2819]
Currently you are only able to update the default media width by selecting static amounts from a drop down list.

Are we able to change it so it is either more like the slider option in iOS so that you can have finer control or a field to enter in the exact amount you want?

**Comment by daniloercoli** [comment]
Unfortunately there isn't a slider component/widget in the Android Preference kit. You can use sliders https://material.io/guidelines/components/sliders.html#sliders-discrete-slider in the default UI kit, but not in Preference screens.

The only way is to add additional 3rd party libraries. Closing this issue for now, since we don't want to introduce another library for just this simple thing, maybe a text field where the user can insert the right dimension can be fine, but it doesn't seem a urgent feature for now. We will re-iterate on this topic again in the future and probably shuffling thing around.
