### ISSUE TITLE
WordPress.getBlog and WordPress.getCurrentBlog could love a refactor

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2838]
`WordPress.getBlog` - There is a catch `Exception` without any logging. Wonder why if is possibile to be less generic on the type of Exception catched there.

`WordPress.getCurrentBlog` - Does check the visibility of the blog before returning the blog. Is it really necessary? Why I cannot have a current blog set in the app even if it was hidden? 
Sometimes I want to access the blog, check the stats, etc, even if it's hidden in the app. Thinking to the situation where you open the app from a notification, read the notification, and want to check stats or other things on the blog.

**Comment by maxme** [comment]
That being said, `WordPress.getCurrentBlog()` reflects the current blog which has been selected in the Blog Selector view. This [check](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L409-409) ensures the blog exist and is visible (blog could be deleted or hidden from the Web), because if we don't have a visible blog selected, activities / fragments that depends on it will start to have weird behavior or crash.

In a perfect app, `WordPress.getCurrentBlog()` would not exist at all. We should have the selected blog state stored in the "root" activity (`WPMainActivity` currently) and pass that as a parameter to "child" activities / fragments / services. That would allow us to have multiple instances of the same activity (Comments, Post LIst or Stats for instance). In that perfect app, we would update that state when we:  
* Start the root activity
* Update blogs from the server 
* When we use the Blog Selector.

> Sometimes I want to access the blog, check the stats, etc, even if it's hidden in the app. 

I guess this is not a use case for `getCurrentBlog()` in that case.

**Comment by daniloercoli** [comment]
It's just the name of the function `WordPress.getCurrentBlog()` that leads me to think we can rename it to something more descriptive, like `WordPress.getCurrentVisibleBlog()`. Anyway that' s not a big deal, we can keep as it's right now.
Side note: `setCurrentBlog` can be called on "non-visible" blogs.

I'm going to close this and open a new ticket for the missing logging in getBlog.
