### ISSUE TITLE
Do away with "local changes" limitation in the post list refresh

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2983]
Right now the post list silently skips the automatic refresh if local changes exist, since those local changes would be overwritten during the refresh. This means that new posts will never appear during an automatic refresh if there are local changes.

If the refresh was due to the user initiating a pull-to-refresh, the user is presented with this unfriendly dialog:

![device-2015-07-16-165501](https://cloud.githubusercontent.com/assets/3903757/8735075/1b8b80bc-2bdc-11e5-8213-cd0f19d513e4.png)

Assuming the user understands this dialog, it means we're asking them to choose between seeing new posts and overwriting ones with changes that haven't been uploaded.

The post list should be smart enough to preserve local changes after a refresh, doing away with the need for this dialog and the need to skip automatic refresh if there are local changes.

**Comment by nbradbury** [comment]
Comparing timestamps isn't going to work, but perhaps this alternative approach will:

1. Before updating, retain a list of posts with local changes
2. After updating, save those local changes back to the db, replacing the server versions
3. Visually differ changed posts in the list and provide a way to revert to server version

**Comment by nbradbury** [comment]
Work is underway in [this branch](https://github.com/wordpress-mobile/WordPress-Android/tree/issue/2983-local-changes).

**Comment by aerych** [comment]
Suppose a user starts editing in the app, stops, and saves local changes. Later the user updates the post via some other editor. 

> 2. After refreshing posts, restore those local changes

Meaning the sync is ignored for the locally edited post and it remains in the state it was prior to the sync with the local changes. 

> 3. Provide a "revert" button in the post list which overwrites local changes with latest version of the post from server (should be undo-able)

How is a user likely to interpret this? What are they reverting to? Is the post going to go back to the way it was before the local edits? Will it be updated to what is currently on their blog (synced).  This seems like a likely point of confusion. 

> 4. This revert button would replace the trash button for posts with local changes. 

That might a little hidden for users on small screens when the trash button is hidden behind the more button.   

What happens if the user edits the post again from the app? Are they prompted that doing so will loose the changes on the web? 

Would it make sense to have something new in the UI that explicitly says "discard local changes"? 

Sorry, I'm full of questions. 

cc @bummytime

**Comment by nbradbury** [comment]
> Meaning the sync is ignored for the locally edited post and it remains in the state it was prior to the sync with the local changes.

Right, which isn't ideal but consider that the existing implementation also keeps it in the state prior to the sync *and* fails to show any other changes (including new posts).

> What happens if the user edits the post again from the app?

Same as currently happens - they're editing the post as it exists locally, without changes from the server.

> How is a user likely to interpret [a revert button]? What are they reverting to?...Would it make sense to have something new in the UI that explicitly says "discard local changes"?

Hmm, I assumed "revert" would be self-explanatory, but I see your point - it could be confusing to some, and a "discard changes" item would be much better. My ideal design would be to drop the flipping rows of icons, have only "Edit" and "View" visible at all times, and put the rest under the `...` more icon (where there would be enough space for "Discard changes"). For now, though, I still think this is a big improvement over how it currently works (but I am, of course, open to suggestions).

**Comment by nbradbury** [comment]
Update: thanks to a great suggestion by @aerych, the "revert" button wouldn't exist on the post card, but instead on the post detail (preview). This way the user would be clear about what they're reverting.

This would work best as part of #2997.
