### ISSUE TITLE
Tiny vertical images in reader post detail

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3068]
I created a gallery post in the wp.com editor, and noticed that the android reader displayed the vertical images very small:

https://cloudup.com/c3EJ55-0WkT

http://danroundhill.com/2015/08/13/aberdeens-star-wars-shop/

Assigned to you @nbradbury :)

**Comment by oldcwj** [comment]
Nexus 7
![screenshot_2015-08-29-15-52-27](https://cloud.githubusercontent.com/assets/262734/9561059/600e2c4a-4e68-11e5-8210-6b7417d5f396.png)

ReaderPostRenderer.java->replaceImageTag(final String imageTag, final String imageUrl)
There are four cases(isFullSize, isMidSize, hasWidth, other), only (isFullSize) is true which use screen width, (isMidSize,hasWidth and other) use self width, so that is the problem, screen width and image`s width are not have relationship(like scale),so (isMidSize, hasWidth) are too small.

**Comment by rachelmcr** [comment]
I confirmed that this is still an issue in the latest beta (5.0-rc-2). It would be great to improve this detail view for galleries as part of #1719 (along with adding support in the list view).

**Comment by hypest** [comment]
Fixed with #4222 . Closing.
