### ISSUE TITLE
Tapping back while logging into wpcom doesn't stop the underlying connections...

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3227]
...and left the app in a weird state. 

Steps to repro:
- Suppose you're already logged to wpcom in the app.
- Open the app and go to me ME tab.
- Tap on "Disconnect", confirm, and wait few secs.
- Tap on "Connect to WordPress.com", insert the username, the password and tap on "Sign In".
- Tap back while there is still the loading indicator going.
- The app takes you back to the ME screen. 
- Wait few secs.
- Tap on "Connect"...and BOOM! You're already logged to wpcom.

![login-logout](https://cloud.githubusercontent.com/assets/518232/10050215/913202c6-621b-11e5-93a9-b500c2d0475d.gif)

**Comment by rachelmcr** [comment]
Tested with the steps above and confirmed that this is still an issue in 4.8-rc-3. (Tested on Nexus 9, Android 6.0.)

**Comment by daniloercoli** [comment]
I can reproduce a kind of similar issue on the first login screen, where tapping back doesn't stop connections. When you reopen the app it's in an half state, you're logged with no blogs, and some  "wpcom" features are missing.

**Comment by aforcier** [comment]
Still a problem after FluxC - depending on your timing, you might be fully logged in with everything working if you press back during login. Otherwise, you might end up with a 'half state', which resolves itself if you dismiss and re-open the app (missing WP.com sites are fetched and show up). So it's perhaps a bit better than it was before, but still we should improve this.

**Comment by hypest** [comment]
Closing this as no longer valid. In the new login flow, the user cannot go Back when the final stage of login has commenced.
