### ISSUE TITLE
Update colors to use standard colors

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3320]
Related to the Gridicons update #3300 , colors (of text and icons) need to be updated to use standard colors:

Essentially, colors should be:

- Links - `wordPressBlue`
- Text (non-links) - `darkGrey`
- Gridicons and accompanying text - `darkGrey` (except in Tags & Categories)
- Module column heading - `grey`

See https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/330 for reference.

@jancanvan - Could you please confirm those colors above? 
- darkGrey -->     `<color name="grey_dark">#2e4453</color>`
- grey --> `    <color name="grey">#87a6bc</color>`

cc @astralbodies

**Comment by jancavan** [comment]
@daniloercoli

**Equivalent hex values:**

`blue_wordpress` = `#0087be`
`grey` = `#87a6bc`
`grey_dark` =  `#2e4453`

**Essentially, colors should be:**

- Text Links - `blue_wordpress`
- Text (non-links) - `grey_dark`
- Icons (for Views, Visitors, Likes, Comments) and accompanying text - `grey_dark`
- Other icons - `blue_wordpress`
- Module column heading - `grey`

I also included these screenshots specifically for Android because I noticed there are still some slight color differences if compared to iOS:

![1](https://cloud.githubusercontent.com/assets/4924246/10402187/b3a01460-6e78-11e5-8c15-1a15df78132a.jpg)
![2](https://cloud.githubusercontent.com/assets/4924246/10402186/b3a0010a-6e78-11e5-9730-88df71f9167e.jpg)
![3](https://cloud.githubusercontent.com/assets/4924246/10402188/b3a1b7d4-6e78-11e5-9609-54285b2a7525.jpg)
![4](https://cloud.githubusercontent.com/assets/4924246/10402189/b3a20478-6e78-11e5-9f1f-b6e69de6987d.jpg)
![5](https://cloud.githubusercontent.com/assets/4924246/10402191/b3a359c2-6e78-11e5-86f6-ccb191e6d59a.jpg)
![6](https://cloud.githubusercontent.com/assets/4924246/10402190/b3a2d8c6-6e78-11e5-9a2a-cf159e9a5c82.jpg)
![7](https://cloud.githubusercontent.com/assets/4924246/10402192/b3b3c82a-6e78-11e5-91ac-1763cd424682.jpg)

**Comment by daniloercoli** [comment]
Hey @jancavan  - I've updated the colors but we now need a bunch of new images.

The following icons need to be updated to WordPress Blue:
- stats_chevron_right
- stats_chevron_down
- stats_link
- stats_icon_categories 
- stats_icon_tags 

![device-2015-10-15-105803](https://cloud.githubusercontent.com/assets/518232/10521330/83a9dfe4-732c-11e5-889e-567b3619ff29.png)




Note that for all of the pictures above we need three version of them (See the folder hdpi, xhdpi, xxhdpi for the correct dimensions).

**Comment by daniloercoli** [comment]
@jancavan - Did we remove the site placeholder icon in `Referrers` and `Clicks` ?

Mobile app:
![device-2015-10-15-110933](https://cloud.githubusercontent.com/assets/518232/10521519/83087108-732d-11e5-8f1f-5812ee9d6de1.png)

Web Version:
<img width="328" alt="screen shot 2015-10-15 at 11 11 25" src="https://cloud.githubusercontent.com/assets/518232/10521525/8cc0c966-732d-11e5-8ef4-b6e4c794b1a9.png">

**Comment by jancavan** [comment]
@daniloercoli That's a good point. Yes, we did get rid of the placeholder icon. We'll also just use the "open new window" icon instead of the link icon. /cc @astralbodies 

The trophy icon also needs to be updated, but color remains the same.

Here are the icons:
https://cloudup.com/cdK2E1W3shH
