### ISSUE TITLE
Capture blog/site ID as a parameter in WPAnalytics calls where appropriate

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-Android#3371]
Find all calls to event tracking in WPAnalytics around the app and pass in blog/site ID if it's a .com or a Jetpack site when it makes sense.

cc: @daniloercoli

**Comment by astralbodies** [comment]
iOS issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/4405

**Comment by daniloercoli** [comment]
@astralbodies I did a first pass on this. Below are the events I selected for adding `blog_id` and `is_jetpack` when available. 
<sub><b>Note that i'm not tracking .org installations. For the reader I'm tracking only blogs (and not feeds) since feed_id is not so interesting for us. We may want to add it if needed.</b></sub>

   case THEMES_ACCESSED_THEMES_BROWSER:
            case THEMES_CHANGED_THEME:
            case THEMES_PREVIEWED_SITE:


            case READER_ARTICLE_COMMENTED_ON:
            case READER_ARTICLE_LIKED:
            case READER_ARTICLE_OPENED:
            case READER_ARTICLE_REBLOGGED:
            case READER_ARTICLE_UNLIKED:
            case READER_BLOG_BLOCKED:
            case READER_BLOG_FOLLOWED:
            case READER_BLOG_PREVIEWED:
            case READER_BLOG_UNFOLLOWED:

            case EDITOR_CREATED_POST:
            case EDITOR_SAVED_DRAFT:
            case EDITOR_ADDED_PHOTO_VIA_LOCAL_LIBRARY:
            case EDITOR_ADDED_PHOTO_VIA_WP_MEDIA_LIBRARY:
            case EDITOR_PUBLISHED_POST:
            case EDITOR_UPDATED_POST:
            case EDITOR_SCHEDULED_POST:


            case OPENED_POSTS:
            case OPENED_PAGES:
            case OPENED_COMMENTS:
            case OPENED_VIEW_SITE:
            case OPENED_VIEW_ADMIN:
            case OPENED_MEDIA_LIBRARY:
            case OPENED_BLOG_SETTINGS:

            case SIGNED_INTO_JETPACK:
            case PERFORMED_JETPACK_SIGN_IN_FROM_STATS_SCREEN:

            case STATS_ACCESSED:
            case STATS_INSIGHTS_ACCESSED:
            case STATS_PERIOD_DAYS_ACCESSED:
            case STATS_PERIOD_WEEKS_ACCESSED:
            case STATS_PERIOD_MONTHS_ACCESSED:
            case STATS_PERIOD_YEARS_ACCESSED:
            case STATS_VIEW_ALL_ACCESSED:
            case STATS_SINGLE_POST_ACCESSED:
            case STATS_OPENED_WEB_VERSION:
            case STATS_TAPPED_BAR_CHART:
            case STATS_WIDGET_ADDED:
            case STATS_WIDGET_REMOVED:
            case STATS_WIDGET_TAPPED:
            case MY_SITE_ACCESSED:

Could you please check that i'm not missing anything?
Commit here: https://github.com/wordpress-mobile/WordPress-Android/commit/bac388aac9284360069856505ee1c89c713211d6

**Comment by astralbodies** [comment]
@daniloercoli This looks right to me!
