### ISSUE TITLE
Gravatar disappearing after scroll in Comments

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3500]
Note this is the same user, some gravatars are shown while others default to mystery man, before scroll everything looks OK:
https://cloudup.com/c7IB6B3260w

**Comment by nbradbury** [comment]
I was able to reproduce this, but only when one or more of the comments is from a user that doesn't have an avatar.

**Comment by nbradbury** [comment]
Debugging this further, there appears to be a flaw in the way [we skip](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/WPNetworkImageView.java#L203) requesting images that previously 404'd.

I'm not sure where the problem lies, but when I remove the 404 handling the avatars all appear correctly. And based on the network traffic I'm seeing while scrolling through the comments, I suspect Volley's caching makes our 404 handling unnecessary.

**Comment by nbradbury** [comment]
@maxme Are you able to repro this on a real device? So far I've only been able to repro this in an emulator.

**Comment by maxme** [comment]
Yes, reproduced on a xperia z5 compact (running Android 5.1), same blog as in the video, same steps (scroll down and then up).

**Comment by maxme** [comment]
xperia z5 capture: https://cloudup.com/cbH4XdgQL65

**Comment by nbradbury** [comment]
@maxme When you have a minute, can you disable the 404 handling by commenting out [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/WPNetworkImageView.java#L205) and see if the problem goes away? I want to verify whether the 404 handling is somehow involved. Thanks!
