### ISSUE TITLE
Private Blog images sometimes aren't loaded in the post preview

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#3510]
Sometimes images from private sites aren't being loaded in the post list preview's `WebView` (only for locally changed posts).

![wpandroid-private-blog-image](https://cloud.githubusercontent.com/assets/9613966/11781406/aab0f20a-a237-11e5-8a8d-bb457898dbca.png)

**Comment by daniloercoli** [comment]
I can replicate the issue on public blogs too. Just tap on a post in the main posts list, and the preview screen can contain the empty image link.

![screen shot 2015-12-16 at 14 49 35](https://cloud.githubusercontent.com/assets/518232/11842497/43bc7e9c-a404-11e5-8471-01cacdea74b3.png)

The example above is from Mobile Manger blog. 
The issue is due to a 301 redirect. The app asks for `http://mobilemanger.files.wordpress.com/2015/10/wpid-wp-1445359659074.jpg` but got back a 301 response with the following Location header `https://mobilemanger.files.wordpress.com/2015/10/wpid-wp-1445359659074.jpg` and then fails to validate the certificate.

```
primary error: 2 certificate: Issued to: CN=*.wordpress.com,OU=Domain Control Validated;
Issued by: O=Internet Widgits Pty Ltd,ST=Some-State,C=IT;
 on URL: https://mobilemanger.files.wordpress.com/2015/10/wpid-wp-1445359659074.jpg
```
