### ISSUE TITLE
My Sites: Add Tablet UI

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3551]
We should add a UI that looks and feels similar to the Desktop app or WordPress.com when on a tablet. It has the menu on the left with the content pane to the right:

<img width="1113" alt="screen shot 2015-12-23 at 2 25 50 pm" src="https://cloud.githubusercontent.com/assets/789137/11986165/63c92eec-a981-11e5-8d7f-b1b6df8b59be.png">

Most of the items in my sites are already fragments, so should work well for placing in a two-pane view for tablets.

**Comment by khaykov** [comment]
As suggested by designer, we should revisit this issue after having a more thoughtful discussion about  tablet view of each individual screen.

I made a [branch](https://github.com/khaykov/WordPress-Android/tree/feature/tablet-ui-beta) that has all the dual pane functionality, with temporary design. It's a quite behind develop, but still should give an idea how everything works. Feel free to check it out.
It's based on this [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3663) which is just a core framework + working selectors for MySite.

I excluded some activities from tablet UI - “View Admin” and and "View Site”, they are both WebView's and can be quite heavy in ViewPager.  “Settings” and “Media Browser” - are also not the best candidates, especially Media Browser - it relies heavily on Toolbar and fragment transactions. We can add them later, but it will require serious rethinking of how they work.

**Comment by khaykov** [comment]
On related note, I kinda feel that if we'll wait for perfect design for all screens, it might never happen :)
So there is another option - to have a partial tablet UI support first (where it does not interfere with smartphone UX) and release/change screens as we go. This might actually increase the number of tablet users (cool tablet screenshots on Play Store), and we might get some feedback from users.

I would love hear what @nbradbury and @maxme think about this. 
Maybe @mattmiklic and @jasmussen could also pitch some ideas?

cc @beaucollins

**Comment by jasmussen** [comment]
I'd personally be okay with rolling out a tablet layout on a piecemeal basis. Also so far the work I've seen you do is great from a visual standpoint. 

Just in order to avoid any technical debt, I would defer to Nick or Maxime as having the final words on how to approach this. But just from a design/visual/platform specific point of view, I would suggest the following two bullets as being important for a tablet layout, no matter if it's rolled out piecemeal or as a big sweeping change:

- Walk a careful balance between adhering to platform standards, and Calypso standards. Both are equally important.
- Any switches between portrait single-column layout and landscape multi-column layout should feel as natural and predictable as possible

It may make a lot of sense to convert only a few screens to tablet layout first, perhaps the ones that won't have us explore hacks to make it all work. Maybe the editor is a good candidate?

Also, any lessons learned in developing a good tablet layout for the apps, we should use those lessons to also improve the iOS app, and especially the web app.

**Comment by maxme** [comment]
@hypest what was the latest update about the tablet UI? IIRC, we won't follow a multipane approach but we'll better use the screen estate (with grid views for instance instead of lists).

**Comment by hypest** [comment]
@maxme , the latest on the matter is yes, multipane has dropped out of favour in the vanilla Android system apps and and so we better look at other paradigms (like grids, yes) for utilising the available space on tablets. In essence, this project is effectively still at the design phase, looking for design love.
