### ISSUE TITLE
Reader details is blank after opening a web link

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#3575]
Reader details page is blank when returning to it from an external link.
Steps to repro:
- Open the reader list.
- Tap on an article (that contains pictures?) and open the details screen.
- Tap on a link in the post that opens the webview (external link)
- go back to the article details ---> Blank!

See the video:
https://cloudup.com/cTXEvNsgiEz

**Comment by nbradbury** [comment]
Note: I can repro this even in `release/4.8`, and I should've noticed this already if it has been around that long. My guess is it's related to a system WebView update.

**Comment by nbradbury** [comment]
Looks like the problem lies in the `onPause()` call [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostDetailFragment.java#L880). I do note that I never call [onResume()](http://developer.android.com/reference/android/webkit/WebView.html#onResume()), but previously this worked just fine.
