### ISSUE TITLE
Site Settings: "Learn More" popup in discussion settings has inactive Menu item in header

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#3638]
When you go to Settings > More > Learn More, a window pops up displaying <a href="https://en.support.wordpress.com/settings/discussion-settings/#other-comment-settings">a support document</a> with details about the other discussion settings. However, that page includes a header with a "More" item that doesn't respond when tapped on. (In the browser on small devices, that "Menu" item opens to display links to Themes, Support, Blog, and Features).

Can we either hide that header or ensure Menu responds when you tap it in that in-app popup window? (I don't think we need that navigation in this context so it seems reasonable to hide it.)

Screenshot:

![2016-01-21 12 58 27](https://cloud.githubusercontent.com/assets/8658164/12481279/e84f456e-c03f-11e5-9f58-ff9ab1f279cc.png)

Tested on Nexus 9, Android 6.0.1, app beta v. 5.0-rc-1.

**Comment by tonyr59h** [comment]
@kwonye has some experience with this from his work on Themes. We should hide it if possible.

**Comment by kwonye** [comment]
I believe @lancewillett added a parameter for me for it to be hidden

**Comment by lancewillett** [comment]
There are various parameters you can use, for example on a theme demo site:

iframe=true
preview=true
demo=true

https://venturedemo.wordpress.com/?demo=true&iframe=true&theme_preview=true

To hide the various things.

I'm not sure the menu in this exact case is covered by that, though — will need testing and possible changes on the WordPress.com side.

**Comment by mattmiklic** [comment]
Took a look at the branch in progress. It looks pretty good, but I think we could improve it with a few changes -- some in the app itself, others probably would have to happen on the server side. Here are my recommendations:

- Increase the size of the popup to fill all of the active screen area except for a 12dp border on all sizes (is currently 16dp on top/bottom and 36dp on left/right on a Nexus 5.
- Decrease the font size of the page title, and make it semibold instead of light to provide hierarchy and contrast without overwhelming a mobile screen.
- Equalize the padding on the content inside the popup to 24dp on all sides.

These changes would give us room to fit more content on the screen at once, and give us a more comfortable line length for reading.

##### Before and After:
![slice 1](https://cloud.githubusercontent.com/assets/1396552/13020968/61cd5882-d1a6-11e5-9f5c-5da5782324d6.png)

Annotated with measurements:

![slice 2](https://cloud.githubusercontent.com/assets/1396552/13021004/9c4de76a-d1a6-11e5-81e4-ac719383ed7f.png)

**Comment by tonyr59h** [comment]
Addressed in #3754.
