### ISSUE TITLE
Delete site - polish

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3648]
Make sure the `feature/delete-site` has been looked over by @oguzkocer, @nbradbury, @mattmiklic, and 
@adambbecker for the following:

* Wording
* Design
* Icons

- [x] Address primary domain label
- [x] Remove Site for self-hosted pass (Not going to do anything right now as that will be deprecated soon)
- [x] Verify all font is Roboto (No more open sans in app #3814)
- [x] Align all icons/headers/text views
- [x] Verify all error messages
- [ ] I recommend adding if (!NetworkUtils.checkConnection(getActivity())) return; before making the network calls

**Comment by kwonye** [comment]
Per @nbradbury:

The "Primary domain" label here seems unnecessary. If we decide to keep it, the spacing needs to be tweaked a bit.

![device-2016-01-22-175353](https://cloud.githubusercontent.com/assets/3903757/12525323/73c93496-c131-11e5-96a2-be5fb4ca1d9d.png)

**Comment by mattmiklic** [comment]
> The "Primary domain" label here seems unnecessary. 

Agreed; with the explicit text "entering the primary domain below" the label itself shouldn't be necessary.

**Comment by nbradbury** [comment]
Wasn't sure where else to mention this: as part of the "delete site" feature, we may want to change how self-hosted sites are removed from the app. 

The way we use "Remove Site" for self-hosted blogs has long bothered me because it's unclear to the user whether it's simply removing the site from the app or actually deleting it, and I think this will be even more confusing once we add "delete site" for .com sites.

![delete-site-org](https://cloud.githubusercontent.com/assets/3903757/12695819/499d7f64-c727-11e5-839c-382785cf9aca.png)

**Comment by mattmiklic** [comment]
Sorry I'm late...

@adambbecker should give these a review for more specifics, but I noticed a few visual differences on on an initial review. 

Overall, I noticed that Adam's mockups are in Roboto, but these have been implemented in Open Sans, which is a good thing I think; since the app is currently using Open Sans consistently throughout. In the screenshots below I've compared the mockups (left) with screenshots of the branch as it exists today (right). I haven't mentioned the Roboto/Open Sans difference in my notes below.

<img width="806" alt="screen shot 2016-02-02 at 2 45 16 pm" src="https://cloud.githubusercontent.com/assets/1396552/12762218/362cf080-c9bc-11e5-9289-2408d987bf94.png">

Again I'll defer to Adam for specific font weights and sizes, but the header appears to be too bold, it may be the bold weight when we ordinarily use the semibold weight of Open Sans. 

The button here is in bold Roboto (I think), should be semibold Open Sans. It could also use more padding on the left/right sides.

The gridicon used here is correct  but it should be aligned with the arrow icon above it on the 16dp keyline. The "Start Over" title and the body text should be aligned to the <a href="https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing">keyline at 72dp</a>. Looks like there's too much margin above the icon and Let Us Help text.

<img width="839" alt="screen shot 2016-02-02 at 2 45 56 pm" src="https://cloud.githubusercontent.com/assets/1396552/12762349/bc5f75b0-c9bc-11e5-9f80-a009d154b64e.png">

Icon beside Domain Removal is missing, domain isn't listed below text that says "remove your domain(s) listed below". Text should be on the 72dp keyline.

Domain Removal/Keep Your Content/Are You Sure? subheaders should be the semibold weight of Open Sans.

Buttons are in Roboto, should be semibold Open Sans. Can also use more padding on left/right sides.

Export Content button text is black (I think), should be `grey_dark`. (This is wrong in the mockup)

"Can not" should be semibold in the "Are you sure" description.

<img width="868" alt="screen shot 2016-02-02 at 2 47 12 pm" src="https://cloud.githubusercontent.com/assets/1396552/12762446/2bd947ae-c9bd-11e5-9012-331f800000f1.png">

This dialog is in Roboto, but should probably switch to Open Sans to match others. You can use the dialogs in the Site Settings section as a template. 

I noticed while testing that the hint text goes away as I start typing -- I'd replace the "Primary Domain" label with the domain name being deleted, so the user has a reference on screen of what they're supposed to be typing. If the domain is very long or includes a typo (created accidentally) it could be hard to retype from memory.

The buttons are in Roboto, should be semibold Open Sans (and match the color of dialog buttons in Site Settings, except for the red Delete button).

<img width="395" alt="screen shot 2016-02-02 at 2 59 51 pm" src="https://cloud.githubusercontent.com/assets/1396552/12762547/a283ede6-c9bd-11e5-97a4-08cd672f1553.png">

This dialog should also use Open Sans, and the button should be floated to the right corner (and updated to match the color of dialog buttons in Site Settings).

**Comment by nbradbury** [comment]
I have some concerns with this feature beyond polish.

It looks like three separate actions - "Domain Removal," "Keep Your Content," and "Are You Sure?" - because each section is given the same weight. The icons on the first two sections are cryptic as well.

The wording is awkward, especially under "Keep Your Content." It starts with, "If you are sure..." which apparently refers to the "Are You Sure?" section below it, then repeats the word "sure" ("If you are *sure*, please be *sure*..."), which is poor style.

Having the "Export content" and "Delete site" buttons different sizes seems off as well.

But really, my main concern is I have to think about this screen too much in order to figure out how to use it.

**Comment by kwonye** [comment]
> I have some concerns with the delete site feature beyond polish.

Thanks for speaking up! My interpretation is that your concerns are not contained to just the mobile version of this feature (It is fairly similar to how it's done on calypso web). Is that correct? 

I'll work with @adambbecker to address your concerns (for both platforms if it applies)

**Comment by nbradbury** [comment]
> My interpretation is that your concerns are not contained to just the mobile version of this feature (It is fairly similar to how it's done on calypso web). Is that correct?

Calypso Web seems fairly straightforward - it's the mobile interpretation that I find confusing.

<img width="370" alt="delete-web" src="https://cloud.githubusercontent.com/assets/3903757/12770031/f57e9f5a-c9ea-11e5-9a63-eaf8d8bee62d.png">

**Comment by kwonye** [comment]
Ah fair. For export content I believe the wording was changed because we weren't sure if we could export to mobile. Now that we know we can (at least for Android), we may be able to copy the wording from the web.

**Comment by adambbecker** [comment]
@nbradbury: Thanks for giving this a look. While I don't share the same concerns that you do, I certainly understand where you're coming from.

In thinking about this a bit more, and really getting a feel for more traditional flows on the platform, what do you think about something like this?

##### 1. Settings screen

The shift here would be to move the export option out of the delete flow and place it in the advanced section of the main settings screen.

![site settings scrolled](https://cloud.githubusercontent.com/assets/1427136/12793613/72bd6002-ca7f-11e5-8e2a-af05e4ed44ea.png)

##### 2. Export bottom sheet

If the user choses to export content, the available options can be presented using a bottom sheet.

![site settings export](https://cloud.githubusercontent.com/assets/1427136/12793675/a6f2b5f2-ca7f-11e5-95ac-922ee3b974e6.png)

##### 3. Delete site dialog

This is the major shift, but potentially a worthwhile one, as it focuses much more on the exact task at hand. If the user choses the delete site option, they are presented with a dialog that mentions exactly that.

It still warns them of the content removal and still requires an input to confirm however. The input however might be better utilized as the account password since it is more traditional to be required for a flow such as this. 

![site settings delete modal](https://cloud.githubusercontent.com/assets/1427136/12793714/c95b822c-ca7f-11e5-833b-be2e34c8331c.png)

**Comment by nbradbury** [comment]
@adambbecker I can't overstate how much better I like this than the previous flow :) It's simpler and more clear what's happening, plus it feels more native. It might be better to put the warning about exporting content on a separate line, but that's a minor point.

**Comment by adambbecker** [comment]
@nbradbury: Awesome! Glad this feels better. I'll work on getting these design files updated in their appropriate places as well as taking a look the same flow for iOS.

@kwonye, @mattmiklic: Does [the above](https://github.com/wordpress-mobile/WordPress-Android/issues/3648#issuecomment-179414048) feel more appropriate for you as well?

**Comment by mattmiklic** [comment]
Looks good to me. Will defer to Nick on what's most native; it sounds like this is the right approach.

**Comment by kwonye** [comment]
Only thing I'd like to suggest is that 'export content' doesn't show the sharing dialog. If we open the wp-admin/export.php site, they'll be able to configure their export (like on the web).

Also, on the "are you sure" dialog, do you mind if I make "export your content" a link so that they can click it and it'll go to the export site straight from there?

Besides that, it works for me! I'll get to consolidating some branches right away!

**Comment by nbradbury** [comment]
> Only thing I'd like to suggest is that 'export content' doesn't show the sharing dialog. If we open the wp-admin/export.php site, they'll be able to configure their export (like on the web).

That sharing sheet could **really** complicate things so I share your desire to skip it, but I'd still want to keep things 100% native. Suddenly switching to wp-admin is a jarring experience.

**Comment by kwonye** [comment]
@adambbecker: regarding Site URL

![](https://cloud.githubusercontent.com/assets/1427136/12793613/72bd6002-ca7f-11e5-8e2a-af05e4ed44ea.png)

Settings already shows the address of the website (right below Site Title and Tagline). Is Site URL necessary in this new design?

**Comment by adambbecker** [comment]
@kwonye: Nope, definitely not needed. It was added to that mockup before that particular setting was in the app. Only needs to be shown once.

**Comment by kwonye** [comment]
@adambbecker for consistency with iOS/web, I think we should keep the confirmation dialog text the domain instead of password

**Comment by kwonye** [comment]
Note to self: Verify all error message per @nbradbury: "We shouldn't say "Please contact support" without providing an obvious, immediate way to do so. In this case I think the feature isn't going to be widely used, and the error isn't very likely, so a generic error message without the support mention should suffice."

**Comment by kwonye** [comment]
Another comment I missed from @nbradbury (sorry):

> I recommend adding if (!NetworkUtils.checkConnection(getActivity())) return; before making the network call. Even though site settings won't appear if there's no connection, there's no guarantee that won't change, and it's possible the connection could exist when settings appears but is lost by the time the user chooses to export.
