### ISSUE TITLE
Reader: Featured image selection should not include attachments missing from the post body.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3664]
Posts can have images in the media attachments that do not appear in the post body.  It can be confusing to the post author if one of these images happens to be selected as the "featured" image in the post cards and detail.  Let's filter attachments missing from the post body from the featured image candidate pool.

**Comment by nbradbury** [comment]
Since we're requiring the featured image to be in the post body, we probably don't need to scan the attachments at all since we're already scanning for images in the post body. The only reason I can think of to scan attachments is if the image dimensions are missing from the post body, but so far I haven't found any posts with this situation.

**Comment by kwonye** [comment]
@nbradbury can you check https://kwonyetest.wordpress.com/2016/02/09/testing-2/? I am seeing a featured image despite there being no content there.

**Comment by nbradbury** [comment]
@kwonye I don't see any content for that post, but I am seeing that it has [a featured image](https://kwonyetest.files.wordpress.com/2016/02/papers-co-my54-lake-mountain-summer-nature-blue-healing-cloud-36-3840x2400-4k-wallpaper.jpg). Did you not assign a featured image?

**Comment by kwonye** [comment]
> Did you not assign a featured image?

I did not unfortunately. @aerych has decided not to include this change in iOS: wordpress-mobile/WordPress-iOS/#4779. 

Should we revert #3679 to be consistent?

**Comment by nbradbury** [comment]
Yes, we should revert #3679.
