### ISSUE TITLE
Location permission shouldn't appear unless location is enabled

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3728]
If "enable location" is turned off in site settings, you still get a permission dialog about location when creating a post. It should only request location permission when location is enabled. 

![screenshot_20160209-133016](https://cloud.githubusercontent.com/assets/3903757/12932757/652e9de8-cf52-11e5-893e-2afb8463e0c4.png)

**Comment by khaykov** [comment]
I found two related issues.

First, If you click Deny, then go into Post Settings and tap "Locate" - app will crash because of missing permissions. Same will happen if you press search icon in IME after entering location.

Second, when "Enable location" is turned on in settings, press Allow in permission dialog when creating a  new post - current location would not be attached to the post.
