### ISSUE TITLE
Use FilteredRecyclerView component from Comments in Reader

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#3776]
The reader currently has a custom spinner selector embedded as the first element in the list. We now have a component being used in Comments (and Stats) to filter content following a `FilterCriteria`. For the specific case of Comments, a new component has been added that allows a RecyclerView to be filtered given such FilterCriteria is set. In the case of reader, we also have a RecyclerView and a filter, so it makes a lot of sense to reuse such component.

@mattmiklic what do you think is best, should we keep the look and feel as it is right now (grey background) or should we implement it with the lighter blue background as implemented in Comments and Stats?

**Comment by mattmiklic** [comment]
I think it makes sense to re-use the new component, both for the sake of consistency and because it seems more in line with the material design guidelines (I believe -- cc @nbradbury).

**Comment by mzorz** [comment]
Good @mattmiklic - fortunately your request was super easy to fulfil just by changing these 3 lines as I could foresee this change would probably be wanted/needed here or elsewhere and so I extended our `FilteredRecyclerView` component with a small set of convenience methods to change those broad aspects of L&F as well.

Changed this:

        mRecyclerView.setToolbarBackgroundColor(getResources().getColor(R.color.grey_lighten_20));
        mRecyclerView.setToolbarSpinnerTextColor(getResources().getColor(R.color.grey_dark));
        mRecyclerView.setToolbarSpinnerDrawable(R.drawable.reader_dropdown_arrow);

To this:

        mRecyclerView.setToolbarBackgroundColor(getResources().getColor(R.color.blue_medium));
        mRecyclerView.setToolbarSpinnerTextColor(getResources().getColor(R.color.white));
        mRecyclerView.setToolbarSpinnerDrawable(R.drawable.arrow);


Here the before/after screenshots:

![screenshot_2016-03-04-06-52-31](https://cloud.githubusercontent.com/assets/6597771/13523906/f6f24284-e1d6-11e5-906f-98c3ad87b28d.png)
![screenshot_2016-03-04-06-59-16](https://cloud.githubusercontent.com/assets/6597771/13523907/f6f336c6-e1d6-11e5-9069-c6f0db1686f5.png)


As you can see, we’d also need a new drawable for the `settings` icon on the right, to match the light blue tint we have for the arrow there on the sliding toolbar.

Let me know when you can provide that resource and I’ll put it in place @mattmiklic

Thanks for your insight :+1:

**Comment by mattmiklic** [comment]
A couple of visual design suggestions:

- The new bar should be on the same elevation as the tab bar, with no shadow between them, just like where it's being used in Stats and Comments.
- The dropdown text should be aligned 16dp from the left edge of the screen, so it lines up with the text and icons below.
- The gear icon should be aligned 16dp from the right edge of the screen.

Here is the gear icon asset you requested: https://cloudup.com/files/ijGXJGp1yKn/download

Before and after:
![before-after](https://cloud.githubusercontent.com/assets/1396552/13541382/d32a429a-e229-11e5-8695-0e15cb430d3a.png)

**Comment by mzorz** [comment]
I saw this one too:

> The new bar should be on the same elevation as the tab bar, with no shadow between them, just like where it's being used in Stats and Comments.

But there's a problem with it: we are using _tabs_  and the elevation is _needed_ on the other tabs. AFAIK, I couldn't find any easy way to set/unset the elevation on tab switching, and even doing so on swiping animations would look anything but nice IMHO. @nbradbury any thoughts?

I'll check what I can do in regards to the left alignment for the Spinner, it was another painful point.

**Comment by nbradbury** [comment]
I think @mattmiklic is right that there shouldn't be a shadow between the tabs and the filter, but the big problem here - as @mzorz points out - is swiping between pages in the "masterbar" ViewPager.

The only way I can think of to accomplish this is to remove the elevation from the tabs and add a shadow drawable to the top of every fragment in the ViewPager (which on the reader tab only appears once the filter is hidden, since the filter would have its own shadow). And I don't recommend doing that because it feels like the kind of hack that would come back and bite us.

I'll continue to think about this, but for now I'm afraid it's something that can't be done. And I apologize to Matt for that, because I know now every time he looks at the app he's going to see that cursed shadow which shouldn't be there ;)

**Comment by mattmiklic** [comment]
Would it be reasonable to consider leaving the existing design in place for the Reader, at least for now? This feels like something that really needs further thought given to its design (maybe a different design for the Reader screen altogether on Android), and I'm not sure making this change to the reader would be an improvement, since the shadow looks pretty bad and introduces an inconsistency with the way this component is used on other screens.

**Comment by nbradbury** [comment]
@mattmiklic I don't find the shadow to be a big deal, but I also have lousy eyesight and spent my days absorbed in code rather than design. If you feel the design isn't cutting it, then we should leave it as-is until we can accomplish what you believe is best.

**Comment by mzorz** [comment]
I agree @mattmiklic and @nbradbury  - we might try something else but it will take longer time as it's all experimental. 
BTW the margins stuff is ready and pushed :+1:

**Comment by mattmiklic** [comment]
> If you feel the design isn't cutting it, then we should leave it as-is until we can accomplish what you believe is best.

My impression is that since we're not able to achieve a desirable visual result within the limitations of how the current design works, that probably means we should spend a little time thinking the design through. So I think it would make sense to leave the current design in place for the time being, and try to get the designer working on the Reader to collaborate on an Android-specific design. We might be able to come up with something that does a better job of surfacing the Reader navigation altogether as a result.

**Comment by nbradbury** [comment]
> We might be able to come up with something that does a better job of surfacing the Reader navigation altogether as a result.

:100:

**Comment by nbradbury** [comment]
Closed via #3801
