### ISSUE TITLE
Use the official volley library

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3870]
`com.mcxiaoke.volley` is now [deprecated](https://github.com/mcxiaoke/android-volley), use the official library: `compile 'com.android.volley:volley:1.0.0'`.

**Comment by kwonye** [comment]
Attempted this while updating Automattic/android-wordpress-com-rest#10, but was unable to get it working without a significant amount of work. Here are some notes:

1. wordpress-mobile/MediaPicker-Android is also using  `com.mcxiaoke.volley` so that must be updated.
2. `com.android.volley.RedirectError` is not available in the official volley library (used in `ApiHelper.java`)
3. `getOriginUrl()` is now simply `getUrl()` (used in `StatsService.java`)

**Comment by maxme** [comment]
> wordpress-mobile/MediaPicker-Android is also using com.mcxiaoke.volley so that must be updated.

Yep, in the meantime, we can exclude it in gradle

> com.android.volley.RedirectError is not available in the official volley library (used in ApiHelper.java)

If there is a redirect error in the underlying http client, we'll get it in the `deliverResponse` call. I'm pretty sure we can drop that check.

**Comment by hypest** [comment]
To expand on Maxime's comment about the excluding volley, I used the following line while working on a similar issue yesterday:  try adding `exclude group: 'com.android.volley', module: 'volley'` to `configurations.all` in `WordPress/build.gradle`.

**Comment by daniloercoli** [comment]
@maxme Can we mark this ticket FluxC obsolete and close it?

**Comment by maxme** [comment]
@daniloercoli I keep fluxc-obsoble ticket opened, so we can make sure they're actually fixed when we merge FluxC in develop

**Comment by aforcier** [comment]
Per discussion with @maxme, I'm closing this.

Post-FluxC, there are now two remaining places using `com.mcxiaoke.volley` - `:libs:utils:WordPressUtils` and https://github.com/Automattic/android-wordpress-com-rest. There are open issues in both repos (and a PR in `android-wordpress-com-rest`).
