### ISSUE TITLE
Stats: Insights - Latest Post Summary continues showing stats for deleted post

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3925]
### Expected behavior
When the latest post is deleted the `Latest Post Summary` stat in `Insights` should update and use the next most recent post.

### Actual behavior
The `Latest Post Summary` continues to show the deleted post data, even if another post is made or a refresh performed. Logging out and 

### Steps to reproduce the behavior
* Have at least two posts on your site
* Publish a new post and verify the `Latest Post Summary` stat shows the new post title
* Delete the new post and see that the `Latest Post Summary` stat shows the deleted post title
* Publish a new post and see that the `Latest Post Summary` stat shows the deleted post title

**Comment by daniloercoli** [comment]
I would mark this as `won't fix`. It's the expected behavior of the app, since there is a cache of 10 minutes over Stats data. We can invalidate the cache if a user deletes the post within the app, but this will not work if the user trashes it from the web interface.
I'm open to any suggestion though.

**Comment by tonyr59h** [comment]
> It's the expected behavior of the app, since there is a cache of 10 minutes over Stats data.

Oops, didn't realize there was a cache timer! The behavior makes sense in this case, closing.
