### ISSUE TITLE
Jetpack: Add support for detecting connection status.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3972]
Jetpack is getting some handy API for detecting connection status slated for the v4.1 plugin release.  Let's take advantage of this to do some smarter checking for self-hosted blogs.  When connecting to Jetpack from Stats or Notifications let's let the user know if Jetpack is not installed, or installed and disconnected, or installed but having problems and provide them proper guidance.

**Comment by daniloercoli** [comment]
Don't know how the new API will work, but I doubt that we will be able to check for Jetpack if the plugin is installed but de-activated on the self-hosted installation side.

Maybe they will implement some black sorcery ;)

**Comment by aerych** [comment]
I'm hoping for sorcery.   Fwiw, I tried disabling the Jetpack plugin on my test blog and then searched for the plugin to install.  Somehow the plugins directory knew Jetpack was already installed. 
<img width="788" alt="screen shot 2016-04-14 at 11 06 14 am" src="https://cloud.githubusercontent.com/assets/1435271/14534947/017d7032-0231-11e6-9f55-9987ec0e3c74.png">

**Comment by daniloercoli** [comment]
Yep, because you're looking at it in the admin area of your site.

If the plugin is installed, but disabled, FWIK the only way to check its presence is to test the URL
htttp://site-url/wp-content/plugins/plugin-folder and see if the HTTP response code is != 404.

**Comment by maxme** [comment]
I wonder if we could get plugin informations from the REST WP-API - we should eventually make the Site model more complete in FluxC and add installed plugins as well as some informations about them (installed, disabled, etc.).

**Comment by maxme** [comment]
> When connecting to Jetpack from Stats or Notifications let's let the user know if Jetpack is not installed, or installed and disconnected, or installed but having problems and provide them proper guidance.

In [FluxC we have 2 states](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java#L59-L63):
1. Jetpack installed (Jetpack is installed and activated, can be connected or not).
2. Jetpack connected (Jetpack is installed, activated and connected to a wordpress.com account).

And that's what we use in wpandroid (Stats for instance) to ask the user if he wants to install or connect Jetpack to his self hosted site.

I doubt we can detect if the plugin is disabled and this probably won't change much how we handle things since there is no way to programatically install or activate a plugin via the API.
