### ISSUE TITLE
Themes: Themes option missing after signing into wpcom after first adding a self-hosted blog

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3981]
To reproduce: 
Be signed into the app with just a self-hosted account. 
Tap on the profile tab and sign into a wpcom account. 
Return to the sites tab. 
Notice you are now viewing your primary wpcom site. 
Notice that the themes option is missing. 
<img width="281" alt="screen shot 2016-04-18 at 12 05 04 pm" src="https://cloud.githubusercontent.com/assets/1435271/14612715/4b24de70-055e-11e6-8bfb-a1a9e2da017f.png">

**Comment by rachelmcr** [comment]
I re-tested this issue with the above steps on my Nexus 9, Android 6.0.1, WPAndroid 5.4-rc-2 and couldn't reproduce. My primary wpcom site shows the Themes option as expected.

Is this resolved or is there another factor underlying this issue?

**Comment by maxme** [comment]
> Is this resolved or is there another factor underlying this issue?

After sign in, the app will fetch primary site options, depending of these options it will show / hide some parts of the My Site screen (Theme is one that could be hidden). I guess the situation described by @aerych happens when the network call fetching site options is still on going. 

Some solutions:

1. Show a progress dialog after sign in until the site options have been fetched (kind of what happen during sign in on the login screen).
1. Add a loading indicator on this screen when site options haven't been fetched yet.
1. Show all menus if site options haven't been fetched, but some sub menus may fail to load if the site doesn't support it.
1. Show all menus but grey out and disable optional menus (themes for instance) until options have been fetched.

**Comment by aerych** [comment]
> happens when the network call fetching site options is still on going

That's a fair guess.  There was a ton of latency in the emulator when I was testing.
