### ISSUE TITLE
Reader: List position not restored when returning from detail view

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#3994]
Seeing some strange behavior when returning to the reader list from the detail view:

1. Scroll down the list.
2. Select a post to view the detail view.
3. Press the Up button.
4. Observe that you are not returned to the same position in the list view. Sometimes posts appear to get swapped out for older ones.

Video: https://cloudup.com/cumchkQJp9V

Observed on 5.3-beta-1 and current develop branch.

cc @nbradbury

**Comment by nbradbury** [comment]
It took a while to figure out what's going wrong, but here's the problem:

* When you go to the detail view, the post is displayed and then requested in the background via `read/sites/{blodId}/posts/{postId}` to make sure we're reflecting the latest version of the post
* If the latest version is different than the local version, we store the latest version in the db
* When you return to the list view, it detects that there were changes and refreshes

All that is fine - it ensures both the list & detail views show the latest like & comment counts, etc. 

However, it turns out that when the post is requested by the detail view, the endpoint incorrectly says the post comes from a blog that is *not* followed (`is_following` is false), so when we return to the list view it removes that post since it's not in a followed blog (this is why the bug only occurs when viewing "Followed Sites").
