### ISSUE TITLE
Performance Issues caused by AsyncTask

### ISSUE THREAD

**Issue by frankFic** [wordpress-mobile/WordPress-Android#3997]
Hello, developers of WordPress-Android,

I have just found out `AsyncTask.execute` is used in many places like 3 times in EditPostSettingsFragment, 4 times in ThemeBrowserActivity, etc.

However, this API is slower on devices with version higher than Android 3.0. As tasks started by this API are executed serially on a single background thread on those devices (stated in [API guide](http://developer.android.com/intl/zh-cn/reference/android/os/AsyncTask.html#execute(Params...))).

Using method  `executeOnExecutor` to achieve real multi-thread may improve the performance.

Thanks a lot.

**Comment by maxme** [comment]
That's not really an issue in `EditPostSettingsFragment` since the tasks can't be executed simultaneously. The 2 calls to `FetchThemesTask` in `ThemeBrowserActivity` are only adding requests to the volley queue (network call is not happening in the task's `doInBackground`) so it won't change anything if we use THREAD_POOL_EXECUTOR here. Closing this ticket.
