### ISSUE TITLE
Pin lock screen should show every time app opens

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#4020]
### Expected behavior
The pin lock screen should show up every time I open the screen:

![pin-lock-screen](https://cloud.githubusercontent.com/assets/11487924/14818038/cd3b93f6-0b88-11e6-82f3-88f8b2eceba7.png)

### Actual behavior
Instead, the pin lock screen only shows up when the app is opened for the first time and is not in the recents screen. If it's already in the recents screen list, then the pin lock does not show up.

### Steps to reproduce the behavior
1. Open the WordPress app
2. If you don't already have a pin code, go to User > App > Turn PIN lock on, and enter a pin
3. Close the app
4. Open the app and notice that you are not asked for your pin code (problem # 1)
5. Close the app and swipe the app away from the recents screen
6. Open the WordPress app again, and see the pin lock
7. Close the app
8. Open it again and see that you are not asked for a pin code (problem # 2)

##### Tested on Nexus 6, Android 6.0.01

**Comment by daniloercoli** [comment]
I can't seem to reproduce this issue.  Note that there is a 2 secs timeout before Passlock jumps in.

**Comment by theck13** [comment]
I cannot reproduce this either.  See the attached animation for details.

![pin](https://cloud.githubusercontent.com/assets/3827611/15547635/e1124b00-2261-11e6-92d0-7e859370cfe9.gif)

The app is working as expected.  As @daniloercoli mentioned, the app is locked and the pin is required after two seconds have passed since the app was open.  In other words, if you close and open the app in less than two seconds, the pin is not required.  That is by design.
