### ISSUE TITLE
Reader: squashed smilies on Genymotion 4.1.1 Emulator

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4046]
Discovered while testing #4039 - create a post with two smilies, then view it in the reader. They'll appear squashed. Only occurs on Genymotion 4.1.1 emulator (I think).

![b8820752-107d-11e6-9851-390036db3192](https://cloud.githubusercontent.com/assets/3903757/14958794/5d43e13a-105a-11e6-9b6a-55f26da51167.png)

Note that by two smilies, I mean simply:

:)
:)

**Comment by nbradbury** [comment]
Update: This problem most likely occurs on small screens (such as 480x800) rather than on any specific Android version.

**Comment by daniloercoli** [comment]
The issue is still there. Even though I'm able to reproduce a slightly different behavior:
![screen shot 2017-01-31 at 09 56 28](https://cloud.githubusercontent.com/assets/518232/22458224/c5c9a76c-e79b-11e6-8c15-3367c0c49690.png)

The smiles are two `X` characters in my case. Galaxy S2 - 4.1.1 - API 16.

It seems there are also problem with emoticons in the in-app web browser:
![screen shot 2017-01-31 at 09 54 00](https://cloud.githubusercontent.com/assets/518232/22458170/83390c9e-e79b-11e6-88c0-2287285f6829.png)

**Comment by karama78** [comment]
Bon jour frère je n'aime pas les applications mobiles

thimognedierry
