### ISSUE TITLE
Gravatar: should ask for image rating

### ISSUE THREAD

**Issue by v18** [wordpress-mobile/WordPress-Android#4063]
### Expected behavior

When I upload a new Gravatar using the app, it should ask me for a rating. Like here:

<img width="992" alt="screen shot 2016-05-05 at 6 56 59 am" src="https://cloud.githubusercontent.com/assets/11487924/15042037/9713eda2-128e-11e6-86b9-9f6147bd2f51.png">
### Actual behavior

The new Gravatar saves without a rating.

**Comment by hypest** [comment]
Thanks for opening the ticket @v18 !

I've altered the issue's labelling from `[Type] Bug` to `[Type] Task` to better reflect the current understanding of the Rating marking on the mobile.

The app is not offering a Rating setting during the upload as a "shortcut" in order to streamline the Gravatar change feature itself. The newly uploaded Gravatar is actually marked as "rated G". The Rating can be changed, if the user wishes to, by visiting her Gravatar profile on the web.

We will probably come back to this after we've seen how the users are finding the feature on the mobile and whether the default Rating arises as an issue on its own merit.

Thanks!

**Comment by maxme** [comment]
I don't think we should add any step to the Gravatar upload from the app. It would make sense if we had an "advanced profile app" (kindof a Gravatar app), but here you just want to change your profile picture. Like any other app, I'm expecting to pick a photo, upload and be done.

cc @mattmiklic - can we close this?

**Comment by v18** [comment]
I'd +1 closing this

**Comment by mattmiklic** [comment]
> I don't think we should add any step to the Gravatar upload from the app.

Agreed; this is something to keep in mind but I don't think we've got a particular reason to delve into adding a rating to the apps just yet.
