### ISSUE TITLE
Sharing Design/Polish review

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#4089]
Before merging into `develop`, Sharing feature should be reviewed by @mattmiklic @hugobaeta @aerych @nbradbury.

**Comment by kwonye** [comment]
Note to self: Remove all magic numbers/strings/etc

**Comment by kwonye** [comment]
@nbradbury @mattmiklic @hugobaeta @aerych Sharing functionality is all set! Now we just need the design pass.

Please check out `feature/sharing-design-review` for where it's at currently, thanks in advance :)

**Comment by folletto** [comment]
Heya! I'm not sure if I have time to review this, but a question that might be useful for any designer to review this: how do I test it? ;)

**Comment by kwonye** [comment]
@folletto good point 😉 

Whoever's interested, feel free to ping me on Slack and I'll send over the apk to install to your device :)

**Comment by folletto** [comment]
Ok did a run of testing, here some screenshots:

A. Share screen with list and Manage button (above)
![screenshot_20160908-175221](https://cloud.githubusercontent.com/assets/4389/18358912/5368ba50-75ef-11e6-9cf7-e92820480c7f.png)


B. Connect action screen (empty state)
![screenshot_20160908-175349](https://cloud.githubusercontent.com/assets/4389/18358917/57ed94e2-75ef-11e6-9705-bd0517c233fb.png)


C. Connect action screen (with one item already)
![screenshot_20160908-175327](https://cloud.githubusercontent.com/assets/4389/18358925/5c40f7c8-75ef-11e6-9325-ad67efc7ed25.png)


D. Manage button goes into a settings area
![screenshot_20160908-175542](https://cloud.githubusercontent.com/assets/4389/18358927/611acdaa-75ef-11e6-82b6-bac6aca5ad9e.png)


E. Everything else happens in a webview

**Comment by folletto** [comment]
Minimum changes I'd consider required for shipping:

1. Change the "MANAGE" button to be styled. The simple fix would just to color it white, however I have the impression we don't use that kind of buttons in WordPress Android, so a different solution would be ideal.
2. The "CONNECT", "CONNECT OTHER ACCOUNT" and "DISCONNECT" buttons should be styled matching the "MANAGE" button too.
3. Change the icons to match iOS (or Calypso Web) ones. 

I'll try to get a design refresh too, but otherwise, the above are a stepping stone up. :)

**Comment by folletto** [comment]
Here's i2 of the design, aligned with Material Design standards. For reference check the settings panel on Android, and the Material Design page with the [Settings pattern](https://material.google.com/patterns/settings.html).

![android-sharing-i2](https://cloud.githubusercontent.com/assets/4389/18370279/d0197c18-7623-11e6-9aeb-a4a9a70c30a3.png)

Notes:

1. I recognize the Android app doesn't follow precisely yet the Material Design standards. The above does, which is why the Manage screen is different from the other pages in the WordPress Android app.
2. I decided to use smaller cards in the actual screens to add them. This is because it conveys better the meaning of blocks that can be swapped in or out.
3. The icons are either [Gridicons](https://github.com/Automattic/gridicons) or [Social Logos](https://github.com/Automattic/social-logos).
4. The color of the switch has been darkened to match better the color palette, and have more contrast.
5. I'm not entirely sure "Disconnect" follows the Material standards. Also, on iOS that's an additional settings page, which will solve the ambiguity on Android too. We can revisit that later.

I'd like the review of some other designer, however, I already think the above is more aligned and if possible we should ship it. I recognize it's not MVP tho, so I can't make a call about it.

**Comment by kwonye** [comment]
@folletto wow looks amazing, thank you! I'll ping you again when it's ready!

**Comment by jasmussen** [comment]
> I'm not entirely sure "Disconnect" follows the Material standards. Also, on iOS that's an additional settings page, which will solve the ambiguity on Android too. We can revisit that later.

Looks great to me!
