### ISSUE TITLE
"Use as featured image" is not works every time

### ISSUE THREAD

**Issue by dreamonsjp** [wordpress-mobile/WordPress-Android#4229]
### Expected behavior

When user upload an image with "Use as featured image", the featured image shall be saved.

### Actual behavior

When user upload an image with "Use as featured image", the featured image is not saved.

### Steps to reproduce the behavior

(1) Upload an image (select a photo from gallery or Capture photo)
(2) Tap the image to open a modal window "Image setting"
(3) Check "Use as featured image"

##### Tested on [device], Android [version]

FTJ152A, Android version 5.1
(I reproduced the behavior also Xpedia, but didn't confirmed the model type and version)

**Comment by rachelmcr** [comment]
Thank you for this report! This issue was previously reported in https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/391 and fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/4161. (The fix was released in version 5.4.1.)

Can you confirm if you are still seeing this issue in version 5.4.1 of the app?

**Comment by dreamonsjp** [comment]
Hello Rachel, thank you very much for your comments. I confirmed this problem is not happened after updated 5.4.2.
