### ISSUE TITLE
Posts from blogs followed from web do not appear in Reader until explict refresh.

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#4231]
### Expected behavior
Posts from blog you started to follow from web appear in Reader when you open app.

### Actual behavior
Posts from blog you started to follow from web do no appear in Reader until you do pull to refresh twice.

### Steps to reproduce the behavior
Follow blog from web.
Open app. 
Go to Reader that set to show "Followed Sites".
Posts from blog followed in first step do not appear in reader.

I believe this happens because at both onResume and after FollowedBlogsChanged event we reload posts from local DB and not from server.

**Comment by nbradbury** [comment]
@khaykov Is it possible that what you're seeing is the result of the reader not immediately requesting new posts due to [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/ReaderPostListFragment.java#L268), which tells the reader to only auto-update the current tag if it hasn't been updated in the last  10 minutes?

**Comment by khaykov** [comment]
Thanks, this is totally it. Checked after waiting and it works as expected. Closing.
