### ISSUE TITLE
Analytics Audit

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-Android#4245]
Let's perform an Analytics Audit as it's been a while. We should check for redundant events, consistency, and add in any missing events.

**Comment by sendhil** [comment]
Parallel WPiOS Issue - https://github.com/wordpress-mobile/WordPress-iOS/issues/5581

**Comment by maxme** [comment]
`dotcom_user` metadata is not set correctly (based on `isSignedIn`: https://github.com/wordpress-mobile/WordPress-Android/blob/7d7117d7007fc8e6f097045979a030a9477b5eef/WordPress/src/main/java/org/wordpress/android/models/AccountHelper.java#L31-L33)

**Comment by aforcier** [comment]
^ `dotcom_user` is also not being sent to Tracks at the moment, only to Mixpanel.

**Comment by kwonye** [comment]
Also, can we add Helpshift auditing to this please? I know there are a lot of things we can send as Helpshift metadata to help out our Happiness Engineers cc @rachelmcr

**Comment by maxme** [comment]
Adding some related issues here:

- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/4199 - Add analytics properties to "Signed In" events
- [ ] https://github.com/wordpress-mobile/WordPress-Android/issues/4088 - Add Analytics to Sharing

**Comment by designsimply** [comment]
Added to Prioritized Android Groundskeeping to ask for a refresh of this issue during a future maintenance rotation. I noticed the two linked issues in the most recent prior comment were both auto-closed by stalebot some time ago. 

Can both of the issues, https://github.com/wordpress-mobile/WordPress-Android/issues/4199 and https://github.com/wordpress-mobile/WordPress-Android/issues/4088, please be re-checked and re-opened if they are still valid?

Can this issue please be updated with more specific instructions or can new issues be created that are more up-to-date compared to this issue?

**Comment by planarvoid** [comment]
This is really hard to do since there are no specs for what we should be tracking and I can't really read the iOS code. Would it be possible to split this into separate steps. Like defining the tracking events and when they should be sent for all the components and making sure they are sent correctly on both platforms? This sounds like a project out of groundskeeping scope but I think it's the correct approach. I can't really validate the two issues without someone from iOS specifying what's being sent on these platforms.

**Comment by designsimply** [comment]
@bummytime may we have your input on prioritization for this one? Should the `[Pri] High` label remain or be removed?

**Comment by designsimply** [comment]
I removed the high priority label from this issue due to inactivity and removed it from the Groundskeeping project because we reviewed it twice in two separate rotations and received feedback that it would be helpful to break the task down into smaller, more manageable steps. 🙏

Please feel free to move this back into Groundskeeping after adding some additional, more specific direction (a checklist perhaps?) or to close the issue in favor of re-assessing analytics at a later date if that's preferable. Thanks! cc @bummytime

**Comment by bummytime** [comment]
@designsimply thank you for updating this issue. From my perspective, this is a nebulous request that we are always addressing as we ship features. Soooo, I am going to close this one.
