### ISSUE TITLE
Batch “Unspam" of comments is unclear

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#4274]
### Steps to reproduce the behavior

Go to Comments.
Select Spam from dropdown list.
Select multiple comments using long press.
From context menu select SPAM.
Nothing happens.
### Expected behavior

Context menu label should say "Not Spam" and comments will be “unspammed” after clicking on it.

**Comment by khaykov** [comment]
Just figured out that Approve button acts as "Not Spam" button, which is quite confusing to be honest. And the fact that there is not indication that Spam button is disabled when it's in overflow menu only adds to this confusion.

**Comment by rachelmcr** [comment]
I agree that the options with the context menu are unclear. Here's a screenshot of that context menu in version 5.5 for reference:

![screen shot 2016-07-07 at 11 48 35 am](https://cloud.githubusercontent.com/assets/8658164/16651006/0eddc390-4439-11e6-964f-26511bdda099.png)

When moderating individuals comments, the "spam" option becomes "not spam" which is clearer:

![screen shot 2016-07-07 at 11 49 43 am](https://cloud.githubusercontent.com/assets/8658164/16651029/2f38fa2e-4439-11e6-980c-cf0cd9849962.png)

It's also clearer that the "spam" button is disabled in the tablet view, where there is a row of icons instead of a context menu:

![2016-07-07 10 49 15](https://cloud.githubusercontent.com/assets/8658164/16651040/500063fa-4439-11e6-95d0-371fa344bdf8.png)

**Comment by maxme** [comment]
> Just figured out that Approve button acts as "Not Spam" button, which is quite confusing to be honest.

I think this is the correct approach, if you see a comment marked spam and you want to approve it, you don't want to 1. unspam it 2. approve it. IMO the confusing thing here is the icon.

> Context menu label should say "Not Spam" and comments will be “unspammed” after clicking on it.

I agree with that, but this can only be done if *all* comments are already marked "Spam" which is the case when the Spam filter is selected. 

In tablet mode, we should add new icon for the "Unspam" action or drop the icon completely and keep the text only. cc @mattmiklic
