### ISSUE TITLE
Post auto-save mechanism

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#4325]
Based on a discussion here #4240, I thought it could be useful to have a separate thread about the new auto-saving mechanism, because there a few open questions. 
#### Conclusion from our discussion on Slack
1. We ditch the Save alert dialog
2. On editor exit, a Snackbar is displayed with a timeout, when users can discard the changes
3. If a user reverts the changes, all local changes are discarded. Otherwise, after the timeout the post gets uploaded (if a device is offline, changes are saved locally)

Imagine a scenario: I have a draft post both online and in my phone. I make some changes but since the phone is offline the changes are saved locally. Later someone makes changes on the website. Because the app ignores updates on posts with local changes, I'll never see this new draft on my phone. After I make additional changes on the phone, the post gets uploaded and overwrites the previous changes. 

So my question is -- Is there a way to detect remote changes and shouldn't we tell the users about it?

CC: @hypest, @diegoreymendez, @nbradbury, @maxme

**Comment by diegoreymendez** [comment]
My opinion on this is that auto-saving would be a bad idea without first having revision support (which at least iOS doesn't have yet).

Once we have revisions support, all of this discussion becomes much simpler.  Especially if we can place a date on each revision.

**Comment by hypest** [comment]
I might be missing some background on this @diegoreymendez : how do we currently protect the user from overwriting remote draft changes? AFAIU, manually saving the draft will have the same problem, right?

**Comment by diegoreymendez** [comment]
@hypest - To make the discussion easier I'll refer to remote-autosaving as auto-uploading. (which is what I think we mean by auto-saving in the context of this discussion).

At least under iOS, a post never gets auto-uploaded, meaning the user can opt to discard changes instead of uploading them if there are local changes.

If the app crashes as you're editing, the local changes ARE autosaved, just never uploaded automatically.  This is an important distinction because when you open the app again, the changes are still there.

The problem I see with auto-uploading is that if you open the app after a month and there are local changes for a post, that doesn't mean you want those changes to go live automatically.  As simple as that.

**Comment by diegoreymendez** [comment]
And one more thing:

>  AFAIU, manually saving the draft has the same problem(s), right?

Manual saving requires an explicit interaction with the user, so it's definitely not the same as auto-uploading local changes.

If (for example) the auto-uploading can happen as I launch the application, then I think it's going to cause trouble because I may not be aware that my post is being modified at all.  This can be a pain unless we have revision support and we can compare modification dates in some way - thus not automatically overwriting posts.

**Comment by hypest** [comment]
Allow me to elaborate a bit:
Let's say that, with the current _wpandroid_ app, a draft has local changes. Now, say that someone else introduces remote changes via Calypso. Back in the first user's phone, no matter how many times the list gets updated (say, by pull-to-refresh), the draft is still showing the local change only, even though the local DB does have the remote state of the draft as well. At least that's how the Android app behaves today.
Not having a way to review those remote changes (not even an indication there are remote changes!) the user hits the "update" button inadvertently overwriting the draft. That's the problem I was referring to by `manually saving the draft has the same problem(s)`.

**Note: Auto-upload or not, WordPress.com _does_ save both revisions even though the Draft seems to have been overwritten when viewed in Calypso. A user can revert to the remotely-changed draft via wp-admin. So ultimately, there is no data loss.** This might be the same for self-hosted WP sites as well, but I'm not informed enough at this point.

I don't think that introducing auto-upload will make things worse. On the contrary, I think it will minimise the number of those cases where overwrites happen because the local changes live too long and deviate from the remote. Also, nothing's stoping us from making auto-upload smart enough to detect potential overwrites and warn the user accordingly. We can even opt for cancelling the auto-upload in that case. I expect us to tweak and refine the feature as we implement it.

Unless overwrites are the typical case today, auto-upload will actually make the drafting process more fluid for the majority of users, and that's a good thing.

Beyond that, I'd second adding revision control exposed to the user anyway but it shouldn't be a blocker for auto-upload.

Sorry for the long reply :)

**Comment by 0nko** [comment]
Thanks @hypest! I didn't know the local DB keeps the remote state as well. I really like the idea of detecting conflicts and letting the user know. Since we can compare both revisions it shouldn't be too hard.

**Comment by diegoreymendez** [comment]
So let's go specific.  What happens if the app is opened after a month, and a post has local changes?  How is that handled?

Is it automatically uploaded at any point in time?  If this is the case, I'd argue it's a terrible design decision to let that happen.  By having revision support before moving that route *you'd at least be able to compare dates before overwriting the remote post*.

The manual case means the user can choose what to do.  There's an explicit order by the user to overwrite the remote post.

**Comment by hypest** [comment]
> Is it automatically uploaded at any point in time? I'd argue it's a terrible design decision to let that happen.

The app should try to upload it at first chance, that's what I have in mind anyway. With overwrite detection, that auto-upload could trigger a warning to the user to verify or cancel. I'd expect these cases to be rather few so, such a warning wouldn't be too obnoxious to have.
