### ISSUE TITLE
Reader: It's not obvious what the row of gravatars are (especially if there's only one Like)

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-Android#4352]
When I was viewing a post with only one Like, I wasn't sure what the gravatar was because it seemed out of place. Had to check other posts for me to remember that it's actually supposed to be a list of people who liked that post.

### Expected behavior
I think a heading similar to "Related Reading" would be nice.

### Actual behavior
![likers](https://cloud.githubusercontent.com/assets/4924246/16597639/e0672bea-42ae-11e6-9bc6-d81c511a9e35.jpg)

### Steps to reproduce the behavior
Visit a post with only one like.

##### Tested on [device], Android [version]
Nexus 5 simulator, Android 6.0

/cc @nbradbury

**Comment by nbradbury** [comment]
@jancavan I can add a heading similar to related posts, but I wonder if we should do more than that? One of the things I dislike about my implementation is there's a disconnect between liking users and the like button.

We show liking user avatars in that row below the article, but the like button (which shows a like count and enables the user to like the post) is on the bottom toolbar.

I thought it might be nice to show the liking avatars in that same toolbar, but there's no space for them since we show the #tag there. What do you think of moving the tag elsewhere, then moving those liking avatars to the left of the toolbar?

**Comment by jancavan** [comment]
@nbradbury That's a valid point. I've explored two different options:

**(A) Simply adding a heading:**
- with "Recommended By" or Liked By" as a heading

![party-people001](https://cloud.githubusercontent.com/assets/4924246/17120123/03ba3986-527f-11e6-843e-1e2e05450fb1.jpg)

**(B) Adding gravatars next to Like action:**

![party-people002](https://cloud.githubusercontent.com/assets/4924246/17119883/a78fecc4-527d-11e6-814e-9ea23db226a3.jpg)

I think (B) works great. However, one concern I have is if there's only one like:
- if the user has not set up a gravatar, I don't think it's obvious what that user icon means as it looks like one of the 3 icons
- it feels kind of imbalanced with all the white space on the right

![party-people-empty](https://cloud.githubusercontent.com/assets/4924246/17120044/9b518d22-527e-11e6-89a5-cced709edd16.jpg)

Thoughts?

**Comment by jancavan** [comment]
I think it'd be helpful to have a count on the heading. That way, when there's more, it's a bit more obvious that we're only showing a limited number of faces:
![likers-1](https://cloud.githubusercontent.com/assets/4924246/17535551/1599be9e-5e44-11e6-825c-1f143dc0e32d.jpg)

Probably for a separate PR, but a Follow button next to the list of likers would be nice:
![likers-2](https://cloud.githubusercontent.com/assets/4924246/17535606/6ea5cb5e-5e44-11e6-90a6-c98d03238b8b.jpg)
