### ISSUE TITLE
Sharing to Media Library then task-switching crashes app

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4412]
### Steps to reproduce the behavior
1. Share an image to WordPress and select the Media Library
2. Once the image has uploaded, press the Back button to return to the previous app
3. Attempt to task switch back to WordPress
### Expected behavior

WordPress opens
### Actual behavior

WordPress fails to open and throws an error

https://cloudup.com/cQsK0hUQ6sS

**Comment by karambir252** [comment]
### I found a different behaviour - Image is shared multiple times
Tested it on Android 4.4 , 5.1 , 6.0
1. Share an image to wordpress and select media library
2. Once the image has uploaded, press the Back button to return to the previous app
3. Attempt to task switch back to WordPress

## Expected behaviour
Image is only shared one time

## Actual behaviour
every time you press back button in MediaBrowserActivity and launch it again using tasks  => image is shared again.

https://cloudup.com/chTKS-DFTng
