### ISSUE TITLE
People: Add ability to filter Team by role

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4512]
There's currently no way to restrict the People view by anything more than Team/Followers/E-mail Followers.  It would be great to be able to also filter by role (Editor, Administrator, Contributor, Author).  This would also mitigate #4511, since if I knew the list was only showing me Editors I wouldn't need to see that displayed on every entry.

**Comment by rachelmcr** [comment]
The current behavior matches Calypso (which also doesn't include a filter by role). It's a cool idea (especially for sites with a lot of users), but since we're going for parity with the web behavior this would probably need to be proposed in Calypso first and then we could look at how to bring it into the app.
