### ISSUE TITLE
Reader: Discover list not loading posts after viewing the Following list

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4513]
### Steps to reproduce the behavior
1) Open the Reader -> Discover
2) Click the gear icon
3) Click the back arrow (either the Android back button or the navigation arrow in the app)
4) Repeat several times (in the GIF below it happened on the first try, but usually it takes at least two)

### Expected behavior
To see the Discover list of posts again

### Actual behavior
A note saying "No posts with this tag".  Refreshing by pulling down successfully re-loads the list.  It happens whether there are tags in the Follow list or not

![508172692147405037](https://cloud.githubusercontent.com/assets/7233112/18017802/50b74536-6ba1-11e6-9c0d-bba9a6d7e14a.gif)

**Comment by nbradbury** [comment]
Thanks for reporting this, @hoverduck! I was able to reproduce it and I'm looking into it now.

**Comment by nbradbury** [comment]
Update: this is caused by calling [deletePostsFromUnfollowedBlogs](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/datasets/ReaderPostTable.java#L422) when the post list is resumed. That method is faulty and should either be removed or replaced with one that simply marks those posts as unfollowed.
