### ISSUE TITLE
Manual line breaks, the text of the vertical spacing is very big, the middle is empty a line, how do I solve?

### ISSUE THREAD

**Issue by HeavenWen** [wordpress-mobile/WordPress-Android#4520]
Create a new blog, enter a line of text, and then use the line coloring feed key, the result is empty out two lines，Vertical spacing is very big, I want to keep it only empty out one line, how to do it,thank you!

**Comment by rachelmcr** [comment]
The editor in the app creates a new paragraph when you tap the Enter key on your keyboard, similar to how the WordPress web editor works.

If you'd like to have a single line break (instead of a paragraph break) you can tap "HTML" in the editor toolbar to switch to HTML mode. In HTML mode, you can tap Enter to create a single line break.

If you have any other questions or concerns about that, please go to "Help & Support" in the app and tap "Contact us" to get in touch with our support team. :)
