### ISSUE TITLE
Notifications: Comment requiring moderation still provided "Like" option

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4601]
### Expected behavior
Comments awaiting moderation should have "Reply / Approve" actions

### Actual behavior
I received "Reply / Like" actions

### Steps to reproduce the behavior
I was unable to reproduce this, but I wanted a bug report out there in case others see the problem.  This is what I did (on a blog with moderation required only for the first time a user comments on the site): 

1) Left a comment on a blog as a new user
 -- Received the "Reply / Approve" notification, the Approve button worked
2) Left several new comments as that user
 -- Received the "Reply / Like" notification, both buttons worked
3) Left a comment as another new user
 -- Received the "Reply / Like" notification, despite the fact that the comment required moderation

Here's a screenshot showing the corresponding e-mail notification for context:

<img src="https://cloud.githubusercontent.com/assets/7233112/19082227/39763cda-8a2b-11e6-9afb-45576577d28c.jpg" width=350>

**Comment by rachelmcr** [comment]
I believe we expect the notifications to default to Reply/Like if we aren't able to determine whether the comment needs to be moderated when we send the push notification. The idea is that both replying to and liking a comment will also approve it if it isn't already approved, so that's a better default than Reply/Approve if we have trouble checking the comment status.

@mzorz could you confirm that?

**Comment by mzorz** [comment]
Yes, that's the implemented behavior indeed

On Oct 5, 2016 11:36 AM, "Rachel McR." <notifications@github.com> wrote:
>
> I believe we expect the notifications to default to Reply/Like if we
aren't able to determine whether the comment needs to be moderated when we
send the push notification. The idea is that both replying to and liking a
comment will also approve it if it isn't already approved, so that's a
better default than Reply/Approve if we have trouble checking the comment
status.

**Comment by mzorz** [comment]
Closing this one as it's the implemented behavior 👍
