### ISSUE TITLE
Notifications: Comment PNs missing action icons

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4605]
### Expected behavior

In https://github.com/wordpress-mobile/WordPress-Android/pull/4537 the actions on the push notifications are evenly spaced, with icons next to each action (e.g. a checkmark for Approve, a star for Like):

![new-comment-pn](https://cloud.githubusercontent.com/assets/6597771/18280979/7894185c-7431-11e6-8cb3-6342ca7d5839.png)

### Actual behavior

I see both actions left-aligned with no icon:

![2016-10-05 11 46 52](https://cloud.githubusercontent.com/assets/8658164/19112505/116240ea-8afd-11e6-8f36-c045ad2e511e.png)

Is that the expected formatting for the push notification on Android 7.0? If it's possible, it would be nice to at least space out the actions more to avoid accidentally tapping the wrong one.

**Comment by hoverduck** [comment]
The new Android 7.0 default is no images on the notification actions, and I'm fairly certain that the spacing is pre-defined as well.  At least with this standard type of notification...there are other forms that can get pretty fancy, like the Google Play Music app pictured below.  I defer to @mzorz as to whether doing anything to make it prettier is worthwhile (since I'm not sure how much work it is), whether this issue should be reclassified as an Enhancement or closed.

![screen shot 2016-10-05 at 10 23 53 am](https://cloud.githubusercontent.com/assets/7233112/19117117/effc5740-8ae5-11e6-8037-4ccf599982a3.png)

**Comment by mzorz** [comment]
interesting!, will check 👍 
thanks @hoverduck and @rachelmcr

**Comment by mzorz** [comment]
Ok closing this as per the following

> You’ll note that the icons are not present in the new notifications; instead more room is provided for the labels themselves in the constrained space of the notification shade. However, the notification action icons are still required and continue to be used on older versions of Android and on devices such as Android Wear.

(from http://android-developers.blogspot.com.ar/2016/06/notifications-in-android-n.html)
