### ISSUE TITLE
Editor: Option to save draft without returning to the post list. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#4613]
Requested by @jeherve

> Steps to reproduce:
> 1. Start writing a brand new post.
> 2. Go to Post Settings, and change the post status to Draft.
> 3. Keep writing.
> 4. Get worried that you’ll lose your content, maybe (I know I won’t, but saving often is a habit I’ve bad since I started using computers). Hit the Save button.
> 5. You get redirected to the Posts list, and have to tap to enter the post editor again. I’d much rather stay on the post editor when saving a draft. It would save me some time and frustration.

**Comment by 0nko** [comment]
After a discussion with @maxme, the proposed won't work unfortunately. When a post is published to the WP back-end, the back-end may modify the post (like changing <br/> to <p>, convert Youtube links into shortcodes, etc.) And that's why a new post is pulled from the back-end after we publish or update. Saving/updating a post and staying inside the editor might create inconsistencies and cause bad UX. That's why also the planned auto-save feature has been put on hold until back-end API can support this.

Closing this issue.
