### ISSUE TITLE
Add App Shortucts to launcher (Android 7.1+)

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#4681]
With Android 7.1 came application shortcuts - by long-pressing on launcher icon you can display the popup list with shortcuts to different app activities. They can be both dynamic and static.

We could implement this feature and add shortcuts to often used parts of the app or the ones we would like to showcase. Couple of suggested options: Quick Photo, Quick Post, Stats, Reply to someone.

Reference:
https://developer.android.com/preview/shortcuts.html

**Comment by iamthomasbishop** [comment]
We have this type of thing (via a Force Touch gesture) on iOS, would be worth referencing.

What we show:

* New Post
* New Photo Post
* Stats
* Notifications
* Additionally we show a quick snapshot of stats (views, visitors)

Here's what it looks like: 

https://cloudup.com/cLiuL8OAJPU

**Comment by malinajirka** [comment]
**Android Shortcuts**
Available shortcuts are shown when a user long-presses the app launcher icon. Android has limit of 5 shortcuts per app.

_Static shortcuts (Android 7.1+)_
 - static shortcuts are “hard-coded” - its titles/target screen can’t be changed in runtime

- I suggest - _New Post, New Photo Post, Stats_ - for currently selected site. We could also show site picker screen, but I think the shortcut should be as simple as possible. 

- I would omit _Notifications_ as it's a top level screen and we are limited to 5 shortcuts per app. We might want to add more important shortcuts in the future. I know that it can be removed, however some users might be already used to it.

_Dynamic shortcuts (Android 7.1+)_
- dynamic shortcuts can be added/updated/removed during runtime

- We might consider - _Open Draft_ - I’m not sure how much work would that be, as we’d need to remove the shortcut when the draft gets published (even when it gets published on the web).

_Pinned shortcuts (Android 8.0+)_
- Both static and dynamic shortcuts can be pinned to the ‘desktop/homescreen’.

Each shortcut has an icon, short and long title.
- Short title - The recommended maximum length is 10 characters.

- Long title - The launcher shows this instead of the short title when it has enough space. The recommended maximum length is 25 characters.

We’ll need an icon for each shortcut - the same icon is used in static, dynamic and pinned mode (check out the screenshot with dummy icons).

<img width="400" alt="shortcuts" src="https://user-images.githubusercontent.com/2261188/35924260-da60cc94-0c22-11e8-8784-e3db6b6a1d51.png">


**Current state**

We don't support Android Shortcuts, however we have a widget which can be pinned to the 'desktop/home screen'. It lets the user pick a site, when they add the widget to the 'desktop/home screen'. The widget opens the New Post screen when clicked.

<img width="600" alt="widget" src="https://user-images.githubusercontent.com/2261188/35922785-c06f5a52-0c1e-11e8-8fc3-194264e75b5f.png">

Any suggestions are appreciated!

cc @iamthomasbishop, @khaykov, @kwonye, @nbradbury
