### ISSUE TITLE
Notifications - quick actions enhancements

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4689]
Follow up from #4673:

Implement the following flow:
- tap Like
- notification changes into...
- feedback saying that the comment/post was liked
- dismiss notification
- show error if there was a problem

Also, make these changes:
- change wording: "Updating" for "Processing"

cc @drw158 feel free to add 👍

**Comment by daniloercoli** [comment]
Note: This should be fixed in develop before the next code freeze.

**Comment by drw158** [comment]
Thanks for looping me in!

Regarding the wording change:

Ideally we wouldn't need the progress bar at all.

> I think I like the loading indicator for Reply though. I would prefer just to show the circular spinner, and skip the progress bar altogether; I think it is unnecessary if we have the circular spinner.

![screen shot 2016-10-26 at 10 34 19 am](https://cloud.githubusercontent.com/assets/618551/19732859/cfe8749c-9b67-11e6-920e-cce8abad7f27.png)


Is it possible to only keep the loading spinner, and not use the added progress bar at the top? I'm imagining:

- user types in the field
- hits the send button
- circle spinner animation as shown in #4673 
- notification transforms to success/fail message (would be cool to have undo also?)

If that is not possible, and we need to keep the progress bar, then the text should be "Replying" instead of "Updating"

Also, I agree we should use stock Android when we can; no need for custom views for this imo.

**Comment by mzorz** [comment]
Awesome @drw158 thanks for the feedback!

Ok so basically, the inline-reply works on Android N (versions 7.0 and up), but it is not present on other versions of Android. That said, the inline-reply line, including the spinner, is all made up by Android 7.0+ itself. Other actions such as Like or Approve (but not reply)  don't get the fancy inline-reply line (because these are not designed for text input, like reply is). That means LIKE/APPROVE behave the very same way on all Android versions, only REPLY behaves differently on Android 7.0 and later.

Regarding using the spinner instead of the progress bar, the stock Android only offers the progress bar (https://developer.android.com/training/notify-user/display-progress.html). (please note we could do custom views though, if we really wanted to :) )

Knowing all this, I can still go ahead and:
- make the same notification change to the progress bar when the user hits LIKE/APPROVE 
- in case of success, it transforms into a message (have to give the UNDO a thought later, as it might imply something else, because UNDOing might as well fail too! 😁 )
- in case of error, re-build the notification and show what it had originally (so the user can try again), with an error toast, maybe?.
- for the case of REPLYING on Android N (7.0+), do not even show the progress bar, as we already have the spinner.
- change the wording on a case by case basis, from  "Updating" to "Replying", "Liking", and  "Approving".

Does that sound good?

**Comment by drw158** [comment]
Yep
