### ISSUE TITLE
Reader: Posts with no Gravatar are showing somebody else's icon

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#4709]
### Expected behavior

To see the blank 'mystery man' icon when the user has no gravatar or site icon
### Actual behavior

I'm seeing a different user's face...in this case it happens to be the user who posted the last post I had open (and Liked), but I can't say for sure that's why it got picked up.  At this point I can't seem to do anything to get it to change.

Android:
<img src='https://cloud.githubusercontent.com/assets/7233112/19775284/ee88842e-9c3d-11e6-9a46-a2de00280c5c.png' width='350px'>

Web:
![screen shot 2016-10-27 at 12 08 20 pm](https://cloud.githubusercontent.com/assets/7233112/19775331/1423cdce-9c3e-11e6-8b9a-1f3a820da860.png)
### Steps to reproduce the behavior

View a post in the Reader from a user with no gravatar or site icon

**Comment by lancewillett** [comment]
I saw this today in alpha-25 also:

Blog post URL: https://ryelle.codes/2016/10/wordpress-rest-api-reactredux-helpers/

![2016-10-27 21 02 29](https://cloud.githubusercontent.com/assets/66797/19787188/492211d0-9c56-11e6-826a-8fc8735e9296.png)

![2016-10-27 21 07 11](https://cloud.githubusercontent.com/assets/66797/19787189/4923a57c-9c56-11e6-895a-399ddec6482f.png)

![2016-10-27 21 07 48](https://cloud.githubusercontent.com/assets/66797/19787190/4923b79c-9c56-11e6-83d5-52e903dd6c3e.png)

**Comment by maxme** [comment]
Reopened after  #4964 merge.

**Comment by nbradbury** [comment]
Just realized we can actually close this one. The latest reader redesign does away with blank mystery man avatar, instead showing no avatar at all when there isn't one (screenshot below). So this problem can no longer occur.

I'm not entirely comfortable with closing this, since there was obviously a problem some where. I'll keep a lookout for similar problems elsewhere.

![screenshot_1483466963](https://cloud.githubusercontent.com/assets/3903757/21618316/5195b7da-d1b8-11e6-9014-026ed37dc091.png)

**Comment by daniloercoli** [comment]
Re-openig this issue since https://github.com/wordpress-mobile/WordPress-Android/pull/4964
