### ISSUE TITLE
Sign in: jetpack-connected sites are not fully logged in to the app

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4763]
### Expected behavior
When you log in to the app with your jetpack-connected, self hosted site credentials and URL, you should also get all the functionality from wp.com.

In order for that to happen, once you're logged in  using your self-hosted site credentials, you should be hinted/requested your wp.com credentials if we can verify your site is a Jetpack-connected site.

### Actual behavior

When you log in to the app with your jetpack-connected, self hosted site credentials and URL, the app only logs you in and shows the Profile screen. It also shows the rest of the functionality such as the Reader and main screen, but you can't go much further without login in to WordPress.com.
We're landing on the Profile screen, which shows a "Log in to wordpress.com" option, but that's pretty much it.

![screenshot_20161109-111930](https://cloud.githubusercontent.com/assets/6597771/20151516/3bb787b4-a66f-11e6-92d7-557238b33270.png)

### Steps to reproduce the behavior
1. App start, sign in screen is shown
2. Enter username, password, url for your Jetpack connected self-hosted site
3. Tap `Sign In` button
4. The Profile screen is shown

**Comment by aforcier** [comment]
This is still an issue in FluxC - we don't even support Jetpack sites that aren't connected to the currently-used WP.com account. We need a more elegant way of handling this, but for now adding such sites 'works', but you're not able to do anything with them.

The current behavior when logged out of WP.com and adding a self-hosted Jetpack site is that the site will be added, but nothing will work. If you visit Stats and sign in to WP.com when prompted, everything works properly.

Ideally we would check for Jetpack on sign in, and if the site is a Jetpack site and we're not logged into WP.com, we should stop the user there and prompt them to sign in to WP.com to continue. Our currently flow doesn't support this very easily though, since we don't know a self-hosted site's Jetpack status until we've finished log in and done a `wp.getOptions` call (a successful `wp.getUsersBlogs` is all that we do to verify self-hosted sign in).

As a first pass, I suggest we catch a self-hosted Jetpack site for a logged-out user as early as possible, and show them a 'Please sign in to WP.com to access your Jetpack site' screen, as we do for Stats.

**Comment by bhwebworks** [comment]
In my opinion this is a problem. 

I host and manage 30 or so sites for various clients, with Jetpack installed on each site primarily for Stats and Brute force attack protection. I use one WP.com account (mine) to connect all the sites to WordPress.com.

One of my clients is trying to add her site to her WordPress android app, but after signing in it forces her to the WordPress.com Jetpack login screen. I'm not going to give her my WP.com login credentials, so she won't be able to connect the app to her site. 

Sure, I could disconnect my account in Jetpack and have her connect, but she's not an administrator, just an editor. (Life's simpler when there's only one administrator managing a website.)

Anyhow, that's my two cents.

John

**Comment by mzorz** [comment]
Thank you @bhwebworks ! You can expect this to be fixed in our upcoming 7.1 release, via this PR #5598

**Comment by bhwebworks** [comment]
And thank you @mzorz for the quick response! Glad to hear this will be fixed soon.
