### ISSUE TITLE
Reader comments: handle backend returning same page of comments

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4816]
I'm not sure yet, but it looks like the Android reader suffers from the same thing described in [this iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/6224).

**Comment by oguzkocer** [comment]
We have a different mechanism to decide whether to load more comments or not, which is comparing the server comment count with the comments in the DB [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/adapters/ReaderCommentAdapter.java#L510-L512).

```
int numServerComments = ReaderPostTable.getNumCommentsForPost(mPost);
int numLocalComments = ReaderCommentTable.getNumCommentsForPost(mPost);
tmpMoreCommentsExist = (numServerComments > numLocalComments);
```

IMO this is a better way to handle the paging. Similar to any other paging implementation, there is a slight chance things can go out of snyc and we go into a loop here. I think that specific case would be when a comment is deleted on the server while we are fetching some pages and it's a very edge case. Since we also re-fetch the post and the comments at certain points, the application will self-correct. I don't think we need to take any steps here and certainly the iOS issue **does not** apply here.
