### ISSUE TITLE
Re-instate checking email for common typos

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#4905]
In the past the wp.com login screen checked email addresses for common typos ("gmial.com" instead of "gmail.com," etc.). It appears we're no longer doing this, and as a result the user is directed to the self-hosted login screen when they make a typo, which is a very confusing flow.

**Comment by tonyr59h** [comment]
We're still not doing this, but at least with the new login flow user's aren't taken to the self-hosted login screen. @hypest are there any plans to do this email as part of the login project?

**Comment by hypest** [comment]
As @tonyr59h mentioned, the new flows don't drop the user to the self-hosted path so, not adding to the confusion in that respect. Having said that, an invalid invalid (like with a typo) it not handled nicely apparently. We only show the user a `Currently unavailable. Please enter your password` message on the magiclink request screen which it not exactly helping to surface the typo error so, i'm inclined to leave this ticket open.

@nheagy (or @aerych ) is wpios performing any email address autocorrection in this manner? How does it work there?

**Comment by aerych** [comment]
The iOS does this only for sign ups.  I took a quick look at the previous code and I don't see where we ever used it for login.
If the user typos their email address in the current login flow they should just be prompted either that the email address isn't registered with wpcom, or that they entered invalid credentials, depending on what they are logging into. 

It makes more sense to me for sign up since a typo there is going to cause other problems. For login it seems less important but I'm fairly neutral on making this change or just closing.
