### ISSUE TITLE
App Settings: Interface Language setting does not persist after closing app completely

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4932]
### Expected behavior

I expect the language setting under Me > App Settings > Interface Language to persist until I change the setting (or perhaps until I log out).

### Actual behavior

When the app goes to the background, the language setting persists. However, if I swipe to close the app completely, when I reopen the app the interface language is reset to my device language.

### Steps to reproduce the behavior

1. Go to Me > App Settings > Interface Language
2. Select a language other than your device language
3. Tap OK
4. Completely close the app
5. Reopen the app

Result: The interface language is now your device language, instead of the language you selected as the app's interface language.

##### Reported in 150629-h on Samsung Galaxy A7, Android 6.0.1, WPAndroid 6.2

**Comment by tonyr59h** [comment]
At first glance it looks like [this line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/prefs/AppSettingsFragment.java#L148) is where the problem is. It will always be evaluated to true because the bit above updates the config it's checking against.
