### ISSUE TITLE
FluxC check: add a wpcom site when already logged in a wpcom account

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4960]
I'm not sure what happens then, but we should prevent that case since we don't support multi wpcom accounts.

**Comment by oguzkocer** [comment]
I have made the initial exploration on this one. It turns out we basically switch the auth token when you add another .com site. We call `AccountStore.authenticate` which updates the token and sends a `OnAuthenticationChanged` event.

I am not totally sure what we should do here. We could maybe just treat the site as self-hosted and work from there. Or, if we don't depend on the account much, we can maybe fetch all the .com & jetpack sites on that account and add them one by one.
