### ISSUE TITLE
Crossposts Do Not Follow Links and Hide Post Content

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5058]
### Expected
Tapping a crosspost goes to the linked site.

### Observed
Tapping a crosspost hides the post contents.  See the screenshots below for example.

~~screenshot removed~~

### Reproduced
1. Go to ***Reader*** tab.
2. Tap a post with a crosspost link.
3. Notice the post content (see ***Before*** above).
4. Tap the crosspost link.
5. Notice the post content disappears (see ***After*** above).

##### Tested
Google Pixel on Android 7.1.1 with WordPress 6.5

**Comment by nbradbury** [comment]
Note: problem is due to the post content itself. The crosspost link starts with simply `//` (ie: not http:// or https://) which causes the webView to behave incorrectly. 

In the post shown in the screenshot above, the link in question is `<a href="//example.wordpress.com/" class="po-xpost">+ravenclawsquad</a>`

**Comment by nbradbury** [comment]
This has been resolved on the backend - https://wpcom.trac.automattic.com/changeset/149856
