### ISSUE TITLE
Opening Post with Aztec Editor Removes More Span

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5103]
### Expected
All spans remain intact when opening a post.

### Observed
More spans are removed leaving `<!--more-->` text when opening a post.

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Blog Posts*** item.
3. Tap ***Create*** floating button.
4. Tap ***HTML*** format button.
5. Enter `<!--more-->`.
6. Tap ***HTML*** format button.
7. Notice more span is shown like `--------MORE--------`.
8. Tap back arrow or back button to exit editing.
9. Tap ***Edit*** button on post.
10. Notice more span is shown like `<!--more-->`.

##### Tested
Google Pixel on Android 7.1.1 with WordPress alpha-33

**Comment by theck13** [comment]
This is working [as expected](https://github.com/wordpress-mobile/WordPress-Android/blob/9237f4f2893a06ddd9519022079d35887d437c7e/WordPress/src/main/java/org/wordpress/android/models/Post.java#L466) and similar behavior occurs with the current visual editor.  This issue should be kept open and revisited once the [`feature/fluxc-integration`](https://github.com/wordpress-mobile/WordPress-Android/tree/feature/fluxc-integration) branch is merged.

**Comment by aforcier** [comment]
Some extra background: In FluxC, we dropped the `metaWeblog.newPost` and `metaWeblog.editPost` XML-RPC methods in favor of `wp.newPost` and `wp.editPost`. The `metaWeblog` methods were the reason for separating the content into description and more tag (where the bug came from) - as of FluxC we don't split/rejoin post content anymore.

I'll mark this as `fluxc-obsolete` instead since it's already working, we just need to do a sanity check when the integration branch is merged.

**Comment by aforcier** [comment]
@0nko I was going through `fluxc-obsolete` issues and I tested this one before I saw your assignment. The original issue seems to be resolved - are you okay with closing this? Or is there another issue with the more span you're seeing?

**Comment by 0nko** [comment]
I've been meaning to test it but I didn't get around to it till now. So we can go ahead and close it 👍
