### ISSUE TITLE
Media - No Permissions to Upload Media

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5110]
If the user doesn't have permissions to upload media on the blog, there is no clear error message in the editor. Just the "Retry" option. 
It allows you to try and retry, but doesn’t show no permissions until you press and hold on the failed image.

**Comment by daniloercoli** [comment]
Dupe of to https://github.com/wordpress-mobile/WordPress-Android/issues/6160

**Comment by nbradbury** [comment]
Looking at Calypso, it seems we should prevent users without upload permission from adding new media. Admin users see an "Add New" button when adding media to a post:

<img width="422" alt="admin" src="https://user-images.githubusercontent.com/3903757/28371911-47ecafa0-6c6c-11e7-967c-2b3907d79c54.png">

But this button doesn't exist for contributors:

<img width="431" alt="screen shot 2017-07-19 at 10 21 09 am" src="https://user-images.githubusercontent.com/3903757/28371995-8b141926-6c6c-11e7-8776-5a3ca775ce0a.png">

So rather than provide an error message when contributors try to upload media, we should be preventing it entirely.

**Comment by daniloercoli** [comment]
Fixed in #6357 and #6356
