### ISSUE TITLE
Notifications: Change icon for in-line replies in notifications

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#5115]
Here's a mockup of a potential change to in-line notification replies, to use a text “REPLY” button to submit instead of the mail/paper airplane icon used before, which isn’t used anywhere else in WordPress.

![image](https://cloud.githubusercontent.com/assets/7233112/22606520/31221d9a-ea22-11e6-874e-3bc9b290089a.png)

cc: @mattmiklic

**Comment by theck13** [comment]
The only place the [send icon](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/drawable/ic_send_white_24dp.xml) is used in the app is ***Editing Comment*** screen as shown in the screenshot below.

<img src="https://user-images.githubusercontent.com/3827611/35630807-8d5df1e2-065f-11e8-99e8-5681cfb8af34.png" width="300">

Using the "REPLY" text in place of the icon in the notification may confuse users since the same text is used to trigger the inline reply interface.  That icon is set by the operating system rather than the app and it is used in notifications across Android.  See the screenshots below from the [Android documentation](https://developer.android.com/guide/topics/ui/notifiers/notifications.html#direct) for illustration.

<img src="https://user-images.githubusercontent.com/3827611/35631382-01f7342c-0661-11e8-94f5-f3864625cd97.png" width="300">

<img src="https://user-images.githubusercontent.com/3827611/35631418-159407e4-0661-11e8-83c4-0aed0277e9d2.png" width="300">

**Comment by mattmiklic** [comment]
@theck13 Yeah, seeing it in the context of a standard notification reply UI for another app, the paper plane icon makes more sense. I don't mind it there.

I actually never realized we were using it for the Edit Comment screen though -- that case _does_ feel wrong to me. The paper plane icon feels like something is being _sent_ or _delivered_, it doesn't feel right for a case where the user is saving changes to an existing bit of content. Could we change that button to simply read "Save"?

**Comment by theck13** [comment]
> I actually never realized we were using it for the Edit Comment screen though -- that case does feel wrong to me.

I didn't know either, and I agree it seems weird in that case.

> Could we change that button to simply read "Save"?

We can definitely change that button to "SAVE" text or use the [ic_save](https://material.io/icons/#ic_save) icon.

**Comment by mattmiklic** [comment]
👍 Let's go with `SAVE`; I don't mind the Material paper plane icon in notifications, since it's outside the app, but would prefer to only use Gridicons inside the app and we don't really have one that represents "save" yet (I think we've just tried to avoid the floppy disk metaphor. :))

**Comment by theck13** [comment]
That works for me.  I created a [new issue for that](https://github.com/wordpress-mobile/WordPress-Android/issues/7187) and I'll close this one.
