### ISSUE TITLE
Posting: Remember Post status when when creating new posts

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5157]
### Expected behavior
The app should remember the "post status" set the last time the user posted something and use the same status when creating a new post again unless the user change it.

Reported here: https://appbot.co/apps/723515-wordpress/reviews/375371642
> What's more, the only intuitive options for a post are "local draft" or "publish". I can't get the app to default to "draft", in which it is uploaded and able to be edited on my computer.

### Actual behavior
Post status default to "Publish"

**Comment by maxme** [comment]
I'm not 100% sure that's a good solution.

**Comment by daniloercoli** [comment]
It's fairly common in apps to remember the last "status" used by the user. For example both FB, and G+  remember the last status.

**Comment by rachelmcr** [comment]
I'm not sure that using the last status is a good way to handle the status of a new post. Depending on whether you last saved a draft or published a post, you'd get different default behavior for your new post — that could be confusing and potentially lead to mistakes if you aren't paying attention.

It might be better to offer a quick way to save a draft to the server, instead. On iOS, we did this by offering a quick action menu (e.g. if the status is Publish, a "Save as Draft" option; if the status is Draft, a "Publish Now" option): https://github.com/wordpress-mobile/WordPress-iOS/pull/6207

Another option could be to allow the user to set a default status other than Publish for all new posts. This feels more reliable than using the last post status that was used, since it would provide a consistent experience.

**Comment by daniloercoli** [comment]
> It might be better to offer a quick way to save a draft to the server, instead.
I like this option, and hope there is the space on the UI to show both the `publish` and `save draft` labels.

> Another option could be to allow the user to set a default status other than Publish for all new posts. 
I'm not in favor of another option ;)

**Comment by mattmiklic** [comment]
> It might be better to offer a quick way to save a draft to the server, instead.

My instinct is to say that anytime the user saves but doesn't publish, we automatically try to save the draft on the server. We'd only fall back to a local draft if the user is offline. Interested to know if there are any reasons why we don't already go that route, though.

**Comment by maxme** [comment]
Can we close this ticket? We'll probably implement some remote automatic saving.
