### ISSUE TITLE
Compress pictures locally before uploading to the site

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5170]
I think as a first step of "picture optimization" we should add a new setting in `site settings` that turns on/off picture compression device side (not resizing, just compression). Having it ON as default value.
We may label it `Save bandwidth`. Together with `Default Image Width` should give us enough flexibility, and save bandwidth.

We should be careful with this setting, since people may not expect we compress picture before uploading. 

*Note 1:* We should be careful when applying the compression, since we can probably easily fall on `Out of Memory` errors and such.

*Note 2:* A step further could be the removal of both those options above, and instead just add one single "optimize picture" setting. Don't know how it could fit for all blogs/sites/themes out there.

cc @SergioEstevao

**Comment by SergioEstevao** [comment]
I've discussed this before with @koke, 

At the moment on iOS we have one Slider that allows to select the pixel size of the image.

By default it chooses the Original Size, but then you can change it from 3000px down to 200px.

We discusses to change the pixel size to two options:

- Instead of pixel, use MP, 1MP 2MP, etc... because that is more related to image quality in digital cameras.
 - Instead of pixel use the WordPress Media Size Options, thumbnail, medium, large. My main issue with this settings is that by default they use very low resolution: 150px, 300px, 1024px

**Comment by daniloercoli** [comment]
@SergioEstevao  I think you are referring to this other ticket here https://github.com/wordpress-mobile/WordPress-Android/issues/2819

In this ticket we're discussing to apply compression to the picture, without changing its sizes, before uploading to the server. Mostly JPEG compression.

**Comment by SergioEstevao** [comment]
@daniloercoli thanks for the clarification, btw can you explain what kind of image compression is done on the server side? it this something that is done automatically when we upload an image using the REST API?

**Comment by daniloercoli** [comment]
We will probably rethink bottom-up the way Media are uploaded to the server. Closing this ticket here for now.
