### ISSUE TITLE
Improve the picture resize / optimize image option

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5228]
We all agreed that the current resizing options are kind of lame. 
A single `Optimize Pictures` toggle seems the way to go.  Once enabled the picture will be resized to a pre-defined size, and compressed .85 or .90 quality.  Maybe offering advanced settings for power users.

![screen-shot-2017-02-17-at-09-43-05](https://cloud.githubusercontent.com/assets/518232/23127171/4bd640d4-f77a-11e6-9f07-14fe5c5dda88.png)

Note: Would be interesting to make the option apply only if bandwidth is limited (not on wifi).

The following tickets are related, but no need to work on them if we want to pursue this way.

Ref 1: https://github.com/wordpress-mobile/WordPress-Android/issues/4241
Ref 2: https://github.com/wordpress-mobile/WordPress-Android/issues/2819

**Comment by quicoto** [comment]
**Can I upvote the advanced settings?** I think it's a great feature to allow us to fine tune the compression and specially the image width.

In my blog I do have a plugin for image compression that was worked well so far, so in my case I would not need quality compression in client (I would simply set the value to 100).

The max width, in the other hand, it's an excellent feature that we should bring back. Otherwise some WordPress instanced with a max file size (like mine) no longer can upload images from the app. The photos taken with my phone are quite big.

Thank you so much.
