### ISSUE TITLE
Draft reminder pop-up incorrectly assumes drafts were created "yesterday"

### ISSUE THREAD

**Issue by zandyring** [wordpress-mobile/WordPress-Android#5301]
### Expected behavior
The "don't forget to publish it!" pop up would know when the post was started

### Actual behavior
The pop up always thinks the post was drafted "yesterday" - I've had two reminders; the first was for a post written on Feb 16 - the pop up was Feb 24. The second was for the same post (drafted feb 16) and popped up on Feb 26 or 27 - both said "you drafted (post name) yesterday!"

### Steps to reproduce the behavior
1. start a post on mobile
2. abandon the post
3. wait until the reminder pops up

##### Tested on [device], Android [version]
Moto G (3rd Gen), Android 6.0, WP alpha-36

**Comment by zandyring** [comment]
I have a screenshot, but I cannot upload it to github for some reason today.

**Comment by zandyring** [comment]
https://cldup.com/YSvlVBSJUY.jpg

**Comment by maxme** [comment]
@mzorz can you have a look at this one? In the `fluxc-integration` branch preferably.

**Comment by mzorz** [comment]
Hello @zandyring ! Thanks for bringing this up. One thing to have in mind, is that drafts are saved and updated each time you open them and make a change, even if it's just a small change such as deleting/inserting a line or a space. The reminders functionality is set at that point for such a draft. Just to sort out this possibility, do you remember whether this could have been the case or not? In case not, do you recall at least opening the draft at any point again since the day you originally wrote it (Feb 16)? We might need to consider re-wording the message if this is the case.
Thanks in advance!

**Comment by zandyring** [comment]
Yep, I HAVE opened the draft (to test funkiness in Aztec), but I _want_ to say it was in the time before the first reminder. I am not 100% certain. I am nearly 100% certain, however, that I didn't open it between the first and second reminder. But maybe that's something that's visible in the logs to be certain?
