### ISSUE TITLE
Do not send GCM tokens for logged-out users or self-hosted ones

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5311]
It seems that we're always sending the GCM token to our backend. 
Logged out, and self-hosted users should not send the GCM token to our backend.

##### Seen in alpha-36 and FluxC integration branch.

This should be fixed in `develop`.

**Comment by daniloercoli** [comment]
cc @mzorz

**Comment by mzorz** [comment]
Closing this issue as it was observed to work correctly on both branches - I have detected though, a situation in which uninstalling the app then reinstalling it seems to be able to retrieve the old data (at least in our dev environment), thus leading to having a GCM token that is actually sent to the server.

The way I could get rid of this issue was by doing the following:

1. uninstall the app
2. power the device off
3. wait for a few minutes and turn it back on
4. re-install the app

cc @daniloercoli @aforcier
