### ISSUE TITLE
Stats are using UTC time

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5323]
### Expected behavior
Stats should use the blog's timezone setting.

### Actual behavior
It's using UTC time (not even device's time).
![screen-shot-2017-03-02-at-8-35-35-pm](https://cloud.githubusercontent.com/assets/518232/23543038/94d18c34-fff0-11e6-8cf8-af02bea33bdb.png)

I bet the blog's timezone setting returned from the blog object is incorrectly set to UTC.

##### Tested on:
- alpha-37 on a 3gen Moto G (Android 6.0),
- alpha-38, Nexus 6 with stock 7.1
- alpha-37 or -38, Nexus 5x, Android 7.1.1 (stock)

**Comment by aforcier** [comment]
> I bet the blog's timezone setting returned from the blog object is incorrectly set to UTC.

Pretty much exactly the case - we were storing the `options.timezone` field from the API but that always seems to be blank. What we actually wanted was `options.gmt_offset`, which returns a number offset (which is what the stats code was expecting anyway). Fixed that in https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/344.

(GMT was being used rather than device timezone because the timezone string was empty instead of null, so it got [this far](https://github.com/wordpress-mobile/WordPress-Android/blob/26459d24bb4ce680e6b75a80368a1195db81ca8a/WordPress/src/main/java/org/wordpress/android/ui/stats/StatsUtils.java#L159-L161) and defaulted to GMT.)

**Comment by daniloercoli** [comment]
Thanks Alex for the details. I cannot repro this issue anymore in the current `fluxc-integration` branch. Closing it!
