### ISSUE TITLE
Media - Stuck in uploading while no data connection

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5389]
When I start uploading a picture, and then turn data off **(*)**, the progress bar uploading indicator is stuck in the current position, and nothing is shown to the user.

I can wait forever, but the "Media uploading" failed event doesn't seem to be thrown from FluxC, and the UI in the Editor screen is not updated.

**(*)** do not set the phone to airplane mode, instead disable mobile data, and keep WiFi off. More or less what happens when you use your mobile device on the go.

Maybe in another PR, but we should also test what happens when the upload starts over a WiFi connection, and then the WiFi is turned off but GSM data connection is available.

Tested on 7.0-rc1

**Comment by designsimply** [comment]
I tested this using WPAndroid alpha-171 on Pixel 3 Android 9 today and found that if I turn off data and WiFi during an image upload I see a message that says, "Failed to insert media. Please tap to retry." I see the same result in both Aztec and the block editor. When I turn data or WiFi back on, the image proceeds to update normally on it's own or I can tap either the system notification to retry.

<img src="https://user-images.githubusercontent.com/1119271/58993325-7514d380-87aa-11e9-8f52-1c0536a026d4.png" width="200" alt="Screenshot_20190605-154613"> <img src="https://user-images.githubusercontent.com/1119271/58993330-780fc400-87aa-11e9-8fe4-19c6d64a7e76.png" width="200" alt="Screenshot_20190605-154648"> <img src="https://user-images.githubusercontent.com/1119271/58993337-7d6d0e80-87aa-11e9-8122-0abbef05639f.png" width="200" alt="Screenshot_20190605-154702">

<img src="https://user-images.githubusercontent.com/1119271/58993343-7fcf6880-87aa-11e9-8817-744975e81ed8.png" width="200" alt="Screenshot_20190605-155213"> <img src="https://user-images.githubusercontent.com/1119271/58993345-82ca5900-87aa-11e9-820b-0e9df6d36f10.png" width="200" alt="Screenshot_20190605-155220"> <img src="https://user-images.githubusercontent.com/1119271/58993347-85c54980-87aa-11e9-9249-a6ccfd5db925.png" width="200" alt="Screenshot_20190605-155249">

Closing because the issue has been inactive, is old, and I was unable to replicate the problem. Please re-open if you find this happening again!

**Comment by designsimply** [comment]
Aside: while the editor image worked normally in my testing, the system notification still got stuck and we are tracking that in a separate issue at https://github.com/wordpress-mobile/WordPress-Android/issues/9802.
