### ISSUE TITLE
Tap 'Add Media' button twice creates two overlapped media options view

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5398]
### Expected behavior
Only one insert media option view presented

### Actual behavior
Two insert media option view overlapped each other

### Steps to reproduce the behavior
From Android app, create a new post. Tap twice on the `Insert Media` button **quickly**. It brings two insert media option view that overlaps each other.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

![twice](https://cloud.githubusercontent.com/assets/1484624/23935129/4e33c826-0907-11e7-8786-1c1d954f5ba6.jpg)

**Comment by BoKKeR** [comment]
Cant reproduce or I am not seeing it. 

![2018-04-09_15-07-40](https://user-images.githubusercontent.com/2664857/38499522-1e9cfa8a-3c08-11e8-83a6-180a25a1d140.gif)

**Comment by designsimply** [comment]
I tested tapping the `Insert Media` "+" icon twice very quickly in the classic editor (Aztec) using WPAndroid alpha-191 (13.4 alpha) on Pixel 3 Android 10 and I wasn't able to see two overlapping insert media views. I know that a lot of changes have been made to the editor since your original post! So it's possible the issue was resolved during one of those updates. If you can still see the problem happening in a recent version of the app though, please make a note in the comments and we can take another look. Thank you for the report!
