### ISSUE TITLE
No Cancel option during the gallery creation process

### ISSUE THREAD

**Issue by chenchaoyi** [wordpress-mobile/WordPress-Android#5400]
### Expected behavior
Able to Cancel in the middle of gallery creation

### Actual behavior
Once started, always go to the edit step no matter if there is image selected or not

### Steps to reproduce the behavior
There is no **Cancel** option after the user clicks on `insert media` and start the gallery creation process.

If a user decides to abort the process and go back to edit the new post, it still goes to the `Edit gallery` step, even when no image is selected, which is quite confusing.

##### Tested on [device], Android [version]
- WorePress Android App **Version 6.9** 
- **Samsung Galaxy S5**, 
- **Android version 6.0.1**

<img width="273" alt="nocancel" src="https://cloud.githubusercontent.com/assets/1484624/23935282/5f8b921a-0908-11e7-8892-e67464848c0c.png">

**Comment by daniloercoli** [comment]
Thanks for reporting this @chenchaoyi!

We've decided to remove the `Media Gallery` feature from the app, since it's not in a good state, and we are not providing a nice experience to our users.
We're are working hard on improving Media, and among other things, we will revisit the gallery feature bottom-up. Unfortunately no ETA at the moment.

**Comment by chenchaoyi** [comment]
Thanks @daniloercoli 
The Media Gallery feature is still quite nice. I myself find it quite useful (and wish the iOS app had similar feature), and quite usable too (given some parts could use some polish). Looking forward to the improvement!

**Comment by nbradbury** [comment]
Closing this since gallery creation was rewritten in #5805
