### ISSUE TITLE
Add ability to Search Comments

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5510]
Remotely for jetpack/.com sites and locally only for self hosted (unless we find a trick with a XMLRPC call).

**Comment by tonyr59h** [comment]
I'm actively tackling #62, but since this is going to be a pretty similar implementation I'll assign it and work through it after the post search is merged.

**Comment by tonyr59h** [comment]
The REST API doesn't provide support for this feature at the moment. We can support searching locally with a bit of work, but implementing it would require downloading all Comments before searching and that might be a bit overkill on the bandwidth.

I've put in a ticket to update the endpoint. Going to hold off on this issue till we hear back.

**Comment by tonyr59h** [comment]
Remove the LHF label since it requires more work than we thought with the API change.

**Comment by designsimply** [comment]
I checked back in on Calypso to see if comment search is available at this time, and it is not. 

<img src="https://user-images.githubusercontent.com/1119271/67593332-36fb5a80-f71f-11e9-894a-5eed974411ff.png" width="600" alt="comments screen">

I also found the request to update the WordPress.com REST API Comments endpoint to allow searching comments (internal reference: p3hLNG-U3-p2), and the response there says that teams are responsible to write/modify the endpoints they need so someone would need to do that work first in order to unblock this request.

**Comment by designsimply** [comment]
Tested and confirmed this issue is still valid and searching comments is still not available on Calypso.

<img src="https://user-images.githubusercontent.com/1119271/99438732-09082b80-28c9-11eb-8789-626c062dd031.png" width="600" alt="image">

<sup>Comments screen in Calypso as of 2020-11-17 viewed using Firefox 82.0.3 on macOS 10.15.6 with a WordPress.com Free site using a free .blog subdomain.</sup>

Noting there's also an open issue in the `wp-calypso` repo at https://github.com/Automattic/wp-calypso/issues/13901 noting the desire to add an endpoint that would allow searching comments.

**Comment by thehenrybyrd** [comment]
Search is still not available in Calypso. Given that, and the fact we've had no reported user requests for this to date, I'm closing this issue. Feel free to reopen if necessary!
