### ISSUE TITLE
New adaptative launcher icon for Android O

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5529]
See https://developer.android.com/preview/features/adaptive-icons.html

**Comment by oguzkocer** [comment]
@mattmiklic & @bysl When one of you have time, could you prepare the new icons? The relevant section from that documentation seems to be the one below, but it's a short doc, so it might be a good idea to check the whole thing out. Thanks!


    In previous versions of Android, launcher icons were sized at 48 x 48 dp. You must now size your icon layers using the following guidelines.

    Both layers must be sized at 108 x 108 dp.
    The inner 72 x 72 dp of the icon appears within the masked viewport.
    The system reserves the outer 36 dp on each of the 4 sides to create interesting visual effects, such as parallax or pulsing

**Comment by maxme** [comment]
cc @jasmussen because he has some opinions about launcher icons in Android ;)

**Comment by jasmussen** [comment]
Thanks so much Maxime! I _do_ love icons, and I'd also love to help here if you need anything. I've got all the templates running regardless.

And short answer, aside from icons having to look good, I'm a big fan of following platform rules, so we should absolutely embrace the cool new stuff in O!

In this case it's going to be an interesting challenge that will require some noodling. The guidelines would suggest we scale down the white WordPress logomark on a blue badge, so it can "float on it" and the blue background would then be masked and badged by the system. Only — our icon is _round_, and the blue badge is part of our icon. In a way the blue badge PLUS the white logomark should not really be changed. In other words — we might want to do something like the following. If round icons are requested:

<img width="189" alt="screen shot 2017-03-30 at 11 11 14" src="https://cloud.githubusercontent.com/assets/1204802/24496929/0c283310-153a-11e7-8ccb-da93da10fc69.png">

If squircle icons are requested:

<img width="340" alt="screen shot 2017-03-30 at 11 13 38" src="https://cloud.githubusercontent.com/assets/1204802/24496934/10642f42-153a-11e7-9e87-c6e432c54aad.png">

I'm not a fan of putting the logo on a pedestal, though. We may want to do what we do on iOS and just embrace the blue:

<img width="322" alt="screen shot 2017-03-30 at 11 18 43" src="https://cloud.githubusercontent.com/assets/1204802/24497117/a7c31538-153a-11e7-9b1a-f858b41d09cc.png">

But what we should _NOT_ do, is the following:

<img width="312" alt="screen shot 2017-03-30 at 11 19 16" src="https://cloud.githubusercontent.com/assets/1204802/24497133/ba7ad800-153a-11e7-901c-5132dd99e201.png">

I guess what I'm saying is — it's not as easy as just upgrading our icon. It will need a little noodling. I don't know for sure that i have time to do so, and I know it's in the best possible hands with @mattmiklic, but I'd like to at the very least offer all the advice I can, so feel free to ping me any time. 

Sidenote: Google will encounter the same issue with their Chrome icon, which is already round. I'd love to see what Google is going to do for launchers that request squircles, like the Samsung launcher. Will they pedestal it? And if yes, will they pedestal it even when requested on a round icon? Time will tell.

**Comment by mattmiklic** [comment]
Thanks for weighing in here @jasmussen.  Agree with all the points you made. I noticed this in the documentation:

> You can also define an icon drawable resource using the android:roundIcon attribute. You must only use this attribute if you require a different icon asset for circular masks, if for example the branding of your logo relies on a circular shape. 

So it sounds like we can provide a separate circular icon for the launchers that use them, and provide the two-layer version for those that request other shapes. In that case, I'd probably go with your "embrace the blue" example above. That way I think the icon appears most consistently between platforms; always a white W on a blue background, regardless of shape.

I can take a look at this on an upcoming design groundskeeping day.

**Comment by maxme** [comment]
Just a note: this is super low priority, we have 6 months until the launch of Android O ;)

**Comment by oguzkocer** [comment]
I am just going to un-assign this for now then. I am glad the design discussion has started though, it'll move quicker when we get to it!

**Comment by jasmussen** [comment]
> So it sounds like we can provide a separate circular icon for the launchers that use them, and provide the two-layer version for those that request other shapes. In that case, I'd probably go with your "embrace the blue" example above. That way I think the icon appears most consistently between platforms; always a white W on a blue background, regardless of shape.

Yep that sounds like a good approach, though I do think that the badging/masking in Android O is essentially admitting defeat on the past efforts. And so I'm not _convinced_ that the roundIcon will stay around indefinitely. This is why it'll be so interesting to see what Google does with the Chrome logo. But sounds like you have totally the right instincts in any case, and let me know if I can help.

**Comment by bysl** [comment]
I agree 'embrace the blue' would adapt the best and be most on brand.

**Comment by theck13** [comment]
### Chrome
Chrome's icon has been updated for Oreo!  They are using default and round versions which are both the new adaptive icon style.  The default version uses the legacy icon as the foreground and the color white as the background.  That results in these variants.

<img src="https://user-images.githubusercontent.com/3827611/31460890-fc38b850-ae84-11e7-9a65-3cb215a12b74.png">

The round version's foreground is transparent and the background basically extents the legacy icon's design into a square which ends up looking exactly like the legacy icon.

Foreground | Background | Result
-|-|-
<img src="" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31460411-989ef8b4-ae83-11e7-8571-b39aa97ebb5f.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31460405-947522cc-ae83-11e7-9cc2-c908fed440e7.png" width="48px">

### Others
I reviewed three other Google apps with intrinsically circular icons to see how they handle this.  Two of them (i.e. Authenticator and Earth) don't have adaptive _or_ round icons defined which means they either haven't been updated for Oreo or they don't care.  The third (i.e. YouTube Music) doesn't have an adaptive icon, but it does have a round icon with the white background like Chrome's adaptive icon which means they probably just haven't updated it to be adaptive.  See the table below for a visual breakdown of these three.

App | Default | Round | Adaptive
-|-|-|-
Authenticator | <img src="https://user-images.githubusercontent.com/3827611/31458325-fcf2833c-ae7c-11e7-9fb9-52379ebca437.png" width="48px"> | N/A | N/A
Earth | <img src="https://user-images.githubusercontent.com/3827611/31458404-3d58622a-ae7d-11e7-8446-29760191a480.png" width="48px"> | N/A | N/A
YouTube Music | <img src="https://user-images.githubusercontent.com/3827611/31458437-5844c04c-ae7d-11e7-8605-1840e4252726.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31458442-5c978864-ae7d-11e7-9996-47a9b0e0aaed.png" width="48px"> | N/A

### WordPress
Personally, I think the white background with a circular logo on a pedestal like the Chrome and YouTube Music icons looks weird as well.  I think the "embrace the blue" is the way to go too.  We can use the white W with the blue background as the default version and our legacy icon for the round version.  That would result in these variants.

#### Default (Adaptive)
<img src="https://user-images.githubusercontent.com/3827611/31461730-9a9cad06-ae87-11e7-996e-07cee43503bc.png">

#### Round (Legacy)
<img src="https://user-images.githubusercontent.com/3827611/31461835-e50ccdee-ae87-11e7-8832-a0091913a6aa.png" width="48px">

#### Pro Tip
Click the icons to see them a little larger.

**Comment by jasmussen** [comment]
Thanks for the research, @theck13. 

Is it technically possible to do the following using adaptive assets (white logo foreground, blue background):

<img width="189" alt="0c283310-153a-11e7-8ccb-da93da10fc69" src="https://user-images.githubusercontent.com/1204802/31482338-2fa95ae8-af28-11e7-9ff8-4817e9e538a5.png">

That is — have the foreground sized up so it looks exactly like the legacy roundicon? 

And if yes, how would that look with squircles, rounded squares and squares?

I think we should avoid the following, if at all possible:

<img width="130" alt="screen shot 2017-10-12 at 08 35 06" src="https://user-images.githubusercontent.com/1204802/31482365-493e31e0-af28-11e7-9e64-b6071a9eadcf.png">

**Comment by theck13** [comment]
Going to the very edge of the "safe" area (which is very hard to see, but it's the light gray circle on the outer edge of the logo) results in these variants.

<img src="https://user-images.githubusercontent.com/3827611/31509500-f5579988-af3e-11e7-8cff-42dc541fbc6f.png">

I think that makes the circle version close to your preferable example.  What do you think of the other variations?

**Comment by jasmussen** [comment]
Thanks a bunch for testing that out, really appreciate it. Yeah, it makes the circle version work well for us, but all the other ones are kinda terrible alas. 

Tricky.

**Comment by theck13** [comment]
YouTube Music updated their icon today.  Here's the rundown.

App | Default | Round | Adaptive
-|-|-|-
YouTube Music | <img src="https://user-images.githubusercontent.com/3827611/31799554-004917fe-b4f8-11e7-90bb-1748418aec82.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31799399-209ee76e-b4f7-11e7-8eb6-48ad04bb4d20.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31799554-004917fe-b4f8-11e7-90bb-1748418aec82.png" width="48px">

It's not my favorite.  Why they didn't go with this, I don't know.

Foreground | Background | Result
-|-|-
<img src="https://user-images.githubusercontent.com/3827611/31799757-56841a82-b4f9-11e7-8081-90e8f342fac5.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31799751-4d86e072-b4f9-11e7-9a66-12e345c5bd8c.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31458437-5844c04c-ae7d-11e7-8605-1840e4252726.png" width="48px">

**Comment by jasmussen** [comment]
Thanks for the screenshots, @theck13 — can you clarify a little bit the top table for music, though? 

Default/round/adaptive — does that mean every Oreo device with the pixel launcher (and presumably future launchers) will show only the adaptive icons? 

I'm asking because if there's a way to have a dedicated round-icon, and then _adaptive for the rest_, that could be a great solution.

**Comment by jasmussen** [comment]
I noticed today that the Android Clock app has both an adaptive icon, and one that goes almost edge to edge without being ugly in non-circle versions. Behold:

![screenshot_20171027-100249](https://user-images.githubusercontent.com/1204802/32093956-8b380210-bafe-11e7-8534-77ae4d27b5b9.png)

![screenshot_20171027-100306](https://user-images.githubusercontent.com/1204802/32093963-8f7c22a2-bafe-11e7-9622-be1e61b0f22d.png)

![screenshot_20171027-100318](https://user-images.githubusercontent.com/1204802/32093969-92bcfdf6-bafe-11e7-83da-ed56043fcf09.png)

![screenshot_20171027-100329](https://user-images.githubusercontent.com/1204802/32093970-95753004-bafe-11e7-81f4-6b56a0ee794d.png)

![screenshot_20171027-100341](https://user-images.githubusercontent.com/1204802/32093971-98177b6e-bafe-11e7-9c34-a0141e5e0c2c.png)

Since they're Google, it's possible they do some technical wizardry to make this work — after all, [the clock app is now animated which requires launcher support](http://www.androidpolice.com/2017/06/26/android-o-will-introduce-animated-clock-app-icon-launchers/). But if there's any chance we can utilize some of the tricks they use, I think the above is an example that the _really big WordPress shape on a blue background_ might just work fine for us. Please compare the clock icon in the various shapes, and imagine the WordPress logo on a blue similar shape — I think it could work. Thoughts?

By the way, I just noticed a fun benefit of the adaptive icons — when you shake them they wiggle ;)

![wigglyshake](https://user-images.githubusercontent.com/1204802/32093799-f9895ab2-bafd-11e7-8c71-56092aca745d.gif)

**Comment by theck13** [comment]
### Clock

It looks like the blue circle of the Clock icon has the same padding for all variants (i.e. 8 pixels), which is a little more than the white logo on the WordPress icon (i.e. 6 pixels).  Are you suggesting just adding a little more padding to this?

<img src="https://user-images.githubusercontent.com/3827611/31509500-f5579988-af3e-11e7-8cff-42dc541fbc6f.png">

One of the cool features of adaptive icons is that they can animate like you saw with the wiggle.  That's why there is a designated safe area in the design to allow for those visual effects.  [This post](https://medium.com/google-design/designing-adaptive-icons-515af294c783) by a Googler about designing adaptive icons has some really good information.  I especially like the ***Background Anchoring*** and ***Leave Behinds***.  I'm not sure we can do much with the WordPress logo, but those are cool nonetheless.  The post also has an [Adaptive Icon Playground app](https://github.com/nickbutcher/AdaptiveIconPlayground/releases), which shows all the adaptive icons on your device and allows you to change the icon mask as well as modify the strength of the visual effects.

### Combination

My reply below has been sitting as a draft and I was waiting for a reply to [my inquiry](https://medium.com/@heckofanapp/regarding-round-icons-does-this-statement-imply-roundicon-will-override-icon-for-all-launcher-mask-c1f259efad8a) from an Android Framework Developer at Google before publishing, but I haven't received a response yet.

> can you clarify a little bit the top table for music, though?
> 
> Default/round/adaptive — does that mean every Oreo device with the pixel launcher (and presumably future launchers) will show only the adaptive icons?

I copied that table from the ***Others*** section in my original comment.  Sorry for the confusion.  It would be better if it was like this.

App | Default | Round
-|-|-
YouTube Music | <img src="https://user-images.githubusercontent.com/3827611/31799554-004917fe-b4f8-11e7-90bb-1748418aec82.png" width="48px"> | <img src="https://user-images.githubusercontent.com/3827611/31799399-209ee76e-b4f7-11e7-8eb6-48ad04bb4d20.png" width="48px">

The ***Default*** version in this table uses the adaptive icon style.  The ***Round*** version is the legacy icon style.

> I'm asking because if there's a way to have a dedicated round-icon, and then _adaptive for the rest_, that could be a great solution.

Yes, we can use different designs for a round icon (i.e. `android:roundIcon` in code) and default/other icons (i.e. `android:icon` in code).  That's what I meant in the ***WordPress*** section of my original comment, but it wasn't very clear.  From the [Android adaptive icon documentation](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html#creating_adaptive_icons_in_xml), it says:

> You can also define an icon drawable resource using the `android:roundIcon` attribute.  You must only use the `android:roundIcon` attribute if you require a different icon asset for circular masks, if for example the branding of your logo relies on a circular shape.

Technically, both icons could be the adaptive style as well with the round version only using the circle adaptation.  If we go to the very edge of the safe area with the round version and keep 25% padding with the default version, it would look something like this.

<img src="https://user-images.githubusercontent.com/3827611/31910400-98e09118-b7fa-11e7-8e64-37c371263ad8.png">

### Conclusion

I would like to have the best of both worlds and get the results shown above, but I haven't been able to get the behavior in practice.  If I don't get a reply to my inquiry and I can't figure out why it's not working, we may have to go with the extra padding like the Clock app if we want to use adaptive icons.  If I do get a reply or something changes, I'll share it here.

**Comment by mattmiklic** [comment]
> Technically, both icons could be the adaptive style as well with the round version only using the circle adaptation. If we go to the very edge of the safe area with the round version and keep 25% padding with the default version, it would look something like this.

That seems like the result we want, I think. Thanks for checking with Google about why that's not working.

@jasmussen if there's something preventing that approach from working in the current version of Android, do you think we should keep the existing icon until it works, or go with the less-than-perfect adaptive version? I don't have a good sense of how important the adaptive icons are to users yet. Obviously it's only an issue on Oreo devices, but it seems like those users might be the most discerning, too.

**Comment by jasmussen** [comment]
> @jasmussen if there's something preventing that approach from working in the current version of Android, do you think we should keep the existing icon until it works, or go with the less-than-perfect adaptive version? I don't have a good sense of how important the adaptive icons are to users yet. Obviously it's only an issue on Oreo devices, but it seems like those users might be the most discerning, too.

An adaptive icon is absolutely going to make those looking for it happy. But I do agree we shouldn't rush it, as honestly it feels like Google has with some of their icons. 

I have Android Studio set up, I think I should be able to fiddle around a bit and test in an emulator. I feel like we are pretty dang close to striking a balance, like the clock does, that would work for us. I may get time to fiddle with this some time this week, or the next.

**Comment by theck13** [comment]
I received [a response](https://medium.com/@ianhlake/on-a-device-that-uses-roundicon-that-roundicon-will-always-be-used-youll-note-that-there-are-ef59a2df4c60) from [my inquiry](https://medium.com/@heckofanapp/regarding-round-icons-does-this-statement-imply-roundicon-will-override-icon-for-all-launcher-mask-c1f259efad8a).  Evidently, the wording on the Android documentation is a little misleading.  We can't have different adaptive icons for `roundIcon` and `icon`.  Our options are:
1. Keep the non-adaptive legacy icon.
2. Use a less-than-perfect adaptive icon.

**Comment by jasmussen** [comment]
I created a new adaptive icon PR (#6867) where I have a logoshape margin that matches that of the outer ring of the WordPress logo. That means the round version of the icon looks exactly like the `roundIcon` we have now.

The question again becomes whether the other versions of the icon look good. As I note in the PR, that outer padding is 3dp. Should we try a version with 4dp, which I think is what the clock icon uses?

CC: @mattmiklic @theck13
