### ISSUE TITLE
Reverse the order of Publish  & undo/redo buttons

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#5592]
Move the Publish/Update button to the right, and set the undo/redo button left to it so the buttons don't jump when opening post settings.

![image](https://cloud.githubusercontent.com/assets/1522856/24775649/0a9a5f48-1b1e-11e7-9ea8-09a40de36426.png)

![image](https://cloud.githubusercontent.com/assets/1522856/24775652/0d4a42a8-1b1e-11e7-895f-ccb380744375.png)

**Comment by maxme** [comment]
@iamthomasbishop can you help us with that one? We're not sure where to put the undo / redo buttons.

**Comment by 0nko** [comment]
iOS doesn't have it because it's not working properly yet, but it's planned and it's actually one of the highlight features of Aztec over the hybrid editor.

**Comment by iamthomasbishop** [comment]
Fair enough. Fwiw, I can certainly understand that `undo` is the sort of feature that while perhaps not needing premiere placement, could be a life saver in some cases.

**Comment by iamthomasbishop** [comment]
Also worth noting that iOS has an OS-level undo gesture (shake device to undo).

**Comment by rachelmcr** [comment]
The undo/redo buttons (and other actions besides the primary action, e.g. Publish) are now hidden in an ellipsis menu. There's still a small shift when switching to the post settings (because the ellipsis menu doesn't appear there) but it isn't the drastic jump that was happening before.

Closing this as resolved, but please reopen if there's something more to be done here.
