### ISSUE TITLE
The corresponding HMAC for this files does not match

### ISSUE THREAD

**Issue by Alphaz74** [wordpress-mobile/WordPress-Android#5704]
### Expected behavior
Just upload the damn pictures with their original size

### Actual behavior
Error message : The corresponding HMAC for this files does not match

### Steps to reproduce the behavior
Try to upload a photo from the gallery of my mobile

##### Tested on [device], Android [version]
Samsung Galaxy S4, Android 5.0.1
WordPress App version 4.2

The toggle to optimize pictures is enabled. Why can't I just upload the file and why can't I set the optimize settings anymore?

Many thanks in advance for the help

**Comment by maxme** [comment]
Related: https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/402

**Comment by Alphaz74** [comment]
THanks for the response, but I'll try to edit the php.ini file and remove the restriction in order to upload a file of 50MB if I want to.  
The link provided points to something that does not propose a solution.

**Comment by kristyrobledo** [comment]
So bloody frustrating. I have an iPhone 6plus, wordpress 7.9. Same option is checked and have extensively troubleshooted. Please advise when I can use the application.

**Comment by designsimply** [comment]
@Alphaz74 @kristyrobledo I'm looping back to check up on the problem you reported where you saw the error "The corresponding HMAC for this files does not match" when trying to upload photos. I tested the linked issue and found that you are right that the linked issue didn't provide a solution, but the comment was just noting that it's relevant which is a good and helpful thing to do for later triage or debugging. I did also try testing uploads larger than the php.ini limit and I couldn't get the HMAC error message you noted to show up. I tested with version 13.5-rc-1 of the app.

If you are still experiencing this issue in the WordPress for Android app, could you let me know if you can think of any other details that might be helpful in trying to figure out why you're seeing that message and I'm not? Is it possible you're using a plugin and there's a conflict or that your web host has added restriction that is not typical and could be blocking file transfers somehow?

**Comment by designsimply** [comment]
I regret that we weren't able to be more helpful with this case when it came up before. I have re-tested using the latest beta (16.2-rc-1) and I was still not able to replicate the problem. 

My testing steps:

1. Set up a Jetpack site and use php.ini to set `upload_max_filesize = 1M`.
1. In the app, go to My Site > Account > App Settings and enable the "Optimize Images" setting.
1. Go to My Sites > Media.
1. Try to upload an image larger than 1MB.

**Result:** when I try to upload an image larger than the max upload file size set by the server I don't see an HMAC-related error message but I do see an expected error letting me know "File exceeds the maximum upload filesize" and when I try to upload an image that's an allowed size smaller than the max filesize setting on the server it works normally. ([30s](https://cloudup.com/ce70v7TeyKZ))

<sup>Tested with WPAndroid 16.2-rc-2 on Pixel 3 Android 11.</sup>

We've made several updates to the media picker in the app since this issue was originally reported. Because of that and because I haven't been able to replicate the problem in testing based on the information provided, I am closing this issue with a note to say that we can re-open it if you still think it's a problem or if you think I've missed something in my tests. Apologies for the frustration!
