### ISSUE TITLE
7.2: Missing title and part of the content - New post in the (old) visual editor

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5753]
It seems there are "content loss" issues in the old visual editor, writing a new post or modifying an existing one.

**New post**
Title is missing and part of the body is also missing:
https://cloudup.com/c5m5vFU83Sg

**Edit post**
Can't add new content to the body:
https://cloudup.com/cH7FQt1IrzM (Sorry for the long video, in which I repeat the same action 3 or 4 times).

**Comment by aforcier** [comment]
Hmm, I can't reproduce the first case (new post) on `alpha-50`, Android 7.1.2. I'll try the second case too.

Is this on a device or an emulator @daniloercoli?

**Comment by daniloercoli** [comment]
It's a real device running Android 5.0.2. Wiko Ridge 4G.

I can repro the issue on the current version of wp-android `7.2`.

**Comment by aforcier** [comment]
Can reproduce on a `5.0` emulator 👍 looks like a threading issue with the WebView, narrowing it down.

**Comment by aforcier** [comment]
Findings so far:
1. There are simpler ways to reproduce this: start a new post, type something, and Publish - you'll get a 'cannot publish empty post message'
2. I'm able to reproduce this consistently on 5.0 and 4.1 emulators, but not on 5.1 or later (or 4.4.4)

The issue was introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/4305 - certain calls to `getContent()` and `getTitle()` that were running on worker threads are now on the UI thread. This isn't always a problem, but the visual editor has to [fetch the field data asynchronously](https://github.com/wordpress-mobile/WordPress-Android/blob/8c6ba3d344e29000045540bdc763e752c6de5021/libs/editor/WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java#L990-L1007) from the `WebView`, and it's down to the `WebView` internals whether this ends up blocking the UI thread or not. I'm not sure if this can affect Android versions other than `5.0.x` and `4.1`.

This bug was introduced in `7.2` - I think it's probably worth a hotfix.

**Comment by daniloercoli** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5754
