### ISSUE TITLE
Problem image upload with website and htaccess protection (http auth)

### ISSUE THREAD

**Issue by LiloBzH** [wordpress-mobile/WordPress-Android#5800]
Hi

Since some months, there is a bug when uploading image with android application.
If website has auth protection with an htaccess, image is uploaded but parameters of image are brocken in the page .

Exemple 
`<a href="https://toto.com/wp-content/uploads/2017/04/20170430_101658.jpg"><img class="alignnone size-large wp-image-1814" src="https://toto.com/wp-content/uploads/2017/04/20170430_101658-1024x768.jpg" alt="" width="0" height="0" /></a>`

Problem => **width="0" height="0"**

Thanks

-------------

Wordpress 7.2 (last)
Android 6 and Android 7

**Comment by LiloBzH** [comment]
youhou ?

**Comment by LiloBzH** [comment]
Someone read this github ?....

**Comment by LiloBzH** [comment]
very reactive... Thank you wordpress

**Comment by rachelmcr** [comment]
Thanks for the report! My apologies for the delayed reply. We are tracking this issue here:

https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/444

However, we also launched a new editor (currently in beta), if you'd like to try it out and see if it works better for you. You can go to Me (the person icon) > App Settings > Set editor type and select "Beta" to try it out.

**Comment by LiloBzH** [comment]
It's ok  with Beta editor. . Thank's
