### ISSUE TITLE
Tags v2

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5921]
This is a great design, but since post settings is going through a big design update we want to release it as soon as we can. Once post settings re-design is completed, we can go back to this.

![tags](https://cloud.githubusercontent.com/assets/662023/26366456/db22ce58-3ff3-11e7-986a-412dc56b7bcd.png)

**Comment by tonyr59h** [comment]
I'm going to leave some relevant notes from my review of #5932 here:

* Adding a space after a comma shouldn't include that space character as part of the search since it filters out all single word tags
* Should Enter save tags and return? Felt natural when testing and the back button didn't assure me that my tags would be saved

**Comment by oguzkocer** [comment]
* We should consider how we want to handle duplicate tags in the UI

**Comment by tonyr59h** [comment]
* The separator [extends to the end](https://cldup.com/FB31z8jbCG.png) on the right, but has padding on the left
