### ISSUE TITLE
Add Settings Button to Notifications

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#5922]
In Calypso web we recently added a settings button to the first time grouping, to make it easier to navigate to the notification settings:

<img width="412" alt="screen shot 2017-05-23 at 1 46 04 pm" src="https://cloud.githubusercontent.com/assets/789137/26375587/66255e3e-3fbe-11e7-8647-0fbed7fe55fc.png">

Should we add this to the app as well?

**Comment by iamthomasbishop** [comment]
We've heard from users that this is an expected location when tasked with finding Notification Settings. So I'm going to re-open this issue in order to get it prioritized. 

Here is the proposed design (Android and iOS):

![image](https://user-images.githubusercontent.com/1200432/57023926-f64fd800-6bf8-11e9-8cfd-5039ab4abeba.png)

Adds a simple Settings (`gridicons-cog`) icon to the App Bar that provides quick access to Notification Settings.

**Comment by iamthomasbishop** [comment]
We've heard from users that this is an expected location when tasked with finding Notification Settings. So I'm going to re-open this issue in order to get it prioritized. 

Here is the proposed design (Android and iOS):

![image](https://user-images.githubusercontent.com/1200432/57023926-f64fd800-6bf8-11e9-8cfd-5039ab4abeba.png)

Adds a simple Settings (`gridicons-cog`) icon to the App Bar that provides quick access to Notification Settings.

**Comment by planarvoid** [comment]
It is already present in the Android app. Can I close this issue @iamthomasbishop ?

**Comment by iamthomasbishop** [comment]
Yup this was part of that recent work, can close this one.
