### ISSUE TITLE
Default Post Format should be set while instantiating a new post

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#6044]
We currently retrieve the default post format from the `SiteSettingsInterface` as can be seen from [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L301-L308). However, this only works if the user has opened the Site Settings page first and at least tapped on the default post format once. We should re-fetch the site settings before creating a new post and make sure the default post format is up-to-date. This setting is meaningless if it doesn't work properly for new posts and if we default to "Standard" as the first option.

This should be done before the Post Settings revamp is finished.

/cc @tonyr59h

**Comment by tonyr59h** [comment]
> We should re-fetch the site settings before creating a new post and make sure the default post format is up-to-date.

Rather than having it re-fetch the settings every time a post is created, which could happen without a network connection, I think we should force a fetch of the settings after a successful login. That way we'll know they're connected and it will only need to fetch them once instead of every time a new post is created.

> This setting is meaningless if it doesn't work properly for new posts and if we default to "Standard" as the first option.

I agree that it's meaningless if not working but I think `Standard` is an acceptable fallback _just in case_ (bugs happen).

**Comment by tonyr59h** [comment]
On second thought, if we only do it at login we won't pick up any changes that may have happened since logging in...Probably best to just make the call when creating a post in that case.

**Comment by tonyr59h** [comment]
Leaving a reminder here: I've got a working solution on [this branch](https://github.com/wordpress-mobile/WordPress-Android/tree/issue/6044-pre-fetch-default-post-format) that you can add to the settings feature branch so we can avoid conflicts.

**Comment by tonyr59h** [comment]
Closed via #6083.
