### ISSUE TITLE
Remove duplicate string resource values to reduce translation load

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6066]
[Some](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L41) [of](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L1539) [our](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L1541) [string](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L1538) [resource](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L236) [values](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L239) [are](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L223) [duplicates](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/values/strings.xml#L186). We can simplify the translations by referencing a common string (that is translated) and adding `translatable="false"` with the added benefit of a smaller APK.

**Comment by catehstn** [comment]
So this is true, and the strings.xml does not include a description (which it should). BUT - just because the strings are the same in one language, doesn't mean they are the same in all languages. E.g. in English a "post" can be to post or a post. In French a post is "un article" and to post is "publier".

I very much doubt this will make a significant difference to APK size.
