### ISSUE TITLE
Outdated description WordPress.com Plans 

### ISSUE THREAD

**Issue by formosattic** [wordpress-mobile/WordPress-Android#6074]
### Expected behavior
I expect to see information matching what's on https://wordpress.com/pricing/
![fireshot capture 16 - wordpress com plans i wordpress com store - https___wordpress com_pricing_](https://user-images.githubusercontent.com/15944096/27181041-2053238a-51d6-11e7-81fe-a336946e8f86.png)

### Actual behavior
Outdated info, for example:

- Chat support missing in Personal plan
![photo_2017-06-15_14-27-05](https://user-images.githubusercontent.com/15944096/27181191-c350a5b2-51d6-11e7-92fa-82b89ae5df4f.jpg)

- Unlimited premium themes missing in Premium plan
![photo_2017-06-15_14-27-18](https://user-images.githubusercontent.com/15944096/27181199-ca0c0f7c-51d6-11e7-9218-0f331ef88168.jpg)

- Install third-party plugins and themes missing in Business plan
![photo_2017-06-15_14-27-12](https://user-images.githubusercontent.com/15944096/27181202-d33020c0-51d6-11e7-8da3-cfc283d51d84.jpg)

##### Tested on [device], Android [version]
Android S7 Edge, Android 7.0

**Comment by rachelmcr** [comment]
Related discussion on Plans & API (internal ref): p58i-6hy-p2

**Comment by nellofn** [comment]
Just a heads up that a user contacted us (280872-h) asking as to whether or not they could add music files to their site under a Free plan, given that the Plans description displays a wrong “space” description.

I expected the Plans page to match what's on https://wordpress.com/pricing/

#### Tested on Android (9.9)

**Comment by planarvoid** [comment]
The information we're showing is coming from these endpoint - 
https://public-api.wordpress.com/rest/v1.2/sites/{siteId}/plans?locale=en_US
https://public-api.wordpress.com/rest/v1.2/plans/features/?locale=en_US . In order to fix the plans info in the app we need to change the endpoints. 

I'd strongly suggest to completely rewrite the current plans to match Calypso.

The current differences:

Free plan - **id 1**
* Featured - "free-blog", "space", "support"

Missing: 
* Jetpack Essential Features
* Dozens of Free Themes
Needs changes:
* WordPress.com Site - Your own space to create posts and pages with basic customization.
  - WordPress.com Subdomain
  - Basic Design Customization

Personal plan - **id 1009**
* Featured - "no-adverts\/no-adverts.php", "custom-domain", "support"
* Included in all plans: "free-blog"

Missing: 
* Jetpack Essential Features
* Email and Live chat support 
* Dozens of Free Themes
Needs rewording - the same as the Free plan

Premium plan - **id 1003**
* Featured "custom-design", "videopress", "support", "space", "custom-domain", "no-adverts\/no-adverts.php"
* Included in all plans: "free-blog"

Missing:
* Jetpack Essential Features
* Email and Live chat support
* Unlimited Premium Themes
* Simple payments
* Monetize your site

Business plan - **id 1008**
* Featured - "premium-themes", "space", "support"
* Includes WordPress.com Premium features: "custom-design", "videopress", "no-adverts\/no-adverts.php", "custom-domain"
* Included in all plans: "free-blog"

Missing: 
* Jetpack Essential Features
* Email and Live chat support
* Unlimited Premium Themes
* Simple payments
* Monetize your site
* Attend live courses
* SEO tools 
* Install plugins
* Upload themes
* Google Analytics
* Remove WordPress.com branding

**Comment by mattmiklic** [comment]
The current logic in the app makes sense, though it's not really consistent, because some personal/premium features are listed in the Business plan features. It'd probably be easiest to match Calypso for the time being, though they may benefit from considering reversing the order of plan features on the web for mobile browsers, too.
