### ISSUE TITLE
Clumsy like animation on comments

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6101]
I think something changed when we switched to vector drawables, the rotate animation is now decentered and feels clumsy, see it in action [here](https://cloudup.com/cvlQMBGdkJG).

It looks better in the Reader (same kind of animation, icon is smaller but seems centered correctly).

**Comment by tonyr59h** [comment]
That might make a good bell ringing 🔔  animation but i agree, it just looks weird here.

**Comment by tonyr59h** [comment]
The problem is the padding in [the layout file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/comment_action_footer.xml#L36) has uneven vertical padding. It doesn't happen in the reader because all those comment buttons are implemented using `ReaderIconCountView`.
