### ISSUE TITLE
Can't upload videos to Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6157]
"Unknown error communicating with the Jetpack site"

![screenshot_20170627-104050](https://user-images.githubusercontent.com/40213/27578972-29e81c62-5b26-11e7-8669-057af291ae16.png)

**Comment by designsimply** [comment]
I tested uploading videos using both Aztec and Gutenberg Mobile and both worked without failures. (screenshots: [Aztec](https://user-images.githubusercontent.com/1119271/69822189-f8940800-11c2-11ea-9910-02d46c5a5a6b.png), [Gutenberg](https://user-images.githubusercontent.com/1119271/69822193-faf66200-11c2-11ea-8369-057df671df1f.png))

<sup>Tested with WPAndroid 13.7-rc-2 on Pixel 3 Android 10 on a site running WordPress 5.3 and Jetpack 7.9.1.</sup>

There have been some improvements to video handling since this issue was originally created:

https://github.com/wordpress-mobile/AztecEditor-iOS/pulls?utf8=%E2%9C%93&q=is%3Apr+in%3Atitle+video+closed%3A2017-06-27..2019-11-28

https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+in%3Atitle+video+closed%3A2017-06-27..2019-11-28

However, if you are still seeing problems, please re-open and please include any additional details about your Jetpack setup which may be relevant to replicating this bug in testing. Thanks!
