### ISSUE TITLE
Edits to media made in post editor are not reflected in media library

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6169]
### Expected behavior
When I make changes to media in the post editor I expect the media library to pick up on those changes.

### Actual behavior
After editing the media in the post the media library does not show difference.

### Steps to reproduce the behavior
1. Refresh media library and posts
2. Edit a piece of media in a post, change the title to something
3. You can either keep the changes local or update it remotely, it doesn't matter
4. You can refresh the media library or not, same result
5. Edit the media from the media library, check the title to see that it's not updated

**Comment by nbradbury** [comment]
@tonyr59h I was confused by this, too, and I'm sure some users are as well. The problem is that when you tap to edit an image attached to a post, you're actually changing the **HTML** that will be inserted for that image (ie: you're changing the `title` attribute on the `img` tag).

Even more confusing is that if you give the image a title in the media library and then add it to a post, that title doesn't automatically get used as the `title` attribute - see #5779

**Comment by tonyr59h** [comment]
> Even more confusing is that if you give the image a title in the media library and then add it to a post, that title doesn't automatically get used

I noticed that too, the title was still set to the filename 😕 

We should make that more clear to ~users~ _customers_ somehow.

**Comment by mattmiklic** [comment]
> The problem is that when you tap to edit an image attached to a post, you're actually changing the HTML that will be inserted for that image (ie: you're changing the title attribute on the img tag).

> Even more confusing is that if you give the image a title in the media library and then add it to a post, that title doesn't automatically get used as the title attribute - see #5779

This is confusing for sure, but it seems like the best way to address it is by changing the behavior so that changes made to an image title, etc. in the editor are reflected in the media library. This mirrors how things work in Calypso; changing metadata on an image in a post updates the metadata of the image in the media library. Is there a particular reason why it doesn't work this way currently in the apps?

**Comment by tonyr59h** [comment]
> Is there a particular reason why it doesn't work this way currently in the apps?

It was probably just an oversight, not intentionally implemented that way. I'm thinking we'll also want to use the same editor in both places. Right now there's a different dialog for the editor.

**Comment by mattmiklic** [comment]
> I'm thinking we'll also want to use the same editor in both places. Right now there's a different dialog for the editor.

Cool, yeah, that sounds right to me.
