### ISSUE TITLE
Combine WP media utils

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#6363]
We have two WP media utils files - `ui/media/WordPressMediaUtils.java` and `util/WPMediaUtils.java`. We should combine those.

**Comment by daniloercoli** [comment]
@nbradbury I'm not quite sure we should combine those 2 classes, since `WPMediaUtils.java` is a utility class placed in our `utils` external library, and it meant to be used everywhere not only in WordPress prjs. We should, for sure, remove the `WP` prefix from it, since it already created some confusions in the past.
Thoughts?

**Comment by nbradbury** [comment]
> We should, for sure, remove the WP prefix from it, since it already created some confusions in the past.

`WPMediaUtils.java` is part of WPAndroid. Perhaps you're thinking of `MediaUtils.java`, which *is* part of our `utils` library?

**Comment by daniloercoli** [comment]
Ah right! Too many utils.
