### ISSUE TITLE
Media Library - Overlays are missing when deleting items

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6629]
Deleting items from WP Media Library doesn't show the `deleting` overlay over them. There is basically no UI feedback on the taken and in progress action.
See the video here: https://cloudup.com/cvVRVRt9h39

cc @nbradbury

**Comment by nbradbury** [comment]
Looks like problem is somehow due to the upload state for the items isn't being set to `DELETING`. Working on a fix now.

**Comment by nbradbury** [comment]
I share the blame with @mzorz for this one! The problem was introduced [here](https://github.com/wordpress-mobile/WordPress-Android/commit/ad6cbef56b700a25ce09c195a3de57ba0928ee16#diff-fdc9b5c706ac889526b8df93c55351ce) based on [this comment](https://github.com/wordpress-mobile/WordPress-Android/pull/6578#pullrequestreview-58217555) from me.

I had noticed we were setting the upload state to `DELETING` in both the fragment and the activity, so I suggested getting rid of one of them. The problem is the the fragment sets the upload state for the selected items - but the activity clears the selected items before that code happens.

I'll fix this in `release/8.2`

**Comment by mzorz** [comment]
Nice catch @nbradbury !

**Comment by mzorz** [comment]
And thank you @daniloercoli  🙇

**Comment by daniloercoli** [comment]
Fixed in #6630
