### ISSUE TITLE
Posts List card action labels get cut

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6691]
### Expected behavior
Labels in Posts List card actions shouldn't be cut, on any language

<img src="https://user-images.githubusercontent.com/6597771/31142931-195781a2-a852-11e7-9f29-ceea2f1a745e.png" width="270" alt="horizontal_cut">

### Actual behavior
They get cut, so the full action label is not shown, therefore it doesn't make sense

<img src="https://user-images.githubusercontent.com/6597771/31142917-0fdd4742-a852-11e7-9a8f-d0da216ed70a.png" width="270" alt="vertical_cut">

### Steps to reproduce the behavior

1 .Switch the device to German
2. go to the Posts List and check:

**Comment by designsimply** [comment]
Several changes have been made since the time this issue was originally filed. I checked the Posts Lists card actions just now with my device language set to German and none of them are overlapping any more. 👍

<img src="https://user-images.githubusercontent.com/1119271/105114068-62383b00-5a83-11eb-9acc-1a5235168e5b.png" width="270" alt="Screenshot_20210119-182214">
<sup>Tested with WPAndroid 16.5-rc-2 on Pixel 3 Android 11.</sup>

Please re-open this issue if I've missed something! Thank you.
