### ISSUE TITLE
Sharing does not continue after login

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#6694]
### Expected behavior
Precondition - User is not logged into WordPress

1. User shares an image/video/text with WordPress.
2. Login flow is shown
3. When the user logs in, the sharing flow continues.

### Actual behavior
1. User shares an image/video/text with WordPress.
2. Login flow is shown along with an error toast message.
3. When the user logs in, the sharing flow **doesn't** continue. 
4. The Main screen is displayed.

### Steps to reproduce the behavior
1. Clear app data.
2. Share image/video/text with WordPress app.
3. The app redirects you to the Login screen and displays an error message - "No WordPress account found, add an account and try again".
4. Log in.
5. The app doesn't continue with the sharing flow and displays the Main screen.

**Comment by hypest** [comment]
It's not very clear what this issue is about. If I understand it correctly, the real issue is that the sharing action doesn't continue after logging. I'd suggest revising the `Actual behavior` section to make it more clear what is currently happening after logging in.

Also, the "Steps to reproduce the behavior" are too generic and don't provide clear steps to reach the problem. Please update it as well. Thanks!

See here an example: https://github.com/wordpress-mobile/WordPress-Android/issues/6654#issue-259910799

**Comment by malinajirka** [comment]
@hypest Is the edited description ok or should I write even more detailed description?

**Comment by hypest** [comment]
I think it's clearer , thanks @malinajirka!

While we're at it, the ticket title is a bit off as well. We already have support for logging in while sharing (albeit incomplete) so, the title is confusing. Let's change it to something more accurate like "Sharing does not continue after login" or something. What do you think?

**Comment by malinajirka** [comment]
Good point. I've changed the title. Thanks @hypest
