### ISSUE TITLE
Async media: stopping an upload incorrectly generates an error

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6750]
First reported in https://github.com/wordpress-mobile/WordPress-Android/pull/6747#issuecomment-337847844  by @daniloercoli 🙇 

### Expected behavior
When uploading a media item within a Post, then stopping the upload by tapping the image and answering "yes" to the "Stop upload?" dialog, there shouldn't be any error notifications given the upload was actively interrupted by the user theirselves.

### Actual behavior
When uploading a media item in a Post, then cancelling it, an error notification is (incorrectly) shown.

### Steps to reproduce the behavior
1. start a draft
2. include a media item (large enough so you can tap on it to stop it)
3. exit the editor by tapping Back
4. open the editor again
5. tap on the image
6. the dialog "Stop uploading?" appears
7. tap YES
8. observe the error notification appears.

**Comment by daniloercoli** [comment]
Re-opening since I found another flow to replicate the issue:
- Start a new post and add several media
- Publish it!
- On the posts list select the post and erase it while media is uploading.

`if (!mUploadStore.isPendingPost(postToCancel) && !mUploadStore.isCancelledPost(postToCancel)) {` is true and thus a new notification is shown to the user.
Upload failed for <title of the post here> - There was an error uploading the media...
