### ISSUE TITLE
Media title, caption and alt-text not updated in media gallery when editing an image

### ISSUE THREAD

**Issue by ectatomma** [wordpress-mobile/WordPress-Android#6757]
### Expected behavior
When I edit an image from the Android app to add a title, caption and alt-text, those details are added to the media gallery and the post, so if I reuse the image I don't need to rewrite them.

### Actual behavior
When I edit an image from the Android app to add a title, caption and alt-text, those details are added to post only and not to the media gallery, so each time I use the image I should write them again. 

### Steps to reproduce the behavior
Add an image to a post, tab the image and edit it, fill the title, caption and alt-text fields and tab Save. Try to add the same image from the WordPress media, the info on the title/caption/alt-text fields is not there.

##### Tested on [device], Android [version]
Tested on Moto G XT1033 (first gen), Android 7.1.2 Lineage OS 14.1-20170926-NIGHLY-falcon
Wordpress app v.8.3.1.

**Comment by rachelmcr** [comment]
I confirmed that changes made to the image meta (title, caption, alt text) in the editor aren't saved to the media library/reused for that image in future posts. Even if you edit the image meta in the Media Library (under My Sites > Media, rather than in the editor) that meta isn't used when you add the image to a post in the editor.

I could see the changes from the editor being restricted to only the post you're editing, but I definitely expect changes made to the image meta in the media library to be used for that image when I add it to a post.

##### Tested on Nexus 9, Android 7.1.1, WPAndroid alpha-86
