### ISSUE TITLE
When switching to HTML view cursor goes to the beginning of the post instead of staying at the current editing position

### ISSUE THREAD

**Issue by ectatomma** [wordpress-mobile/WordPress-Android#6758]
### Expected behavior
When I tab the HTML view icon, the editor keeps the cursor position.

### Actual behavior
When I tab the HTML view icon, the editor goes to the beginning of the post, so I need to find the line I were working on, which is annoying.

### Steps to reproduce the behavior
Write a post that is longer than your screen, tab the HTML view icon while being in the last line, cursor goes to the beginning of the post.

##### Tested on [device], Android [version]
Tested on Moto G XT1033 (first gen) , Android 7.1.2 Lineage OS 14.1-20170926-NIGHLY-falcon
Wordpress app v.8.3.1.

**Comment by hypest** [comment]
This will be fixed when [this Aztec fix](https://github.com/wordpress-mobile/AztecEditor-Android/pull/701) gets merged into wpandroid.

**Comment by designsimply** [comment]
Tested and confirmed using WPAndroid alpha-186 (13.1 alpha) on Pixel 3 Android 9 that if you place the cursor at the end of a long document in the editor (Aztec or Block) and go to More > HTML Mode that the cursor does not maintain it's position in the document.

I noticed the same issue is also being discussed at https://github.com/wordpress-mobile/gutenberg-mobile/issues/118#issuecomment-476726660 and so I think we can close this issue in favor of the one in the `gutenberg-mobile` repository because that is where future work to solve this problem will be happening and it covers both the Android and iOS platforms there.

Closing in favor of tracking at https://github.com/wordpress-mobile/gutenberg-mobile/issues/118 instead and noting we can re-open if anyone feels strongly that this issue also still remain open.
