### ISSUE TITLE
Site picker: hidden sites not immediately reflected in recents list

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6859]
Originally reported by @rachelmcr 

### Expected behavior
If I hide a site that’s in the recent sites list, the recent sites list should reflect this change.

### Actual behavior
If I hide a site that’s in the recent sites list, the recent sites list doesn’t replace that site right away. So until I select another site, I’ll have fewer than 5 recent sites showing up.

**Comment by designsimply** [comment]
(I _think_) I was able to reproduce this bug using Pixel, Android 8.1.0, WPAndroid alpha-90 with the following steps:

1. Start with an account that has >8 sites.
1. Go to My Sites > Switch Site.
1. Select several sites until you can see five in the recent sites list.
1. In a browser, go to wp-admin > Dashboard > My Blogs & hide one of the blogs in the recent sites list.
1. Go back to the app and go to My Sites > Switch Site.
1. Select the recent site which was just hidden.
1. Tap Switch Site again.

<strong>Result:</strong> there will now be four sites listed in the recent sites list instead of five.

fwiw, I don't think this behavior is strange and that if a site is in the recent sites list and then hidden that it's fine to have it disappear from the recent sites list after it is selected again.
