### ISSUE TITLE
Data loss in editor on screen off for Jetpack site

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6905]
A user reported via Helpshift that they lost their editor contents while editing a post on a Jetpack site. Happened twice.

Here's the description from the user:
> Device: lenovo tab4 10 android 7.1.1 with bluetooth external keyboard
> 
> I can not reproduce it anymore, but it happened to me twice already.
> 
> when it happened, both times I was offline:
opened the wordpress app, create new post and started writing. Without pressing save draft or the back button, I lock my tablet (or it locks automatically after timeout). When I unlocked it, the wordpress is still active, but all the text is gone.

Internal ref: #240905-h

**Comment by designsimply** [comment]
It looks like this is labeled high priority because of the potential data loss, however, because the original report is over a year and 3 months old and was reported by only one person we should consider removing the `[Pri] High` label if we test and cannot replicate the problem described.

Let's have a few different people try to replicate the problem:

1. Create a new post and start writing.
1. Without pressing "Save draft or the back button, lock the device.
1. Unlock the device and check whether the text is still there or not

**Comment by designsimply** [comment]
I tested on Samsung Galaxy Tab4 (SM-T330NU), Android 5.1.1 with WPAndroid 11.9-rc-1 just now and the content was still there after I started a new post with some new content and locked then unlocked the device.

**Comment by hypest** [comment]
I cannot replicate the issue with app version `alpha-155`, Android version 7.1.2 on a Nexus 5X and I can't replicate the issue. Will close this ticket as non-reproducible.
