### ISSUE TITLE
Post with media ends up in duplicate Post

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7088]
### Expected behavior
When creating a post with media, one Post should be created on the server.

### Actual behavior
After media completes uploading and the user stays on the Editor, a copy of the Post is saved (it's updated every few seconds with autosave). Once the user exits the Editor, a new copy is uploaded to the server as well.

### Steps to reproduce the behavior
1. start a new draft
2. include a media item
3. wait until it finishes uploading.
4. check on the web admin to see there's already a draft copy in there
5. exit the editor, and observe the Post is uploaded again
6. check on the web admin to see there's yet another copy (this time,  a published one) of the Post.
7. pull to refresh in the Posts list in the app to get both copies on the client application end.

**Comment by FuckUToo** [comment]
Who is this? Instead of hiding behind your screen like a coward, speak.                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: January 11, 2018 6:03 PMTo: WordPress-Android@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [wordpress-mobile/WordPress-Android] Post with media ends up in duplicate Post (#7088)  Expected behavior
When creating a post with media, one Post should be created on the server.
Actual behavior
After media completes uploading and the user stays on the Editor, a copy of the Post is saved (it's updated every few seconds with autosave). Once the user exits the Editor, a new copy is uploaded to the server as well.
Steps to reproduce the behavior
start a new draftinclude a media itemwait until it finishes uploading.check on the web admin to see there's already a draft copy in thereexit the editor, and observe the Post is uploaded againcheck on the web admin to see there's yet another copy (this time,  a published one) of the Post.pull to refresh in the Posts list in the app to get both copies on the client application end.
Tested on [Google Pixel], Android [8.0]
