### ISSUE TITLE
WPGlobus plugin support

### ISSUE THREAD

**Issue by AiratHalitov** [wordpress-mobile/WordPress-Android#7126]
### Behavior
Titles of pages in analytics looks like this:
`{:ru}Блог{:}{:en}Blog{:}`
To fix this you need add [WPGlobus plugin](https://wordpress.org/plugins/WPGlobus/) support ([GitHub](https://github.com/WPGlobus/WPGlobus)).

The same behavior in WP-Desktop App [#404](https://github.com/Automattic/wp-desktop/issues/404).
In JetPack plugin analytics titles looks normal.

### Steps to reproduce the behavior
Open App and go to Stats

##### Tested on Xiaomi Redmi Note 4X, Android 6.0

- WordPress Forum: https://wordpress.org/support/topic/optimization-for-mobile-devices/#post-9871949
- WordPress Android 9.0.1
- JetPack  5.7.1
- WordPress 4.9.2

### Screenshot from mobile app: 
![screenshot_2018-01-17-14-51-51-292_org wordpress android](https://user-images.githubusercontent.com/4050715/35083434-f8d713e6-fc40-11e7-89ab-882d174a746b.png)

**Comment by designsimply** [comment]
@mzorz or @planarvoid would we consider applying filters to titles before they they are output as suggested at https://wordpress.org/support/topic/optimization-for-mobile-devices/#post-9877531 in order to support plugins such as WPGlobus?

**Comment by designsimply** [comment]
I believe this issue is still valid, @AiratHalitov can you confirm?

**Comment by AiratTop** [comment]
> I believe this issue is still valid, @AiratHalitov can you confirm?

@designsimply 
Yes, the bug is still actual.

**Comment by planarvoid** [comment]
Thanks for checking in on this issue. It would be difficult for us to add specific cases to support every plugin out there, but as the WordPress mobile project is open source plugin authors are welcome to submit PRs for their own changes. In this case it changes the way titles are stored in DB so it might not get approved. The suggested solution doesn't make sense on mobile because it uses a [purely PHP function](https://github.com/Automattic/wp-desktop/issues/404#issuecomment-359722450).

The mobile app uses this endpoint `/sites/$site/stats/top-posts/` to load the data and shows exactly what it receives. Localising the endpoint probably makes more sense than an in-app solution. 

I'd be in favour of closing this issue right now as it is more than 2 years old and we'll not implement it in the app. What do you think @designsimply ?

**Comment by irfano** [comment]
I am closing this issue based on the previous comment.
