### ISSUE TITLE
Android App can't delete comments when connected via Jetpack.

### ISSUE THREAD

**Issue by georgestephanis** [wordpress-mobile/WordPress-Android#7131]
This is an xpost of https://github.com/Automattic/jpop-issues/issues/633

When the app is connected via legacy xml-rpc connection, everything works fine.

When connected via Jetpack/WPCOM it can't delete comments.

However, Calypso can delete comments -- so it's not an issue with the connection between wpcom servers and the Jetpack site.

There's some investigation in the linked issue, but as some of it may be private info I'm not xposting here.

cc: @elibud

**Comment by elibud** [comment]
@oguzkocer can you take a look at this one in your upcoming Groundskeeping rotation?
I've checked and this works on iOS, the endpoint we are using is: `sites/SITE_ID/comments/COMMENT_ID/delete` under version `1.1`

Thanks

**Comment by khaykov** [comment]
Took me some time, but, I was able to reproduce it, under certain circumstances. Maybe it's a totally different issue. To my shame, I have almost no knowledge of Jetpack and Flux-C, so maybe this will give someone else ideas about what is wrong. (maybe @maxme ?)

You can reproduce this with the app or with a [console](https://developer.wordpress.com/docs/api/console/), so maybe it's not 100% mobile issue. I used endpoints and parameters that we use in the app.

So I got a fresh Jepacks site with Pressable.

**Step 1: create a reply to a default comment that comes with my WP install.**

In the app go to comment list, open the comment, input some text in the reply box and submit it.

In console:
```
POST: /sites/141473819/comments/1/replies/new/
"content" -> "awesome comment”
```
Everything looks ok so far.

**Step 2: Trash the comment we created.**

In the app open the comment we just created and click Trash.

In console:
```
POST: /sites/141473819/comments/20/
"status" -> "trash"
"date" -> "2018-01-19T07:30:04+00:00"
"content" -> "<p>awesome comment</p>\n”
```
No problems here.

**Step 3: Changed my mind. Let’s restore it.**

In the app select the "Trashed" filter, open the comment and click "Approve".

In console:
```
POST: /sites/141473819/comments/20/
"status" -> "approved"
"date" -> "2018-01-19T07:30:04+00:00"
"content" -> "<p>awesome comment</p>\n”
```
No problems here.

**Step 4: But no. Let’s trash it after all.**

In the app, select All filter, open the comment we just Approved and tap Trash.

In console:

```
POST: /sites/141473819/comments/20/
"status" -> "trash"
"date" -> "2018-01-19T07:30:04+00:00"
"content" -> "<p>awesome comment</p>\n”
```
Still looking good.

Now, at this point, everything looks good. But we dice to do "pull-to-refresh", or left the app and came later, and comments list got refreshed.  

**Step 5: Ok. Let’s see all the comments we got.**

The comment we just deleted appears in the app, under All filter with "approved" status.

Let's try console!
`GET: /sites/141473819/comments/?number=30&force=wpcom&status=all&offset=0`

[![https://gyazo.com/4bfc16a741ba9938a8cbe6dd4ae4817c](https://i.gyazo.com/4bfc16a741ba9938a8cbe6dd4ae4817c.png)](https://gyazo.com/4bfc16a741ba9938a8cbe6dd4ae4817c)

Wat.

![masaka](https://user-images.githubusercontent.com/728822/35140552-09e7bb90-fd3b-11e7-9901-dc56756edf22.jpg)

**Comment by khaykov** [comment]
Interesting thing is that at WordPress.com side everything looks ok. Comment is trashed. No issues.

**Comment by elibud** [comment]
@khaykov can you try if adding the following parameter fixes this: `"force": "wpcom"`? @lezama what do you think?

**Comment by lezama** [comment]
he is already using "force=wpcom" 😊

**Comment by lezama** [comment]
This is super useful! thanks!

I tried to reproduce your steps just using the API, and even after approving and trashing multiple times I wasn't able to end on a bad state 🤦‍♂️ 

This is what I did:

**Step 1: create reply**
```
http POST https://public-api.wordpress.com/rest/v1/sites/migueluy.wpsandbox.me/comments/139/replies/new  'Authorization: BEARER ...' content='<p>awesome comment</p>\n'
```

**Step 2: Trash the comment we created.**
```
http POST https://public-api.wordpress.com/rest/v1/sites/migueluy.wpsandbox.me/comments/140  'Authorization: BEARER ...' status='trash' date='2018-01-19T07:30:04+00:00' content='<p>awesome comment</p>\n'
```

**Step 3: Changed my mind. Let’s restore it.**
```
http POST https://public-api.wordpress.com/rest/v1/sites/migueluy.wpsandbox.me/comments/140  'Authorization: BEARER ...' status='approved' date='2018-01-19T07:30:04+00:00' content='<p>awesome comment</p>\n'
```

**Step 4: But no. Let’s trash it after all.**
```
http POST https://public-api.wordpress.com/rest/v1/sites/migueluy.wpsandbox.me/comments/140  'Authorization: BEARER ...' status='trash' date='2018-01-19T07:30:04+00:00' content='<p>awesome comment</p>\n'
```

**Step 5: Ok. Let’s see all the comments we got.**
```
http GET 'https://public-api.wordpress.com/rest/v1/sites/migueluy.wpsandbox.me/comments?status=trash&force=wpcom'  'Authorization: BEARER ...'
```

Result:
```"raw_content": "<p>awesome comment</p>\\n",
            "short_URL": "https://wp.me/p3oDRb-aV%23comment-140",
            "status": "trash",
            "type": "comment"
        }
```

**Comment by elibud** [comment]
> he is already using "force=wpcom"

I shouldn't type anything before coffee 🤦‍♀️ I wasn't able to replicate this either on iOS, so I'm quite puzzled by this one.

**Comment by elibud** [comment]
Assigning this over to @planarvoid as he has a support rotation in two weeks during which he can take care of this.

**Comment by planarvoid** [comment]
I can't reproduce this issue, deleting comments on Android seems to work fine

**Comment by oguzkocer** [comment]
I have tried approving/trashing/deleting on both the app and Calypso at the same time and put my site in this unstable state. The app uses `force=wpcom` whereas Calypso doesn't I am guessing this is what causes the unstable state, but I am not sure. After it's put into this unstable state, I get 2 different responses for my Jetpack site from the `/comments` endpoint depending on if I use the `force=wpcom`:

https://public-api.wordpress.com/rest/v1.1/sites/92407962/comments?http_envelope=1&number=20&order=DESC&page=1&status=all&type=any

```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"found":1,"site_ID":1,"comments":[{"ID":10,"post":{"ID":288,"type":"post","title":"i_like this","link":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288"},"author":{"ID":0,"login":"","email":"oguz.kocer@automattic.com","name":"oguzkocer","first_name":"","last_name":"","nice_name":"","URL":"","avatar_URL":"\/\/www.gravatar.com\/avatar\/72fd8bb5c2db88123813ad77c33d5647?s=96&#038;r=g&#038;d=mm","profile_URL":"https:\/\/en.gravatar.com\/72fd8bb5c2db88123813ad77c33d5647","ip_address":"209.20.29.169"},"date":"2017-10-24T22:12:46-04:00","URL":"https:\/\/oguzkocer.wpsandbox.me\/?p=288#comment-10","short_URL":"https:\/\/wp.me\/p6fJx0-4E%23comment-10","content":"<p>12341234<\/p>\n<p>arst<\/p>\n","raw_content":"<p>12341234<\/p>\n<p>arst<\/p>\n","status":"approved","parent":false,"type":"comment","meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962","post":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288","replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/replies\/","likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/likes\/"}},"can_moderate":true}]}}
```

https://public-api.wordpress.com/rest/v1.1/sites/92407962/comments?http_envelope=1&number=20&order=DESC&page=1&status=all&type=any&force=wpcom

```
{"code":200,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"found":2,"site_ID":92407962,"comments":[{"ID":10,"post":{"ID":288,"title":"i_like this","type":"post","link":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288"},"author":{"ID":0,"login":"","email":"oguz.kocer@automattic.com","name":"oguzkocer","first_name":"","last_name":"","nice_name":"","URL":"","avatar_URL":"https:\/\/1.gravatar.com\/avatar\/72fd8bb5c2db88123813ad77c33d5647?s=96&d=https%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D96&r=G","profile_URL":"https:\/\/en.gravatar.com\/72fd8bb5c2db88123813ad77c33d5647","ip_address":"209.20.29.169"},"date":"2017-10-24T22:12:46-04:00","URL":"https:\/\/oguzkocer.wpsandbox.me\/?p=288\/#comment-10","short_URL":"https:\/\/wp.me\/p6fJx0-4E%23comment-10","content":"<p>12341234<\/p>\n<p>arst<\/p>\n","raw_content":"<p>12341234<\/p>\n<p>arst<\/p>\n","status":"approved","parent":false,"type":"comment","like_count":0,"i_like":false,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962","post":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288","replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/replies\/","likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/10\/likes\/"}},"can_moderate":true},{"ID":9,"post":{"ID":288,"title":"i_like this","type":"post","link":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288"},"author":{"ID":0,"login":"","email":"oguz.kocer@automattic.com","name":"oguzkocer","first_name":"","last_name":"","nice_name":"","URL":"","avatar_URL":"https:\/\/1.gravatar.com\/avatar\/72fd8bb5c2db88123813ad77c33d5647?s=96&d=https%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D96&r=G","profile_URL":"https:\/\/en.gravatar.com\/72fd8bb5c2db88123813ad77c33d5647","ip_address":"209.20.29.169"},"date":"2017-10-24T22:12:40-04:00","URL":"https:\/\/oguzkocer.wpsandbox.me\/?p=288\/#comment-9","short_URL":"https:\/\/wp.me\/p6fJx0-4E%23comment-9","content":"<p>arstartsoi<\/p>\n","raw_content":"<p>arstartsoi<\/p>\n","status":"approved","parent":false,"type":"comment","like_count":1,"i_like":true,"meta":{"links":{"self":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/9","help":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/9\/help","site":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962","post":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/posts\/288","replies":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/9\/replies\/","likes":"https:\/\/public-api.wordpress.com\/rest\/v1.1\/sites\/92407962\/comments\/9\/likes\/"}},"can_moderate":true}]}}
```

Notice that I get 2 comments in the second response and only one in the first one. @lezama You can use my site to debug the issue `oguzkocer.wpsandbox.me`, let me know if you need a user to check things out!

**Comment by elibud** [comment]
Thanks @oguzkocer, @lezama let us know if we can help on this one.

**Comment by oguzkocer** [comment]
Quick note about how things are handled on the Android side that might add to the confusion of a user. We use the local status of the comment to decide whether to trash or delete it and if the status has been changed in another client, this can behave a little weird. I haven't looked into it in detail but here is what happened to me:

1. Trash a comment in app
2. Go to calypso and restore it
3. Don't refresh the client and delete the comment
4. It'll look like the comment is deleted and will show up after waiting a while (I am not sure if it happens every time)

This is exactly what the user described in one of their comments and it's completely unrelated to the original issue.

**Comment by lezama** [comment]
@oguzkocer could you add me as an administrator?

**Comment by oguzkocer** [comment]
@lezama Any progress on this one? I can help with testing/debugging next week if there is anything I can do.

**Comment by lezama** [comment]
I couldn't replicate Today, is still going on on your site?

**Comment by designsimply** [comment]
Following up, I see that _a lot_ of work was done on this case already, but without a resolution, so let's start with a re-cap:

* 2017-05-11 - Originally reported on May 11, 2017 16:24:01 (3207800-t) for WPAndroid 7.0.
* 2017-06-01 - Notes posted at p4a5px-1Nh-p2, unable to replicate using direct API calls.
* 2017-06-21 - Investigated and unable to replicate in the app. (p4a5px-1Nh-p2#comment-6894)
* 2017-07-03 - Continued at jpop-issues/633.
* 2018-01-19 - Very intricate set of potential steps to reproduce WordPress-Android/7131#issuecomment-358895236.
* 2018-01-19 - Attempt to reproduce with latest steps and unable to replicate 7131#issuecomment-358945086.
* 2018-02-18 - jpop-issues/633 closed in favor of this issue.
* 2018-02-23 - Steps to reproduce a second scenario separate from the original issue posted at WordPress-Android/7131#issuecomment-368047553.
* 2018-03-26 - 2nd developer attempts second scenario and unable to reproduce.
* 2019-06-12 - Issue becomes stale.

Original issue as described by the user:

> Since updating to WP app 7.0 and later versions, I am unable to delete or mark as spam comments. Older, pre v.7.0 versions of the app work fine. Can delete from browser, but not from the app. 

Testing steps from above, attempt 1

1. Create reply to a default comment that comes with my WP install.
1. Trash the comment we created.
1. Changed my mind. Let’s restore it.
1. But no. Let’s trash it after all.
1. Ok. Let’s see all the comments we got.
Result: The comment we just deleted appears in the app, under All filter with "approved" status.

Tested and confirmed using WPAndroid 15.6 beta, WP 5.5.1, Jetpack 8.9—and I also noticed the default comment does not show up in WPAndroid at all after Jetpack is connected. 🤔
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10 using `used-silverfish.jurassic.ninja` running WordPress 5.5.1. and Jetpack 8.9.</sup></p>

Testing steps from above, attempt 2

1. Trash a comment in app
1. Go to calypso and restore it
1. Don't refresh the client and delete the comment
Result: It'll look like the comment is deleted and will show up after waiting a while (I am not sure if it happens every time)

I tried testing scenario 2 and was unable to replicate.
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-2 on Pixel 3 Android 10 using `managerial-milkweed.jurassic.ninja` running WordPress 5.5.1. and Jetpack 8.9.</sup></p>

I also looked up the current list of active plugins on the reporting user's site for reference. Active plugins as of 2020-09-02:

* SB Welcome Email Editor
* Attachment Pages Redirect
* Cloudflare
* DB Cache Reloaded Fix
* Download Monitor Page Addon
* Download Monitor
* EZP Maintenance Mode
* Google Adsense Dashboard
* Google Analytics Dashboard for WP (GADWP)
* Jetpack by WordPress.com
* Mime Types Extended
* Ultimate Nofollow
* Quick Adsense
* Reverse-Proxy Comment IP Fix
* Revision Control
* Shortcodes Ultimate
* Cookie Consent
* UpdraftPlus - Backup/Restore
* Use Google Libraries
* Varnish HTTP Purge
* WordPress Tinymce visual editor buttons
* Ajax Edit Comments
* WP htaccess Control
* WP-Mail-SMTP
* WP Robots Txt
* WP-Sweep

I found the length of this thread difficult to follow and also quite a lot of changes have been made to the apps since the original report, so I decided to create new issues to use for tracking the problems I was able to test and confirm and I would like to continue the discussion in those issues.

**Comment by designsimply** [comment]
Let's continue working on the problems reported in this thread in the following two issues: https://github.com/wordpress-mobile/WordPress-Android/issues/12880, https://github.com/wordpress-mobile/WordPress-Android/issues/12881.
