### ISSUE TITLE
Media browser: Incorrect behavior when displaying search results 

### ISSUE THREAD

**Issue by jorgecasariego** [wordpress-mobile/WordPress-Android#7398]
### Expected behavior
When performing a search, only display items related to the selected tab.

### Actual behavior
When performing a search it is displaying items not related to the current Tab

### Steps to reproduce the behavior

1. Go to **Sites** tab.
2. Tap **Media** item.
3. Add one or more images.
4. Tap **Documents** tab.
5. Tap **Search** action.
6. Notice images show in empty search. That's wrong. Only documents should be shown.
7. Enter search text to filter out images.
8. Tap back arrow to exit search.
9. Notice images show in **Documents** tab. That's wrong. Only documents should be shown.

**Before Tap on Search icon**

<img src="https://user-images.githubusercontent.com/2581647/37042178-ab738320-213c-11e8-895c-614e105736a3.png" width=300/>

**After Tap on Search icon**

<img src="https://user-images.githubusercontent.com/2581647/37042179-aba38480-213c-11e8-8151-1cf51cf634f5.png" width=300/>

##### Tested on Nexus 5, Android API 26

**Comment by jorgecasariego** [comment]
@theck13 I've been trying to understand how **media search** works and what I could notice is that when I do a search from Documents tab or any other specific tab, the method `searchSiteMedia (SiteModel siteModel, String searchTerm)` is looking for all files with the term `searchTerm` and I'm not finding a way to filter this search. This is why when on query text change it is showing all the possible result of media with that term.

What I solved is that when returning from a search and if we were in the Documents Tab it shows only documents (**step 9 of Test**) just reloading the grid

Do you have any recommendation how I could fix it or any point where I could look and see if I could find the problem?

**Comment by theck13** [comment]
Updating the [`search` method](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L508-L512) to the following gets us most of the way there, but our search pulls back results from *all* media types.

``` java
    public void search(String searchTerm) {
        mSearchTerm = searchTerm;
        List<MediaModel> mediaList = getFilteredMedia();
        mGridAdapter.setMediaList(mediaList);
    }
```

The [`getFilteredMedia` method](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L350-L383) does *almost* everything we need.  It either uses the [same statement](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L353) as [search](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaGridFragment.java#L510) when the search term is not empty, but it doesn't filter the returned list so the results show all media types ***or*** it just filters all media by the selected tab.  We need it to do both.

Rather than trying to filter the returned search list on the client side, we should probably update the [MediaStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/store/MediaStore.java) and [MediaSqlUtils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/MediaSqlUtils.java) in our network and persistence layer to be able to handle search term *and* media type.

**Comment by jorgecasariego** [comment]
Yeah! I think the same way. It would be much better if the data were already filtered rather than trying to filter the returned search list by the customer.

I see that `MediaStore` and `MediaSqlUtils` are part of the **WordPress-FluxC-Android** project  😕 

How is it usually done when you need a change in a project like **FluxC** or **Aztec**?

Would I have to create an issue in **FluxC**, implement, create a PR and then update in this project the call the new method?

**Comment by theck13** [comment]
> Would I have to create an issue in FluxC, implement, create a PR and then update in this project the call the new method?

That's pretty much it.  You don't _have_ to create an issue in the FluxC repository, but you can.  You can also just reference this issue in the FluxC pull request.  Once the FluxC pull request is merged, the [FluxC version in the WordPress `bulid.gradle` file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/build.gradle#L50) must be updated to the hash value of the FluxC pull request merge commit.  Then the new functionality and/or methods can be used to create a pull request in the WordPress-Android repository for the fix.

**Comment by jorgecasariego** [comment]
@theck13 now that FluxC was merged with the new methods to use here, what are the steps to update the FluxC version in the **WordPress-Android build.gradle** file?

**Comment by theck13** [comment]
The [FluxC version in the WordPress-Android bulid.gradle file](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/build.gradle#L72) must be updated to the hash value of the FluxC pull request merge commit.  That's it!

**Comment by jorgecasariego** [comment]
Great! I'll do it
