### ISSUE TITLE
Images in posts retain local device URLs and are not served from Media Library

### ISSUE THREAD

**Issue by pauljacobson** [wordpress-mobile/WordPress-Android#7424]
### URL

997274-zen

### Expected behavior

1. Upload image with post from the Android WordPress.com app;
2. Uploaded images are rendered from the links in Media Library in the relevant post.

### Steps to reproduce

1. User published a post from their Android device.
2. The post included several images.
3. Most images render correctly and are served from Media Library.
4. Some images are not served from the Media Library and, instead, their paths in the post HTML seem to be paths from the user's device.

#### Published post with broken image links

<img width="909" alt="post_with_broken_links_wordpress_com" src="https://user-images.githubusercontent.com/2912202/37094953-3c6d7990-221d-11e8-8855-00f304f0c729.png">

#### HTML for the page reflecting the local device paths

<img width="720" alt="failed_uploads_html" src="https://user-images.githubusercontent.com/2912202/37094981-4b164620-221d-11e8-9f28-44aa878156e1.png">

#### Item in the Media Library

<img width="1282" alt="media_media_library_version_wordpress_com" src="https://user-images.githubusercontent.com/2912202/37094995-558235c4-221d-11e8-8d85-2144f5d0e90c.png">

### What happened instead

It appears that instead of the images being served from Media Library, image links in the post for some images are not updated to the Media Library URLs and, instead, preserve local device paths.

**Comment by designsimply** [comment]
Thank you for including screenshots in this report! I re-tested today with WPAndroid alpha-156 (12.0 alpha) on Pixel 3, Android 9 from a WordPress.com Premium site using the steps given but all of my photos always published normally with the correct paths. I tried posts with around 3 images up to 6 images. I noticed `WhatsApp` was in the local storage path in your HTML screenshot so I tried sending a photo via WhatsApp and then pulling the photo from that location when adding an image to a post. 

I am closing this issue because I couldn't reproduce the problem in testing and because there hasn't been any activity here for over a year. 

@pauljacobson can you please loop back to the user and ask them if they are still having trouble with image uploads. If so, would you please re-open this issue and include more detailed steps about exactly how the images are being uploaded such as what they selected for "Open from" when pulling images from their device ([screenshot](https://user-images.githubusercontent.com/1119271/54319167-4f629e80-45ae-11e9-80a4-5303b989fac7.png)). Could you also note the type of site they are working from (WP.com+plan, Jetpack, self-hosted) and include the app logs from the user if they can send them to you right after they see the error happen again?
