### ISSUE TITLE
App crashes in login with site address screen

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-Android#7426]
### Expected behavior
App doesn't crash

### Actual behavior
App crashes

### Steps to reproduce the behavior
1. Go to: Log in
2. Go to: Log in to your site using your site address instead
3. With the keyboard displayed, press on "Need help finding your site address?"
4. With the alert on the screen, change the orientation of the phone to portrait
5. It will show a textfield with the keyboard. Now type something.
6. "WordPress has stopped"

**Comment by designsimply** [comment]
I tested with WPAndroid alpha-156 (12.0 alpha) on Pixel 3, Android 9 but couldn't replicate—the keyboard didn't show up for me when I changed orientation with the alert showing. ([45s](https://cloudup.com/cf_SaQP3pGj))

I am closing since the issue became stale, I couldn't replicate it in a test, and because no other reports were recorded here. @etoledom if you think this is worth an extra check, could you try again with Nexus 4, Android 5.1.1 and re-open if necessary?

**Comment by etoledom** [comment]
I also tested on a newer device and this issue didn't happen.
Sadly I don't have access to that older device anymore.

I'm not sure if that version is still supported, but I agree that this issue is probably super low occurrence, if any at all. Let's keep it closed 👍
