### ISSUE TITLE
Change default Publish button to Draft

### ISSUE THREAD

**Issue by diditho** [wordpress-mobile/WordPress-Android#7479]
### Expected behavior
'Draft' status when writing

### Actual behavior
'Publish' status when writing. This condition makes the article unintentionally published

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/3233097/37343902-738105b8-26fb-11e8-839c-41c43f8ab689.png)

**Comment by rachelmcr** [comment]
Thanks for the suggestion, @diditho! When you tap "Publish" now, you should see a pop-up appear to confirm that you want to publish the post. That should prevent any posts from being unintentionally published, and you can tap the ellipsis (...) menu on the right to select "Save as Draft" to switch the post status to draft. Does that work for you?

**Comment by designsimply** [comment]
Because we've added some extra help such as the pop-up rachelmcr mentioned earlier and because the button matches with what the core WordPress project does, we are going to leave the button as is. We appreciate the feedback though—thank you for making the suggestion and for using the WordPress app!

Screenshot for reference:

<img src="https://user-images.githubusercontent.com/1119271/70756620-4b5cdc00-1cfa-11ea-9caf-9ebd6afdb205.png" width="270" alt="Screenshot_20191212-161036">
<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>
