### ISSUE TITLE
Do all network communication in background service

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#75]
There are many AsyncTasks in different Activities that comunicates with the network. The data will load when the user opens the Activity. That means, the user has to wait until the data is downloaded. We can do all this stuff in backgound. Another advantage: we don't need the error handling on each Activity.
I started implementing a background service. It's a lot of work and I will add more patches here in the next time.

Patch at: http://android.trac.wordpress.org/ticket/363

**Comment by aforcier** [comment]
All network requests will eventually be transitioned over to FluxC, which performs them asynchronously.

This can be closed when we've eliminated `ApiHelper`, `RestClient`, and any other network calls from WPAndroid.

**Comment by oguzkocer** [comment]
I know we already marked this as obsolete, but since we can't actually assign a milestone to it, I think it'd be better just to close it. In case we change our mind, we can just re-open it, I don't think it's worth keeping track of this.

Closing this for now, but if you guys disagree, do let me know! Thanks!
