### ISSUE TITLE
Signup: Google signup-turned-to-login stays on prologue on rotation

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7521]
### Expected behavior
Rotating the device while waiting for the Google signup-turned-to-login to finish should allow the app to continue and reach the login epilogue.

### Actual behavior
The login (signup bottom sheet) prologue is still visible and stays on if the device gets rotated while waiting  for the Google signup-turned-to-login to finish.

### Steps to reproduce the behavior
1. Clear app data
2. Try to signup with a Google account that has already been used and connected to a WPCOM account
3. Right after selecting the Google account to use, rotate the device
4. The app stays on the login prologue screen with the signup bottom sheet visible
5. Tap Back a couple of times to dismiss the prologue and the app lands on the logged-in state main screen

##### Tested on [device], Android [version]
Nexus 5X, Android v7.1.2

**Comment by designsimply** [comment]
It appears this has been improved because when I try to select a Google account to use and then rotate the device, I am logged in instead of remaining on the login prologue screen. ([1m8s](https://cloudup.com/c45UoyF1hF0))

<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>

@hypest if I missed a detail in my test or if I should test with an older version of the app or Android, please reopen and let me know! 🙇‍♀️
