### ISSUE TITLE
Markup support in plugins description

### ISSUE THREAD

**Issue by AiratHalitov** [wordpress-mobile/WordPress-Android#7596]
App is not showing unsorted lists in plugins descriptions.
You should add support of markup. 

### Steps to reproduce the behavior
1. Go to App > Plugins > Manage Plugins
2. Open some plugin and go to description or changelog
3. Compare with description from wordpress.org

##### Tested on Xiaomi Redmi Note 4X, Android 6.0
* WordPress for Android 9.6

**Comment by AiratHalitov** [comment]
v12.0 
The issue is still actual.

**Comment by designsimply** [comment]
Checking back in on this, I compared the view for a plugin description on the app (I used version 15.8-rc-1) with the description of the app on the web and I found that the app is showing bulleted lists.

<img src="https://user-images.githubusercontent.com/1119271/94941583-4ee07000-0492-11eb-9b39-9250f5dbad45.png" height="340" alt="Screenshot_20201002-092915"> <img src="https://user-images.githubusercontent.com/1119271/94941407-16409680-0492-11eb-82c4-e732b1abda9a.png" height="340" alt="Screen Shot 2020-10-02 at Oct 2 9 30 09 AM">

<p style="clear:both;"><sup>Tested with WPAndroid 15.8-rc-1 on Pixel 3 Android 11.</sup></p>

I'm closing this issue because I believe the unsorted lists are distinguishable and clear for reading. If you feel that the issue should remain open, please comment and let me know!
