### ISSUE TITLE
App is showing editor short code when i use Divi or Visual Composers to Create Pages

### ISSUE THREAD

**Issue by ramakrishnabest** [wordpress-mobile/WordPress-Android#7618]
i am using Divi theme to develop my website after i connect my website into android app it is showing editor short code when i open specific page to edit .... is app not going to support other editors like visual composer and divi editor ?
do you know any editor please help me

**Comment by ramakrishnabest** [comment]
Hi ,

I have a small question here. can i use this app code for my customers of commercial use. Can i also modify this code as per my needs like add new features for this app etc..  is there any copyright issue in feature to use this app for commercial use ....

Thanks

**Comment by designsimply** [comment]
<blockquote>Is the app not going to support other editors like visual composer and divi editor?</blockquote>

We do not currently have any plans to provide support for third-party themes and plugins such as Divi or Visual Composer in the WordPress for Android app. It's possible the mobile team or community or third-party developers may consider adding support for that in the future, but I believe it would take some time. Currently, there is work underway to rebuild the editor as a block editor which are intended to pave the way for simpler integrations for page builders and wysiwyg editors in the future.

<blockquote>I have a small question here. can i use this app code for my customers of commercial use. Can i also modify this code as per my needs like add new features for this app etc.. is there any copyright issue in feature to use this app for commercial use ....</blockquote>

The WordPress for Android app is open source software released using a GPLv2 license. Please read the license documentation at https://github.com/wordpress-mobile/WordPress-Android/blob/develop/LICENSE.md to understand how you may use the software. My understanding is that you may charge for services (such as a fee for the physical act of transferring a copy) but you must also provide any derivative as open source in the same way the WordPress for Android software is provided (meaning your work must also be GPLv2), however, please understand that I am not able to provide you with specific legal advice for your case and you must read the document in it's entirety and follow all of the conditions because the license is a legal document which you must adhere to.

If you are interested in contributing back to the open source project in order to improve it for your own and others' use, please read the [How to Contribute](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md) section of the documentation for this project. Thank you!
