### ISSUE TITLE
Reader: YouTube videos cut off

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7636]
This was noticed by @daniloercoli [here](https://github.com/wordpress-mobile/WordPress-Android/pull/7613#issuecomment-380382839) - sometimes YouTube videos aren't correctly centered in reader detail.

![screenshot_1523445992](https://user-images.githubusercontent.com/3903757/38703209-98b6b2a6-3e70-11e8-850a-19c03f33af47.png)

**Comment by designsimply** [comment]
Tested with 14.6-rc-2 and confirmed this problem happens when using the Vimeo shortcode.

Steps to reproduce:

1. Create a new post.
1. Add a paragraph block.
1. Add a shortcode block.
1. Add the following shortcode: `[vimeo 44633289]`
1. Add another paragraph block.
1. Publish the post.
1. View the post in the Reader.

**Result:** the embedded video looks cut off

Reader in app | Chrome on Android 10
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79517930-e0574500-800c-11ea-9da0-5115bda8ac79.png" width="200" alt="Screenshot_20200416-140023"> | <img src="https://user-images.githubusercontent.com/1119271/79517964-f1a05180-800c-11ea-9e73-fe45ea66a955.png" width="200" alt="Screenshot_20200416-140440">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Comment by designsimply** [comment]
LGTM.

<img src="https://user-images.githubusercontent.com/1119271/86490446-a69cfd00-bd24-11ea-8489-6a4932167b6e.png" width="33%" alt="Screenshot_20200703-115704"> <img src="https://user-images.githubusercontent.com/1119271/86491896-68560c80-bd29-11ea-9bfd-421f8f7fb5cf.png" width="33%" alt="Screenshot_20200703-123134">
<p style="clear:both;"><sup>Tested with WPAndroid 15.2-rc-1 on Pixel 3 Android 10.</sup></p>
