### ISSUE TITLE
Reader:  Display full post within the Reader when viewing a single post.

### ISSUE THREAD

**Issue by cecoates** [wordpress-mobile/WordPress-Android#7723]
When viewing a post via the Reader on the Android app, Jetpack sites will only display an excerpt with a "visit site for more" link below the "cut".

WordPress.com posts display in full, so this appears to be specific to using the Reader in the app.

Tested with multiple Jetpack sites on:

Google Pixel XL

WordPress app version 9.8

Android version 8.1.0

#### Steps to reproduce the issue
Follow a site that uses Jetpack in the Reader: https://wordpress.com/following/manage

Open the WordPress app.

Click on the Reader icon.

Browse to a post from the Jetpack site you just followed.

Tap on post. Only an excerpt displays with a "Visit X site for more" link at the bottom.

#### What I expected

To see the full post once you tap on it in the Reader.

#### What happened instead

Only an excerpt displays with a "Visit X site for more" link at the bottom.

**This is how a post from a WordPress.com displays in the Reader on the app:**

![screenshot_20180506-172006](https://user-images.githubusercontent.com/10121835/39678536-2c6863c8-5154-11e8-83fe-0ab357874d97.png)

**This is how the same post displays once you install a plugin to make it a Jetpack site:**

![screenshot_20180506-172330](https://user-images.githubusercontent.com/10121835/39678535-290e6632-5154-11e8-8d1e-20e633a9c3e2.png)

**For comparison, here's a Jetpack site post in the app on iOS:**

![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/10121835/39678769-2aa2a220-5158-11e8-9d2b-4132d3efcfc7.png)

**And here's the same post on the Android app:**

![screenshot_20180506-180143](https://user-images.githubusercontent.com/10121835/39678773-3eb7cede-5158-11e8-8414-575613b1dc86.png)

Related ticket:

1048870-zen

**Comment by kraftbj** [comment]
Looking at http://gsmumbojetpack.mystagingwebsite.com/feed/ , it appears the Jetpack site in the test had the `For each article in a feed, show` option set to summary, which I presume the app is respecting.

At one time, the Reader within WordPress.com respected that setting as well, so this may be a change on the WordPress.com. I'm trying to trace back if it is intentional or not that Jetpack sites are not respecting that option within WordPress.com's reader, but not sure. ( https://github.com/Automattic/wp-calypso/pull/8497 is the closest I found initially).

@cecoates - for the other test site from your example, what is the Settings->Reading "For each article in feed" set to on the Jetpack site?

**Comment by kraftbj** [comment]
https://github.com/wordpress-mobile/WordPress-Android/pull/6514

The WP.com API provides an automatically crafted excerpt for Jetpack posts -- could this be creating a situation where every Jetpack post is being truncated?

**Comment by cecoates** [comment]
> @cecoates - for the other test site from your example, what is the Settings->Reading "For each article in feed" set to on the Jetpack site?

I made sure the feeds were set to display full post on each of the sites I tested on, for what it's worth!

It's also interesting that iOS and Android display the posts differently. In the above screenshots, same settings, same sites, but iOS displays the full post in the Reader (the same as you'd see in the browser when using Reader.)

**Comment by jeherve** [comment]
> In theory, should it only display the excerpt like that if the post uses an excerpt?

That seems to be the idea, yes, as per #7634.

**Comment by designsimply** [comment]
Thanks for submitting the issue @cecoates!

Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/7651. Props @nbradbury. 🎉

Double checked to confirm and I was able to see the full post in the Reader for Jetpack posts made on a site with My Sites > Settings > Writing > Feed Settings > "Limit feed to excerpt only" set to off and regardless of whether or not the post had an excerpt saved.

<img src="https://user-images.githubusercontent.com/1119271/70757828-4863ea80-1cfe-11ea-9f8e-ccec8b1e4c87.png" width="270" alt="Screenshot_20191212-163304"> <img src="https://user-images.githubusercontent.com/1119271/70757837-4d289e80-1cfe-11ea-8a76-eba84dbff75a.png" width="270" alt="Screenshot_20191212-163333">
<sup>Tested with WPAndroid 13.8-rc-1 on Pixel 3 Android 10.</sup>
