### ISSUE TITLE
Can't find drafts/disappearing drafts

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#7734]
### Expected behavior
All user drafts are visible in the app.

### Actual behavior
Some drafts are not visible (even though they are visible in remote). 

### Steps to reproduce the behavior
Steps -> Unknown

What a user said
`I can’t see any of the drafts which I created either via the app, or the site’s admin page (euromaidanpress.com). However, I can see a draft created by another user of our site. It’s all very strange.
When I create a draft via the app and save it as a draft, it disappears immediately after
`

The issue has been seen on both Jetpack and WordPress.com sites and on both single and multiple user sites.

##### Seen on [device], Android [version]
Honor 7X
WordPress 9.8
Android 7.0

**Comment by GeoJunkie** [comment]
This is happening to a user in 1338678-zen

**Comment by designsimply** [comment]
Closing because we don't have sufficient information to replicate the problem and because several updates have been made to the Post List as well as Offline Support in the Android app since this issue was originally filed.

Note: the ability to [filter posts by author](https://github.com/wordpress-mobile/WordPress-Android/pull/9484) was added to the Android app in version 12.4. 

If this issue comes up again, please re-open this issue (or create a new one!) and include the following details:

* Where were the missing drafts originally created? (app-only, mobile web, desktop, multiple places)
* Has the role been verified for the user creating the posts? (in other words, does the user have rights to edit the posts in question?)
* Ask the person experiencing the problem to please go to the Post List, pull to refresh, make sure they have selected the correct author filter at the top left (see screenshot [here](https://github.com/wordpress-mobile/WordPress-Android/issues/5884#issuecomment-471789386)), then check the app logs and send them to us so we can check for any new/related errors. Please post app logs to +mobilerequests or send them to support directly via the app from the Profile > Help & Support > Contact Us screen.
