### ISSUE TITLE
Consider utilizing DiffUtil to update RecyclerViews

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#7738]
We should consider utilizing [DiffUtil](https://developer.android.com/reference/android/support/v7/util/DiffUtil) to reflect changes in our RecyclerViews.

Benefits are pretty significant, but from my research, one potential issue might be that DiffUtils reports change relative to the data list size (eg. item 4 in a list have changed), and not aware of any decorative views we might have in adapter (eg. item 4 in a list has changed, be we have a header in the list, so the actual item that we need to update is 5).

**Comment by oguzkocer** [comment]
@khaykov We have been using `DiffUtil` in quite a few different places and without any issues. I think the way decorations are addressed is to make it a different view type and do the conversion before the calculation happens. Since this issue is not for any specific view, I think we should close it and keep using `DiffUtil` as much as possible. What do you think?

**Comment by khaykov** [comment]
@oguzkocer I agree. That's a pretty old issue, and currently, we are doing a good job utilizing `DiffUtil`
