### ISSUE TITLE
Stats: remove Stats menu when the stats feature is not active on a site.

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#7761]
### Steps to reproduce the behavior

1. On a Jetpack site, deactivate the Stats module.
2. Open that site in the app.
3. The Stats menu still appears in the app, and clicking it reveals the stats screen, with no stats at all, and no error indicating why I see no stats.

Maybe we should remove that menu when the Stats module is not active?

##### Tested on HTC U11, Android 8.0.0

**Comment by jeherve** [comment]
This is still an issue.

<img src="https://user-images.githubusercontent.com/426388/64263886-b7c48400-cf30-11e9-88d4-e96857bb19c7.png" width="270" alt="Screenshot_20190904-162504">

**Comment by thehenrybyrd** [comment]
Tested on **Samsung Galaxy S21, Android 12, WP Android 20.3-rc-1**. 
The current behavior, rather than removing the stats menu, is to display a prompt "enable site stats" when the stats module is disabled. Tapping that prompt enables the stats module again.

This seems like an acceptable resolution to this behavior, so I'll close this issue.
