### ISSUE TITLE
AlertDialog with `Calypso_Dialog` style is too small

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7787]
It looks like there is something wrong with our AlertDialog's size when we use the `Calypso_Dialog` style. Below you can find how it looks like in Site Settings page with and without the `Calypso_Dialog` style.

![screenshot_1526933366](https://user-images.githubusercontent.com/662023/40327553-61b959c4-5d11-11e8-914d-01d93ff6068c.png)

![screenshot_1526933474](https://user-images.githubusercontent.com/662023/40327620-9a969536-5d11-11e8-93c3-2f28f73ce786.png)

**Comment by theck13** [comment]
This can fixed by creating a new style for `SummaryEditTextPreference` with `@style/Theme.AppCompat.Light.Dialog.Alert` as the parent.

**Comment by oguzkocer** [comment]
It's an issue for everywhere `Calypso_Dialog` style is used.

**Comment by theck13** [comment]
The small width shown in your screenshots above is exaggerated the most in `SummaryEditTextPreference` instances.  That's why I mentioned the fix for that class.

Ultimately, this is related to the dialog style updates from https://github.com/wordpress-mobile/WordPress-Android/pull/7438 where the style parent was changed from `@style/Theme.AppCompat.Light.Dialog.Alert` to `@style/Theme.AppCompat.Light.Dialog`.  That was done to avoid layout issues with some dialog layouts we use.  If we change the parent of `Calypso.Dialog` back to `@style/Theme.AppCompat.Light.Dialog.Alert`, those issues will be reinstated.  See the screenshots below for illustration.

![style](https://user-images.githubusercontent.com/3827611/40331444-a37148da-5d0d-11e8-83df-3636e0605cf0.png)

There are other solutions, I just want to make sure we don't revert to previous issues.

**Comment by oguzkocer** [comment]
> The small width shown in your screenshots above is exaggerated the most in SummaryEditTextPreference instances.

Although that is true, the dialog is still small enough in other places that requires a fix.

I am not working on this issue, so I defer to @elibud who is going to be asking someone to take a look at this.
