### ISSUE TITLE
Recheck a method in PostUtils.java class

### ISSUE THREAD

**Issue by ChrisAntonopoulos** [wordpress-mobile/WordPress-Android#7843]
**showCustomDialog** method is grey colored in my Android Studio which means that this method probably is never been used by the program.

**Comment by designsimply** [comment]
I did a code search just now in the GitHub repo at https://github.com/wordpress-mobile/WordPress-Android/search?q=showCustomDialog and I didn't see any results except this issue. I think this means something must have been updated and this issue is okay to close.

@ChrisAntonopoulos thank you for the note and apologies for not replying sooner. If I've closed this issue in error, please let me know and I will re-open and investigate further.
