### ISSUE TITLE
Move the reader filter to the AppBar

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#7847]
Right now the dropdown filter in the reader (Discover, Followed Sites, etc.) is in a separate toolbar. This was necessary after the "masterbar" redesign, when the AppBar was dropped, but now that bottom nav returned the AppBar we can drop the secondary filter toolbar and move that functionality to the AppBar.

**Comment by AmandaRiu** [comment]
I evaluated what would be needed for this project and discussed some options with @nbradbury and decided that since the filter is a spinner that would need to be added to a custom toolbar view (since it's not an action), the current toolbar will be removed from `WPMainActivity` and each of the main fragments hosted by the `WPMainNavigationView` will host their own toolbar so the view can be customized on a per-fragment basis. 

Some gotcha's to keep in mind:
- [ ] `ReaderPostListFragment` is used by both the `WPMainActivity` _and_ `ReaderPostListActivity`
