### ISSUE TITLE
Analytics: Bumping registerPushNotificationToken stats for non logged users?

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#7881]
Wondering why we're bumping stats calling `AnalyticsTracker.registerPushNotificationToken` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/push/GCMRegistrationIntentService.java#L77) even if the user has no wpcom access token?

Side note: The actual implementation of `registerPushNotificationToken` in the Nosara tracker [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/libs/analytics/WordPressAnalytics/src/main/java/org/wordpress/android/analytics/AnalyticsTrackerNosara.java#L384) has empty implementation.

**Comment by oguzkocer** [comment]
I think we should just clean all this up. I don't even understand why we have a `registerPushNotificationToken` in an Analytics tracker 😕

It looks like it has been 3 years since that code was added and probably the underlying implementation has changed and this has not yet been cleaned up. @daniloercoli Would you like to handle that cleanup or should I?
