### ISSUE TITLE
Timezone selection can be confusing if some major cities are not included in the timezone dropdown list

### ISSUE THREAD

**Issue by simison** [wordpress-mobile/WordPress-Android#7900]
<img src="https://user-images.githubusercontent.com/87168/41403998-ce56fe4a-6fce-11e8-8934-7ede9598ffa7.png" width="220"/>

- If a customer lives in a place that's not listed here, it's hard to skim through a long list of cities to find something that could be near to them. Even if they find something, how would they know if it's on the same timezone as they are? To make it easier, there should be continents listed with city names (i.e. "Europe/Berlin", "Asia/Kuala Lumpur" etc)

- If a customer does not want to use timezone strings but UTC/GMT offsets instead, they are not listed. Timezone strings are special in that they follow summertime changes. Sometimes these work wonky or customers might have some other reasons to stick with "fixed" offsets. Adding a list of "UTC+/-" values would be helpful. 

- Not sure what happens if a customer has already chosen UTC-offset in WordPress wp-admin and then looks at this list?

Screenshots from Calypso:

![image](https://user-images.githubusercontent.com/87168/41404238-5b23f5c6-6fcf-11e8-89cf-94529dc90b97.png)

![image](https://user-images.githubusercontent.com/87168/41404260-66df4f96-6fcf-11e8-8ecb-382b49c822e1.png)

**Comment by designsimply** [comment]
Timezone selection currently follows WordPress Core & Calypso which offers a list of timezones from the PHP zoneinfo database, maintained by PHP. See <a href="https://core.trac.wordpress.org/ticket/3962#comment:67">core.trac/3962#comment:67</a>. Because creating and managing a custom list of timezones may not be something we would want to do, one way to improve this experience would be to match the behavior of a time zone suggester—one has been proposed in [core.trac/10660](https://core.trac.wordpress.org/ticket/10660) and was already implemented in Calypso.

Current screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/55914304-08af9680-5ba4-11e9-9b4d-94c95449a6b0.png" width="270" alt="Screenshot_20190410-140900"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/55914311-0c431d80-5ba4-11e9-8c24-d60b54639de7.png" width="270" alt="Screenshot_20190410-140812">
<sup>Settings > Timezone > [Search] in WPAndroid alpha-163 (12.2 alpha) on Pixel 3 Android 9.</sup>

<img src="https://user-images.githubusercontent.com/1119271/55913678-693dd400-5ba2-11e9-8ae2-1d677d7a62ce.png" alt="Screen Shot 2019-04-10 at 3 04 00 PM">
<sup>Settings > Timezone in WordPress 5.1.1.</sup>

<img src="https://user-images.githubusercontent.com/1119271/55913692-7490ff80-5ba2-11e9-9384-573ad32f78af.png" alt="Screen Shot 2019-04-10 at 3 06 06 PM">
<sup>Settings > Timezone in Calypso on WordPress.com as of 2019-04-10.</sup>
