### ISSUE TITLE
Add Option to Close Account in Settings

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#7944]
As per this documentation, it's now possible for users to close their accounts via their Account Settings in a web browser:

https://en.support.wordpress.com/close-account/

Questions around account deletion often come up in mobile support, so it'd be handy for users to be able to access this setting directly from the app.

**Comment by designsimply** [comment]
This came up today in an app store review:

<blockquote> am totally BLIND and there is NO WAY to DELETE WordPress Account in the app!</blockquote>

<p style="clear:both;"><sub>(internal reference: p1563664437001300-slack-cellular-happiness, p77Llu-c0a-p2#comment-14148) cc @annacmc</sub></p>

**Comment by designsimply** [comment]
For reference, here are some screenshots I took today:

#### Account with no plans or upgrades

![image](https://user-images.githubusercontent.com/1119271/110048358-f34e3300-7d0c-11eb-9669-67e36b3adb75.png)

#### Account with a plan

![Screen Shot 2021-03-04 at Mar 4 5 07 37 PM](https://user-images.githubusercontent.com/1119271/110048098-64d9b180-7d0c-11eb-8a35-d606e832d247.png)

Because closing an account is a permanent change and because the flow is subject to change at the WordPress.com level, would it be a good compromise to add a "How to Close Your Account" link to the "Account Settings" screen that links out to https://wordpress.com/support/close-account/ ? If not, I recommend closing this as it's possible to do from a browser and not a critical change to be able to make from the app because it **should** be hard to make this change considering it is a permanent change and complex if there are upgrades such as domain names involved. @yaelirub may I get your help with a decision about whether to keep this one open or if it would make sense to close it?

**Comment by jkmassel** [comment]
This has been addressed
