### ISSUE TITLE
Aztec: local changes detected after `undo`

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8009]
### Expected behavior
If content remains identical to what the Editor was fed with, it should not show the `Local changes` label when adding content then undoing.

### Actual behavior
Opening an existing post, adding a character then tapping on `undo` still makes the app believe there were changes made to the content.

### Steps to reproduce the behavior
1. Open existing post (make sure it's not a post with local changes at this point)
2. Type a character
3. Press Undo
4. Press back and observe "Local Changes" label on the post list

**Comment by hypest** [comment]
👋 @mzorz , I _think_ the expected behavior is for the case when the post doesn't have local changes _before_ entering the editor, right? If so, I can edit the description to include this condition.

**Comment by mzorz** [comment]
That's correct @hypest, I just edited the "steps to reporduce"  part tonclude this precondition

**Comment by rachelmcr** [comment]
In my testing, the issue here is that the "undo" action wasn't saved.

When I follow those steps to reproduce the issue, and then open the post again, I can see the changes that I made to the post even though those changes were removed with the "undo" button previously. (This also happens if I type a character and backspace to remove it; the character I added is saved locally.)

**Comment by designsimply** [comment]
Still valid. Moved to https://github.com/wordpress-mobile/AztecEditor-Android/issues/896.
