### ISSUE TITLE
Comments: Copy the URL to a specific comment

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8319]
Let's make it possible to copy the URL for a comment in the app. When the URL is copied, a toast message saying something like `URL copied to clipboard` can confirm the action.

A description of locations for copying the comment URL is below. A few outstanding questions:

* Should we include Notifications List and Comments List or only the Notifications Detail and Comments Detail?
* If Notifications List is included, where should be tap target be (there is no timestamp label)?
* If Comments List is included, how should we handle the existing multi-select mode activated with a long press?

**Notifications List**
1. Go to Notifications tab.
2. Long-press comment in notifications list.
3. Notice message that comment URL is copied.

**Notifications Comments List**
1. Go to Notifications tab.
2. Tap post in notifications list.
3. Tap Comments icon in post footer.
4. Long-press timestamp label for comment in comments list.
5. Notice message that comment URL is copied.

**Notifications Detail**
1. Go to Notifications tab.
2. Tap comment in notifications list.
3. Long-press timestamp label for comment.
4. Notice message that comment URL is copied.

**Comments List**
1. Go to My Site tab.
2. Tap Comments item under Publish section.
3. Long-press timestamp label for comment in list.
4. Notice message that comment URL is copied.

**Comments Detail**
1. Go to My Site tab.
2. Tap Comments item under Publish section.
3. Tap comment in comments list.
4. Long-press timestamp label on comment.
5. Notice message that comment URL is copied.

**Reader**
1. Go to Reader tab.
2. Tap Comments icon in post footer.
3. Long-press timestamp label for comment in comments list.
4. Notice message that comment URL is copied.

Internal ref: p4a5px-2gF-p2

**Comment by osullivanchris** [comment]
@rachelmcr  just picking this one up as one of my Hack Week pieces.

The concept is pretty clear to me. Just wanted to understand what the use case for copying the url to a comment is? Would it be for sharing it with someone else within my org? Or for copying to use on desktop/refer to, or something else entirely? Just want to know the workflow we have in mind here.

Thanks!

**Comment by osullivanchris** [comment]
Also just testing this on Calypso and unless I'm missing something - I can't see a place on a comment to copy a url there either. Is that right?

**Comment by rachelmcr** [comment]
@osullivanchris Thanks for picking this up! My understanding from the original (internal) discussion was that this was mostly a power user feature, especially for the first case you mentioned: sharing the comment with someone else within an org (e.g. copy the link and share in Slack/email/etc).

> Also just testing this on Calypso and unless I'm missing something - I can't see a place on a comment to copy a url there either. Is that right?

Copying the comment URL from Calypso can happen in a few places:

1. Notifications detail: Right-click (on desktop) or long tap (on mobile web) on the comment timestamp.
![Screenshot 2019-07-26 14 17 37](https://user-images.githubusercontent.com/8658164/61954308-7bf0e300-afb0-11e9-8241-e22f4093b3ed.png)

2. Reader: Right-click (on desktop) or long tap (on mobile web) on the comment timestamp. 
![Screenshot 2019-07-26 14 17 50](https://user-images.githubusercontent.com/8658164/61954314-7e533d00-afb0-11e9-82c9-e10ac6678aeb.png)

3. Comment detail (under My Sites > Site > Comments): Select a comment and copy the comment permalink listed under the comment.
![Screenshot 2019-07-26 14 18 12](https://user-images.githubusercontent.com/8658164/61954318-814e2d80-afb0-11e9-9aa3-530742559a87.png)

**Comment by osullivanchris** [comment]
Here's some work I did on this for hack week @rachelmcr !

A couple of changes to the proposed solution after working through it.

- I don't think we should add the functionality to the notification screen. The reason being - then different items on that screen will have different functionality. Some notifications would have long press (or a button or whatever) to copy, but others would not.
- Using a button for the action rather than long press. Long press is not always discoverable, and especially in this context if users do not expect to long press on other notifications/items I think it makes it clearer/more disoverable
- Although its buried one level deeper being on the details screen, its a feature for advanced users and something that only needs to be learned once.

Please see the mocks below

- Version 1 I added an extra icon to the list of actions. I already think there might be too many actions. And this new one pushes it over the limit especially on small screens, so
- In version 2 I added a 'more' icon and moved some of the actions into the menu that appears (can re-arrange which ones are on view initially if you think some are more important or if we have any data). 
- Also thought it might be nice to give the user the option to share directly from the Snack Bar that appears

Open to opinion here, I would suggest go with option 2.



![CopyCommentURL](https://user-images.githubusercontent.com/50576199/62064062-fbd2b380-b223-11e9-931d-124761bbaaf3.png)

**Comment by rachelmcr** [comment]
These options look great!

> In version 2 I added a 'more' icon and moved some of the actions into the menu that appears (can re-arrange which ones are on view initially if you think some are more important or if we have any data).

I like the idea of a 'more' icon to give a bit more space (reducing the fear/reality of hitting the wrong button).

As for order, we don't have data on how often comments are edited from here (as far as I see) but of the other actions Approving and Liking are by far the more popular ones so it makes sense to keep them where they are. Trashing and spamming comments are done at similar rates with a _slight_ preference for Trash, so it could be worth swapping those but it could go either way.

**Comment by megsfulton** [comment]
This looks great! I much prefer option 2.

While I like the ability to share from the snackbar, I do wonder about having that be the only place where that functionality is available.

**Comment by osullivanchris** [comment]
Thanks for the feedback @rachelmcr @megsfulton 

Sounds like we're unanimous with **option 2**. Going to move this issue to 'done' from design POV. We should make a duplicate iOS issue also.

🚢

**Comment by osullivanchris** [comment]
> While I like the ability to share from the snackbar, I do wonder about having that be the only place where that functionality is available.

Forgot to reply for this. I'm not too worried about it for now. Its not something you can do today, and it wasn't part of the request. Its a nice extra. If we get some feedback that its hard to share we could make this more prominent.

**Comment by designsimply** [comment]
Moving this into the dev Groundskeeping project with a note to ask Groundskeepers if this is something small enough to include in a one-week maintenance rotation or if it should be recommended as project work instead.

**Comment by osullivanchris** [comment]
@designsimply ace! Thanks for moving it forward
