### ISSUE TITLE
Site Creation: Quick Start pop-up window disappears too quickly

### ISSUE THREAD

**Issue by OlenaBulat** [wordpress-mobile/WordPress-Android#8366]
### Expected behavior: 
Should be enough time to read the pop-up text and to choose the option.   
**Suggestion:** 10 sec for showing or show until a user will not choose the option. 
### Actual behavior
5-6 sec time to show the Quick Start pop-up window. User is not in time to read the text which seeing for the first time and to make the choice. 

### Steps to reproduce the behavior
1. Create a new site
2. Accept the Quick Start helper

**Comment by rachelmcr** [comment]
Thanks for the suggestion! I confirmed that after I select "Yes" on the Quick Start prompt I only see the "View your site" pop-up at the bottom of the screen briefly.

I also don't get anything to point out to me that I can return to the Quick Start checklist at the top of the My Site screen after that pop-up disappears. Since the problem is not having enough time to process what that pop-up says, perhaps the first step could be pointing out the Quick Start menu item and then continue into the checklist steps.

Screenshot of that pop-up for reference:

![screenshot_20180925-113700](https://user-images.githubusercontent.com/8658164/46009648-1c882500-c0b8-11e8-99c0-4026ecee860f.png)

**Comment by khaykov** [comment]
ping @SylvesterWilmott

**Comment by SylvesterWilmott** [comment]
@khaykov correct me if I'm wrong but the behaviour should be that if you miss the notice you'll see it again once you return to the site dashboard after navigating away before finally being directed to the list.

Anyway, if users are having trouble processing the information in 5 seconds we can extend to 10

**Comment by khaykov** [comment]
@SylvesterWilmott Yes, that's correct. Should I go ahead and increase the delay to 10 seconds?

**Comment by antonis** [comment]
Closing since the UI has changed and the issue is not reproducible anymore.
