### ISSUE TITLE
Stats Widget| Latest Post Summary refreshed issue

### ISSUE THREAD

**Issue by OlenaBulat** [wordpress-mobile/WordPress-Android#8388]
### Expected behavior
If still is not any post should be shown the message "You have not published any post yet". 

### Actual behavior
Latest post summary in the Stats can't be refreshed 

### Steps to reproduce the behavior
1. the app is opened on the mobile
2. "My Site" tab is opened
3. click on the "Stats" item
 - the "Stats" item/page is opened
![screenshot_2](https://user-images.githubusercontent.com/26138552/46408997-a66d6900-c71c-11e8-9290-9e288613a390.png)

**Comment by daniloercoli** [comment]
Hi @OlenaBulat - thanks for reporting the issue. 
In case of no posts on the site, the entire `Latest post summary` section should not be visible on the screen.
Would you mind to provide more details about the blog you're experiencing the issue? Is it a WordPress.com or a Jetpack block?

**Comment by OlenaBulat** [comment]
@daniloercoli It is site build on the WP, Jetpack block. 
First, it was totally without statistic, to use the Stats section WP suggested to set up the Jetpack plugin. So after the success setting up, Stats became available and I have seen this **Latest post summary** section.

**Comment by daniloercoli** [comment]
I've just created a new WordPress.org site, removed the demo post. It's now with 0 posts and 1 page only. Installed Jetpack and connected to my WordPress.com account.
When I start the app, and select the site, the Stats "Latest Post Summary" section  is not there (as expected by design).

Would you mind to post your App log here, and help finding the root cause of the issue?
- Start the app
- Select the site
- Go to Stats (wait until Stats are loaded, and try with a "pull to refresh")
- Go back to the home screen
- Select the Me tab --> Help & Support
- Application Log
- Copy or share the application log, and paste the content here

**Comment by elibud** [comment]
Closed due to inactivity, @OlenaBulat please reopen if this is still an issue.
