### ISSUE TITLE
Editor: Headings and List options in toolbar not translated

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8598]
### Expected behavior

I expect the heading options and list options in the editor toolbar to be translated.

### Actual behavior

When you select the Heading button or List button in the toolbar, the options are always listed in English.

It looks like the strings are [translatable in Aztec](https://github.com/wordpress-mobile/AztecEditor-Android/blob/2eb3147d7dbb5d109fa7e477f919015cb1f57c3e/aztec/src/main/res/values/strings.xml), but they aren't actually translated in that repo and we aren't pulling those English strings to translate them on the WordPress end, either. (Presumably the best solution would be to contribute translations back to the Aztec project and then make sure we're using them in the WP app.)

You can test this by changing the app language to any non-English language and checking the heading and list options in the editor toolbar. Screenshots with app set to German:

![screenshot_20181113-145409](https://user-images.githubusercontent.com/8658164/48421772-0fe98a00-e755-11e8-8c52-875d3a1638a9.png)
![screenshot_20181113-145404](https://user-images.githubusercontent.com/8658164/48421773-0fe98a00-e755-11e8-9dcc-2e80d9b12d50.png)

##### Tested on Moto e5 Play, Android 8.1.1, WPAndroid alpha-136

Original report from Louis, internal ref: pxLjZ-52s-p2

**Comment by rachelmcr** [comment]
Setting this as low priority since our focus is currently on Gutenberg.

**Comment by SiobhyB** [comment]
I can confirm that this is still an issue with the classic editor. Here are screenshots taken while testing with German enabled on a Pixel 5, Android version 11, and version alpha-285 of the WordPress app:

| List  | Headings |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/113009442-da9c3600-916f-11eb-8def-bd53c8375fde.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/113009565-f9023180-916f-11eb-9725-be9503793ddc.png" width="100%"> |

This is "resolved" by switching to Gutenberg, you'll see that the headings are translated into German in my testing and the unordered/orders lists are now represented through icons rather than text:

| List  | Headings |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/113010225-9493a200-9170-11eb-9e52-405fbecc3d68.png" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/113010314-a412eb00-9170-11eb-9aa6-30ad33d7ab36.png" width="100%"> |

As this is resolved in Gutenberg, I agree with the low priority and possibly even marking this as a `wontfix`?

**Comment by SiobhyB** [comment]
I'm going to go ahead to close this, as it's resolved in Gutenberg and the classic editor is [set to be removed](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3209). Feel welcome to re-open with any further thoughts!
