### ISSUE TITLE
Editor: Add Justify option

### ISSUE THREAD

**Issue by KokkieH** [wordpress-mobile/WordPress-Android#8667]
We've [received a request](https://twitter.com/TwentySwans/status/1067239890574807040) to have a Justify button added to the editor toolbar on the app. Currently is only has left, right and center-aligned.

For context, here's a corresponding request to have it added to the block editor on WordPress.com: https://github.com/Automattic/wp-calypso/issues/28696

This is also under discussion for Gutenberg in Core: https://github.com/WordPress/gutenberg/issues/8450

**Comment by rachelmcr** [comment]
Thanks for reporting the request! I'm going to close this issue because we're tracking alignment issues in each mobile editor repo separately.

We're currently tracking this for Aztec here: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/649

And for mobile Gutenberg, we are tracking work for an alignment toolbar in the paragraph block here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/170
