### ISSUE TITLE
Preserve scroll and caret position after rotating (Gutenberg Editor)

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/WordPress-Android#8739]
Preserve scroll and caret position after rotating in Gutenberg Editor

**Comment by koke** [comment]
Can you add this as part of https://github.com/wordpress-mobile/gutenberg-mobile/issues/196 instead to keep track of it for the alpha?

**Comment by marecar3** [comment]
@koke done.

**Comment by mzorz** [comment]
Moving to `Beta` and unassigning it for now a per the following https://github.com/wordpress-mobile/WordPress-Android/pull/8800#issuecomment-448231918

**Comment by mzorz** [comment]
Unassigning, sorry for keeping myself assigned to it @hypest 

What happened is: this is something I assigned to me because I thought of fixing it with #8874 with the `GutenbergEditPostActivity` (that PR was created 2 days later), but this other approach has been [superseeded now as per this](https://github.com/wordpress-mobile/WordPress-Android/pull/8874#issuecomment-457182072). In this other approach, as you mentioned in our video call, still needs the caret position and scroll position to be preserved, so this issue is still valid and needs to be tackled.

Unassigning as per conversation then 👍

**Comment by hypest** [comment]
> Assuming this is related, @rachelmcr reported some more issues on rotation:
> 
> > when I rotated between portrait and landscape the content prompt and toolbar disappeared and took a noticeable amount of time to reappear on screen
> > If I rotate the device with a post that has content, all the content disappears and takes some time to reload
> 
> I imagine this is caused by the same thing (Android reloading the full RN view when rotating), but feel free to create separate issues if not

Performance and caret position are addressed in #9030 . Scrolling position will most probably be handled in a separate PR.
