### ISSUE TITLE
Saved Posts Removed From Release App When Refreshing Old Debug App

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8791]
### Expected
All saved posts remain in the ***Saved posts*** list of the ***Reader*** until they are removed by the user and none are removed after using a debug version of the app.

### Observed
Some saved posts remain in the ***Saved posts*** list of the ***Reader*** until they are removed by the user and some are removed after using a debug version of the app.

#### Note
The issue seems to occur when two instances of the WordPress app are installed on a single device (i.e. one release app `org.wordpress.android` and one debug app `org.wordpress.android.beta`) _and_ the debug app does not include the ***Saved posts*** feature.  When testing the steps below on a device with the current release app, 11.3, and the `develop` branch, alpha-142, the issue doesn't occur.  The device producing the issue has the current release app, 11.3, and an old debug app, alpha-80, which did not have the ***Saved posts*** feature.

Also, saved posts recently published remain after performing the steps below while saved posts published long ago are removed.

When the posts are saved does not seem to affect whether they remained or they are removed.

This scenario is not common for users since it requires both release and debug apps on a single device, but it may reveal an underlying issue with saved posts.

### Reproduced
Steps performed in the release app are prefaced with "Release:" and "Debug:" for the debug app.

0. Install release app 11.3 and debug app alpha-80.
1. Launch release WordPress app.
2. Release: Save one post from first page of ***Reader*** and one post from long ago.
3. Release: Go to ***Reader*** tab.
4. Release: Select ***Saved posts*** from toolbar filter.
5. Release: Notice recent post and old post are shown.
6. Tap overview navigation button.
7. Dismiss release WordPress app from recent apps list.
8. Debug: Launch debug WordPress app.
9. Debug: Go to ***Reader*** tab.
10. Debug: Notice post list refreshes.
11. Tap overview navigation button.
12. Dismiss debug WordPress app from recent apps list.
13. Launch release WordPress app.
14. Release: Go to ***Reader*** tab.
15. Release: Select ***Saved posts*** from toolbar filter.
16. Release: Notice recent post remains and old post is removed.

##### Tested
Google Pixel 3 on Android 9.0 with WordPress 11.3 and alpha-80

**Comment by theck13** [comment]
I don't think this is related to having a debug version and a release version of the app on one device.  I removed the debug app from my device and verified the saved posts were still shown in the release app four days ago.  Today I noticed two out of three of my saved posts were removed.  The one post that was not removed was recently published (i.e. about two days ago).  The two posts that were removed were published months ago (i.e. October 31, 2018 and November 15, 2018).

**Comment by malinajirka** [comment]
>I don't think this is related to having a debug version and a release version of the app on one device.

As we discussed I don't think it can be related as for the OS the two apps are completely independent apps - they are signed with a different key.


The issue is caused by a bug which has been in the app for ages, it just hadn't had any user-facing impact until we implemented Saved Posts.

Steps to reproduce
1. Open Reader - followed sites tab
2. Scroll down as far as you can (there is a limit)
3. Save the last post in the list
4. Go to Saved posts and notice the post is there
5. Go to Discover tab
6. Start following one of the sites
7. Go back to Followed-sites tab
8. Restart the app
9. Go to Saved posts and notice the post is not there

We keep only 200 most recent posts in the cache. When you start following a new site and you restart the app all posts which are not in 200 most recent posts are removed. However, there is a bug in the SQL query so we are not removing just posts which don't fit in first 200, but also all posts which have different tag than "followed-sites" (or the one which has more than 200 posts).

**Comment by theck13** [comment]
I'm unable to reproduce the issue when performing those steps on `develop`.  Do you have any other details that may help me cause it consistently?

**Comment by malinajirka** [comment]
> Step 7. Go back to Followed-sites tab

Maybe just try to pull-to-refresh in step 7. If it doesn't help I'll dm you credentials to my testing account on which I'm able to reproduce it consistently.
