### ISSUE TITLE
Post List: Sync posts automatically

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#8807]
We've had a user suggest automatic syncing in 1645933-zen. 
What they're imagining is that if they write a post offline, the app would sync them immediately as soon as an internet connection is regained.
It sounds like they'd expect this to happen behind the scenes, whether they have the app open or not.

Not sure if this is something we want to explore, but I'll add it here in case we get other similar requests.

**Comment by rachelmcr** [comment]
Work on this syncing behavior could be part of the User Expectations work in 2019 (seamless syncing, offline support).

**Comment by SiobhyB** [comment]
+1 to this. We have some more feedback from a user in 1651288-z. The user notes that they are often confused about whether changes they've made in the app have been synced correctly or not, as there's no clear visual indicator. It seems like automatic syncing would go some way to resolving this (and may also help with problems we see around posts being overridden when edited across devices).

**Comment by SiobhyB** [comment]
The user from 1651288-zen (my original comment) has come back again in 2575660-zen to reiterate their feedback. They frequently edit posts across both the app and the web, and lack of seamless syncing is a pain point for them.

**Comment by designsimply** [comment]
Should be fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/10319 and https://github.com/wordpress-mobile/WordPress-Android/pull/10353. Props @malinajirka. 🎉

Note: there are still potentially some quirks to work out with the conflict resolution such as https://github.com/wordpress-mobile/WordPress-Android/issues/10292 and that work has not yet been assigned but is worth considering as a project, especially if more users raise the issue going forward.
