### ISSUE TITLE
Injectable AppLog

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#8817]
It's unnecessary complicated to write unit tests for classes which use AppLog's static methods. Goal of this task is to create an injectable wrapper for AppLog which can be easily mocked.

**Comment by aforcier** [comment]
Just sharing the approach we took to solve this issue in the Woo app in case it's useful - we kept `AppLog` (we have a modified version called `WooLog`) as-is but overwrote the class in the unit tests with a version that logs to `System.out` (so you can read the output in the unit tests) instead of using the Android `Log` framework class. This meant nothing had to change in production code.

```kotlin
package com.woocommerce.android.util

import com.woocommerce.android.util.WooLog.LogLevel
import com.woocommerce.android.util.WooLog.T
...

 * Testing version: replaces android.util.Log calls with System.out, since the unit tests don't have access
 * to Android Framework classes.
 */
object WooLog {
    // T for Tag
    enum class T {
        DASHBOARD,
        ORDERS,
        UTILS
    }

...
    /**
     * Sends a VERBOSE log message
     * @param tag Used to identify the source of a log message.
     * It usually identifies the class or activity where the log call occurs.
     * @param message The message you would like logged.
     */
    fun v(tag: T, message: String) {
        System.out.println("v - " + TAG + "-" + tag.toString() + " - " + message)
        addEntry(tag, LogLevel.v, message)
    }
...
}
```

**Comment by aforcier** [comment]
@malinajirka haven't taken a close look, but if you just recently added the `SITE_CREATION` tag, it might be a dependency conflict issue - I would guess that an updated `utils` binary would solve the problem.
