### ISSUE TITLE
Media: Can't save image from media library on Atomic site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#8840]
### Expected behavior

I expect to be able to save any media item in my site's media library to my device.

### Actual behavior

When I try to download a media item from a WordPress.com Atomic site, it doesn't download correctly.

I can download media from WordPress.com Simple, Jetpack, and self-hosted (non-Jetpack) sites.

### Steps to reproduce the behavior

1. On an Atomic site, go to the My Sites tab.
2. Open the Media section.
3. Tap on a media item (e.g. image) to open the details.
4. In the top right corner, tap the cloud icon (on a small screen, tap the ellipsis menu and select "Save").
5. Note that a toast message "Saving media to this device" appears.
6. Open your device files and look for the downloaded media file.

Result: The media file is not downloaded. On one device (moto e5 play with Android 8.1) I didn't see anything downloaded anywhere on the device. On another device (Nexus 9 with Android 7.1.1) I see this downloaded file that doesn't contain any filename or data:

![screenshot_20181220-123131](https://user-images.githubusercontent.com/8658164/50285514-51f0a480-0454-11e9-83a8-1df96999d005.png)

##### Originally reported by user with two devices using WPAndroid 11.3 & 11.4.

Internal ref: p4a5px-2jX-p2

**Comment by daniloercoli** [comment]
It seems that tapping on the "Download" icon does properly enqueue the request by using the  `DownloadManager` ...but querying it after a while with the proper `mDownloadId` (returned when the request is enqueued),  the manager does return the status `STATUS_PAUSED` and the reason is `PAUSED_WAITING_TO_RETRY`. 

```
PAUSED_WAITING_TO_RETRY
added in API level 9
public static final int PAUSED_WAITING_TO_RETRY
Value of COLUMN_REASON when the download is paused because some network error occurred and the download manager is waiting before retrying the request.

Constant Value: 1 (0x00000001)
```


If you wait a minute or so the broadcast that is registered to monitor the download progress is called with the `STATUS_FAILED` and the reason `ERROR_HTTP_DATA_ERROR`.

```
ERROR_HTTP_DATA_ERROR
added in API level 9
public static final int ERROR_HTTP_DATA_ERROR
Value of COLUMN_REASON when an error receiving or processing data occurred at the HTTP level.

Constant Value: 1004 (0x000003ec)
```

It seems that something is happening at HTTP level, since the URL of the picture passed to the download manager can be opened in a browser, or download by a command line program like `cURL` or `wget`.
