### ISSUE TITLE
Blog posts: View: Link always opens with site address instead of custom domain

### ISSUE THREAD

**Issue by arunsathiya** [wordpress-mobile/WordPress-Android#8884]
### Expected behavior

The link that opens on the new tab of the browser shows the custom domain of the site, or the primary domain of the site

### Actual behavior

The link that opens on the new tab of the browser shows the WordPress.com site address

### Steps to reproduce the behavior

- Start with a WordPress.com site on the app
- Click on `Blog posts`
- Click `View`
- When the preview opens up, click on the browser icon at the top
- Notice the link on the browser

##### Tested on [device], Android [version]

Tested on OnePlus 5 with Android 8.1.0. WordPress app version alpha-144

I searched a bit and the closest related issue is https://github.com/wordpress-mobile/WordPress-Android/issues/3171. I did not see any other reports as the one I have mentioned.

I haven't been able to test on iOS either.

**Comment by rachelmcr** [comment]
Does this cause a specific problem? This behavior matches Calypso, which always uses a WordPress.com site's underlying *.wordpress.com site address when viewing or previewing posts from the posts list. This also appends a preview parameter to the post link (see https://github.com/wordpress-mobile/WordPress-Android/issues/5806 for a related issue on that point).

If you're sharing the post, though, you can use the "Share Link" option to get a link with the site's primary domain.

**Comment by arunsathiya** [comment]
No, it does not cause any problems, but this was more of an enhancement request. 

That's good to know! 

I just looked at Calypso, and it appears it shows the WordPress.com site address as well, but it automatically redirects to the primary domain.

This does not seem to happen on the mobile browser, and doesn't feel like something that's caused by the WordPress Android app. Essentially when I open the preview, the preview is launched on the in-build WordPress Android app's browser, and when I click on the browser icon, Google Chrome kind of loads up the same session. 

I think this mimics Chrome Custom tabs, or actually is Chrome Custom tabs in use.

Having said this, I think it's safe to say that everything is behaving as expected. I shall close this issue. 👍🏽 

Please feel free to reopen if you feel otherwise.

**Comment by designsimply** [comment]
This came up today in Slack (internal reference: p1560457969019100-slack-cellular-happiness). I tested published posts and drafts in the Post List on a WP.com site with a custom domain `artindesignco.blog` using WPAndroid alpha-173 (12.6 alpha) on Pixel 3 Android 9 and found the following.

For published posts in the Post List:

* World icon lands at: https://artindesignco.wordpress.com/2019/06/11/block-editor-test/?preview=true
* Share icon > Copy to clipboard: http://artindesignco.blog/2019/06/11/block-editor-test/

For unpublished posts in the Post List, such as drafts or scheduled posts:

* World icon lands at: https://artindesignco.blog/?p=33 (HTTP may be redirecting to HTTPS)
* Share icon > Copy to clipboard: http://artindesignco.blog/?p=33

I can confirm there is a difference in Calypso (as of 2019-06-13) where the View link for posts in the Post List points to the `*.wordpress.com` version of the domain (as Arun mentioned) but without the `?preview=true` query string, which is why it is able to redirect. I don't think `?preview=true` is needed if you are coming from the post list but I think it is needed if you are previewing coming from the editor or else unsaved changes could be missed.

My recommendation would be to us the custom domain and the proper protocol (HTTP/HTTPS) for the site for the World icon and the Copy to clipboard options for all posts in the Post List and to use the `*.wordpress.com` version of the link with the `?preview=true` from inside the editor so that it's possible to preview unsaved changes to published posts (which doesn't seem to work without the query string).

Re-opening for a 2nd opinion. @diegoreymendez or @malinajirka could you help with a decision on this request?

**Comment by designsimply** [comment]
Note: I found that @megsfulton also recommended using the published post view (the one without `?preview=true`) for Site > Blog Posts > View at https://github.com/wordpress-mobile/WordPress-Android/issues/9649#issuecomment-487706183 so I think updating to use the custom domain for the world icon makes sense to update for that case while editor previews should still use `?preview=true`.

**Comment by malinajirka** [comment]
>My recommendation would be to us the custom domain and the proper protocol (HTTP/HTTPS) for the site for the World icon and the Copy to clipboard options for all posts in the Post List and to only use the *.wordpress.com version of the link with the ?preview=true from inside the editor so that it's possible to preview unsaved changes to published posts (which doesn't seem to work without the query string).

I think it'd be great to bring consistency between the mobile platforms and this proposal sounds good to me.

**Comment by thehenrybyrd** [comment]
Had this come up again in a ticket, #2127446-zen. 
The confusion stems in this case from the user wanting to share the URL used. It's undesirable to share the .wordpress.com URL when a custom domain is being used, so redirecting to the custom domain would clear up the confusion.

**Comment by malinajirka** [comment]
I'd suggest holding this ticket until `https://github.com/wordpress-mobile/WordPress-Android/tree/master-auto-upload` is merged. It contains a lot of changes to remote previews. It should be merged in the following two weeks.
