### ISSUE TITLE
Error: Unexpected error message when attempting to login via site address with incorrect credentials

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#8945]
When using the “site address” login flow to connect directly to a self-hosted site account with the site address being an IP address if the credentials are incorrect an unexpected error message is displayed.

### Expected behavior

Something like,

<img src="https://user-images.githubusercontent.com/6520461/49553850-9c581a00-f8c7-11e8-95dd-94322a80efbb.png" width="270" alt="screenshot_2018-12-05-19-47-34">

### Actual behavior

<img src="https://user-images.githubusercontent.com/6520461/49553849-9c581a00-f8c7-11e8-8e83-593d5f536d4b.png" width="270" alt="screenshot_2018-12-05-19-47-03">

### Steps to reproduce the behavior

Follow steps

* Create an account on a self hosted site with or with out Jetpack installed, make sure to set that account as an author and do not connect it to a WordPress.com account via jetpack.
* Use the “site address” login flow to connect directly to that account

From the 11.4 call for testing (internal reference: p5T066-JC-p2#comment-2273) but use the IP address for the site as the site address.

**Comment by theck13** [comment]
@JavonDavis, can you provide more details about logging in with the IP address?  I'm unable to get to the username/password screen shown in the second screenshot above using an IP address for the site.  I get the following error message on the site address screen.

```
Couldn't connect to the WordPress site. There is no valid WordPress site at this address. Check the site address (URL) you entered.
```

**Comment by JavonDavis** [comment]
> @JavonDavis, can you provide more details about logging in with the IP address? I'm unable to get to the username/password screen shown in the second screenshot above using an IP address for the site. I get the following error message on the site address screen.

@theck13 Umm I think I stopped paying for that digital ocean account and the server I was using for that IP is no longer available, sorry about that! It just needs to the IP address of a self-hosted site instead of the hostname. Once I entered that I got prompted for the username/password.

**Comment by designsimply** [comment]
Raising in priority because error message handling came up recently from the Mobile Guild as an ongoing problem.

**Comment by malinajirka** [comment]
I've just tried to enter IP addresses of 5+ self-hosted sites and none of them worked. The app always displays "The site at this address is not a WordPress site. For us to ...". 

Tbh I think the error message is actually correct. The server apparently responded with "Invalid_response" error message, instead of "invalid_credentials". As a result, we show user friendly "Error while adding site" message and error code/message to help us debug the issue "Error code: Invalid response". We can't tell the user the credentials were invalid since we don't know it. 

@designsimply All in all I I'd suggest closing this issue with "works as expected". We'd be ideally showing only number error codes instead of "INVALID_RESPONSE" but this improvement is more of a project than groundskeeping task.

**Comment by designsimply** [comment]
Does updating to number error codes mean it would change from saying "Error code: INVALID_RESPONSE" to something like "Error code: 502 Bad Gateway" or "Error code: 503 Service Unavailable" or "Error code: 410 Gone" — in other words, it would be the more specific HTTP response status code instead of "INVALID_RESPONSE" to cover several of those (which is what is happening now)?

**Comment by malinajirka** [comment]
In an ideal scenario it'd be even more specific. Eg. `Error Code: 92938` which we could translate into a specific error the API returned. However, I'm not sure it's even feasible with the current state of the API documentation.

**Comment by designsimply** [comment]
Thanks for the clarification!

Closing this issue per the recommendation and opening a separate enhancement ticket for the error messaging improvement: https://github.com/wordpress-mobile/WordPress-Android/issues/10406.
