### ISSUE TITLE
Posts list: new draft should scroll to top

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#9146]
### Expected behavior
Start a new draft and come back: should scroll to the top when I'm back from starting a new draft, so I can see the newly created item.

### Actual behavior
Start a new draft and come back: the list doesn't move, so I don't know where my draft is. Should scroll to the top when I'm back from starting a new draft.

### Steps to reproduce the behavior
1. go to Posts list
2. start a new draft (be sure to enter some content in title and/or body)
3. tap BACK
4. observe the draft gets uploaded and the snackbar appears, but the list does not scroll. You have to scroll up to see your new draft.

**Comment by oguzkocer** [comment]
This is a known issue with the `DiffUtil` we are using. We'll try to address it in the post filters project, but I am not sure if it's going to work out without a hack.

**Comment by oguzkocer** [comment]
I've been thinking about this quite some time and I feel like `DiffUtil` is doing the correct thing by not scrolling the user to the top when new items are added. The reason is that the user is currently looking at a specific item and if that item hasn't changed, there is no reason to change the visible item other than letting the user know that there are new items. So, why not address that part separately?

What I am thinking off is somewhat similar to what the Reddit app does. Whenever there are new items added at the top of the list, it shows a [Refresh] button at the top and when it's tapped it brings you to the top of the page. The button is shown and hidden as the user scrolls up and down. I believe this approach is used in several different apps in slightly different ways, so it's something users are used to.

By using this approach we'd:

* Keep the user looking at the same item they were looking at before the reload, so no interruptions
* We'll indicate that there are new items so they won't go unnoticed
* Have a solution that works even if the user is looking at the item 100. In the original hacky solution we used, it'd only work if the user is looking at the top few items because scrolling 100 items would be a really bad experience, but this way it works regardless of the user's position and when the fetch happens.

@malinajirka @mzorz @SylvesterWilmott What do you think?

**Comment by malinajirka** [comment]
Yep, I was thinking about almost the same solution. I think we could scroll automatically when the user is at the top of the list before the new item at the top appears and show the "Scroll to new posts/Refresh" or similar button when the user is not at the top. But I guess it's not necessary to complicate it and we can just always show the button.

**Comment by SylvesterWilmott** [comment]
@oguzkocer Interesting idea. I like it a lot.

I'm trying to visualise it, do you mean something like this:

<img width="401" alt="Screenshot 2019-04-08 at 11 23 49" src="https://user-images.githubusercontent.com/36532468/55717253-d6aa0300-59f0-11e9-83bc-81e5778ca5c2.png">

**Comment by oguzkocer** [comment]
Yeap, exactly like this @SylvesterWilmott!

**Comment by SylvesterWilmott** [comment]
@oguzkocer I've added a design for this to Zeplin.

**Comment by oguzkocer** [comment]
For full disclosure, below is a screenshot of the design from Zeplin as I don't know how to export it.

![Screen Shot 2019-04-16 at 2 07 45 PM](https://user-images.githubusercontent.com/662023/56233430-1310db00-6051-11e9-80cc-ebe32b272f90.png)

**Comment by oguzkocer** [comment]
I've looked into this issue a bit to at least see what's possible to do and following @malinajirka's suggestions, I was at least able to detect that the first item of the list has changed to show a `New Posts` button. I hacked together something (very temporary) which might be useful later on as I don't think I'll be able to finish this during my Groundskeeping. The changes are in the `try/post-list-new-posts-button` branch.
