### ISSUE TITLE
WPScreenshotTest fails

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#9271]
Looks like there's an issue with WPScreenshotTest where it doesn't pass. Looks to be a an actual issue with `Screengrab.screenshot()`, nothing with our code specifically.

**Comment by rachelmcr** [comment]
WPScreenshotTest has been worked on and significantly updated since this issue was opened, with tests confirmed working as of the major update in https://github.com/wordpress-mobile/WordPress-Android/pull/9928. I haven't worked on WPScreenshotTest since then, and I am having trouble running the test now, but I think we can close this issue and resolve any new issues separately as needed.
