### ISSUE TITLE
Post List: Draft created twice

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9347]
### Expected behavior
Only one draft is created.

### Actual behavior
Two drafts are created.

### Steps to reproduce the behavior
1. Go to My Site -> Blog Posts
2. Click on Create post button
3. Enter title + content
4. Click on toolbar overflow menu -> Save as draft
5. Press Up button (arrow) before the upload finishes
6. Notice the app creates two drafts

##### Tested on [device], Android [version]
Android 9, Emulator Pixel 2 Google Play

**Comment by oguzkocer** [comment]
@malinajirka Is this the same issue as #8594?

**Comment by malinajirka** [comment]
I think it's not the same issue, however I'm not 100% sure.
- In this issue two drafts are created and both are sent to the server. 
- I think in #8594 only one post is actually created, it's just displayed twice in two states - If I recall correctly leaving the screen and going back fixes it.

**Comment by malinajirka** [comment]
I believe this issue is not related to the Post List. The issue is that one draft is created when you click on the "Save as draft" overflow menu and the second draft is created when you click on the "Up button".

**Comment by maxme** [comment]
I experienced that bug today. I had a quick look at the debugger and found that the culprit is [`EditPostActivity.isFirstTimePublish`](https://github.com/wordpress-mobile/WordPress-Android/blob/4d1258f47d4dd8acd690f9a2c7efd218c1ba3fb3/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L2170-L2174): either the test is incorrect or the post is not well updated.
