### ISSUE TITLE
Account Settings: better error messaging for change email flow when address is already in use

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-Android#9384]
### Expected behavior
While logged into a WordPress.com account on the app, I try to update my email address to one that's used on a different WordPress.com account.
I expect to get an error which explains the email address is already being used on another account.

### Actual behavior
I get the error "Could not save your account settings".

![nochange](https://user-images.githubusercontent.com/15107387/54023080-b3472a80-419c-11e9-92ce-93b60da80aed.png)

### Steps to reproduce the behavior
You'll need two WordPress.com accounts to test.
1. Logged into account #1, go to Me > Account Settings and tap Email.
2. Change the email address to the email address associated with account #2.
3. See the "Could not save your account settings" error.

User report, Xiaomi Redmi Note 4X, WP Android 11.6 - #1855172-zen
I also tested on WPiOS 11.9 with similar results, reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/11214

**Comment by rachelmcr** [comment]
Note that if the email address change fails in this case, the API returns a nice error message we could use:

`{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_input","message":"That e-mail address is already being used."}}`

**Comment by jtj9817** [comment]
Mind if I take a look at this issue?

**Comment by rachelmcr** [comment]
> Mind if I take a look at this issue?

Hi, sorry I missed your comment earlier — you're welcome to take a look! You may be interested in looking at how this was solved on the iOS side of things for inspiration: https://github.com/wordpress-mobile/WordPress-iOS/pull/11229

**Comment by jtj9817** [comment]
@rachelmcr Thank you very much! I have hit a dead end for finding a solution to this problem but with that PR I might be able to solve it properly.

**Comment by jtj9817** [comment]
@rachelmcr I followed the logic of the solution in the PR that you posted. Since WordPress uses FluxC for handling network requests, it has a specific function for returning corresponding error messages. The problem is, since I'm using a development build (Oauth2), it's returning an error that my client is unauthorized to change the email (which might be true). So unless this fix is shipped in the production release, there's no way to verify if it's returning the correct error. Here's the screenshot:

![](https://raw.githubusercontent.com/jtj9817/MediaFiles/master/9384Solution2.png)

Now here's a simpler solution, to just use another string that displays the appropriate code **but** there's no guarantee that all errors will be only because of invalid email:

![](https://raw.githubusercontent.com/jtj9817/MediaFiles/master/9384Solution1.png)

**Comment by rachelmcr** [comment]
Thanks for the update! Sorry for not catching earlier that this would be a tricky one to work on.

> Since WordPress uses FluxC for handling network requests, it has a specific function for returning corresponding error messages. 

This is definitely the approach we want to take here, since there could be other reasons for a failed update (e.g. entering an invalid email address). Are you comfortable opening a PR to make that change despite not being able to verify the error message in your dev build? During the PR review, your reviewer can use the production keys to test the change and verify the message that's returned.

(And thank you for raising this here and in the WordPress Slack! It has sparked discussion among the release team about how this could be improved for anyone working on developing the apps.)

**Comment by jtj9817** [comment]
@rachelmcr I would push a PR later today for this one, thank you for encouraging it!

**Comment by aforcier** [comment]
As I mentioned here: https://github.com/wordpress-mobile/WordPress-Android/pull/9496#issuecomment-486740671, we could patch this server-side (to return a distinct error code instead of `invalid_input`). However, it's a little involved and perhaps not worth the effort given that the error message string we receive has decent translation coverage server-side (though it's not translated to all languages we support).

Recommended that we proceed with the fix in #9496.
