### ISSUE TITLE
Wrong number of followers shown in Insights -> Followers

### ISSUE THREAD

**Issue by kosmasdimitropoulos** [wordpress-mobile/WordPress-Android#9488]
##### Tested on Samsung Galaxy A5

![2019-03-28 02 50 29](https://user-images.githubusercontent.com/33027134/55121685-4d4b2480-5104-11e9-8156-80b9ee4608ff.jpg)

**Comment by designsimply** [comment]
I used two test accounts to try to reproduce the issue you have described with the following steps and I couldn't see the same problem:

1. Log in to the WPAndroid app as user `user476`.
1. Go to My Sites > Stats > Insights and find the Followers card.
1. Note the number of "Total WordPress.com Followers" (5 in my case).
1. Log in to WordPress in a web browser as user `madefortesting190313`.
1. Go to `https://madefortesting426.wordpress.com/`.
1. Click the "Follow" button at the bottom right.
1. Go back to the WPAndroid app still logged in as the first user.
1. Go to My Sites > Stats > Insights and find the Followers card.
1. Check to see if the number of "Total WordPress.com Followers" has increased by 1 as expected.<br>(Note that you may need to refresh the page to see recent changes.)

**Result:** the number of followers had the correct count and correctly increased by one after a new follower was added.

<sup>Tested with WPAndroid alpha-160 (12.1 alpha) on Pixel 3 Android 9.</sup>

Here is a screenshot showing the results from my test:

<img src="https://user-images.githubusercontent.com/1119271/55421089-b6cc9800-5535-11e9-93c6-2e96d7edca79.png" width="270" alt="Screenshot_20190402-104546">

I tested twice, once for a WordPress.com Premium site `madefortesting426.wordpress.com` and again for a Jetpack 7.1.1 WP 5.1.1 site `serious-snake.jurassic.ninja` (which had slightly different steps 5 & 6 where I entered the domain into the Reader and clicked "Follow" there—I added two followers in that case, see [screenshots](https://cloudup.com/caOLyaAkrlu)).

Because I was unable to reproduce the issue in a few different tests, I would like to ask for the following information and troubleshooting steps:

1. Can you find anything wrong in the testing steps above? 
1. In your case, I see you have two followers and that you may be testing yourself—if so, what were your exact testing steps to add those two followers?
1. What type of site were you testing? If it was Jetpack, can you verify the site is connected properly?
1. For reference, can you please note which version of Android  your Samsung Galaxy A5 is currently using and also note the version of the WordPress app you are currently testing with? (It's always good to note version numbers when possible.)
1. Does the "Total WordPress.com Followers" count get corrected if you pull to refresh the Insights screen in the app?
1. If refreshing does not work, can you go to Me > Help & Support > Application log and look for any relevant errors? If you find any, can you copy the whole log and send it to our support team using the Me > Help & Support > Contact us section and reference this issue?
1. If you are using a Jetpack site and refreshing the Insights screen does not help and if others cannot reproduce the problem in testing, one possibility is that another plugin installed on your site may be causing a conflict somehow and the generally accepted troubleshooting advice in that case would be to temporarily deactivate all other plugins besides Jetpack, clear cache if you are using a caching tool, and try the testing steps to see if you can repeat the problem without the influence of other plugins.

**Comment by planarvoid** [comment]
@kosmasdimitropoulos could you please follow the suggested steps to confirm the issue? thanks!

**Comment by irfano** [comment]
Since the issue is stale and I can't reproduce it, I am closing the issue.
