### ISSUE TITLE
Post List - "Post published" Snackbar is dismissed immediately 

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9604]
### Expected behavior
When you publish a post a Snackbar with text "Post Published" + "View" action is shown for a couple of seconds.

### Actual behavior
When you publish a post a Snackbar with text "Post Published" + "View" action is shown, but disappears immediately.

![post-published-snackbar-disappears-vv3](https://user-images.githubusercontent.com/2261188/56041347-ca97ab80-5d38-11e9-9780-6171d1e8044c.gif)

![post-published-snackbar-disappears](https://user-images.githubusercontent.com/2261188/56041342-c8cde800-5d38-11e9-809c-c4d69eb34686.gif)

### Steps to reproduce the behavior
1. My Site
2. Blog Posts
3. Edit a post
4. Change title
5. Publish
6. The Post List is displayed and a SnackBar "Publishing post" is shown
7. When the post is publish - "Post Published" SnackBar is shown for a fraction of a second

##### Tested on [device], Android [version]
Tested on commit 21454786c80d70c576d92557a5b66528c5297e54 - after we moved things from PostListViewModel to PostListMainViewModel
Nexus 5x, Android 8.1.0

cc @oguzkocer

**Comment by oguzkocer** [comment]
I've looked into this issue and I have to say, this one was very interesting. The reason it's happening is because we are trying to show the same snackbar from two different places. One from the post list, the other from the `WPMainActivity` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/WPMainActivity.java#L1099). There are a couple problems here:

1. `WPMainActivity` never stops listening for the `Dispatcher` events. I guess that's not going to change anytime soon as we'll need to make sure we are not missing any events
2. When the `WPMainActivity` is not the current activity, the snackbar does not show up. Unless I am missing something, the `CoordinatorLayout` we are trying to show the snackbar from will not be there while we are on the post list.

**Why does it work in `develop` but not in the current post filters branch?**

Interestingly, when the event is handled in the post list fragment, it'll be handled after the `WPMainActivity` which means, `WPMainActivity` will try to show the snackbar, it can't and then `PostListFragment` tries to show it and it works. However, in the post filters branch, `PostsListActivity` will first try to show the snackbar, it'll work but then `WPMainActivity` will try to show it which will not only not work, but it'll also cancel the previous snackbar that did work.

**How to fix it?**

1. For me the easy fix is to remove the logic that shows the snackbar from the `WPMainActivity`. I don't think it's a good idea to handle this event there unless we can ensure that the activity will always live and can handle the event regardless of where the user is. I don't think that's the case.
2. Somehow check from `WPMainActivity` whether we can show the snackbar from there. One sad way to do that would be to have a flag keeping track of if the activity is paused or not.
3. If we can check whether a snackbar is successfully shown or not (which I don't think we can) I guess we can keep track of whether a certain post publish snackbar is already shown. That feels even sadder for me.

---

@malinajirka I'll leave the follow up of this issue to you. If you don't want to spend too much time on it, I suggest going with the solution 1 and maybe opening up a new issue for being able to show the post published snackbar from everywhere. I don't think that's even worth it, but it's your call 🤷‍♂️

**Comment by malinajirka** [comment]
Thanks for looking into this @oguzkocer! It's a really interesting issue.

I have been thinking about our options and I came up with a pretty decent solution. It's not perfect as this usage of the event bus isn't perfect. But I think it's good enough #9620

**Comment by oguzkocer** [comment]
Fixed in #9620.
