### ISSUE TITLE
Submit for review button in the contributor just uploads draft

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#9718]
### Expected behavior
When I switch to a site with the ~Editor~ Contributor role and I click on the "Submit" button in the editor, the post is uploaded and submitted for review.

### Actual behavior
When I switch to a site with the ~Editor~Contributor role and I click on the "Submit" button in the editor, the post is uploaded but it's not submitted for review.

![submit-for-review](https://user-images.githubusercontent.com/2261188/56721046-5dc2df00-6744-11e9-8ccd-f4db77af8dec.gif)

### Steps to reproduce the behavior
0. Log in as an ~editor~Contributor
1. Open Blog posts
2. Create a new post
3. Click on the "Submit" button in the toolbar
4. Notice the post in the post list doesn't contain "Pending review" label

##### Tested on [device], Android [version], WPAndroid [version]
Pixel 3 Api 28

cc @mzorz It's probably related to the recent changes we've made.

**Comment by mzorz** [comment]
Nice find @malinajirka ! Will look into it and come back here 🙇

**Comment by mzorz** [comment]
I haven't been able to reproduce on current `develop` - I did change the role from `Editor` to `Contributor` (given Editors can publish posts, but only Contributors can't and need to submit for review [by default](https://codex.wordpress.org/Roles_and_Capabilities)), but still when trying that, I create a draft, I can tap on `submit`, and once I do that it uploads and changes the status to `Pending review`, which is expected, and the `submit` button changes to `View`.
I think what the gif above shows is correct, unless I'm missing something? What is exactly the expected behavior, if it's other than what's shown in the gif? (sorry if I'm not seeing something obvious here)

**Comment by malinajirka** [comment]
Oh, right - you need to be `Contributor` not `Editor`, sorry.

I've tested it again on develop and double check the gif and I still believe it's not the expected behavior. However, I might be missing something.

1. Open the editor
2. Type something into title input field
3. Click on the Submit button in the toolbar **(still in the editor)** and notice the post gets uploaded, but it's still not submitted for review. You need to click on the Submit button in the post list in order to submitted for review.
