### ISSUE TITLE
Stats Widget: WordPress Today's Stats widgets load the wrong site when more than one widget is added to the home screen

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-Android#9775]
If you create a homepage widget on an android device for multiple sites, the correct stats will appear on the device homepage, but when you tap on them they load the primary site for the user regardless of which one you click on.

Check out this video to see an example of this problem
https://youtu.be/wqQAuLke9-w

You can recreate this behavior by creating a stats widget on an android device for a site that is not the primary site.
Then tap on the stats widget
WordPress will load, but it will load the stats for the wrong site.

**Comment by daniloercoli** [comment]
There is another issue that seems very close to this one. If you tap on a Stats spike notification, the app does take you on the Stats screen for the main blog. https://github.com/wordpress-mobile/WordPress-Android/issues/9741

**Comment by designsimply** [comment]
Steps to reproduce:

1. Long press the WordPress app icon.
1. Tap the widget option at top right.
1. Tap "WordPress Today's Stats" widget.
1. Select a site.
1. Repeat the steps with a different side and compare what happens when tapping on each.

<strong>Result:</strong> in my case I found that tapping the widget resulted in opening the latest site I was on (not the primary site) instead of the one referenced

<img src="https://user-images.githubusercontent.com/1119271/57485404-deb3c780-7268-11e9-8079-0dc351fce6c9.png" width="200" alt="Screenshot_20190509-142139"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57485402-de1b3100-7268-11e9-987f-c581cc442030.png" width="200" alt="Screenshot_20190509-142146"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57485401-de1b3100-7268-11e9-8d91-65e038db6777.png" width="200" alt="Screenshot_20190509-143614">
<p style="clear:both;"><sub>Tested with WPAndroid alpha-170 on Pixel 3 Android 9.</sub></p>

**Comment by designsimply** [comment]
Re-tested with WPAndroid alpha-177 (12.8 alpha) on Pixel 3 Android 9 since new stats widgets are being added and I found there is still a problem with the "WordPress Today's Stats" widgets where only the primary site's stats are opened for every widget even if they are setup for different sites.

I also tested the "At a glance" widget in 12.8 beta testing and found that the correct stats open for different widgets added with different sites but that the back button (arrow at top left) always takes you back to whatever site's stats you were previously switched to in the app before tapping on the widget.
