### ISSUE TITLE
Site Creation: Improve "Creating new Site" screen.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-Android#9854]
## Description:

When creating a site through our New Site Creation flow, the screen that tells the user the site is being created could use some design improvements.

## Images:

![Screenshot_20190513-222801](https://user-images.githubusercontent.com/1836005/57664398-777e7600-75ce-11e9-8735-aff69912b405.png)

## Matching iOS Issue:

https://github.com/wordpress-mobile/WordPress-iOS/issues/11686

## Steps
1. My Site
2. Switch Site
3. Click on the "+" in the top right corner
4. Create a WordPress.com site
5. Walk through the flow
6. The screen is displayed when you click on "Create Site" after choosing a domain

**Comment by MonikaJethani** [comment]
@nbradbury Can I work on this issue?

**Comment by shiki** [comment]
Hi, @MonikaJethani! Thank you for contributing! 🎉 This issue is currently labeled with **Needs Design** which means we're waiting for UI/UX designs to be sorted out before we can proceed. 

Were you thinking of contributing code or proposing a design? 🙂  

If it's code, you may pick one of the [issues marked with **good first issue**](https://github.com/wordpress-mobile/WordPress-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for the mean time. Or any other issue in the [Issues list](https://github.com/wordpress-mobile/WordPress-Android/issues). Let me know if there's anything I can help you with.

**Comment by malinajirka** [comment]
@osullivanchris Could you please put this into your backlog. I believe there is no rush as it's just a design improvement. Thanks!

**Comment by malinajirka** [comment]
Sorry, disregard my comment :X. I just noticed Matt added it to "Design Groundskeeping". Sorry for the ping Chris.

**Comment by malinajirka** [comment]
Design can be found here - https://href.li/?https://github.com/wordpress-mobile/WordPress-iOS/issues/11686
