### ISSUE TITLE
Bug: Password visible

### ISSUE THREAD

**Issue by mavhc** [wordpress-mobile/WordPress-Android#9899]
### Expected behavior
Once a password has been entered correctly it should be able to be to viewable on screen, to avoid other people being able to find it.

### Actual behavior
Anyone with access to your device can view your password

### Steps to reproduce the behavior
Log in with password. Close app. Open app. Configuration>Settings. Tap Password, see password.

**Comment by designsimply** [comment]
I tried replicating this for three different types of sites: WordPress.com, Jetpack, Self-hosted. 

I could not find a Password field in My Sites > Settings for either a WordPress.com or a Jetpack site.

On the self-hosted site, I can go to My Site > Settings > Password but I cannot see the password displayed like you have noted. Here is what I see:

<img src="https://user-images.githubusercontent.com/1119271/58121516-de022600-7bc4-11e9-884c-7141619dc747.PNG" width="270" alt="IMG_2759">
<p style="clear:both;"><sup>Tested on an iPhone 6S iOS 12.2 using WPiOS 12.3.</sup></p>

I searched and found that it is possible to save account passwords and view them through iOS settings directly, however, it requires an authentication step such as Touch ID or Face ID before you can see the password. See https://www.imore.com/how-find-your-accounts-and-passwords-ios-11 for details.

@mavhc please definitely let me know if I have missed anything in my testing!

**Comment by mavhc** [comment]
I've not tested it on iOS, but on android when you open that same Password field it shows the current password on screen

**Comment by designsimply** [comment]
Well, that's embarrassing! I switch back and forth for testing quite a bit… I will re-test on Android right now.

**Comment by designsimply** [comment]
All right. I found that this is only an issue for self-hosted sites on either platform and not an issue for WordPress.com and Jetpack sites because the same password field is not available there.

On a self-hosted site, I am able to go to My Sites > Settings  > Password and see the password as you described and here are some screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/58122893-d5f7b580-7bc7-11e9-93c7-71d44e9c43da.png" width="270" alt="Screenshot_20190521-125321"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/58122794-a0eb6300-7bc7-11e9-9c5e-b1d60662b0ca.png" width="270" alt="image">
<sup>Tested with WPAndroid alpha-171 on Pixel 3 Android 9.</sup>

Sorry for the platform mix-up @mavhc !
