### ISSUE TITLE
Testing: Implement UI tests verifying activity log

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-Android#9927]
Implement UI tests to verify the activity log activity within the app...

Possible checks could be to 
1. Publish a post 
2. Check for the post in the activity log

or 

1. Upload a media
2. Check for the update in the activity log

** Update ** 

Since we're mocking the network requests here, walking through the action to trigger the event in the activity log tests a bit more than what I was aiming to accomplish with this one. The goal was to ensure the app behaves as expected on the activity log screen based on the different events in the list from the API.

**Comment by rachelmcr** [comment]
@JavonDavis I get the feeling that this proposed test is testing the API more than the UI (ensuring that a recently completed action is captured and displayed in the log). Since we're mocking the network requests, I'd focus an activity log test on ensuring that the correct log details are displayed for different kinds of user actions but not worrying about actually completing those user actions in the test (since we can provide the necessary log data in the mocked request).

Do you still think that kind of test is needed, i.e. that we need to test the Activity screen UI in that way?

**Comment by JavonDavis** [comment]
>I'd focus an activity log test on ensuring that the correct log details are displayed for different kinds of user actions but not worrying about actually completing those user actions in the test 

@rachelmcr hmm you're right on this one since we're mocking there's no need to go through the initial action. I'll update the description. 

> Do you still think that kind of test is needed, i.e. that we need to test the Activity screen UI in that way?

I had opened this one as a kind of `Good First Issue` for someone wanting to come in and contribute to the UI tests.  WDYT about leaving it open for that purpose? but otherwise I don't feel too strongly about adding a test to cover this flow.

**Comment by JavonDavis** [comment]
> I don't feel too strongly about adding a test to cover this flow.

I know this doesn't count as much of a flow either since the steps would now look like Sign in > choose site > Activity and check for the post published in the list or something to that effect. I'm for closing it if you think there's not enough value added here to keep it but originally created it as a smaller change that we could add later or as a `Good First Issue`

**Comment by rachelmcr** [comment]
> I had opened this one as a kind of Good First Issue for someone wanting to come in and contribute to the UI tests. WDYT about leaving it open for that purpose?

That sounds good to me for now. Thanks for updating the description!

**Comment by Stanzin7** [comment]
is this open ?

**Comment by rachelmcr** [comment]
Hi @Stanzin7! I no longer work in this area so I'm not sure if it's still needed; @wordpress-mobile/apps-quality could you take a look?

**Comment by pachlava** [comment]
@rachelmcr @Stanzin7 👋 

The `Activity Log` screen is indirectly tested as a part of `Activity Log` dashboard card navigation UI test added via #18582. For Android, the test checks the fact of opening an individual activity, but not the list of activities. For iOS, however, the test checks for the list of activites. More on the reasons behind this is in the mentioned PR description. I hope this helps.

At the moment I think the issue can be closed, since automating an additional flow to get to the activity log via tapping the menu item (while we already have one test that gets there via dashboard card) goes against our strategy of automating the critical flows in the first place, and not trying to cover all the possible flows.
